### YamlMime:ManagedReference
items:
- uid: System.Data.Services.Configuration.DataServicesSectionGroup
  id: DataServicesSectionGroup
  children:
  - System.Data.Services.Configuration.DataServicesSectionGroup.#ctor
  - System.Data.Services.Configuration.DataServicesSectionGroup.Features
  langs:
  - csharp
  - vb
  name: DataServicesSectionGroup
  nameWithType: DataServicesSectionGroup
  fullName: System.Data.Services.Configuration.DataServicesSectionGroup
  type: Class
  syntax:
    content: 'public sealed class DataServicesSectionGroup : System.Configuration.ConfigurationSectionGroup'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationSectionGroup
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationSectionGroup.ForceDeclaration
  - System.Configuration.ConfigurationSectionGroup.ForceDeclaration(System.Boolean)
  - System.Configuration.ConfigurationSectionGroup.IsDeclarationRequired
  - System.Configuration.ConfigurationSectionGroup.IsDeclared
  - System.Configuration.ConfigurationSectionGroup.Name
  - System.Configuration.ConfigurationSectionGroup.SectionGroupName
  - System.Configuration.ConfigurationSectionGroup.SectionGroups
  - System.Configuration.ConfigurationSectionGroup.Sections
  - System.Configuration.ConfigurationSectionGroup.ShouldSerializeSectionGroupInTargetVersion(System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSectionGroup.Type
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: System.Data.Services.Configuration.DataServicesSectionGroup.#ctor
  id: '#ctor'
  parent: System.Data.Services.Configuration.DataServicesSectionGroup
  langs:
  - csharp
  - vb
  name: DataServicesSectionGroup()
  nameWithType: DataServicesSectionGroup.DataServicesSectionGroup()
  fullName: System.Data.Services.Configuration.DataServicesSectionGroup.DataServicesSectionGroup()
  type: Constructor
  assemblies:
  - System.Data.Services
  namespace: System.Data.Services.Configuration
  syntax:
    content: public DataServicesSectionGroup ();
    parameters: []
- uid: System.Data.Services.Configuration.DataServicesSectionGroup.Features
  id: Features
  parent: System.Data.Services.Configuration.DataServicesSectionGroup
  langs:
  - csharp
  - vb
  name: Features
  nameWithType: DataServicesSectionGroup.Features
  fullName: System.Data.Services.Configuration.DataServicesSectionGroup.Features
  type: Property
  assemblies:
  - System.Data.Services
  namespace: System.Data.Services.Configuration
  syntax:
    content: public System.Data.Services.Configuration.DataServicesFeaturesSection Features { get; }
    return:
      type: System.Data.Services.Configuration.DataServicesFeaturesSection
      description: Return description to be filled
references:
- uid: System.Configuration.ConfigurationSectionGroup
  isExternal: false
  name: System.Configuration.ConfigurationSectionGroup
- uid: System.Data.Services.Configuration.DataServicesSectionGroup.#ctor
  parent: System.Data.Services.Configuration.DataServicesSectionGroup
  isExternal: false
  name: DataServicesSectionGroup()
  nameWithType: DataServicesSectionGroup.DataServicesSectionGroup()
  fullName: System.Data.Services.Configuration.DataServicesSectionGroup.DataServicesSectionGroup()
- uid: System.Data.Services.Configuration.DataServicesSectionGroup.Features
  parent: System.Data.Services.Configuration.DataServicesSectionGroup
  isExternal: false
  name: Features
  nameWithType: DataServicesSectionGroup.Features
  fullName: System.Data.Services.Configuration.DataServicesSectionGroup.Features
- uid: System.Data.Services.Configuration.DataServicesFeaturesSection
  parent: System.Data.Services.Configuration
  isExternal: false
  name: DataServicesFeaturesSection
  nameWithType: DataServicesFeaturesSection
  fullName: System.Data.Services.Configuration.DataServicesFeaturesSection
