### YamlMime:ManagedReference
items:
- uid: System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1
  id: ConfiguredTaskAwaitable`1
  children:
  - System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.GetAwaiter
  langs:
  - csharp
  - vb
  name: ConfiguredTaskAwaitable<TResult>
  nameWithType: ConfiguredTaskAwaitable<TResult>
  fullName: System.Runtime.CompilerServices.ConfiguredTaskAwaitable<TResult>
  type: Struct
  syntax:
    content: public struct ConfiguredTaskAwaitable<TResult>
    typeParameters:
    - id: TResult
      description: Parameter description to be filled
  inheritance:
  - System.Object
  - System.ValueType
  implements: []
  inheritedMembers:
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.ValueType.Equals(System.Object)
  - System.ValueType.GetHashCode
  - System.ValueType.ToString
- uid: System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.GetAwaiter
  id: GetAwaiter
  parent: System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1
  langs:
  - csharp
  - vb
  name: GetAwaiter
  nameWithType: ConfiguredTaskAwaitable<TResult>.GetAwaiter
  fullName: System.Runtime.CompilerServices.ConfiguredTaskAwaitable<TResult>.GetAwaiter
  type: Method
  assemblies:
  - mscorlib
  namespace: System.Runtime.CompilerServices
  syntax:
    content: public System.Runtime.CompilerServices.ConfiguredTaskAwaitable<TResult>.ConfiguredTaskAwaiter GetAwaiter ();
    parameters: []
    return:
      type: System.Runtime.CompilerServices.ConfiguredTaskAwaitable{TResult}+ConfiguredTaskAwaiter
      description: Return description to be filled
references:
- uid: System.ValueType
  isExternal: false
  name: System.ValueType
- uid: System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.GetAwaiter
  parent: System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1
  isExternal: false
  name: GetAwaiter
  nameWithType: ConfiguredTaskAwaitable<TResult>.GetAwaiter
  fullName: System.Runtime.CompilerServices.ConfiguredTaskAwaitable<TResult>.GetAwaiter
- uid: System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter
  parent: System.Runtime.CompilerServices
  isExternal: false
  name: ConfiguredTaskAwaitable<TResult>+ConfiguredTaskAwaiter
  nameWithType: ConfiguredTaskAwaitable<TResult>+ConfiguredTaskAwaiter
  fullName: System.Runtime.CompilerServices.ConfiguredTaskAwaitable<TResult>+ConfiguredTaskAwaiter
