### YamlMime:ManagedReference
items:
- uid: System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter
  id: ConfiguredTaskAwaitable.ConfiguredTaskAwaiter
  children:
  - System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult
  - System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.IsCompleted
  - System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.OnCompleted(System.Action)
  - System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.UnsafeOnCompleted(System.Action)
  langs:
  - csharp
  - vb
  name: ConfiguredTaskAwaitable+ConfiguredTaskAwaiter
  nameWithType: ConfiguredTaskAwaitable+ConfiguredTaskAwaiter
  fullName: System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter
  type: Struct
  syntax:
    content: 'public struct ConfiguredTaskAwaitable.ConfiguredTaskAwaiter : System.Runtime.CompilerServices.ICriticalNotifyCompletion'
  inheritance:
  - System.Object
  - System.ValueType
  implements:
  - System.Runtime.CompilerServices.ICriticalNotifyCompletion
  inheritedMembers:
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.ValueType.Equals(System.Object)
  - System.ValueType.GetHashCode
  - System.ValueType.ToString
- uid: System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult
  id: GetResult
  parent: System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter
  langs:
  - csharp
  - vb
  name: GetResult
  nameWithType: ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult
  fullName: System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult
  type: Method
  assemblies:
  - mscorlib
  namespace: System.Runtime.CompilerServices
  syntax:
    content: public void GetResult ();
    parameters: []
    return:
      type: System.Void
      description: Return description to be filled
- uid: System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.IsCompleted
  id: IsCompleted
  parent: System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter
  langs:
  - csharp
  - vb
  name: IsCompleted
  nameWithType: ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.IsCompleted
  fullName: System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.IsCompleted
  type: Property
  assemblies:
  - mscorlib
  namespace: System.Runtime.CompilerServices
  syntax:
    content: public bool IsCompleted { get; }
    return:
      type: System.Boolean
      description: Return description to be filled
- uid: System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.OnCompleted(System.Action)
  id: OnCompleted(System.Action)
  parent: System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter
  langs:
  - csharp
  - vb
  name: OnCompleted
  nameWithType: ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.OnCompleted
  fullName: System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.OnCompleted
  type: Method
  assemblies:
  - mscorlib
  namespace: System.Runtime.CompilerServices
  syntax:
    content: public void OnCompleted (Action continuation);
    parameters:
    - id: continuation
      type: System.Action
      description: Parameter description to be filled
    return:
      type: System.Void
      description: Return description to be filled
- uid: System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.UnsafeOnCompleted(System.Action)
  id: UnsafeOnCompleted(System.Action)
  parent: System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter
  langs:
  - csharp
  - vb
  name: UnsafeOnCompleted
  nameWithType: ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.UnsafeOnCompleted
  fullName: System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.UnsafeOnCompleted
  type: Method
  assemblies:
  - mscorlib
  namespace: System.Runtime.CompilerServices
  syntax:
    content: public void UnsafeOnCompleted (Action continuation);
    parameters:
    - id: continuation
      type: System.Action
      description: Parameter description to be filled
    return:
      type: System.Void
      description: Return description to be filled
references:
- uid: System.ValueType
  isExternal: false
  name: System.ValueType
- uid: System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult
  parent: System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter
  isExternal: false
  name: GetResult
  nameWithType: ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult
  fullName: System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult
- uid: System.Void
  parent: System
  isExternal: false
  name: Void
  nameWithType: Void
  fullName: System.Void
- uid: System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.IsCompleted
  parent: System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter
  isExternal: false
  name: IsCompleted
  nameWithType: ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.IsCompleted
  fullName: System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.IsCompleted
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.OnCompleted(System.Action)
  parent: System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter
  isExternal: false
  name: OnCompleted
  nameWithType: ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.OnCompleted
  fullName: System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.OnCompleted
- uid: System.Void
  parent: System
  isExternal: false
  name: Void
  nameWithType: Void
  fullName: System.Void
- uid: System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.UnsafeOnCompleted(System.Action)
  parent: System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter
  isExternal: false
  name: UnsafeOnCompleted
  nameWithType: ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.UnsafeOnCompleted
  fullName: System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.UnsafeOnCompleted
- uid: System.Void
  parent: System
  isExternal: false
  name: Void
  nameWithType: Void
  fullName: System.Void
