### YamlMime:ManagedReference
items:
- uid: System.Runtime.CompilerServices.ConfiguredTaskAwaitable
  id: ConfiguredTaskAwaitable
  children:
  - System.Runtime.CompilerServices.ConfiguredTaskAwaitable.GetAwaiter
  langs:
  - csharp
  name: ConfiguredTaskAwaitable
  nameWithType: ConfiguredTaskAwaitable
  fullName: System.Runtime.CompilerServices.ConfiguredTaskAwaitable
  type: Struct
  summary: Provides an awaitable object that enables configured awaits on a task.
  remarks: This type is intended for compiler use; do not use it directly in your code.
  syntax:
    content: public struct ConfiguredTaskAwaitable
  inheritance:
  - System.Object
  - System.ValueType
  implements: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Runtime.CompilerServices.ConfiguredTaskAwaitable.GetAwaiter
  id: GetAwaiter
  parent: System.Runtime.CompilerServices.ConfiguredTaskAwaitable
  langs:
  - csharp
  name: GetAwaiter()
  nameWithType: ConfiguredTaskAwaitable.GetAwaiter()
  fullName: System.Runtime.CompilerServices.ConfiguredTaskAwaitable.GetAwaiter()
  type: Method
  assemblies:
  - mscorlib
  namespace: System.Runtime.CompilerServices
  summary: Returns an awaiter for this awaitable object.
  remarks: This method is intended for compiler use; do not use it directly in your code.
  syntax:
    content: public System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter GetAwaiter ();
    parameters: []
    return:
      type: System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter
      description: The awaiter.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.ValueType
  isExternal: false
  name: System.ValueType
- uid: System.Runtime.CompilerServices.ConfiguredTaskAwaitable.GetAwaiter
  parent: System.Runtime.CompilerServices.ConfiguredTaskAwaitable
  isExternal: false
  name: GetAwaiter()
  nameWithType: ConfiguredTaskAwaitable.GetAwaiter()
  fullName: System.Runtime.CompilerServices.ConfiguredTaskAwaitable.GetAwaiter()
- uid: System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter
  parent: System.Runtime.CompilerServices
  isExternal: false
  name: ConfiguredTaskAwaitable+ConfiguredTaskAwaiter
  nameWithType: ConfiguredTaskAwaitable+ConfiguredTaskAwaiter
  fullName: System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter
