### YamlMime:ManagedReference
items:
- uid: System.Web.UI.Design.IWebApplication
  id: IWebApplication
  children:
  - System.Web.UI.Design.IWebApplication.GetProjectItemFromUrl(System.String)
  - System.Web.UI.Design.IWebApplication.OpenWebConfiguration(System.Boolean)
  - System.Web.UI.Design.IWebApplication.RootProjectItem
  langs:
  - csharp
  - vb
  name: IWebApplication
  nameWithType: IWebApplication
  fullName: System.Web.UI.Design.IWebApplication
  type: Interface
  syntax:
    content: >-
      [System.Runtime.InteropServices.Guid("cff39fa8-5607-4b6d-86f3-cc80b3cfe2dd")]

      public interface IWebApplication : IServiceProvider
  implements:
  - System.IServiceProvider
- uid: System.Web.UI.Design.IWebApplication.GetProjectItemFromUrl(System.String)
  id: GetProjectItemFromUrl(System.String)
  parent: System.Web.UI.Design.IWebApplication
  langs:
  - csharp
  - vb
  name: GetProjectItemFromUrl
  nameWithType: IWebApplication.GetProjectItemFromUrl
  fullName: System.Web.UI.Design.IWebApplication.GetProjectItemFromUrl
  type: Method
  assemblies:
  - System.Design
  namespace: System.Web.UI.Design
  syntax:
    content: public System.Web.UI.Design.IProjectItem GetProjectItemFromUrl (string appRelativeUrl);
    parameters:
    - id: appRelativeUrl
      type: System.String
      description: Parameter description to be filled
    return:
      type: System.Web.UI.Design.IProjectItem
      description: Return description to be filled
- uid: System.Web.UI.Design.IWebApplication.OpenWebConfiguration(System.Boolean)
  id: OpenWebConfiguration(System.Boolean)
  parent: System.Web.UI.Design.IWebApplication
  langs:
  - csharp
  - vb
  name: OpenWebConfiguration
  nameWithType: IWebApplication.OpenWebConfiguration
  fullName: System.Web.UI.Design.IWebApplication.OpenWebConfiguration
  type: Method
  assemblies:
  - System.Design
  namespace: System.Web.UI.Design
  syntax:
    content: public System.Configuration.Configuration OpenWebConfiguration (bool isReadOnly);
    parameters:
    - id: isReadOnly
      type: System.Boolean
      description: Parameter description to be filled
    return:
      type: System.Configuration.Configuration
      description: Return description to be filled
- uid: System.Web.UI.Design.IWebApplication.RootProjectItem
  id: RootProjectItem
  parent: System.Web.UI.Design.IWebApplication
  langs:
  - csharp
  - vb
  name: RootProjectItem
  nameWithType: IWebApplication.RootProjectItem
  fullName: System.Web.UI.Design.IWebApplication.RootProjectItem
  type: Property
  assemblies:
  - System.Design
  namespace: System.Web.UI.Design
  syntax:
    content: public System.Web.UI.Design.IProjectItem RootProjectItem { get; }
    return:
      type: System.Web.UI.Design.IProjectItem
      description: Return description to be filled
references:
- uid: System.Web.UI.Design.IWebApplication.GetProjectItemFromUrl(System.String)
  parent: System.Web.UI.Design.IWebApplication
  isExternal: false
  name: GetProjectItemFromUrl
  nameWithType: IWebApplication.GetProjectItemFromUrl
  fullName: System.Web.UI.Design.IWebApplication.GetProjectItemFromUrl
- uid: System.Web.UI.Design.IProjectItem
  parent: System.Web.UI.Design
  isExternal: false
  name: IProjectItem
  nameWithType: IProjectItem
  fullName: System.Web.UI.Design.IProjectItem
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.UI.Design.IWebApplication.OpenWebConfiguration(System.Boolean)
  parent: System.Web.UI.Design.IWebApplication
  isExternal: false
  name: OpenWebConfiguration
  nameWithType: IWebApplication.OpenWebConfiguration
  fullName: System.Web.UI.Design.IWebApplication.OpenWebConfiguration
- uid: System.Configuration.Configuration
  parent: System.Configuration
  isExternal: false
  name: Configuration
  nameWithType: Configuration
  fullName: System.Configuration.Configuration
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Web.UI.Design.IWebApplication.RootProjectItem
  parent: System.Web.UI.Design.IWebApplication
  isExternal: false
  name: RootProjectItem
  nameWithType: IWebApplication.RootProjectItem
  fullName: System.Web.UI.Design.IWebApplication.RootProjectItem
- uid: System.Web.UI.Design.IProjectItem
  parent: System.Web.UI.Design
  isExternal: false
  name: IProjectItem
  nameWithType: IProjectItem
  fullName: System.Web.UI.Design.IProjectItem
