### YamlMime:ManagedReference
items:
- uid: System.Configuration.Install.AssemblyInstaller
  id: AssemblyInstaller
  children:
  - System.Configuration.Install.AssemblyInstaller.#ctor
  - System.Configuration.Install.AssemblyInstaller.#ctor(System.Reflection.Assembly,System.String[])
  - System.Configuration.Install.AssemblyInstaller.#ctor(System.String,System.String[])
  - System.Configuration.Install.AssemblyInstaller.Assembly
  - System.Configuration.Install.AssemblyInstaller.CheckIfInstallable(System.String)
  - System.Configuration.Install.AssemblyInstaller.CommandLine
  - System.Configuration.Install.AssemblyInstaller.Commit(System.Collections.IDictionary)
  - System.Configuration.Install.AssemblyInstaller.HelpText
  - System.Configuration.Install.AssemblyInstaller.Install(System.Collections.IDictionary)
  - System.Configuration.Install.AssemblyInstaller.Path
  - System.Configuration.Install.AssemblyInstaller.Rollback(System.Collections.IDictionary)
  - System.Configuration.Install.AssemblyInstaller.Uninstall(System.Collections.IDictionary)
  - System.Configuration.Install.AssemblyInstaller.UseNewContext
  langs:
  - csharp
  - vb
  name: AssemblyInstaller
  nameWithType: AssemblyInstaller
  fullName: System.Configuration.Install.AssemblyInstaller
  type: Class
  syntax:
    content: 'public class AssemblyInstaller : System.Configuration.Install.Installer'
  inheritance:
  - System.ComponentModel.Component
  - System.Configuration.Install.Installer
  implements: []
  inheritedMembers:
  - System.Configuration.Install.Installer.AfterInstall
  - System.Configuration.Install.Installer.AfterRollback
  - System.Configuration.Install.Installer.AfterUninstall
  - System.Configuration.Install.Installer.BeforeInstall
  - System.Configuration.Install.Installer.BeforeRollback
  - System.Configuration.Install.Installer.BeforeUninstall
  - System.Configuration.Install.Installer.Committed
  - System.Configuration.Install.Installer.Committing
  - System.Configuration.Install.Installer.Context
  - System.Configuration.Install.Installer.Installers
  - System.Configuration.Install.Installer.OnAfterInstall(System.Collections.IDictionary)
  - System.Configuration.Install.Installer.OnAfterRollback(System.Collections.IDictionary)
  - System.Configuration.Install.Installer.OnAfterUninstall(System.Collections.IDictionary)
  - System.Configuration.Install.Installer.OnBeforeInstall(System.Collections.IDictionary)
  - System.Configuration.Install.Installer.OnBeforeRollback(System.Collections.IDictionary)
  - System.Configuration.Install.Installer.OnBeforeUninstall(System.Collections.IDictionary)
  - System.Configuration.Install.Installer.OnCommitted(System.Collections.IDictionary)
  - System.Configuration.Install.Installer.OnCommitting(System.Collections.IDictionary)
  - System.Configuration.Install.Installer.Parent
- uid: System.Configuration.Install.AssemblyInstaller.#ctor
  id: '#ctor'
  parent: System.Configuration.Install.AssemblyInstaller
  langs:
  - csharp
  - vb
  name: .ctor
  nameWithType: AssemblyInstaller..ctor
  fullName: System.Configuration.Install.AssemblyInstaller..ctor
  type: Constructor
  assemblies:
  - System.Configuration.Install
  namespace: System.Configuration.Install
  syntax:
    content: public AssemblyInstaller ();
    parameters: []
- uid: System.Configuration.Install.AssemblyInstaller.#ctor(System.Reflection.Assembly,System.String[])
  id: '#ctor(System.Reflection.Assembly,System.String[])'
  parent: System.Configuration.Install.AssemblyInstaller
  langs:
  - csharp
  - vb
  name: .ctor
  nameWithType: AssemblyInstaller..ctor
  fullName: System.Configuration.Install.AssemblyInstaller..ctor
  type: Constructor
  assemblies:
  - System.Configuration.Install
  namespace: System.Configuration.Install
  syntax:
    content: public AssemblyInstaller (System.Reflection.Assembly assembly, string[] commandLine);
    parameters:
    - id: assembly
      type: System.Reflection.Assembly
      description: Parameter description to be filled
    - id: commandLine
      type: System.String[]
      description: Parameter description to be filled
- uid: System.Configuration.Install.AssemblyInstaller.#ctor(System.String,System.String[])
  id: '#ctor(System.String,System.String[])'
  parent: System.Configuration.Install.AssemblyInstaller
  langs:
  - csharp
  - vb
  name: .ctor
  nameWithType: AssemblyInstaller..ctor
  fullName: System.Configuration.Install.AssemblyInstaller..ctor
  type: Constructor
  assemblies:
  - System.Configuration.Install
  namespace: System.Configuration.Install
  syntax:
    content: public AssemblyInstaller (string fileName, string[] commandLine);
    parameters:
    - id: fileName
      type: System.String
      description: Parameter description to be filled
    - id: commandLine
      type: System.String[]
      description: Parameter description to be filled
- uid: System.Configuration.Install.AssemblyInstaller.Assembly
  id: Assembly
  parent: System.Configuration.Install.AssemblyInstaller
  langs:
  - csharp
  - vb
  name: Assembly
  nameWithType: AssemblyInstaller.Assembly
  fullName: System.Configuration.Install.AssemblyInstaller.Assembly
  type: Property
  assemblies:
  - System.Configuration.Install
  namespace: System.Configuration.Install
  syntax:
    content: public System.Reflection.Assembly Assembly { get; set; }
    return:
      type: System.Reflection.Assembly
      description: Return description to be filled
- uid: System.Configuration.Install.AssemblyInstaller.CheckIfInstallable(System.String)
  id: CheckIfInstallable(System.String)
  parent: System.Configuration.Install.AssemblyInstaller
  langs:
  - csharp
  - vb
  name: CheckIfInstallable
  nameWithType: AssemblyInstaller.CheckIfInstallable
  fullName: System.Configuration.Install.AssemblyInstaller.CheckIfInstallable
  type: Method
  assemblies:
  - System.Configuration.Install
  namespace: System.Configuration.Install
  syntax:
    content: public static void CheckIfInstallable (string assemblyName);
    parameters:
    - id: assemblyName
      type: System.String
      description: Parameter description to be filled
    return:
      type: System.Void
      description: Return description to be filled
- uid: System.Configuration.Install.AssemblyInstaller.CommandLine
  id: CommandLine
  parent: System.Configuration.Install.AssemblyInstaller
  langs:
  - csharp
  - vb
  name: CommandLine
  nameWithType: AssemblyInstaller.CommandLine
  fullName: System.Configuration.Install.AssemblyInstaller.CommandLine
  type: Property
  assemblies:
  - System.Configuration.Install
  namespace: System.Configuration.Install
  syntax:
    content: public string[] CommandLine { get; set; }
    return:
      type: System.String[]
      description: Return description to be filled
- uid: System.Configuration.Install.AssemblyInstaller.Commit(System.Collections.IDictionary)
  id: Commit(System.Collections.IDictionary)
  parent: System.Configuration.Install.AssemblyInstaller
  langs:
  - csharp
  - vb
  name: Commit
  nameWithType: AssemblyInstaller.Commit
  fullName: System.Configuration.Install.AssemblyInstaller.Commit
  type: Method
  assemblies:
  - System.Configuration.Install
  namespace: System.Configuration.Install
  syntax:
    content: public override void Commit (System.Collections.IDictionary savedState);
    parameters:
    - id: savedState
      type: System.Collections.IDictionary
      description: Parameter description to be filled
    return:
      type: System.Void
      description: Return description to be filled
- uid: System.Configuration.Install.AssemblyInstaller.HelpText
  id: HelpText
  parent: System.Configuration.Install.AssemblyInstaller
  langs:
  - csharp
  - vb
  name: HelpText
  nameWithType: AssemblyInstaller.HelpText
  fullName: System.Configuration.Install.AssemblyInstaller.HelpText
  type: Property
  assemblies:
  - System.Configuration.Install
  namespace: System.Configuration.Install
  syntax:
    content: public override string HelpText { get; }
    return:
      type: System.String
      description: Return description to be filled
- uid: System.Configuration.Install.AssemblyInstaller.Install(System.Collections.IDictionary)
  id: Install(System.Collections.IDictionary)
  parent: System.Configuration.Install.AssemblyInstaller
  langs:
  - csharp
  - vb
  name: Install
  nameWithType: AssemblyInstaller.Install
  fullName: System.Configuration.Install.AssemblyInstaller.Install
  type: Method
  assemblies:
  - System.Configuration.Install
  namespace: System.Configuration.Install
  syntax:
    content: public override void Install (System.Collections.IDictionary savedState);
    parameters:
    - id: savedState
      type: System.Collections.IDictionary
      description: Parameter description to be filled
    return:
      type: System.Void
      description: Return description to be filled
- uid: System.Configuration.Install.AssemblyInstaller.Path
  id: Path
  parent: System.Configuration.Install.AssemblyInstaller
  langs:
  - csharp
  - vb
  name: Path
  nameWithType: AssemblyInstaller.Path
  fullName: System.Configuration.Install.AssemblyInstaller.Path
  type: Property
  assemblies:
  - System.Configuration.Install
  namespace: System.Configuration.Install
  syntax:
    content: public string Path { get; set; }
    return:
      type: System.String
      description: Return description to be filled
- uid: System.Configuration.Install.AssemblyInstaller.Rollback(System.Collections.IDictionary)
  id: Rollback(System.Collections.IDictionary)
  parent: System.Configuration.Install.AssemblyInstaller
  langs:
  - csharp
  - vb
  name: Rollback
  nameWithType: AssemblyInstaller.Rollback
  fullName: System.Configuration.Install.AssemblyInstaller.Rollback
  type: Method
  assemblies:
  - System.Configuration.Install
  namespace: System.Configuration.Install
  syntax:
    content: public override void Rollback (System.Collections.IDictionary savedState);
    parameters:
    - id: savedState
      type: System.Collections.IDictionary
      description: Parameter description to be filled
    return:
      type: System.Void
      description: Return description to be filled
- uid: System.Configuration.Install.AssemblyInstaller.Uninstall(System.Collections.IDictionary)
  id: Uninstall(System.Collections.IDictionary)
  parent: System.Configuration.Install.AssemblyInstaller
  langs:
  - csharp
  - vb
  name: Uninstall
  nameWithType: AssemblyInstaller.Uninstall
  fullName: System.Configuration.Install.AssemblyInstaller.Uninstall
  type: Method
  assemblies:
  - System.Configuration.Install
  namespace: System.Configuration.Install
  syntax:
    content: public override void Uninstall (System.Collections.IDictionary savedState);
    parameters:
    - id: savedState
      type: System.Collections.IDictionary
      description: Parameter description to be filled
    return:
      type: System.Void
      description: Return description to be filled
- uid: System.Configuration.Install.AssemblyInstaller.UseNewContext
  id: UseNewContext
  parent: System.Configuration.Install.AssemblyInstaller
  langs:
  - csharp
  - vb
  name: UseNewContext
  nameWithType: AssemblyInstaller.UseNewContext
  fullName: System.Configuration.Install.AssemblyInstaller.UseNewContext
  type: Property
  assemblies:
  - System.Configuration.Install
  namespace: System.Configuration.Install
  syntax:
    content: public bool UseNewContext { get; set; }
    return:
      type: System.Boolean
      description: Return description to be filled
references:
- uid: System.Configuration.Install.Installer
  isExternal: false
  name: System.Configuration.Install.Installer
- uid: System.Configuration.Install.AssemblyInstaller.#ctor
  parent: System.Configuration.Install.AssemblyInstaller
  isExternal: false
  name: .ctor
  nameWithType: AssemblyInstaller..ctor
  fullName: System.Configuration.Install.AssemblyInstaller..ctor
- uid: System.Configuration.Install.AssemblyInstaller.#ctor(System.Reflection.Assembly,System.String[])
  parent: System.Configuration.Install.AssemblyInstaller
  isExternal: false
  name: .ctor
  nameWithType: AssemblyInstaller..ctor
  fullName: System.Configuration.Install.AssemblyInstaller..ctor
- uid: System.Reflection.Assembly
  parent: System.Reflection
  isExternal: false
  name: Assembly
  nameWithType: Assembly
  fullName: System.Reflection.Assembly
- uid: System.Configuration.Install.AssemblyInstaller.#ctor(System.String,System.String[])
  parent: System.Configuration.Install.AssemblyInstaller
  isExternal: false
  name: .ctor
  nameWithType: AssemblyInstaller..ctor
  fullName: System.Configuration.Install.AssemblyInstaller..ctor
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.Install.AssemblyInstaller.Assembly
  parent: System.Configuration.Install.AssemblyInstaller
  isExternal: false
  name: Assembly
  nameWithType: AssemblyInstaller.Assembly
  fullName: System.Configuration.Install.AssemblyInstaller.Assembly
- uid: System.Reflection.Assembly
  parent: System.Reflection
  isExternal: false
  name: Assembly
  nameWithType: Assembly
  fullName: System.Reflection.Assembly
- uid: System.Configuration.Install.AssemblyInstaller.CheckIfInstallable(System.String)
  parent: System.Configuration.Install.AssemblyInstaller
  isExternal: false
  name: CheckIfInstallable
  nameWithType: AssemblyInstaller.CheckIfInstallable
  fullName: System.Configuration.Install.AssemblyInstaller.CheckIfInstallable
- uid: System.Void
  parent: System
  isExternal: false
  name: Void
  nameWithType: Void
  fullName: System.Void
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.Install.AssemblyInstaller.CommandLine
  parent: System.Configuration.Install.AssemblyInstaller
  isExternal: false
  name: CommandLine
  nameWithType: AssemblyInstaller.CommandLine
  fullName: System.Configuration.Install.AssemblyInstaller.CommandLine
- uid: System.Configuration.Install.AssemblyInstaller.Commit(System.Collections.IDictionary)
  parent: System.Configuration.Install.AssemblyInstaller
  isExternal: false
  name: Commit
  nameWithType: AssemblyInstaller.Commit
  fullName: System.Configuration.Install.AssemblyInstaller.Commit
- uid: System.Void
  parent: System
  isExternal: false
  name: Void
  nameWithType: Void
  fullName: System.Void
- uid: System.Collections.IDictionary
  parent: System.Collections
  isExternal: false
  name: IDictionary
  nameWithType: IDictionary
  fullName: System.Collections.IDictionary
- uid: System.Configuration.Install.AssemblyInstaller.HelpText
  parent: System.Configuration.Install.AssemblyInstaller
  isExternal: false
  name: HelpText
  nameWithType: AssemblyInstaller.HelpText
  fullName: System.Configuration.Install.AssemblyInstaller.HelpText
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.Install.AssemblyInstaller.Install(System.Collections.IDictionary)
  parent: System.Configuration.Install.AssemblyInstaller
  isExternal: false
  name: Install
  nameWithType: AssemblyInstaller.Install
  fullName: System.Configuration.Install.AssemblyInstaller.Install
- uid: System.Void
  parent: System
  isExternal: false
  name: Void
  nameWithType: Void
  fullName: System.Void
- uid: System.Collections.IDictionary
  parent: System.Collections
  isExternal: false
  name: IDictionary
  nameWithType: IDictionary
  fullName: System.Collections.IDictionary
- uid: System.Configuration.Install.AssemblyInstaller.Path
  parent: System.Configuration.Install.AssemblyInstaller
  isExternal: false
  name: Path
  nameWithType: AssemblyInstaller.Path
  fullName: System.Configuration.Install.AssemblyInstaller.Path
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.Install.AssemblyInstaller.Rollback(System.Collections.IDictionary)
  parent: System.Configuration.Install.AssemblyInstaller
  isExternal: false
  name: Rollback
  nameWithType: AssemblyInstaller.Rollback
  fullName: System.Configuration.Install.AssemblyInstaller.Rollback
- uid: System.Void
  parent: System
  isExternal: false
  name: Void
  nameWithType: Void
  fullName: System.Void
- uid: System.Collections.IDictionary
  parent: System.Collections
  isExternal: false
  name: IDictionary
  nameWithType: IDictionary
  fullName: System.Collections.IDictionary
- uid: System.Configuration.Install.AssemblyInstaller.Uninstall(System.Collections.IDictionary)
  parent: System.Configuration.Install.AssemblyInstaller
  isExternal: false
  name: Uninstall
  nameWithType: AssemblyInstaller.Uninstall
  fullName: System.Configuration.Install.AssemblyInstaller.Uninstall
- uid: System.Void
  parent: System
  isExternal: false
  name: Void
  nameWithType: Void
  fullName: System.Void
- uid: System.Collections.IDictionary
  parent: System.Collections
  isExternal: false
  name: IDictionary
  nameWithType: IDictionary
  fullName: System.Collections.IDictionary
- uid: System.Configuration.Install.AssemblyInstaller.UseNewContext
  parent: System.Configuration.Install.AssemblyInstaller
  isExternal: false
  name: UseNewContext
  nameWithType: AssemblyInstaller.UseNewContext
  fullName: System.Configuration.Install.AssemblyInstaller.UseNewContext
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
