### YamlMime:ManagedReference
items:
- uid: System.Configuration.Install.UninstallAction
  id: UninstallAction
  children:
  - System.Configuration.Install.UninstallAction.NoAction
  - System.Configuration.Install.UninstallAction.Remove
  langs:
  - csharp
  - vb
  name: UninstallAction
  nameWithType: UninstallAction
  fullName: System.Configuration.Install.UninstallAction
  type: Enum
  syntax:
    content: public enum UninstallAction
  inheritance:
  - System.Object
  - System.ValueType
  - System.Enum
- uid: System.Configuration.Install.UninstallAction.NoAction
  id: NoAction
  parent: System.Configuration.Install.UninstallAction
  langs:
  - csharp
  - vb
  name: NoAction
  nameWithType: UninstallAction.NoAction
  fullName: System.Configuration.Install.UninstallAction.NoAction
  type: Field
  assemblies:
  - System.Configuration.Install
  namespace: System.Configuration.Install
  syntax:
    content: NoAction
    return:
      type: System.Configuration.Install.UninstallAction
      description: Return description to be filled
- uid: System.Configuration.Install.UninstallAction.Remove
  id: Remove
  parent: System.Configuration.Install.UninstallAction
  langs:
  - csharp
  - vb
  name: Remove
  nameWithType: UninstallAction.Remove
  fullName: System.Configuration.Install.UninstallAction.Remove
  type: Field
  assemblies:
  - System.Configuration.Install
  namespace: System.Configuration.Install
  syntax:
    content: Remove
    return:
      type: System.Configuration.Install.UninstallAction
      description: Return description to be filled
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Configuration.Install.UninstallAction.NoAction
  parent: System.Configuration.Install.UninstallAction
  isExternal: false
  name: NoAction
  nameWithType: UninstallAction.NoAction
  fullName: System.Configuration.Install.UninstallAction.NoAction
- uid: System.Configuration.Install.UninstallAction
  parent: System.Configuration.Install
  isExternal: false
  name: UninstallAction
  nameWithType: UninstallAction
  fullName: System.Configuration.Install.UninstallAction
- uid: System.Configuration.Install.UninstallAction.Remove
  parent: System.Configuration.Install.UninstallAction
  isExternal: false
  name: Remove
  nameWithType: UninstallAction.Remove
  fullName: System.Configuration.Install.UninstallAction.Remove
- uid: System.Configuration.Install.UninstallAction
  parent: System.Configuration.Install
  isExternal: false
  name: UninstallAction
  nameWithType: UninstallAction
  fullName: System.Configuration.Install.UninstallAction
