### YamlMime:ManagedReference
items:
- uid: System.Configuration.Install.InstallEventArgs
  id: InstallEventArgs
  children:
  - System.Configuration.Install.InstallEventArgs.#ctor
  - System.Configuration.Install.InstallEventArgs.#ctor(System.Collections.IDictionary)
  - System.Configuration.Install.InstallEventArgs.SavedState
  langs:
  - csharp
  name: InstallEventArgs
  nameWithType: InstallEventArgs
  fullName: System.Configuration.Install.InstallEventArgs
  type: Class
  summary: 'Provides data for the events: <see cref="E:System.Configuration.Install.Installer.BeforeInstall">, <xref:System.Configuration.Install.Installer.AfterInstall>, <xref:System.Configuration.Install.Installer.Committing>, <xref:System.Configuration.Install.Installer.Committed>, <xref:System.Configuration.Install.Installer.BeforeRollback>, <xref:System.Configuration.Install.Installer.AfterRollback>, <xref:System.Configuration.Install.Installer.BeforeUninstall>, <xref:System.Configuration.Install.Installer.AfterUninstall>.'
  remarks: InstallEventArgs contains an <xref:System.Collections.IDictionary> that holds information about the current state of the installation. The <xref:System.Configuration.Install.Installer.BeforeInstall>, <xref:System.Configuration.Install.Installer.AfterInstall>, <xref:System.Configuration.Install.Installer.Committing>, <xref:System.Configuration.Install.Installer.Committed>, <xref:System.Configuration.Install.Installer.BeforeRollback>, <xref:System.Configuration.Install.Installer.AfterRollback>, <xref:System.Configuration.Install.Installer.BeforeUninstall>, and <xref:System.Configuration.Install.Installer.AfterUninstall> event handlers use this information.
  example:
  - "The following example demonstrates the <xref:System.Configuration.Install.InstallEventArgs.%23ctor%2A> constructors and the <xref:System.Configuration.Install.InstallEventArgs.SavedState%2A> property of the InstallEventArgs class.  \n  \n There are two new events called `BeforeCommit` and `AfterCommit`. The handlers of these events are invoked from the protected methods named `OnBeforeCommit` and `OnAfterCommit` respectively. These events are raised when the <xref:System.Configuration.Install.Installer.Commit%2A> method is called.  \n  \n [!CODE [InstallEventArgs#1](../CodeSnippet/VS_Snippets_CLR/InstallEventArgs#1)]"
  syntax:
    content: 'public class InstallEventArgs : EventArgs'
  inheritance:
  - System.Object
  - System.EventArgs
  implements: []
  inheritedMembers:
  - System.EventArgs.Empty
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Install.InstallEventArgs.#ctor
  id: '#ctor'
  parent: System.Configuration.Install.InstallEventArgs
  langs:
  - csharp
  name: InstallEventArgs()
  nameWithType: InstallEventArgs.InstallEventArgs()
  fullName: System.Configuration.Install.InstallEventArgs.InstallEventArgs()
  type: Constructor
  assemblies:
  - System.Configuration.Install
  namespace: System.Configuration.Install
  summary: Initializes a new instance of the <see cref="T:System.Configuration.Install.InstallEventArgs"> class, and leaves the <xref:System.Configuration.Install.InstallEventArgs.SavedState%2A> property empty.
  remarks: ''
  example:
  - "The following example demonstrates the InstallEventArgs constructors and the <xref:System.Configuration.Install.InstallEventArgs.SavedState%2A> property of the <xref:System.Configuration.Install.InstallEventArgs> class.  \n  \n There are two new events called `BeforeCommit` and `AfterCommit`. The handlers of these events are invoked from the protected methods named `OnBeforeCommit` and `OnAfterCommit` respectively. These events are raised when the <xref:System.Configuration.Install.Installer.Commit%2A> method is called.  \n  \n [!CODE [InstallEventArgs#1](../CodeSnippet/VS_Snippets_CLR/InstallEventArgs#1)]"
  syntax:
    content: public InstallEventArgs ();
    parameters: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Install.InstallEventArgs.#ctor(System.Collections.IDictionary)
  id: '#ctor(System.Collections.IDictionary)'
  parent: System.Configuration.Install.InstallEventArgs
  langs:
  - csharp
  name: InstallEventArgs(IDictionary)
  nameWithType: InstallEventArgs.InstallEventArgs(IDictionary)
  fullName: System.Configuration.Install.InstallEventArgs.InstallEventArgs(IDictionary)
  type: Constructor
  assemblies:
  - System.Configuration.Install
  namespace: System.Configuration.Install
  summary: Initializes a new instance of the <see cref="T:System.Configuration.Install.InstallEventArgs"> class, and specifies the value for the <xref:System.Configuration.Install.InstallEventArgs.SavedState%2A> property.
  remarks: ''
  example:
  - "The following example demonstrates the <xref:System.Configuration.Install.InstallEventArgs.%23ctor%2A> constructors and the <xref:System.Configuration.Install.InstallEventArgs.SavedState%2A> property of the <xref:System.Configuration.Install.InstallEventArgs> class.  \n  \n There are two new events called `BeforeCommit` and `AfterCommit`. The handlers of these events are invoked from the protected methods named `OnBeforeCommit` and `OnAfterCommit` respectively. These events are raised when the <xref:System.Configuration.Install.Installer.Commit%2A> method is called.  \n  \n [!CODE [InstallEventArgs#1](../CodeSnippet/VS_Snippets_CLR/InstallEventArgs#1)]"
  syntax:
    content: public InstallEventArgs (System.Collections.IDictionary savedState);
    parameters:
    - id: savedState
      type: System.Collections.IDictionary
      description: An <see cref="T:System.Collections.IDictionary"> that represents the current state of the installation.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Install.InstallEventArgs.SavedState
  id: SavedState
  parent: System.Configuration.Install.InstallEventArgs
  langs:
  - csharp
  name: SavedState
  nameWithType: InstallEventArgs.SavedState
  fullName: System.Configuration.Install.InstallEventArgs.SavedState
  type: Property
  assemblies:
  - System.Configuration.Install
  namespace: System.Configuration.Install
  summary: Gets an <see cref="T:System.Collections.IDictionary"> that represents the current state of the installation.
  remarks: ''
  example:
  - "The following example demonstrates the <xref:System.Configuration.Install.InstallEventArgs.%23ctor%2A> constructors and the SavedState property of the <xref:System.Configuration.Install.InstallEventArgs> class.  \n  \n There are two new events called `BeforeCommit` and `AfterCommit`. The handlers of these events are invoked from the protected methods named `OnBeforeCommit` and `OnAfterCommit` respectively. These events are raised when the <xref:System.Configuration.Install.Installer.Commit%2A> method is called.  \n  \n [!CODE [InstallEventArgs#1](../CodeSnippet/VS_Snippets_CLR/InstallEventArgs#1)]"
  syntax:
    content: public System.Collections.IDictionary SavedState { get; }
    return:
      type: System.Collections.IDictionary
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.EventArgs
  isExternal: false
  name: System.EventArgs
- uid: System.Configuration.Install.InstallEventArgs.#ctor
  parent: System.Configuration.Install.InstallEventArgs
  isExternal: false
  name: InstallEventArgs()
  nameWithType: InstallEventArgs.InstallEventArgs()
  fullName: System.Configuration.Install.InstallEventArgs.InstallEventArgs()
- uid: System.Configuration.Install.InstallEventArgs.#ctor(System.Collections.IDictionary)
  parent: System.Configuration.Install.InstallEventArgs
  isExternal: false
  name: InstallEventArgs(IDictionary)
  nameWithType: InstallEventArgs.InstallEventArgs(IDictionary)
  fullName: System.Configuration.Install.InstallEventArgs.InstallEventArgs(IDictionary)
- uid: System.Collections.IDictionary
  parent: System.Collections
  isExternal: false
  name: IDictionary
  nameWithType: IDictionary
  fullName: System.Collections.IDictionary
- uid: System.Configuration.Install.InstallEventArgs.SavedState
  parent: System.Configuration.Install.InstallEventArgs
  isExternal: false
  name: SavedState
  nameWithType: InstallEventArgs.SavedState
  fullName: System.Configuration.Install.InstallEventArgs.SavedState
- uid: System.Collections.IDictionary
  parent: System.Collections
  isExternal: false
  name: IDictionary
  nameWithType: IDictionary
  fullName: System.Collections.IDictionary
