### YamlMime:ManagedReference
items:
- uid: System.Configuration.Install.TransactedInstaller
  id: TransactedInstaller
  children:
  - System.Configuration.Install.TransactedInstaller.#ctor
  - System.Configuration.Install.TransactedInstaller.Install(System.Collections.IDictionary)
  - System.Configuration.Install.TransactedInstaller.Uninstall(System.Collections.IDictionary)
  langs:
  - csharp
  - vb
  name: TransactedInstaller
  nameWithType: TransactedInstaller
  fullName: System.Configuration.Install.TransactedInstaller
  type: Class
  syntax:
    content: 'public class TransactedInstaller : System.Configuration.Install.Installer'
  inheritance:
  - System.ComponentModel.Component
  - System.Configuration.Install.Installer
  implements: []
  inheritedMembers:
  - System.Configuration.Install.Installer.AfterInstall
  - System.Configuration.Install.Installer.AfterRollback
  - System.Configuration.Install.Installer.AfterUninstall
  - System.Configuration.Install.Installer.BeforeInstall
  - System.Configuration.Install.Installer.BeforeRollback
  - System.Configuration.Install.Installer.BeforeUninstall
  - System.Configuration.Install.Installer.Commit(System.Collections.IDictionary)
  - System.Configuration.Install.Installer.Committed
  - System.Configuration.Install.Installer.Committing
  - System.Configuration.Install.Installer.Context
  - System.Configuration.Install.Installer.HelpText
  - System.Configuration.Install.Installer.Installers
  - System.Configuration.Install.Installer.OnAfterInstall(System.Collections.IDictionary)
  - System.Configuration.Install.Installer.OnAfterRollback(System.Collections.IDictionary)
  - System.Configuration.Install.Installer.OnAfterUninstall(System.Collections.IDictionary)
  - System.Configuration.Install.Installer.OnBeforeInstall(System.Collections.IDictionary)
  - System.Configuration.Install.Installer.OnBeforeRollback(System.Collections.IDictionary)
  - System.Configuration.Install.Installer.OnBeforeUninstall(System.Collections.IDictionary)
  - System.Configuration.Install.Installer.OnCommitted(System.Collections.IDictionary)
  - System.Configuration.Install.Installer.OnCommitting(System.Collections.IDictionary)
  - System.Configuration.Install.Installer.Parent
  - System.Configuration.Install.Installer.Rollback(System.Collections.IDictionary)
- uid: System.Configuration.Install.TransactedInstaller.#ctor
  id: '#ctor'
  parent: System.Configuration.Install.TransactedInstaller
  langs:
  - csharp
  - vb
  name: .ctor
  nameWithType: TransactedInstaller..ctor
  fullName: System.Configuration.Install.TransactedInstaller..ctor
  type: Constructor
  assemblies:
  - System.Configuration.Install
  namespace: System.Configuration.Install
  syntax:
    content: public TransactedInstaller ();
    parameters: []
- uid: System.Configuration.Install.TransactedInstaller.Install(System.Collections.IDictionary)
  id: Install(System.Collections.IDictionary)
  parent: System.Configuration.Install.TransactedInstaller
  langs:
  - csharp
  - vb
  name: Install
  nameWithType: TransactedInstaller.Install
  fullName: System.Configuration.Install.TransactedInstaller.Install
  type: Method
  assemblies:
  - System.Configuration.Install
  namespace: System.Configuration.Install
  syntax:
    content: public override void Install (System.Collections.IDictionary savedState);
    parameters:
    - id: savedState
      type: System.Collections.IDictionary
      description: Parameter description to be filled
    return:
      type: System.Void
      description: Return description to be filled
- uid: System.Configuration.Install.TransactedInstaller.Uninstall(System.Collections.IDictionary)
  id: Uninstall(System.Collections.IDictionary)
  parent: System.Configuration.Install.TransactedInstaller
  langs:
  - csharp
  - vb
  name: Uninstall
  nameWithType: TransactedInstaller.Uninstall
  fullName: System.Configuration.Install.TransactedInstaller.Uninstall
  type: Method
  assemblies:
  - System.Configuration.Install
  namespace: System.Configuration.Install
  syntax:
    content: public override void Uninstall (System.Collections.IDictionary savedState);
    parameters:
    - id: savedState
      type: System.Collections.IDictionary
      description: Parameter description to be filled
    return:
      type: System.Void
      description: Return description to be filled
references:
- uid: System.Configuration.Install.Installer
  isExternal: false
  name: System.Configuration.Install.Installer
- uid: System.Configuration.Install.TransactedInstaller.#ctor
  parent: System.Configuration.Install.TransactedInstaller
  isExternal: false
  name: .ctor
  nameWithType: TransactedInstaller..ctor
  fullName: System.Configuration.Install.TransactedInstaller..ctor
- uid: System.Configuration.Install.TransactedInstaller.Install(System.Collections.IDictionary)
  parent: System.Configuration.Install.TransactedInstaller
  isExternal: false
  name: Install
  nameWithType: TransactedInstaller.Install
  fullName: System.Configuration.Install.TransactedInstaller.Install
- uid: System.Void
  parent: System
  isExternal: false
  name: Void
  nameWithType: Void
  fullName: System.Void
- uid: System.Collections.IDictionary
  parent: System.Collections
  isExternal: false
  name: IDictionary
  nameWithType: IDictionary
  fullName: System.Collections.IDictionary
- uid: System.Configuration.Install.TransactedInstaller.Uninstall(System.Collections.IDictionary)
  parent: System.Configuration.Install.TransactedInstaller
  isExternal: false
  name: Uninstall
  nameWithType: TransactedInstaller.Uninstall
  fullName: System.Configuration.Install.TransactedInstaller.Uninstall
- uid: System.Void
  parent: System
  isExternal: false
  name: Void
  nameWithType: Void
  fullName: System.Void
- uid: System.Collections.IDictionary
  parent: System.Collections
  isExternal: false
  name: IDictionary
  nameWithType: IDictionary
  fullName: System.Collections.IDictionary
