### YamlMime:ManagedReference
items:
- uid: System.Configuration.Install.InstallContext
  id: InstallContext
  children:
  - System.Configuration.Install.InstallContext.#ctor
  - System.Configuration.Install.InstallContext.#ctor(System.String,System.String[])
  - System.Configuration.Install.InstallContext.IsParameterTrue(System.String)
  - System.Configuration.Install.InstallContext.LogMessage(System.String)
  - System.Configuration.Install.InstallContext.Parameters
  - System.Configuration.Install.InstallContext.ParseCommandLine(System.String[])
  langs:
  - csharp
  - vb
  name: InstallContext
  nameWithType: InstallContext
  fullName: System.Configuration.Install.InstallContext
  type: Class
  syntax:
    content: public class InstallContext
  inheritance:
  - System.Object
  implements: []
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: System.Configuration.Install.InstallContext.#ctor
  id: '#ctor'
  parent: System.Configuration.Install.InstallContext
  langs:
  - csharp
  - vb
  name: .ctor
  nameWithType: InstallContext..ctor
  fullName: System.Configuration.Install.InstallContext..ctor
  type: Constructor
  assemblies:
  - System.Configuration.Install
  namespace: System.Configuration.Install
  syntax:
    content: public InstallContext ();
    parameters: []
- uid: System.Configuration.Install.InstallContext.#ctor(System.String,System.String[])
  id: '#ctor(System.String,System.String[])'
  parent: System.Configuration.Install.InstallContext
  langs:
  - csharp
  - vb
  name: .ctor
  nameWithType: InstallContext..ctor
  fullName: System.Configuration.Install.InstallContext..ctor
  type: Constructor
  assemblies:
  - System.Configuration.Install
  namespace: System.Configuration.Install
  syntax:
    content: public InstallContext (string logFilePath, string[] commandLine);
    parameters:
    - id: logFilePath
      type: System.String
      description: Parameter description to be filled
    - id: commandLine
      type: System.String[]
      description: Parameter description to be filled
- uid: System.Configuration.Install.InstallContext.IsParameterTrue(System.String)
  id: IsParameterTrue(System.String)
  parent: System.Configuration.Install.InstallContext
  langs:
  - csharp
  - vb
  name: IsParameterTrue
  nameWithType: InstallContext.IsParameterTrue
  fullName: System.Configuration.Install.InstallContext.IsParameterTrue
  type: Method
  assemblies:
  - System.Configuration.Install
  namespace: System.Configuration.Install
  syntax:
    content: public bool IsParameterTrue (string paramName);
    parameters:
    - id: paramName
      type: System.String
      description: Parameter description to be filled
    return:
      type: System.Boolean
      description: Return description to be filled
- uid: System.Configuration.Install.InstallContext.LogMessage(System.String)
  id: LogMessage(System.String)
  parent: System.Configuration.Install.InstallContext
  langs:
  - csharp
  - vb
  name: LogMessage
  nameWithType: InstallContext.LogMessage
  fullName: System.Configuration.Install.InstallContext.LogMessage
  type: Method
  assemblies:
  - System.Configuration.Install
  namespace: System.Configuration.Install
  syntax:
    content: public void LogMessage (string message);
    parameters:
    - id: message
      type: System.String
      description: Parameter description to be filled
    return:
      type: System.Void
      description: Return description to be filled
- uid: System.Configuration.Install.InstallContext.Parameters
  id: Parameters
  parent: System.Configuration.Install.InstallContext
  langs:
  - csharp
  - vb
  name: Parameters
  nameWithType: InstallContext.Parameters
  fullName: System.Configuration.Install.InstallContext.Parameters
  type: Property
  assemblies:
  - System.Configuration.Install
  namespace: System.Configuration.Install
  syntax:
    content: public System.Collections.Specialized.StringDictionary Parameters { get; }
    return:
      type: System.Collections.Specialized.StringDictionary
      description: Return description to be filled
- uid: System.Configuration.Install.InstallContext.ParseCommandLine(System.String[])
  id: ParseCommandLine(System.String[])
  parent: System.Configuration.Install.InstallContext
  langs:
  - csharp
  - vb
  name: ParseCommandLine
  nameWithType: InstallContext.ParseCommandLine
  fullName: System.Configuration.Install.InstallContext.ParseCommandLine
  type: Method
  assemblies:
  - System.Configuration.Install
  namespace: System.Configuration.Install
  syntax:
    content: protected static System.Collections.Specialized.StringDictionary ParseCommandLine (string[] args);
    parameters:
    - id: args
      type: System.String[]
      description: Parameter description to be filled
    return:
      type: System.Collections.Specialized.StringDictionary
      description: Return description to be filled
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Configuration.Install.InstallContext.#ctor
  parent: System.Configuration.Install.InstallContext
  isExternal: false
  name: .ctor
  nameWithType: InstallContext..ctor
  fullName: System.Configuration.Install.InstallContext..ctor
- uid: System.Configuration.Install.InstallContext.#ctor(System.String,System.String[])
  parent: System.Configuration.Install.InstallContext
  isExternal: false
  name: .ctor
  nameWithType: InstallContext..ctor
  fullName: System.Configuration.Install.InstallContext..ctor
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.Install.InstallContext.IsParameterTrue(System.String)
  parent: System.Configuration.Install.InstallContext
  isExternal: false
  name: IsParameterTrue
  nameWithType: InstallContext.IsParameterTrue
  fullName: System.Configuration.Install.InstallContext.IsParameterTrue
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.Install.InstallContext.LogMessage(System.String)
  parent: System.Configuration.Install.InstallContext
  isExternal: false
  name: LogMessage
  nameWithType: InstallContext.LogMessage
  fullName: System.Configuration.Install.InstallContext.LogMessage
- uid: System.Void
  parent: System
  isExternal: false
  name: Void
  nameWithType: Void
  fullName: System.Void
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.Install.InstallContext.Parameters
  parent: System.Configuration.Install.InstallContext
  isExternal: false
  name: Parameters
  nameWithType: InstallContext.Parameters
  fullName: System.Configuration.Install.InstallContext.Parameters
- uid: System.Configuration.Install.InstallContext.ParseCommandLine(System.String[])
  parent: System.Configuration.Install.InstallContext
  isExternal: false
  name: ParseCommandLine
  nameWithType: InstallContext.ParseCommandLine
  fullName: System.Configuration.Install.InstallContext.ParseCommandLine
