### YamlMime:ManagedReference
items:
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.UpdateUnit
  id: UpdateUnit
  children:
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.UpdateUnit.Days
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.UpdateUnit.Hours
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.UpdateUnit.Weeks
  langs:
  - csharp
  - vb
  name: UpdateUnit
  nameWithType: UpdateUnit
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.UpdateUnit
  type: Enum
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(false)]

      public enum UpdateUnit
  inheritance:
  - System.Object
  - System.ValueType
  - System.Enum
  inheritedMembers:
  - System.Enum.CompareTo(System.Object)
  - System.Enum.Equals(System.Object)
  - System.Enum.Format(System.Type,System.Object,System.String)
  - System.Enum.GetHashCode
  - System.Enum.GetName(System.Type,System.Object)
  - System.Enum.GetNames(System.Type)
  - System.Enum.GetTypeCode
  - System.Enum.GetUnderlyingType(System.Type)
  - System.Enum.GetValues(System.Type)
  - System.Enum.HasFlag(System.Enum)
  - System.Enum.IsDefined(System.Type,System.Object)
  - System.Enum.Parse(System.Type,System.String)
  - System.Enum.Parse(System.Type,System.String,System.Boolean)
  - System.Enum.System#IConvertible#ToBoolean(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToByte(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToChar(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToDateTime(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToDecimal(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToDouble(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToInt16(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToInt32(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToInt64(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToSByte(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToSingle(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToType(System.Type,System.IFormatProvider)
  - System.Enum.System#IConvertible#ToUInt16(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToUInt32(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToUInt64(System.IFormatProvider)
  - System.Enum.ToObject(System.Type,System.Byte)
  - System.Enum.ToObject(System.Type,System.Int16)
  - System.Enum.ToObject(System.Type,System.Int32)
  - System.Enum.ToObject(System.Type,System.Int64)
  - System.Enum.ToObject(System.Type,System.Object)
  - System.Enum.ToObject(System.Type,System.SByte)
  - System.Enum.ToObject(System.Type,System.UInt16)
  - System.Enum.ToObject(System.Type,System.UInt32)
  - System.Enum.ToObject(System.Type,System.UInt64)
  - System.Enum.ToString
  - System.Enum.ToString(System.IFormatProvider)
  - System.Enum.ToString(System.String)
  - System.Enum.ToString(System.String,System.IFormatProvider)
  - System.Enum.TryParse``1(System.String,``0@)
  - System.Enum.TryParse``1(System.String,System.Boolean,``0@)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.UpdateUnit.Days
  id: Days
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.UpdateUnit
  langs:
  - csharp
  - vb
  name: Days
  nameWithType: UpdateUnit.Days
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.UpdateUnit.Days
  type: Field
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  syntax:
    content: Days
    return:
      type: Microsoft.Build.Tasks.Deployment.ManifestUtilities.UpdateUnit
      description: Return description to be filled
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.UpdateUnit.Hours
  id: Hours
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.UpdateUnit
  langs:
  - csharp
  - vb
  name: Hours
  nameWithType: UpdateUnit.Hours
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.UpdateUnit.Hours
  type: Field
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  syntax:
    content: Hours
    return:
      type: Microsoft.Build.Tasks.Deployment.ManifestUtilities.UpdateUnit
      description: Return description to be filled
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.UpdateUnit.Weeks
  id: Weeks
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.UpdateUnit
  langs:
  - csharp
  - vb
  name: Weeks
  nameWithType: UpdateUnit.Weeks
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.UpdateUnit.Weeks
  type: Field
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  syntax:
    content: Weeks
    return:
      type: Microsoft.Build.Tasks.Deployment.ManifestUtilities.UpdateUnit
      description: Return description to be filled
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.UpdateUnit.Days
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.UpdateUnit
  isExternal: false
  name: Days
  nameWithType: UpdateUnit.Days
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.UpdateUnit.Days
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.UpdateUnit
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  isExternal: false
  name: UpdateUnit
  nameWithType: UpdateUnit
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.UpdateUnit
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.UpdateUnit.Hours
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.UpdateUnit
  isExternal: false
  name: Hours
  nameWithType: UpdateUnit.Hours
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.UpdateUnit.Hours
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.UpdateUnit
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  isExternal: false
  name: UpdateUnit
  nameWithType: UpdateUnit
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.UpdateUnit
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.UpdateUnit.Weeks
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.UpdateUnit
  isExternal: false
  name: Weeks
  nameWithType: UpdateUnit.Weeks
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.UpdateUnit.Weeks
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.UpdateUnit
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  isExternal: false
  name: UpdateUnit
  nameWithType: UpdateUnit
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.UpdateUnit
