### YamlMime:ManagedReference
items:
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageType
  id: OutputMessageType
  children:
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageType.Error
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageType.Info
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageType.Warning
  langs:
  - csharp
  - vb
  name: OutputMessageType
  nameWithType: OutputMessageType
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageType
  type: Enum
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(false)]

      public enum OutputMessageType
  inheritance:
  - System.Object
  - System.ValueType
  - System.Enum
  inheritedMembers:
  - System.Enum.CompareTo(System.Object)
  - System.Enum.Equals(System.Object)
  - System.Enum.Format(System.Type,System.Object,System.String)
  - System.Enum.GetHashCode
  - System.Enum.GetName(System.Type,System.Object)
  - System.Enum.GetNames(System.Type)
  - System.Enum.GetTypeCode
  - System.Enum.GetUnderlyingType(System.Type)
  - System.Enum.GetValues(System.Type)
  - System.Enum.HasFlag(System.Enum)
  - System.Enum.IsDefined(System.Type,System.Object)
  - System.Enum.Parse(System.Type,System.String)
  - System.Enum.Parse(System.Type,System.String,System.Boolean)
  - System.Enum.System#IConvertible#ToBoolean(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToByte(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToChar(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToDateTime(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToDecimal(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToDouble(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToInt16(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToInt32(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToInt64(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToSByte(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToSingle(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToType(System.Type,System.IFormatProvider)
  - System.Enum.System#IConvertible#ToUInt16(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToUInt32(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToUInt64(System.IFormatProvider)
  - System.Enum.ToObject(System.Type,System.Byte)
  - System.Enum.ToObject(System.Type,System.Int16)
  - System.Enum.ToObject(System.Type,System.Int32)
  - System.Enum.ToObject(System.Type,System.Int64)
  - System.Enum.ToObject(System.Type,System.Object)
  - System.Enum.ToObject(System.Type,System.SByte)
  - System.Enum.ToObject(System.Type,System.UInt16)
  - System.Enum.ToObject(System.Type,System.UInt32)
  - System.Enum.ToObject(System.Type,System.UInt64)
  - System.Enum.ToString
  - System.Enum.ToString(System.IFormatProvider)
  - System.Enum.ToString(System.String)
  - System.Enum.ToString(System.String,System.IFormatProvider)
  - System.Enum.TryParse``1(System.String,``0@)
  - System.Enum.TryParse``1(System.String,System.Boolean,``0@)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageType.Error
  id: Error
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageType
  langs:
  - csharp
  - vb
  name: Error
  nameWithType: OutputMessageType.Error
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageType.Error
  type: Field
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  syntax:
    content: Error
    return:
      type: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageType
      description: Return description to be filled
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageType.Info
  id: Info
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageType
  langs:
  - csharp
  - vb
  name: Info
  nameWithType: OutputMessageType.Info
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageType.Info
  type: Field
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  syntax:
    content: Info
    return:
      type: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageType
      description: Return description to be filled
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageType.Warning
  id: Warning
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageType
  langs:
  - csharp
  - vb
  name: Warning
  nameWithType: OutputMessageType.Warning
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageType.Warning
  type: Field
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  syntax:
    content: Warning
    return:
      type: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageType
      description: Return description to be filled
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageType.Error
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageType
  isExternal: false
  name: Error
  nameWithType: OutputMessageType.Error
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageType.Error
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageType
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  isExternal: false
  name: OutputMessageType
  nameWithType: OutputMessageType
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageType
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageType.Info
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageType
  isExternal: false
  name: Info
  nameWithType: OutputMessageType.Info
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageType.Info
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageType
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  isExternal: false
  name: OutputMessageType
  nameWithType: OutputMessageType
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageType
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageType.Warning
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageType
  isExternal: false
  name: Warning
  nameWithType: OutputMessageType.Warning
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageType.Warning
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageType
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  isExternal: false
  name: OutputMessageType
  nameWithType: OutputMessageType
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageType
