### YamlMime:ManagedReference
items:
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection
  id: OutputMessageCollection
  children:
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection.Clear
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection.ErrorCount
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection.GetEnumerator
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection.Item(System.Int32)
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection.WarningCount
  langs:
  - csharp
  - vb
  name: OutputMessageCollection
  nameWithType: OutputMessageCollection
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection
  type: Class
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(false)]

      public sealed class OutputMessageCollection : System.Collections.IEnumerable
  inheritance:
  - System.Object
  implements:
  - System.Collections.IEnumerable
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection.Clear
  id: Clear
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection
  langs:
  - csharp
  - vb
  name: Clear
  nameWithType: OutputMessageCollection.Clear
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection.Clear
  type: Method
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  syntax:
    content: public void Clear ();
    parameters: []
    return:
      type: System.Void
      description: Return description to be filled
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection.ErrorCount
  id: ErrorCount
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection
  langs:
  - csharp
  - vb
  name: ErrorCount
  nameWithType: OutputMessageCollection.ErrorCount
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection.ErrorCount
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  syntax:
    content: public int ErrorCount { get; }
    return:
      type: System.Int32
      description: Return description to be filled
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection.GetEnumerator
  id: GetEnumerator
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection
  langs:
  - csharp
  - vb
  name: GetEnumerator
  nameWithType: OutputMessageCollection.GetEnumerator
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection.GetEnumerator
  type: Method
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  syntax:
    content: public System.Collections.IEnumerator GetEnumerator ();
    parameters: []
    return:
      type: System.Collections.IEnumerator
      description: Return description to be filled
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection.Item(System.Int32)
  id: Item(System.Int32)
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection
  langs:
  - csharp
  - vb
  name: Item
  nameWithType: OutputMessageCollection.Item
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection.Item
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  syntax:
    content: public Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessage this[int index] { get; }
    parameters:
    - id: index
      type: System.Int32
      description: Parameter description to be filled
    return:
      type: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessage
      description: Return description to be filled
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection.WarningCount
  id: WarningCount
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection
  langs:
  - csharp
  - vb
  name: WarningCount
  nameWithType: OutputMessageCollection.WarningCount
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection.WarningCount
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  syntax:
    content: public int WarningCount { get; }
    return:
      type: System.Int32
      description: Return description to be filled
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection.Clear
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection
  isExternal: false
  name: Clear
  nameWithType: OutputMessageCollection.Clear
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection.Clear
- uid: System.Void
  parent: System
  isExternal: false
  name: Void
  nameWithType: Void
  fullName: System.Void
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection.ErrorCount
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection
  isExternal: false
  name: ErrorCount
  nameWithType: OutputMessageCollection.ErrorCount
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection.ErrorCount
- uid: System.Int32
  parent: System
  isExternal: false
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection.GetEnumerator
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection
  isExternal: false
  name: GetEnumerator
  nameWithType: OutputMessageCollection.GetEnumerator
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection.GetEnumerator
- uid: System.Collections.IEnumerator
  parent: System.Collections
  isExternal: false
  name: IEnumerator
  nameWithType: IEnumerator
  fullName: System.Collections.IEnumerator
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection.Item(System.Int32)
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection
  isExternal: false
  name: Item
  nameWithType: OutputMessageCollection.Item
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection.Item
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessage
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  isExternal: false
  name: OutputMessage
  nameWithType: OutputMessage
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessage
- uid: System.Int32
  parent: System
  isExternal: false
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection.WarningCount
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection
  isExternal: false
  name: WarningCount
  nameWithType: OutputMessageCollection.WarningCount
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection.WarningCount
- uid: System.Int32
  parent: System
  isExternal: false
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
