### YamlMime:ManagedReference
items:
- uid: System.Windows.Automation
  id: System.Windows.Automation
  children:
  - System.Windows.Automation.AutomationProperties
  - System.Windows.Automation.IsOffscreenBehavior
  langs:
  - csharp
  - vb
  name: System.Windows.Automation
  nameWithType: System.Windows.Automation
  fullName: System.Windows.Automation
  type: Namespace
references:
- uid: System.Windows.Automation.AutomationProperties
  parent: System.Windows.Automation
  isExternal: false
  name: AutomationProperties
  nameWithType: AutomationProperties
  fullName: System.Windows.Automation.AutomationProperties
- uid: System.Windows.Automation.IsOffscreenBehavior
  parent: System.Windows.Automation
  isExternal: false
  name: IsOffscreenBehavior
  nameWithType: IsOffscreenBehavior
  fullName: System.Windows.Automation.IsOffscreenBehavior
