### YamlMime:ManagedReference
items:
- uid: System.Configuration.Assemblies.AssemblyHash
  id: AssemblyHash
  children:
  - System.Configuration.Assemblies.AssemblyHash.#ctor(System.Byte[])
  - System.Configuration.Assemblies.AssemblyHash.#ctor(System.Configuration.Assemblies.AssemblyHashAlgorithm,System.Byte[])
  - System.Configuration.Assemblies.AssemblyHash.Algorithm
  - System.Configuration.Assemblies.AssemblyHash.Clone
  - System.Configuration.Assemblies.AssemblyHash.Empty
  - System.Configuration.Assemblies.AssemblyHash.GetValue
  - System.Configuration.Assemblies.AssemblyHash.SetValue(System.Byte[])
  langs:
  - csharp
  - vb
  name: AssemblyHash
  nameWithType: AssemblyHash
  fullName: System.Configuration.Assemblies.AssemblyHash
  type: Struct
  syntax:
    content: >-
      [System.Obsolete("The AssemblyHash class has been deprecated. http://go.microsoft.com/fwlink/?linkid=14202")]

      [System.Runtime.InteropServices.ComVisible(true)]

      public struct AssemblyHash : ICloneable
  inheritance:
  - System.Object
  - System.ValueType
  implements:
  - System.ICloneable
  inheritedMembers:
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.ValueType.Equals(System.Object)
  - System.ValueType.GetHashCode
  - System.ValueType.ToString
- uid: System.Configuration.Assemblies.AssemblyHash.#ctor(System.Byte[])
  id: '#ctor(System.Byte[])'
  parent: System.Configuration.Assemblies.AssemblyHash
  langs:
  - csharp
  - vb
  name: .ctor
  nameWithType: AssemblyHash..ctor
  fullName: System.Configuration.Assemblies.AssemblyHash..ctor
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System.Configuration.Assemblies
  syntax:
    content: public AssemblyHash (byte[] value);
    parameters:
    - id: value
      type: System.Byte[]
      description: Parameter description to be filled
- uid: System.Configuration.Assemblies.AssemblyHash.#ctor(System.Configuration.Assemblies.AssemblyHashAlgorithm,System.Byte[])
  id: '#ctor(System.Configuration.Assemblies.AssemblyHashAlgorithm,System.Byte[])'
  parent: System.Configuration.Assemblies.AssemblyHash
  langs:
  - csharp
  - vb
  name: .ctor
  nameWithType: AssemblyHash..ctor
  fullName: System.Configuration.Assemblies.AssemblyHash..ctor
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System.Configuration.Assemblies
  syntax:
    content: public AssemblyHash (System.Configuration.Assemblies.AssemblyHashAlgorithm algorithm, byte[] value);
    parameters:
    - id: algorithm
      type: System.Configuration.Assemblies.AssemblyHashAlgorithm
      description: Parameter description to be filled
    - id: value
      type: System.Byte[]
      description: Parameter description to be filled
- uid: System.Configuration.Assemblies.AssemblyHash.Algorithm
  id: Algorithm
  parent: System.Configuration.Assemblies.AssemblyHash
  langs:
  - csharp
  - vb
  name: Algorithm
  nameWithType: AssemblyHash.Algorithm
  fullName: System.Configuration.Assemblies.AssemblyHash.Algorithm
  type: Property
  assemblies:
  - mscorlib
  namespace: System.Configuration.Assemblies
  syntax:
    content: public System.Configuration.Assemblies.AssemblyHashAlgorithm Algorithm { get; set; }
    return:
      type: System.Configuration.Assemblies.AssemblyHashAlgorithm
      description: Return description to be filled
- uid: System.Configuration.Assemblies.AssemblyHash.Clone
  id: Clone
  parent: System.Configuration.Assemblies.AssemblyHash
  langs:
  - csharp
  - vb
  name: Clone
  nameWithType: AssemblyHash.Clone
  fullName: System.Configuration.Assemblies.AssemblyHash.Clone
  type: Method
  assemblies:
  - mscorlib
  namespace: System.Configuration.Assemblies
  syntax:
    content: public object Clone ();
    parameters: []
    return:
      type: System.Object
      description: Return description to be filled
- uid: System.Configuration.Assemblies.AssemblyHash.Empty
  id: Empty
  parent: System.Configuration.Assemblies.AssemblyHash
  langs:
  - csharp
  - vb
  name: Empty
  nameWithType: AssemblyHash.Empty
  fullName: System.Configuration.Assemblies.AssemblyHash.Empty
  type: Field
  assemblies:
  - mscorlib
  namespace: System.Configuration.Assemblies
  syntax:
    content: public static readonly System.Configuration.Assemblies.AssemblyHash Empty;
    return:
      type: System.Configuration.Assemblies.AssemblyHash
      description: Return description to be filled
- uid: System.Configuration.Assemblies.AssemblyHash.GetValue
  id: GetValue
  parent: System.Configuration.Assemblies.AssemblyHash
  langs:
  - csharp
  - vb
  name: GetValue
  nameWithType: AssemblyHash.GetValue
  fullName: System.Configuration.Assemblies.AssemblyHash.GetValue
  type: Method
  assemblies:
  - mscorlib
  namespace: System.Configuration.Assemblies
  syntax:
    content: public byte[] GetValue ();
    parameters: []
    return:
      type: System.Byte[]
      description: Return description to be filled
- uid: System.Configuration.Assemblies.AssemblyHash.SetValue(System.Byte[])
  id: SetValue(System.Byte[])
  parent: System.Configuration.Assemblies.AssemblyHash
  langs:
  - csharp
  - vb
  name: SetValue
  nameWithType: AssemblyHash.SetValue
  fullName: System.Configuration.Assemblies.AssemblyHash.SetValue
  type: Method
  assemblies:
  - mscorlib
  namespace: System.Configuration.Assemblies
  syntax:
    content: public void SetValue (byte[] value);
    parameters:
    - id: value
      type: System.Byte[]
      description: Parameter description to be filled
    return:
      type: System.Void
      description: Return description to be filled
references:
- uid: System.ValueType
  isExternal: false
  name: System.ValueType
- uid: System.Configuration.Assemblies.AssemblyHash.#ctor(System.Byte[])
  parent: System.Configuration.Assemblies.AssemblyHash
  isExternal: false
  name: .ctor
  nameWithType: AssemblyHash..ctor
  fullName: System.Configuration.Assemblies.AssemblyHash..ctor
- uid: System.Configuration.Assemblies.AssemblyHash.#ctor(System.Configuration.Assemblies.AssemblyHashAlgorithm,System.Byte[])
  parent: System.Configuration.Assemblies.AssemblyHash
  isExternal: false
  name: .ctor
  nameWithType: AssemblyHash..ctor
  fullName: System.Configuration.Assemblies.AssemblyHash..ctor
- uid: System.Configuration.Assemblies.AssemblyHashAlgorithm
  parent: System.Configuration.Assemblies
  isExternal: false
  name: AssemblyHashAlgorithm
  nameWithType: AssemblyHashAlgorithm
  fullName: System.Configuration.Assemblies.AssemblyHashAlgorithm
- uid: System.Configuration.Assemblies.AssemblyHash.Algorithm
  parent: System.Configuration.Assemblies.AssemblyHash
  isExternal: false
  name: Algorithm
  nameWithType: AssemblyHash.Algorithm
  fullName: System.Configuration.Assemblies.AssemblyHash.Algorithm
- uid: System.Configuration.Assemblies.AssemblyHashAlgorithm
  parent: System.Configuration.Assemblies
  isExternal: false
  name: AssemblyHashAlgorithm
  nameWithType: AssemblyHashAlgorithm
  fullName: System.Configuration.Assemblies.AssemblyHashAlgorithm
- uid: System.Configuration.Assemblies.AssemblyHash.Clone
  parent: System.Configuration.Assemblies.AssemblyHash
  isExternal: false
  name: Clone
  nameWithType: AssemblyHash.Clone
  fullName: System.Configuration.Assemblies.AssemblyHash.Clone
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Configuration.Assemblies.AssemblyHash.Empty
  parent: System.Configuration.Assemblies.AssemblyHash
  isExternal: false
  name: Empty
  nameWithType: AssemblyHash.Empty
  fullName: System.Configuration.Assemblies.AssemblyHash.Empty
- uid: System.Configuration.Assemblies.AssemblyHash
  parent: System.Configuration.Assemblies
  isExternal: false
  name: AssemblyHash
  nameWithType: AssemblyHash
  fullName: System.Configuration.Assemblies.AssemblyHash
- uid: System.Configuration.Assemblies.AssemblyHash.GetValue
  parent: System.Configuration.Assemblies.AssemblyHash
  isExternal: false
  name: GetValue
  nameWithType: AssemblyHash.GetValue
  fullName: System.Configuration.Assemblies.AssemblyHash.GetValue
- uid: System.Configuration.Assemblies.AssemblyHash.SetValue(System.Byte[])
  parent: System.Configuration.Assemblies.AssemblyHash
  isExternal: false
  name: SetValue
  nameWithType: AssemblyHash.SetValue
  fullName: System.Configuration.Assemblies.AssemblyHash.SetValue
- uid: System.Void
  parent: System
  isExternal: false
  name: Void
  nameWithType: Void
  fullName: System.Void
