### YamlMime:ManagedReference
items:
- uid: Microsoft.Build.BuildEngine.BuildSettings
  id: BuildSettings
  children:
  - Microsoft.Build.BuildEngine.BuildSettings.DoNotResetPreviouslyBuiltTargets
  - Microsoft.Build.BuildEngine.BuildSettings.None
  langs:
  - csharp
  - vb
  name: BuildSettings
  nameWithType: BuildSettings
  fullName: Microsoft.Build.BuildEngine.BuildSettings
  type: Enum
  syntax:
    content: >-
      [System.Flags]

      public enum BuildSettings
  inheritance:
  - System.Object
  - System.ValueType
  - System.Enum
- uid: Microsoft.Build.BuildEngine.BuildSettings.DoNotResetPreviouslyBuiltTargets
  id: DoNotResetPreviouslyBuiltTargets
  parent: Microsoft.Build.BuildEngine.BuildSettings
  langs:
  - csharp
  - vb
  name: DoNotResetPreviouslyBuiltTargets
  nameWithType: BuildSettings.DoNotResetPreviouslyBuiltTargets
  fullName: Microsoft.Build.BuildEngine.BuildSettings.DoNotResetPreviouslyBuiltTargets
  type: Field
  assemblies:
  - Microsoft.Build.Engine
  namespace: Microsoft.Build.BuildEngine
  syntax:
    content: DoNotResetPreviouslyBuiltTargets
    return:
      type: Microsoft.Build.BuildEngine.BuildSettings
      description: Return description to be filled
- uid: Microsoft.Build.BuildEngine.BuildSettings.None
  id: None
  parent: Microsoft.Build.BuildEngine.BuildSettings
  langs:
  - csharp
  - vb
  name: None
  nameWithType: BuildSettings.None
  fullName: Microsoft.Build.BuildEngine.BuildSettings.None
  type: Field
  assemblies:
  - Microsoft.Build.Engine
  namespace: Microsoft.Build.BuildEngine
  syntax:
    content: None
    return:
      type: Microsoft.Build.BuildEngine.BuildSettings
      description: Return description to be filled
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: Microsoft.Build.BuildEngine.BuildSettings.DoNotResetPreviouslyBuiltTargets
  parent: Microsoft.Build.BuildEngine.BuildSettings
  isExternal: false
  name: DoNotResetPreviouslyBuiltTargets
  nameWithType: BuildSettings.DoNotResetPreviouslyBuiltTargets
  fullName: Microsoft.Build.BuildEngine.BuildSettings.DoNotResetPreviouslyBuiltTargets
- uid: Microsoft.Build.BuildEngine.BuildSettings
  parent: Microsoft.Build.BuildEngine
  isExternal: false
  name: BuildSettings
  nameWithType: BuildSettings
  fullName: Microsoft.Build.BuildEngine.BuildSettings
- uid: Microsoft.Build.BuildEngine.BuildSettings.None
  parent: Microsoft.Build.BuildEngine.BuildSettings
  isExternal: false
  name: None
  nameWithType: BuildSettings.None
  fullName: Microsoft.Build.BuildEngine.BuildSettings.None
- uid: Microsoft.Build.BuildEngine.BuildSettings
  parent: Microsoft.Build.BuildEngine
  isExternal: false
  name: BuildSettings
  nameWithType: BuildSettings
  fullName: Microsoft.Build.BuildEngine.BuildSettings
