### YamlMime:ManagedReference
items:
- uid: Microsoft.Build.BuildEngine.ProjectLoadSettings
  id: ProjectLoadSettings
  children:
  - Microsoft.Build.BuildEngine.ProjectLoadSettings.IgnoreMissingImports
  - Microsoft.Build.BuildEngine.ProjectLoadSettings.None
  langs:
  - csharp
  - vb
  name: ProjectLoadSettings
  nameWithType: ProjectLoadSettings
  fullName: Microsoft.Build.BuildEngine.ProjectLoadSettings
  type: Enum
  syntax:
    content: >-
      [System.Flags]

      public enum ProjectLoadSettings
  inheritance:
  - System.Object
  - System.ValueType
  - System.Enum
- uid: Microsoft.Build.BuildEngine.ProjectLoadSettings.IgnoreMissingImports
  id: IgnoreMissingImports
  parent: Microsoft.Build.BuildEngine.ProjectLoadSettings
  langs:
  - csharp
  - vb
  name: IgnoreMissingImports
  nameWithType: ProjectLoadSettings.IgnoreMissingImports
  fullName: Microsoft.Build.BuildEngine.ProjectLoadSettings.IgnoreMissingImports
  type: Field
  assemblies:
  - Microsoft.Build.Engine
  namespace: Microsoft.Build.BuildEngine
  syntax:
    content: IgnoreMissingImports
    return:
      type: Microsoft.Build.BuildEngine.ProjectLoadSettings
      description: Return description to be filled
- uid: Microsoft.Build.BuildEngine.ProjectLoadSettings.None
  id: None
  parent: Microsoft.Build.BuildEngine.ProjectLoadSettings
  langs:
  - csharp
  - vb
  name: None
  nameWithType: ProjectLoadSettings.None
  fullName: Microsoft.Build.BuildEngine.ProjectLoadSettings.None
  type: Field
  assemblies:
  - Microsoft.Build.Engine
  namespace: Microsoft.Build.BuildEngine
  syntax:
    content: None
    return:
      type: Microsoft.Build.BuildEngine.ProjectLoadSettings
      description: Return description to be filled
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: Microsoft.Build.BuildEngine.ProjectLoadSettings.IgnoreMissingImports
  parent: Microsoft.Build.BuildEngine.ProjectLoadSettings
  isExternal: false
  name: IgnoreMissingImports
  nameWithType: ProjectLoadSettings.IgnoreMissingImports
  fullName: Microsoft.Build.BuildEngine.ProjectLoadSettings.IgnoreMissingImports
- uid: Microsoft.Build.BuildEngine.ProjectLoadSettings
  parent: Microsoft.Build.BuildEngine
  isExternal: false
  name: ProjectLoadSettings
  nameWithType: ProjectLoadSettings
  fullName: Microsoft.Build.BuildEngine.ProjectLoadSettings
- uid: Microsoft.Build.BuildEngine.ProjectLoadSettings.None
  parent: Microsoft.Build.BuildEngine.ProjectLoadSettings
  isExternal: false
  name: None
  nameWithType: ProjectLoadSettings.None
  fullName: Microsoft.Build.BuildEngine.ProjectLoadSettings.None
- uid: Microsoft.Build.BuildEngine.ProjectLoadSettings
  parent: Microsoft.Build.BuildEngine
  isExternal: false
  name: ProjectLoadSettings
  nameWithType: ProjectLoadSettings
  fullName: Microsoft.Build.BuildEngine.ProjectLoadSettings
