### YamlMime:ManagedReference
items:
- uid: System.Data.SqlClient.ApplicationIntent
  id: ApplicationIntent
  children:
  - System.Data.SqlClient.ApplicationIntent.ReadOnly
  - System.Data.SqlClient.ApplicationIntent.ReadWrite
  langs:
  - csharp
  - vb
  name: ApplicationIntent
  nameWithType: ApplicationIntent
  fullName: System.Data.SqlClient.ApplicationIntent
  type: Enum
  syntax:
    content: public enum ApplicationIntent
  inheritance:
  - System.Object
  - System.ValueType
  - System.Enum
- uid: System.Data.SqlClient.ApplicationIntent.ReadOnly
  id: ReadOnly
  parent: System.Data.SqlClient.ApplicationIntent
  langs:
  - csharp
  - vb
  name: ReadOnly
  nameWithType: ApplicationIntent.ReadOnly
  fullName: System.Data.SqlClient.ApplicationIntent.ReadOnly
  type: Field
  assemblies:
  - System.Data
  namespace: System.Data.SqlClient
  syntax:
    content: ReadOnly
    return:
      type: System.Data.SqlClient.ApplicationIntent
      description: Return description to be filled
- uid: System.Data.SqlClient.ApplicationIntent.ReadWrite
  id: ReadWrite
  parent: System.Data.SqlClient.ApplicationIntent
  langs:
  - csharp
  - vb
  name: ReadWrite
  nameWithType: ApplicationIntent.ReadWrite
  fullName: System.Data.SqlClient.ApplicationIntent.ReadWrite
  type: Field
  assemblies:
  - System.Data
  namespace: System.Data.SqlClient
  syntax:
    content: ReadWrite
    return:
      type: System.Data.SqlClient.ApplicationIntent
      description: Return description to be filled
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Data.SqlClient.ApplicationIntent.ReadOnly
  parent: System.Data.SqlClient.ApplicationIntent
  isExternal: false
  name: ReadOnly
  nameWithType: ApplicationIntent.ReadOnly
  fullName: System.Data.SqlClient.ApplicationIntent.ReadOnly
- uid: System.Data.SqlClient.ApplicationIntent
  parent: System.Data.SqlClient
  isExternal: false
  name: ApplicationIntent
  nameWithType: ApplicationIntent
  fullName: System.Data.SqlClient.ApplicationIntent
- uid: System.Data.SqlClient.ApplicationIntent.ReadWrite
  parent: System.Data.SqlClient.ApplicationIntent
  isExternal: false
  name: ReadWrite
  nameWithType: ApplicationIntent.ReadWrite
  fullName: System.Data.SqlClient.ApplicationIntent.ReadWrite
- uid: System.Data.SqlClient.ApplicationIntent
  parent: System.Data.SqlClient
  isExternal: false
  name: ApplicationIntent
  nameWithType: ApplicationIntent
  fullName: System.Data.SqlClient.ApplicationIntent
