### YamlMime:ManagedReference
items:
- uid: System.Configuration.Provider.ProviderCollection
  id: ProviderCollection
  children:
  - System.Configuration.Provider.ProviderCollection.#ctor
  - System.Configuration.Provider.ProviderCollection.Add(System.Configuration.Provider.ProviderBase)
  - System.Configuration.Provider.ProviderCollection.Clear
  - System.Configuration.Provider.ProviderCollection.CopyTo(System.Configuration.Provider.ProviderBase[],System.Int32)
  - System.Configuration.Provider.ProviderCollection.Count
  - System.Configuration.Provider.ProviderCollection.GetEnumerator
  - System.Configuration.Provider.ProviderCollection.IsSynchronized
  - System.Configuration.Provider.ProviderCollection.Item(System.String)
  - System.Configuration.Provider.ProviderCollection.Remove(System.String)
  - System.Configuration.Provider.ProviderCollection.SetReadOnly
  - System.Configuration.Provider.ProviderCollection.SyncRoot
  - System.Configuration.Provider.ProviderCollection.System#Collections#ICollection#CopyTo(System.Array,System.Int32)
  langs:
  - csharp
  name: ProviderCollection
  nameWithType: ProviderCollection
  fullName: System.Configuration.Provider.ProviderCollection
  type: Class
  summary: Represents a collection of provider objects that inherit from <see cref="T:System.Configuration.Provider.ProviderBase">.
  remarks: The ProviderCollection class utilizes an underlying <xref:System.Collections.Hashtable> object to store the provider name/value pairs.
  syntax:
    content: 'public class ProviderCollection : System.Collections.ICollection'
  inheritance:
  - System.Object
  implements:
  - System.Collections.ICollection
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Provider.ProviderCollection.#ctor
  id: '#ctor'
  parent: System.Configuration.Provider.ProviderCollection
  langs:
  - csharp
  name: ProviderCollection()
  nameWithType: ProviderCollection.ProviderCollection()
  fullName: System.Configuration.Provider.ProviderCollection.ProviderCollection()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Provider
  summary: Initializes a new instance of the <see cref="T:System.Configuration.Provider.ProviderCollection"> class.
  remarks: The ProviderCollection constructor initializes the underlying <xref:System.Collections.Hashtable> object used to store the items of the collection.
  syntax:
    content: public ProviderCollection ();
    parameters: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Provider.ProviderCollection.Add(System.Configuration.Provider.ProviderBase)
  id: Add(System.Configuration.Provider.ProviderBase)
  parent: System.Configuration.Provider.ProviderCollection
  langs:
  - csharp
  name: Add(ProviderBase)
  nameWithType: ProviderCollection.Add(ProviderBase)
  fullName: System.Configuration.Provider.ProviderCollection.Add(ProviderBase)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Provider
  summary: Adds a provider to the collection.
  remarks: The Add method first checks for any exceptions (as listed in the Exceptions section), and then calls the <xref:System.Collections.Hashtable.Add%2A?displayProperty=fullName> method. It passes in the object referenced by the  parameter as well as the <xref:System.Configuration.Provider.ProviderBase.Name%2A> property of the provider to be used as the key in the <xref:System.Collections.Hashtable> object.
  syntax:
    content: public virtual void Add (System.Configuration.Provider.ProviderBase provider);
    parameters:
    - id: provider
      type: System.Configuration.Provider.ProviderBase
      description: The provider to be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Provider.ProviderCollection.Clear
  id: Clear
  parent: System.Configuration.Provider.ProviderCollection
  langs:
  - csharp
  name: Clear()
  nameWithType: ProviderCollection.Clear()
  fullName: System.Configuration.Provider.ProviderCollection.Clear()
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Provider
  summary: Removes all items from the collection.
  remarks: To be added.
  syntax:
    content: public void Clear ();
    parameters: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Provider.ProviderCollection.CopyTo(System.Configuration.Provider.ProviderBase[],System.Int32)
  id: CopyTo(System.Configuration.Provider.ProviderBase[],System.Int32)
  parent: System.Configuration.Provider.ProviderCollection
  langs:
  - csharp
  name: CopyTo(ProviderBase[],Int32)
  nameWithType: ProviderCollection.CopyTo(ProviderBase[],Int32)
  fullName: System.Configuration.Provider.ProviderCollection.CopyTo(ProviderBase[],Int32)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Provider
  summary: Copies the contents of the collection to the given array starting at the specified index.
  remarks: The array into which the items are copied must have zero-based indexing.
  syntax:
    content: public void CopyTo (System.Configuration.Provider.ProviderBase[] array, int index);
    parameters:
    - id: array
      type: System.Configuration.Provider.ProviderBase[]
      description: The array to copy the elements of the collection to.
    - id: index
      type: System.Int32
      description: The index of the collection item at which to start the copying process.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Provider.ProviderCollection.Count
  id: Count
  parent: System.Configuration.Provider.ProviderCollection
  langs:
  - csharp
  name: Count
  nameWithType: ProviderCollection.Count
  fullName: System.Configuration.Provider.ProviderCollection.Count
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Provider
  summary: Gets the number of providers in the collection.
  remarks: To be added.
  syntax:
    content: public int Count { get; }
    return:
      type: System.Int32
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Provider.ProviderCollection.GetEnumerator
  id: GetEnumerator
  parent: System.Configuration.Provider.ProviderCollection
  langs:
  - csharp
  name: GetEnumerator()
  nameWithType: ProviderCollection.GetEnumerator()
  fullName: System.Configuration.Provider.ProviderCollection.GetEnumerator()
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Provider
  summary: Returns an object that implements the <see cref="T:System.Collections.IEnumerator"> interface to iterate through the collection.
  remarks: The <xref:System.Configuration.Provider.ProviderCollection> class stores its collection in a <xref:System.Collections.Hashtable> object. The GetEnumerator method calls the <xref:System.Collections.Hashtable.GetEnumerator%2A?displayProperty=fullName> method.
  syntax:
    content: public System.Collections.IEnumerator GetEnumerator ();
    parameters: []
    return:
      type: System.Collections.IEnumerator
      description: An object that implements <see cref="T:System.Collections.IEnumerator"> to iterate through the collection.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Provider.ProviderCollection.IsSynchronized
  id: IsSynchronized
  parent: System.Configuration.Provider.ProviderCollection
  langs:
  - csharp
  name: IsSynchronized
  nameWithType: ProviderCollection.IsSynchronized
  fullName: System.Configuration.Provider.ProviderCollection.IsSynchronized
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Provider
  summary: Gets a value indicating whether access to the collection is synchronized (thread safe).
  remarks: This property is included to fulfill the <xref:System.Collections.ICollection> interface.
  syntax:
    content: public bool IsSynchronized { get; }
    return:
      type: System.Boolean
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Provider.ProviderCollection.Item(System.String)
  id: Item(System.String)
  parent: System.Configuration.Provider.ProviderCollection
  langs:
  - csharp
  name: Item(String)
  nameWithType: ProviderCollection.Item(String)
  fullName: System.Configuration.Provider.ProviderCollection.Item(String)
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Provider
  summary: Gets the provider with the specified name.
  remarks: To be added.
  syntax:
    content: public System.Configuration.Provider.ProviderBase this[string name] { get; }
    parameters:
    - id: name
      type: System.String
      description: The key by which the provider is identified.
    return:
      type: System.Configuration.Provider.ProviderBase
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Provider.ProviderCollection.Remove(System.String)
  id: Remove(System.String)
  parent: System.Configuration.Provider.ProviderCollection
  langs:
  - csharp
  name: Remove(String)
  nameWithType: ProviderCollection.Remove(String)
  fullName: System.Configuration.Provider.ProviderCollection.Remove(String)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Provider
  summary: Removes a provider from the collection.
  remarks: To be added.
  syntax:
    content: public void Remove (string name);
    parameters:
    - id: name
      type: System.String
      description: The name of the provider to be removed.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Provider.ProviderCollection.SetReadOnly
  id: SetReadOnly
  parent: System.Configuration.Provider.ProviderCollection
  langs:
  - csharp
  name: SetReadOnly()
  nameWithType: ProviderCollection.SetReadOnly()
  fullName: System.Configuration.Provider.ProviderCollection.SetReadOnly()
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Provider
  summary: Sets the collection to be read-only.
  remarks: "The <xref:System.Configuration.Provider.ProviderCollection> class is read/write by default. The SetReadOnly method makes the collection read-only. After a collection is set to read-only, some method calls (such as <xref:System.Configuration.Provider.ProviderCollection.Remove%2A> and <xref:System.Configuration.Provider.ProviderCollection.Add%2A> will result in an exception.  \n  \n Note that most provider-based features will set their <xref:System.Configuration.Provider.ProviderCollection> object to read-only after creating instances of all of the configured providers."
  syntax:
    content: public void SetReadOnly ();
    parameters: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Provider.ProviderCollection.SyncRoot
  id: SyncRoot
  parent: System.Configuration.Provider.ProviderCollection
  langs:
  - csharp
  name: SyncRoot
  nameWithType: ProviderCollection.SyncRoot
  fullName: System.Configuration.Provider.ProviderCollection.SyncRoot
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Provider
  summary: Gets the current object.
  remarks: This property is included to fulfill the <xref:System.Collections.ICollection> interface.
  syntax:
    content: public object SyncRoot { get; }
    return:
      type: System.Object
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Provider.ProviderCollection.System#Collections#ICollection#CopyTo(System.Array,System.Int32)
  id: System#Collections#ICollection#CopyTo(System.Array,System.Int32)
  isEii: true
  parent: System.Configuration.Provider.ProviderCollection
  langs:
  - csharp
  name: System.Collections.ICollection.CopyTo(Array,Int32)
  nameWithType: ProviderCollection.System.Collections.ICollection.CopyTo(Array,Int32)
  fullName: System.Configuration.Provider.ProviderCollection.System.Collections.ICollection.CopyTo(Array,Int32)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Provider
  summary: Copies the elements of the <see cref="T:System.Configuration.Provider.ProviderCollection"> to an array, starting at a particular array index.
  remarks: This member is an explicit interface member implementation. It can be used only when the ICollection.CopyTo instance is cast to an <xref:System.Collections.ICollection> interface.
  syntax:
    content: void ICollection.CopyTo (Array array, int index);
    parameters:
    - id: array
      type: System.Array
      description: The array to copy the elements of the collection to.
    - id: index
      type: System.Int32
      description: The index of the array at which to start copying provider instances from the collection.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Configuration.Provider.ProviderCollection.#ctor
  parent: System.Configuration.Provider.ProviderCollection
  isExternal: false
  name: ProviderCollection()
  nameWithType: ProviderCollection.ProviderCollection()
  fullName: System.Configuration.Provider.ProviderCollection.ProviderCollection()
- uid: System.Configuration.Provider.ProviderCollection.Add(System.Configuration.Provider.ProviderBase)
  parent: System.Configuration.Provider.ProviderCollection
  isExternal: false
  name: Add(ProviderBase)
  nameWithType: ProviderCollection.Add(ProviderBase)
  fullName: System.Configuration.Provider.ProviderCollection.Add(ProviderBase)
- uid: System.Configuration.Provider.ProviderBase
  parent: System.Configuration.Provider
  isExternal: false
  name: ProviderBase
  nameWithType: ProviderBase
  fullName: System.Configuration.Provider.ProviderBase
- uid: System.Configuration.Provider.ProviderCollection.Clear
  parent: System.Configuration.Provider.ProviderCollection
  isExternal: false
  name: Clear()
  nameWithType: ProviderCollection.Clear()
  fullName: System.Configuration.Provider.ProviderCollection.Clear()
- uid: System.Configuration.Provider.ProviderCollection.CopyTo(System.Configuration.Provider.ProviderBase[],System.Int32)
  parent: System.Configuration.Provider.ProviderCollection
  isExternal: false
  name: CopyTo(ProviderBase[],Int32)
  nameWithType: ProviderCollection.CopyTo(ProviderBase[],Int32)
  fullName: System.Configuration.Provider.ProviderCollection.CopyTo(ProviderBase[],Int32)
- uid: System.Configuration.Provider.ProviderBase
  parent: System.Configuration.Provider
  isExternal: false
  name: ProviderBase
  nameWithType: ProviderBase
  fullName: System.Configuration.Provider.ProviderBase[]
- uid: System.Int32
  parent: System
  isExternal: false
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Configuration.Provider.ProviderCollection.Count
  parent: System.Configuration.Provider.ProviderCollection
  isExternal: false
  name: Count
  nameWithType: ProviderCollection.Count
  fullName: System.Configuration.Provider.ProviderCollection.Count
- uid: System.Int32
  parent: System
  isExternal: false
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Configuration.Provider.ProviderCollection.GetEnumerator
  parent: System.Configuration.Provider.ProviderCollection
  isExternal: false
  name: GetEnumerator()
  nameWithType: ProviderCollection.GetEnumerator()
  fullName: System.Configuration.Provider.ProviderCollection.GetEnumerator()
- uid: System.Collections.IEnumerator
  parent: System.Collections
  isExternal: false
  name: IEnumerator
  nameWithType: IEnumerator
  fullName: System.Collections.IEnumerator
- uid: System.Configuration.Provider.ProviderCollection.IsSynchronized
  parent: System.Configuration.Provider.ProviderCollection
  isExternal: false
  name: IsSynchronized
  nameWithType: ProviderCollection.IsSynchronized
  fullName: System.Configuration.Provider.ProviderCollection.IsSynchronized
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.Provider.ProviderCollection.Item(System.String)
  parent: System.Configuration.Provider.ProviderCollection
  isExternal: false
  name: Item(String)
  nameWithType: ProviderCollection.Item(String)
  fullName: System.Configuration.Provider.ProviderCollection.Item(String)
- uid: System.Configuration.Provider.ProviderBase
  parent: System.Configuration.Provider
  isExternal: false
  name: ProviderBase
  nameWithType: ProviderBase
  fullName: System.Configuration.Provider.ProviderBase
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.Provider.ProviderCollection.Remove(System.String)
  parent: System.Configuration.Provider.ProviderCollection
  isExternal: false
  name: Remove(String)
  nameWithType: ProviderCollection.Remove(String)
  fullName: System.Configuration.Provider.ProviderCollection.Remove(String)
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.Provider.ProviderCollection.SetReadOnly
  parent: System.Configuration.Provider.ProviderCollection
  isExternal: false
  name: SetReadOnly()
  nameWithType: ProviderCollection.SetReadOnly()
  fullName: System.Configuration.Provider.ProviderCollection.SetReadOnly()
- uid: System.Configuration.Provider.ProviderCollection.SyncRoot
  parent: System.Configuration.Provider.ProviderCollection
  isExternal: false
  name: SyncRoot
  nameWithType: ProviderCollection.SyncRoot
  fullName: System.Configuration.Provider.ProviderCollection.SyncRoot
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Configuration.Provider.ProviderCollection.System#Collections#ICollection#CopyTo(System.Array,System.Int32)
  parent: System.Configuration.Provider.ProviderCollection
  isExternal: false
  name: System.Collections.ICollection.CopyTo(Array,Int32)
  nameWithType: ProviderCollection.System.Collections.ICollection.CopyTo(Array,Int32)
  fullName: System.Configuration.Provider.ProviderCollection.System.Collections.ICollection.CopyTo(Array,Int32)
- uid: System.Array
  parent: System
  isExternal: false
  name: Array
  nameWithType: Array
  fullName: System.Array
- uid: System.Int32
  parent: System
  isExternal: false
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
