### YamlMime:ManagedReference
items:
- uid: System.Configuration.Provider.ProviderException
  id: ProviderException
  children:
  - System.Configuration.Provider.ProviderException.#ctor
  - System.Configuration.Provider.ProviderException.#ctor(System.String)
  - System.Configuration.Provider.ProviderException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Configuration.Provider.ProviderException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  - vb
  name: ProviderException
  nameWithType: ProviderException
  fullName: System.Configuration.Provider.ProviderException
  type: Class
  syntax:
    content: 'public class ProviderException : Exception'
  inheritance:
  - System.Object
  - System.Exception
  implements: []
  inheritedMembers:
  - System.Exception.Data
  - System.Exception.GetBaseException
  - System.Exception.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Exception.GetType
  - System.Exception.HelpLink
  - System.Exception.HResult
  - System.Exception.InnerException
  - System.Exception.Message
  - System.Exception.SerializeObjectState
  - System.Exception.Source
  - System.Exception.StackTrace
  - System.Exception.TargetSite
  - System.Exception.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
- uid: System.Configuration.Provider.ProviderException.#ctor
  id: '#ctor'
  parent: System.Configuration.Provider.ProviderException
  langs:
  - csharp
  - vb
  name: .ctor
  nameWithType: ProviderException..ctor
  fullName: System.Configuration.Provider.ProviderException..ctor
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Provider
  syntax:
    content: public ProviderException ();
    parameters: []
- uid: System.Configuration.Provider.ProviderException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Configuration.Provider.ProviderException
  langs:
  - csharp
  - vb
  name: .ctor
  nameWithType: ProviderException..ctor
  fullName: System.Configuration.Provider.ProviderException..ctor
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Provider
  syntax:
    content: public ProviderException (string message);
    parameters:
    - id: message
      type: System.String
      description: Parameter description to be filled
- uid: System.Configuration.Provider.ProviderException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.Configuration.Provider.ProviderException
  langs:
  - csharp
  - vb
  name: .ctor
  nameWithType: ProviderException..ctor
  fullName: System.Configuration.Provider.ProviderException..ctor
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Provider
  syntax:
    content: protected ProviderException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: Parameter description to be filled
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: Parameter description to be filled
- uid: System.Configuration.Provider.ProviderException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Configuration.Provider.ProviderException
  langs:
  - csharp
  - vb
  name: .ctor
  nameWithType: ProviderException..ctor
  fullName: System.Configuration.Provider.ProviderException..ctor
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Provider
  syntax:
    content: public ProviderException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: Parameter description to be filled
    - id: innerException
      type: System.Exception
      description: Parameter description to be filled
references:
- uid: System.Exception
  isExternal: false
  name: System.Exception
- uid: System.Configuration.Provider.ProviderException.#ctor
  parent: System.Configuration.Provider.ProviderException
  isExternal: false
  name: .ctor
  nameWithType: ProviderException..ctor
  fullName: System.Configuration.Provider.ProviderException..ctor
- uid: System.Configuration.Provider.ProviderException.#ctor(System.String)
  parent: System.Configuration.Provider.ProviderException
  isExternal: false
  name: .ctor
  nameWithType: ProviderException..ctor
  fullName: System.Configuration.Provider.ProviderException..ctor
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.Provider.ProviderException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Configuration.Provider.ProviderException
  isExternal: false
  name: .ctor
  nameWithType: ProviderException..ctor
  fullName: System.Configuration.Provider.ProviderException..ctor
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: false
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.Configuration.Provider.ProviderException.#ctor(System.String,System.Exception)
  parent: System.Configuration.Provider.ProviderException
  isExternal: false
  name: .ctor
  nameWithType: ProviderException..ctor
  fullName: System.Configuration.Provider.ProviderException..ctor
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Exception
  parent: System
  isExternal: false
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
