### YamlMime:ManagedReference
items:
- uid: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer
  id: VisualBasicSettingsValueSerializer
  children:
  - Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer.#ctor
  - Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  - Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  langs:
  - csharp
  - vb
  name: VisualBasicSettingsValueSerializer
  nameWithType: VisualBasicSettingsValueSerializer
  fullName: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer
  type: Class
  syntax:
    content: 'public sealed class VisualBasicSettingsValueSerializer : System.Windows.Markup.ValueSerializer'
  inheritance:
  - System.Windows.Markup.ValueSerializer
  implements: []
  inheritedMembers: []
- uid: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer.#ctor
  id: '#ctor'
  parent: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer
  langs:
  - csharp
  - vb
  name: .ctor
  nameWithType: VisualBasicSettingsValueSerializer..ctor
  fullName: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer..ctor
  type: Constructor
  assemblies:
  - System.Activities
  namespace: Microsoft.VisualBasic.Activities.XamlIntegration
  syntax:
    content: public VisualBasicSettingsValueSerializer ();
    parameters: []
- uid: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  id: CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer
  langs:
  - csharp
  - vb
  name: CanConvertToString
  nameWithType: VisualBasicSettingsValueSerializer.CanConvertToString
  fullName: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer.CanConvertToString
  type: Method
  assemblies:
  - System.Activities
  namespace: Microsoft.VisualBasic.Activities.XamlIntegration
  syntax:
    content: public override bool CanConvertToString (object value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.Object
      description: Parameter description to be filled
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: Parameter description to be filled
    return:
      type: System.Boolean
      description: Return description to be filled
- uid: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  id: ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer
  langs:
  - csharp
  - vb
  name: ConvertToString
  nameWithType: VisualBasicSettingsValueSerializer.ConvertToString
  fullName: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer.ConvertToString
  type: Method
  assemblies:
  - System.Activities
  namespace: Microsoft.VisualBasic.Activities.XamlIntegration
  syntax:
    content: public override string ConvertToString (object value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.Object
      description: Parameter description to be filled
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: Parameter description to be filled
    return:
      type: System.String
      description: Return description to be filled
references:
- uid: System.Windows.Markup.ValueSerializer
  isExternal: false
  name: System.Windows.Markup.ValueSerializer
- uid: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer.#ctor
  parent: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer
  isExternal: false
  name: .ctor
  nameWithType: VisualBasicSettingsValueSerializer..ctor
  fullName: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer..ctor
- uid: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer
  isExternal: false
  name: CanConvertToString
  nameWithType: VisualBasicSettingsValueSerializer.CanConvertToString
  fullName: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer.CanConvertToString
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer
  isExternal: false
  name: ConvertToString
  nameWithType: VisualBasicSettingsValueSerializer.ConvertToString
  fullName: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer.ConvertToString
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
