### YamlMime:ManagedReference
items:
- uid: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter
  id: VisualBasicSettingsConverter
  children:
  - Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter.#ctor
  - Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter.CanConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Type)
  - Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter.CanConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Type)
  - Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  - Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  langs:
  - csharp
  - vb
  name: VisualBasicSettingsConverter
  nameWithType: VisualBasicSettingsConverter
  fullName: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter
  type: Class
  syntax:
    content: 'public sealed class VisualBasicSettingsConverter : System.ComponentModel.TypeConverter'
  inheritance:
  - System.ComponentModel.TypeConverter
  implements: []
  inheritedMembers: []
- uid: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter.#ctor
  id: '#ctor'
  parent: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter
  langs:
  - csharp
  - vb
  name: .ctor
  nameWithType: VisualBasicSettingsConverter..ctor
  fullName: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter..ctor
  type: Constructor
  assemblies:
  - System.Activities
  namespace: Microsoft.VisualBasic.Activities.XamlIntegration
  syntax:
    content: public VisualBasicSettingsConverter ();
    parameters: []
- uid: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter.CanConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Type)
  id: CanConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Type)
  parent: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter
  langs:
  - csharp
  - vb
  name: CanConvertFrom
  nameWithType: VisualBasicSettingsConverter.CanConvertFrom
  fullName: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter.CanConvertFrom
  type: Method
  assemblies:
  - System.Activities
  namespace: Microsoft.VisualBasic.Activities.XamlIntegration
  syntax:
    content: public override bool CanConvertFrom (System.ComponentModel.ITypeDescriptorContext context, Type sourceType);
    parameters:
    - id: context
      type: System.ComponentModel.ITypeDescriptorContext
      description: Parameter description to be filled
    - id: sourceType
      type: System.Type
      description: Parameter description to be filled
    return:
      type: System.Boolean
      description: Return description to be filled
- uid: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter.CanConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Type)
  id: CanConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Type)
  parent: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter
  langs:
  - csharp
  - vb
  name: CanConvertTo
  nameWithType: VisualBasicSettingsConverter.CanConvertTo
  fullName: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter.CanConvertTo
  type: Method
  assemblies:
  - System.Activities
  namespace: Microsoft.VisualBasic.Activities.XamlIntegration
  syntax:
    content: public override bool CanConvertTo (System.ComponentModel.ITypeDescriptorContext context, Type destinationType);
    parameters:
    - id: context
      type: System.ComponentModel.ITypeDescriptorContext
      description: Parameter description to be filled
    - id: destinationType
      type: System.Type
      description: Parameter description to be filled
    return:
      type: System.Boolean
      description: Return description to be filled
- uid: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  id: ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  parent: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter
  langs:
  - csharp
  - vb
  name: ConvertFrom
  nameWithType: VisualBasicSettingsConverter.ConvertFrom
  fullName: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter.ConvertFrom
  type: Method
  assemblies:
  - System.Activities
  namespace: Microsoft.VisualBasic.Activities.XamlIntegration
  syntax:
    content: public override object ConvertFrom (System.ComponentModel.ITypeDescriptorContext context, System.Globalization.CultureInfo culture, object value);
    parameters:
    - id: context
      type: System.ComponentModel.ITypeDescriptorContext
      description: Parameter description to be filled
    - id: culture
      type: System.Globalization.CultureInfo
      description: Parameter description to be filled
    - id: value
      type: System.Object
      description: Parameter description to be filled
    return:
      type: System.Object
      description: Return description to be filled
- uid: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  id: ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  parent: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter
  langs:
  - csharp
  - vb
  name: ConvertTo
  nameWithType: VisualBasicSettingsConverter.ConvertTo
  fullName: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter.ConvertTo
  type: Method
  assemblies:
  - System.Activities
  namespace: Microsoft.VisualBasic.Activities.XamlIntegration
  syntax:
    content: public override object ConvertTo (System.ComponentModel.ITypeDescriptorContext context, System.Globalization.CultureInfo culture, object value, Type destinationType);
    parameters:
    - id: context
      type: System.ComponentModel.ITypeDescriptorContext
      description: Parameter description to be filled
    - id: culture
      type: System.Globalization.CultureInfo
      description: Parameter description to be filled
    - id: value
      type: System.Object
      description: Parameter description to be filled
    - id: destinationType
      type: System.Type
      description: Parameter description to be filled
    return:
      type: System.Object
      description: Return description to be filled
references:
- uid: System.ComponentModel.TypeConverter
  isExternal: false
  name: System.ComponentModel.TypeConverter
- uid: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter.#ctor
  parent: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter
  isExternal: false
  name: .ctor
  nameWithType: VisualBasicSettingsConverter..ctor
  fullName: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter..ctor
- uid: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter.CanConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Type)
  parent: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter
  isExternal: false
  name: CanConvertFrom
  nameWithType: VisualBasicSettingsConverter.CanConvertFrom
  fullName: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter.CanConvertFrom
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Type
  parent: System
  isExternal: false
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter.CanConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Type)
  parent: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter
  isExternal: false
  name: CanConvertTo
  nameWithType: VisualBasicSettingsConverter.CanConvertTo
  fullName: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter.CanConvertTo
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Type
  parent: System
  isExternal: false
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  parent: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter
  isExternal: false
  name: ConvertFrom
  nameWithType: VisualBasicSettingsConverter.ConvertFrom
  fullName: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter.ConvertFrom
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Globalization.CultureInfo
  parent: System.Globalization
  isExternal: false
  name: CultureInfo
  nameWithType: CultureInfo
  fullName: System.Globalization.CultureInfo
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  parent: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter
  isExternal: false
  name: ConvertTo
  nameWithType: VisualBasicSettingsConverter.ConvertTo
  fullName: Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter.ConvertTo
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Globalization.CultureInfo
  parent: System.Globalization
  isExternal: false
  name: CultureInfo
  nameWithType: CultureInfo
  fullName: System.Globalization.CultureInfo
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Type
  parent: System
  isExternal: false
  name: Type
  nameWithType: Type
  fullName: System.Type
