### YamlMime:ManagedReference
items:
- uid: Microsoft.VisualBasic.Activities.VisualBasicSettings
  id: VisualBasicSettings
  children:
  - Microsoft.VisualBasic.Activities.VisualBasicSettings.#ctor
  - Microsoft.VisualBasic.Activities.VisualBasicSettings.Default
  - Microsoft.VisualBasic.Activities.VisualBasicSettings.ImportReferences
  langs:
  - csharp
  name: VisualBasicSettings
  nameWithType: VisualBasicSettings
  fullName: Microsoft.VisualBasic.Activities.VisualBasicSettings
  type: Class
  summary: Contains settings that <xref:Microsoft.VisualBasic.Activities.VisualBasicValue%601> and <xref:Microsoft.VisualBasic.Activities.VisualBasicReference%601> instances use to compile the source text of the expressions they contain.
  remarks: These settings include assembly references and imported namespaces required to compile an expression.
  syntax:
    content: >-
      [System.ComponentModel.TypeConverter(typeof(Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter))]

      [System.Windows.Markup.ValueSerializer(typeof(Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer))]

      public class VisualBasicSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.VisualBasic.Activities.VisualBasicSettings.#ctor
  id: '#ctor'
  parent: Microsoft.VisualBasic.Activities.VisualBasicSettings
  langs:
  - csharp
  name: VisualBasicSettings()
  nameWithType: VisualBasicSettings.VisualBasicSettings()
  fullName: Microsoft.VisualBasic.Activities.VisualBasicSettings.VisualBasicSettings()
  type: Constructor
  assemblies:
  - System.Activities
  namespace: Microsoft.VisualBasic.Activities
  summary: Initializes a new instance of the <see cref="T:Microsoft.VisualBasic.Activities.VisualBasicSettings"> class.
  remarks: To be added.
  syntax:
    content: public VisualBasicSettings ();
    parameters: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.VisualBasic.Activities.VisualBasicSettings.Default
  id: Default
  parent: Microsoft.VisualBasic.Activities.VisualBasicSettings
  langs:
  - csharp
  name: Default
  nameWithType: VisualBasicSettings.Default
  fullName: Microsoft.VisualBasic.Activities.VisualBasicSettings.Default
  type: Property
  assemblies:
  - System.Activities
  namespace: Microsoft.VisualBasic.Activities
  summary: Gets a <see cref="T:Microsoft.VisualBasic.Activities.VisualBasicSettings"> that contains the default set of assembly references and imported namespaces. This set is available to all <xref:Microsoft.VisualBasic.Activities.VisualBasicValue%601> and <xref:Microsoft.VisualBasic.Activities.VisualBasicReference%601> instances in a given <xref:System.AppDomain>.
  remarks: "The following table lists the default imported namespaces and assembly references.  \n  \n|Imported Namespace|Assembly|  \n|------------------------|--------------|  \n|System|mscorlib|  \n|System|System|  \n|System.Collections|mscorlib|  \n|System.Collections.Generic|mscorlib|  \n|System.Collections.Generic|System|  \n|System.Activities|System.Activities|  \n|System.Activities.Statements|System.Activities|  \n|System.Activities.Expressions|System.Activities|"
  syntax:
    content: public static Microsoft.VisualBasic.Activities.VisualBasicSettings Default { get; }
    return:
      type: Microsoft.VisualBasic.Activities.VisualBasicSettings
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.VisualBasic.Activities.VisualBasicSettings.ImportReferences
  id: ImportReferences
  parent: Microsoft.VisualBasic.Activities.VisualBasicSettings
  langs:
  - csharp
  name: ImportReferences
  nameWithType: VisualBasicSettings.ImportReferences
  fullName: Microsoft.VisualBasic.Activities.VisualBasicSettings.ImportReferences
  type: Property
  assemblies:
  - System.Activities
  namespace: Microsoft.VisualBasic.Activities
  summary: Gets a collection of <see cref="T:Microsoft.VisualBasic.Activities.VisualBasicImportReference"> objects, each of which represents an assembly reference and a namespace imported from that assembly.
  remarks: To be added.
  syntax:
    content: public System.Collections.Generic.ISet<Microsoft.VisualBasic.Activities.VisualBasicImportReference> ImportReferences { get; }
    return:
      type: System.Collections.Generic.ISet{Microsoft.VisualBasic.Activities.VisualBasicImportReference}
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: Microsoft.VisualBasic.Activities.VisualBasicSettings.#ctor
  parent: Microsoft.VisualBasic.Activities.VisualBasicSettings
  isExternal: false
  name: VisualBasicSettings()
  nameWithType: VisualBasicSettings.VisualBasicSettings()
  fullName: Microsoft.VisualBasic.Activities.VisualBasicSettings.VisualBasicSettings()
- uid: Microsoft.VisualBasic.Activities.VisualBasicSettings.Default
  parent: Microsoft.VisualBasic.Activities.VisualBasicSettings
  isExternal: false
  name: Default
  nameWithType: VisualBasicSettings.Default
  fullName: Microsoft.VisualBasic.Activities.VisualBasicSettings.Default
- uid: Microsoft.VisualBasic.Activities.VisualBasicSettings
  parent: Microsoft.VisualBasic.Activities
  isExternal: false
  name: VisualBasicSettings
  nameWithType: VisualBasicSettings
  fullName: Microsoft.VisualBasic.Activities.VisualBasicSettings
- uid: Microsoft.VisualBasic.Activities.VisualBasicSettings.ImportReferences
  parent: Microsoft.VisualBasic.Activities.VisualBasicSettings
  isExternal: false
  name: ImportReferences
  nameWithType: VisualBasicSettings.ImportReferences
  fullName: Microsoft.VisualBasic.Activities.VisualBasicSettings.ImportReferences
- uid: System.Collections.Generic.ISet{Microsoft.VisualBasic.Activities.VisualBasicImportReference}
  parent: System.Collections.Generic
  isExternal: true
  name: ISet<VisualBasicImportReference>
  nameWithType: ISet<VisualBasicImportReference>
  fullName: System.Collections.Generic.ISet<Microsoft.VisualBasic.Activities.VisualBasicImportReference>
