### YamlMime:ManagedReference
items:
- uid: System.Deployment.Internal.InternalApplicationIdentityHelper
  id: InternalApplicationIdentityHelper
  children:
  - System.Deployment.Internal.InternalApplicationIdentityHelper.GetInternalAppId(System.ApplicationIdentity)
  langs:
  - csharp
  - vb
  name: InternalApplicationIdentityHelper
  nameWithType: InternalApplicationIdentityHelper
  fullName: System.Deployment.Internal.InternalApplicationIdentityHelper
  type: Class
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(false)]

      public static class InternalApplicationIdentityHelper
  inheritance:
  - System.Object
  implements: []
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: System.Deployment.Internal.InternalApplicationIdentityHelper.GetInternalAppId(System.ApplicationIdentity)
  id: GetInternalAppId(System.ApplicationIdentity)
  parent: System.Deployment.Internal.InternalApplicationIdentityHelper
  langs:
  - csharp
  - vb
  name: GetInternalAppId
  nameWithType: InternalApplicationIdentityHelper.GetInternalAppId
  fullName: System.Deployment.Internal.InternalApplicationIdentityHelper.GetInternalAppId
  type: Method
  assemblies:
  - mscorlib
  namespace: System.Deployment.Internal
  syntax:
    content: public static object GetInternalAppId (ApplicationIdentity id);
    parameters:
    - id: id
      type: System.ApplicationIdentity
      description: Parameter description to be filled
    return:
      type: System.Object
      description: Return description to be filled
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Deployment.Internal.InternalApplicationIdentityHelper.GetInternalAppId(System.ApplicationIdentity)
  parent: System.Deployment.Internal.InternalApplicationIdentityHelper
  isExternal: false
  name: GetInternalAppId
  nameWithType: InternalApplicationIdentityHelper.GetInternalAppId
  fullName: System.Deployment.Internal.InternalApplicationIdentityHelper.GetInternalAppId
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.ApplicationIdentity
  parent: System
  isExternal: false
  name: ApplicationIdentity
  nameWithType: ApplicationIdentity
  fullName: System.ApplicationIdentity
