### YamlMime:ManagedReference
items:
- uid: System.Runtime.InteropServices.RuntimeEnvironment
  id: RuntimeEnvironment
  children:
  - System.Runtime.InteropServices.RuntimeEnvironment.#ctor
  - System.Runtime.InteropServices.RuntimeEnvironment.FromGlobalAccessCache(System.Reflection.Assembly)
  - System.Runtime.InteropServices.RuntimeEnvironment.GetRuntimeDirectory
  - System.Runtime.InteropServices.RuntimeEnvironment.GetRuntimeInterfaceAsIntPtr(System.Guid,System.Guid)
  - System.Runtime.InteropServices.RuntimeEnvironment.GetRuntimeInterfaceAsObject(System.Guid,System.Guid)
  - System.Runtime.InteropServices.RuntimeEnvironment.GetSystemVersion
  - System.Runtime.InteropServices.RuntimeEnvironment.SystemConfigurationFile
  langs:
  - csharp
  - vb
  name: RuntimeEnvironment
  nameWithType: RuntimeEnvironment
  fullName: System.Runtime.InteropServices.RuntimeEnvironment
  type: Class
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(true)]

      public class RuntimeEnvironment
  inheritance:
  - System.Object
  implements: []
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: System.Runtime.InteropServices.RuntimeEnvironment.#ctor
  id: '#ctor'
  parent: System.Runtime.InteropServices.RuntimeEnvironment
  langs:
  - csharp
  - vb
  name: .ctor
  nameWithType: RuntimeEnvironment..ctor
  fullName: System.Runtime.InteropServices.RuntimeEnvironment..ctor
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System.Runtime.InteropServices
  syntax:
    content: public RuntimeEnvironment ();
    parameters: []
- uid: System.Runtime.InteropServices.RuntimeEnvironment.FromGlobalAccessCache(System.Reflection.Assembly)
  id: FromGlobalAccessCache(System.Reflection.Assembly)
  parent: System.Runtime.InteropServices.RuntimeEnvironment
  langs:
  - csharp
  - vb
  name: FromGlobalAccessCache
  nameWithType: RuntimeEnvironment.FromGlobalAccessCache
  fullName: System.Runtime.InteropServices.RuntimeEnvironment.FromGlobalAccessCache
  type: Method
  assemblies:
  - mscorlib
  namespace: System.Runtime.InteropServices
  syntax:
    content: public static bool FromGlobalAccessCache (System.Reflection.Assembly a);
    parameters:
    - id: a
      type: System.Reflection.Assembly
      description: Parameter description to be filled
    return:
      type: System.Boolean
      description: Return description to be filled
- uid: System.Runtime.InteropServices.RuntimeEnvironment.GetRuntimeDirectory
  id: GetRuntimeDirectory
  parent: System.Runtime.InteropServices.RuntimeEnvironment
  langs:
  - csharp
  - vb
  name: GetRuntimeDirectory
  nameWithType: RuntimeEnvironment.GetRuntimeDirectory
  fullName: System.Runtime.InteropServices.RuntimeEnvironment.GetRuntimeDirectory
  type: Method
  assemblies:
  - mscorlib
  namespace: System.Runtime.InteropServices
  syntax:
    content: public static string GetRuntimeDirectory ();
    parameters: []
    return:
      type: System.String
      description: Return description to be filled
- uid: System.Runtime.InteropServices.RuntimeEnvironment.GetRuntimeInterfaceAsIntPtr(System.Guid,System.Guid)
  id: GetRuntimeInterfaceAsIntPtr(System.Guid,System.Guid)
  parent: System.Runtime.InteropServices.RuntimeEnvironment
  langs:
  - csharp
  - vb
  name: GetRuntimeInterfaceAsIntPtr
  nameWithType: RuntimeEnvironment.GetRuntimeInterfaceAsIntPtr
  fullName: System.Runtime.InteropServices.RuntimeEnvironment.GetRuntimeInterfaceAsIntPtr
  type: Method
  assemblies:
  - mscorlib
  namespace: System.Runtime.InteropServices
  syntax:
    content: public static IntPtr GetRuntimeInterfaceAsIntPtr (Guid clsid, Guid riid);
    parameters:
    - id: clsid
      type: System.Guid
      description: Parameter description to be filled
    - id: riid
      type: System.Guid
      description: Parameter description to be filled
    return:
      type: System.IntPtr
      description: Return description to be filled
- uid: System.Runtime.InteropServices.RuntimeEnvironment.GetRuntimeInterfaceAsObject(System.Guid,System.Guid)
  id: GetRuntimeInterfaceAsObject(System.Guid,System.Guid)
  parent: System.Runtime.InteropServices.RuntimeEnvironment
  langs:
  - csharp
  - vb
  name: GetRuntimeInterfaceAsObject
  nameWithType: RuntimeEnvironment.GetRuntimeInterfaceAsObject
  fullName: System.Runtime.InteropServices.RuntimeEnvironment.GetRuntimeInterfaceAsObject
  type: Method
  assemblies:
  - mscorlib
  namespace: System.Runtime.InteropServices
  syntax:
    content: public static object GetRuntimeInterfaceAsObject (Guid clsid, Guid riid);
    parameters:
    - id: clsid
      type: System.Guid
      description: Parameter description to be filled
    - id: riid
      type: System.Guid
      description: Parameter description to be filled
    return:
      type: System.Object
      description: Return description to be filled
- uid: System.Runtime.InteropServices.RuntimeEnvironment.GetSystemVersion
  id: GetSystemVersion
  parent: System.Runtime.InteropServices.RuntimeEnvironment
  langs:
  - csharp
  - vb
  name: GetSystemVersion
  nameWithType: RuntimeEnvironment.GetSystemVersion
  fullName: System.Runtime.InteropServices.RuntimeEnvironment.GetSystemVersion
  type: Method
  assemblies:
  - mscorlib
  namespace: System.Runtime.InteropServices
  syntax:
    content: public static string GetSystemVersion ();
    parameters: []
    return:
      type: System.String
      description: Return description to be filled
- uid: System.Runtime.InteropServices.RuntimeEnvironment.SystemConfigurationFile
  id: SystemConfigurationFile
  parent: System.Runtime.InteropServices.RuntimeEnvironment
  langs:
  - csharp
  - vb
  name: SystemConfigurationFile
  nameWithType: RuntimeEnvironment.SystemConfigurationFile
  fullName: System.Runtime.InteropServices.RuntimeEnvironment.SystemConfigurationFile
  type: Property
  assemblies:
  - mscorlib
  namespace: System.Runtime.InteropServices
  syntax:
    content: public static string SystemConfigurationFile { get; }
    return:
      type: System.String
      description: Return description to be filled
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Runtime.InteropServices.RuntimeEnvironment.#ctor
  parent: System.Runtime.InteropServices.RuntimeEnvironment
  isExternal: false
  name: .ctor
  nameWithType: RuntimeEnvironment..ctor
  fullName: System.Runtime.InteropServices.RuntimeEnvironment..ctor
- uid: System.Runtime.InteropServices.RuntimeEnvironment.FromGlobalAccessCache(System.Reflection.Assembly)
  parent: System.Runtime.InteropServices.RuntimeEnvironment
  isExternal: false
  name: FromGlobalAccessCache
  nameWithType: RuntimeEnvironment.FromGlobalAccessCache
  fullName: System.Runtime.InteropServices.RuntimeEnvironment.FromGlobalAccessCache
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Reflection.Assembly
  parent: System.Reflection
  isExternal: false
  name: Assembly
  nameWithType: Assembly
  fullName: System.Reflection.Assembly
- uid: System.Runtime.InteropServices.RuntimeEnvironment.GetRuntimeDirectory
  parent: System.Runtime.InteropServices.RuntimeEnvironment
  isExternal: false
  name: GetRuntimeDirectory
  nameWithType: RuntimeEnvironment.GetRuntimeDirectory
  fullName: System.Runtime.InteropServices.RuntimeEnvironment.GetRuntimeDirectory
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Runtime.InteropServices.RuntimeEnvironment.GetRuntimeInterfaceAsIntPtr(System.Guid,System.Guid)
  parent: System.Runtime.InteropServices.RuntimeEnvironment
  isExternal: false
  name: GetRuntimeInterfaceAsIntPtr
  nameWithType: RuntimeEnvironment.GetRuntimeInterfaceAsIntPtr
  fullName: System.Runtime.InteropServices.RuntimeEnvironment.GetRuntimeInterfaceAsIntPtr
- uid: System.IntPtr
  parent: System
  isExternal: false
  name: IntPtr
  nameWithType: IntPtr
  fullName: System.IntPtr
- uid: System.Guid
  parent: System
  isExternal: false
  name: Guid
  nameWithType: Guid
  fullName: System.Guid
- uid: System.Guid
  parent: System
  isExternal: false
  name: Guid
  nameWithType: Guid
  fullName: System.Guid
- uid: System.Runtime.InteropServices.RuntimeEnvironment.GetRuntimeInterfaceAsObject(System.Guid,System.Guid)
  parent: System.Runtime.InteropServices.RuntimeEnvironment
  isExternal: false
  name: GetRuntimeInterfaceAsObject
  nameWithType: RuntimeEnvironment.GetRuntimeInterfaceAsObject
  fullName: System.Runtime.InteropServices.RuntimeEnvironment.GetRuntimeInterfaceAsObject
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Guid
  parent: System
  isExternal: false
  name: Guid
  nameWithType: Guid
  fullName: System.Guid
- uid: System.Guid
  parent: System
  isExternal: false
  name: Guid
  nameWithType: Guid
  fullName: System.Guid
- uid: System.Runtime.InteropServices.RuntimeEnvironment.GetSystemVersion
  parent: System.Runtime.InteropServices.RuntimeEnvironment
  isExternal: false
  name: GetSystemVersion
  nameWithType: RuntimeEnvironment.GetSystemVersion
  fullName: System.Runtime.InteropServices.RuntimeEnvironment.GetSystemVersion
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Runtime.InteropServices.RuntimeEnvironment.SystemConfigurationFile
  parent: System.Runtime.InteropServices.RuntimeEnvironment
  isExternal: false
  name: SystemConfigurationFile
  nameWithType: RuntimeEnvironment.SystemConfigurationFile
  fullName: System.Runtime.InteropServices.RuntimeEnvironment.SystemConfigurationFile
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
