### YamlMime:ManagedReference
items:
- uid: System.Configuration.ConnectionStringSettings
  id: ConnectionStringSettings
  children:
  - System.Configuration.ConnectionStringSettings.#ctor
  - System.Configuration.ConnectionStringSettings.#ctor(System.String,System.String)
  - System.Configuration.ConnectionStringSettings.#ctor(System.String,System.String,System.String)
  - System.Configuration.ConnectionStringSettings.ConnectionString
  - System.Configuration.ConnectionStringSettings.Name
  - System.Configuration.ConnectionStringSettings.Properties
  - System.Configuration.ConnectionStringSettings.ProviderName
  - System.Configuration.ConnectionStringSettings.ToString
  langs:
  - csharp
  name: ConnectionStringSettings
  nameWithType: ConnectionStringSettings
  fullName: System.Configuration.ConnectionStringSettings
  type: Class
  summary: Represents a single, named connection string in the connection strings configuration file section.
  remarks: A ConnectionStringSettings object represents a single entry in the `connectionStrings` configuration file section.
  example:
  - "The following example shows how to access a ConnectionStringSettings object at a given index in a <xref:System.Configuration.ConnectionStringSettingsCollection> collection.  \n  \n [!CODE [System.Configuration.ConnectionStrings#21](../CodeSnippet/VS_Snippets_WebNet/System.Configuration.ConnectionStrings#21)]"
  syntax:
    content: 'public sealed class ConnectionStringSettings : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ConnectionStringSettings.#ctor
  id: '#ctor'
  parent: System.Configuration.ConnectionStringSettings
  langs:
  - csharp
  name: ConnectionStringSettings()
  nameWithType: ConnectionStringSettings.ConnectionStringSettings()
  fullName: System.Configuration.ConnectionStringSettings.ConnectionStringSettings()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Initializes a new instance of a <see cref="T:System.Configuration.ConnectionStringSettings"> class.
  remarks: To be added.
  syntax:
    content: public ConnectionStringSettings ();
    parameters: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ConnectionStringSettings.#ctor(System.String,System.String)
  id: '#ctor(System.String,System.String)'
  parent: System.Configuration.ConnectionStringSettings
  langs:
  - csharp
  name: ConnectionStringSettings(String,String)
  nameWithType: ConnectionStringSettings.ConnectionStringSettings(String,String)
  fullName: System.Configuration.ConnectionStringSettings.ConnectionStringSettings(String,String)
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Initializes a new instance of a <see cref="T:System.Configuration.ConnectionStringSettings"> class.
  remarks: To be added.
  syntax:
    content: public ConnectionStringSettings (string name, string connectionString);
    parameters:
    - id: name
      type: System.String
      description: The name of the connection string.
    - id: connectionString
      type: System.String
      description: The connection string.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ConnectionStringSettings.#ctor(System.String,System.String,System.String)
  id: '#ctor(System.String,System.String,System.String)'
  parent: System.Configuration.ConnectionStringSettings
  langs:
  - csharp
  name: ConnectionStringSettings(String,String,String)
  nameWithType: ConnectionStringSettings.ConnectionStringSettings(String,String,String)
  fullName: System.Configuration.ConnectionStringSettings.ConnectionStringSettings(String,String,String)
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Initializes a new instance of a <see cref="T:System.Configuration.ConnectionStringSettings"> object.
  remarks: ''
  example:
  - "The following example shows how to create a <xref:System.Configuration.ConnectionStringSettings> object and add it to a <xref:System.Configuration.ConnectionStringSettingsCollection> collection.  \n  \n [!CODE [System.Configuration.ConnectionStrings#8](../CodeSnippet/VS_Snippets_WebNet/System.Configuration.ConnectionStrings#8)]"
  syntax:
    content: public ConnectionStringSettings (string name, string connectionString, string providerName);
    parameters:
    - id: name
      type: System.String
      description: The name of the connection string.
    - id: connectionString
      type: System.String
      description: The connection string.
    - id: providerName
      type: System.String
      description: The name of the provider to use with the connection string.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ConnectionStringSettings.ConnectionString
  id: ConnectionString
  parent: System.Configuration.ConnectionStringSettings
  langs:
  - csharp
  name: ConnectionString
  nameWithType: ConnectionStringSettings.ConnectionString
  fullName: System.Configuration.ConnectionStringSettings.ConnectionString
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Gets or sets the connection string.
  remarks: ''
  example:
  - "The following example shows how to use the ConnectionString property.  \n  \n [!CODE [System.Configuration.ConnectionStrings#4](../CodeSnippet/VS_Snippets_WebNet/System.Configuration.ConnectionStrings#4)]"
  syntax:
    content: public string ConnectionString { get; set; }
    return:
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ConnectionStringSettings.Name
  id: Name
  parent: System.Configuration.ConnectionStringSettings
  langs:
  - csharp
  name: Name
  nameWithType: ConnectionStringSettings.Name
  fullName: System.Configuration.ConnectionStringSettings.Name
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Gets or sets the <see cref="T:System.Configuration.ConnectionStringSettings"> name.
  remarks: ''
  example:
  - "The following example shows how to use the Name property.  \n  \n [!CODE [System.Configuration.ConnectionStrings#5](../CodeSnippet/VS_Snippets_WebNet/System.Configuration.ConnectionStrings#5)]"
  syntax:
    content: public string Name { get; set; }
    return:
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ConnectionStringSettings.Properties
  id: Properties
  parent: System.Configuration.ConnectionStringSettings
  langs:
  - csharp
  name: Properties
  nameWithType: ConnectionStringSettings.Properties
  fullName: System.Configuration.ConnectionStringSettings.Properties
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ConnectionStringSettings.ProviderName
  id: ProviderName
  parent: System.Configuration.ConnectionStringSettings
  langs:
  - csharp
  name: ProviderName
  nameWithType: ConnectionStringSettings.ProviderName
  fullName: System.Configuration.ConnectionStringSettings.ProviderName
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Gets or sets the provider name property.
  remarks: ''
  example:
  - "The following example shows how to use the ProviderName property.  \n  \n [!CODE [System.Configuration.ConnectionStrings#6](../CodeSnippet/VS_Snippets_WebNet/System.Configuration.ConnectionStrings#6)]"
  syntax:
    content: public string ProviderName { get; set; }
    return:
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ConnectionStringSettings.ToString
  id: ToString
  parent: System.Configuration.ConnectionStringSettings
  langs:
  - csharp
  name: ToString()
  nameWithType: ConnectionStringSettings.ToString()
  fullName: System.Configuration.ConnectionStringSettings.ToString()
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Returns a string representation of the object.
  remarks: To be added.
  syntax:
    content: public override string ToString ();
    parameters: []
    return:
      type: System.String
      description: A string representation of the object.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Configuration.ConnectionStringSettings.#ctor
  parent: System.Configuration.ConnectionStringSettings
  isExternal: false
  name: ConnectionStringSettings()
  nameWithType: ConnectionStringSettings.ConnectionStringSettings()
  fullName: System.Configuration.ConnectionStringSettings.ConnectionStringSettings()
- uid: System.Configuration.ConnectionStringSettings.#ctor(System.String,System.String)
  parent: System.Configuration.ConnectionStringSettings
  isExternal: false
  name: ConnectionStringSettings(String,String)
  nameWithType: ConnectionStringSettings.ConnectionStringSettings(String,String)
  fullName: System.Configuration.ConnectionStringSettings.ConnectionStringSettings(String,String)
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.ConnectionStringSettings.#ctor(System.String,System.String,System.String)
  parent: System.Configuration.ConnectionStringSettings
  isExternal: false
  name: ConnectionStringSettings(String,String,String)
  nameWithType: ConnectionStringSettings.ConnectionStringSettings(String,String,String)
  fullName: System.Configuration.ConnectionStringSettings.ConnectionStringSettings(String,String,String)
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.ConnectionStringSettings.ConnectionString
  parent: System.Configuration.ConnectionStringSettings
  isExternal: false
  name: ConnectionString
  nameWithType: ConnectionStringSettings.ConnectionString
  fullName: System.Configuration.ConnectionStringSettings.ConnectionString
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.ConnectionStringSettings.Name
  parent: System.Configuration.ConnectionStringSettings
  isExternal: false
  name: Name
  nameWithType: ConnectionStringSettings.Name
  fullName: System.Configuration.ConnectionStringSettings.Name
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.ConnectionStringSettings.Properties
  parent: System.Configuration.ConnectionStringSettings
  isExternal: false
  name: Properties
  nameWithType: ConnectionStringSettings.Properties
  fullName: System.Configuration.ConnectionStringSettings.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Configuration.ConnectionStringSettings.ProviderName
  parent: System.Configuration.ConnectionStringSettings
  isExternal: false
  name: ProviderName
  nameWithType: ConnectionStringSettings.ProviderName
  fullName: System.Configuration.ConnectionStringSettings.ProviderName
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.ConnectionStringSettings.ToString
  parent: System.Configuration.ConnectionStringSettings
  isExternal: false
  name: ToString()
  nameWithType: ConnectionStringSettings.ToString()
  fullName: System.Configuration.ConnectionStringSettings.ToString()
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
