### YamlMime:ManagedReference
items:
- uid: System.Configuration.ConfigurationConverterBase
  id: ConfigurationConverterBase
  children:
  - System.Configuration.ConfigurationConverterBase.#ctor
  - System.Configuration.ConfigurationConverterBase.CanConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Type)
  - System.Configuration.ConfigurationConverterBase.CanConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Type)
  langs:
  - csharp
  - vb
  name: ConfigurationConverterBase
  nameWithType: ConfigurationConverterBase
  fullName: System.Configuration.ConfigurationConverterBase
  type: Class
  syntax:
    content: 'public abstract class ConfigurationConverterBase : System.ComponentModel.TypeConverter'
  inheritance:
  - System.ComponentModel.TypeConverter
  implements: []
  inheritedMembers: []
- uid: System.Configuration.ConfigurationConverterBase.#ctor
  id: '#ctor'
  parent: System.Configuration.ConfigurationConverterBase
  langs:
  - csharp
  - vb
  name: .ctor
  nameWithType: ConfigurationConverterBase..ctor
  fullName: System.Configuration.ConfigurationConverterBase..ctor
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: protected ConfigurationConverterBase ();
    parameters: []
- uid: System.Configuration.ConfigurationConverterBase.CanConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Type)
  id: CanConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Type)
  parent: System.Configuration.ConfigurationConverterBase
  langs:
  - csharp
  - vb
  name: CanConvertFrom
  nameWithType: ConfigurationConverterBase.CanConvertFrom
  fullName: System.Configuration.ConfigurationConverterBase.CanConvertFrom
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: public override bool CanConvertFrom (System.ComponentModel.ITypeDescriptorContext ctx, Type type);
    parameters:
    - id: ctx
      type: System.ComponentModel.ITypeDescriptorContext
      description: Parameter description to be filled
    - id: type
      type: System.Type
      description: Parameter description to be filled
    return:
      type: System.Boolean
      description: Return description to be filled
- uid: System.Configuration.ConfigurationConverterBase.CanConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Type)
  id: CanConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Type)
  parent: System.Configuration.ConfigurationConverterBase
  langs:
  - csharp
  - vb
  name: CanConvertTo
  nameWithType: ConfigurationConverterBase.CanConvertTo
  fullName: System.Configuration.ConfigurationConverterBase.CanConvertTo
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: public override bool CanConvertTo (System.ComponentModel.ITypeDescriptorContext ctx, Type type);
    parameters:
    - id: ctx
      type: System.ComponentModel.ITypeDescriptorContext
      description: Parameter description to be filled
    - id: type
      type: System.Type
      description: Parameter description to be filled
    return:
      type: System.Boolean
      description: Return description to be filled
references:
- uid: System.ComponentModel.TypeConverter
  isExternal: false
  name: System.ComponentModel.TypeConverter
- uid: System.Configuration.ConfigurationConverterBase.#ctor
  parent: System.Configuration.ConfigurationConverterBase
  isExternal: false
  name: .ctor
  nameWithType: ConfigurationConverterBase..ctor
  fullName: System.Configuration.ConfigurationConverterBase..ctor
- uid: System.Configuration.ConfigurationConverterBase.CanConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Type)
  parent: System.Configuration.ConfigurationConverterBase
  isExternal: false
  name: CanConvertFrom
  nameWithType: ConfigurationConverterBase.CanConvertFrom
  fullName: System.Configuration.ConfigurationConverterBase.CanConvertFrom
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Type
  parent: System
  isExternal: false
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Configuration.ConfigurationConverterBase.CanConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Type)
  parent: System.Configuration.ConfigurationConverterBase
  isExternal: false
  name: CanConvertTo
  nameWithType: ConfigurationConverterBase.CanConvertTo
  fullName: System.Configuration.ConfigurationConverterBase.CanConvertTo
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Type
  parent: System
  isExternal: false
  name: Type
  nameWithType: Type
  fullName: System.Type
