### YamlMime:ManagedReference
items:
- uid: System.Configuration.ElementInformation
  id: ElementInformation
  children:
  - System.Configuration.ElementInformation.Errors
  - System.Configuration.ElementInformation.IsCollection
  - System.Configuration.ElementInformation.IsLocked
  - System.Configuration.ElementInformation.IsPresent
  - System.Configuration.ElementInformation.LineNumber
  - System.Configuration.ElementInformation.Properties
  - System.Configuration.ElementInformation.Source
  - System.Configuration.ElementInformation.Type
  - System.Configuration.ElementInformation.Validator
  langs:
  - csharp
  name: ElementInformation
  nameWithType: ElementInformation
  fullName: System.Configuration.ElementInformation
  type: Class
  summary: Contains meta-information about an individual element within the configuration. This class cannot be inherited.
  remarks: The ElementInformation object contains meta-information about an individual element within the configuration. This object can be used when validating and changing the properties of an individual element.
  example:
  - "The following example shows how to get the ElementInformation associated with a <xref:System.Configuration.ConfigurationElement> object.  \n  \n [!CODE [System.Configuration.ConfigurationElement#80](../CodeSnippet/VS_Snippets_WebNet/System.Configuration.ConfigurationElement#80)]  \n  \n The following excerpt shows the configuration used by the previous code example.  \n  \n```  \n<?xml version=\"1.0\" encoding=\"utf-8\"?>  \n<configuration>  \n  <configSections>  \n    <section name=\"MyUrls\" type=\"Samples.AspNet.UrlsSection,  \n      ConfigurationElement, Version=1.0.0.0, Culture=neutral,  \n      PublicKeyToken=null\" allowDefinition=\"Everywhere\"  \n      allowExeDefinition=\"MachineToApplication\"  \n      restartOnExternalChanges=\"true\" />  \n  </configSections>  \n  <MyUrls name=\"MyFavorites\">  \n    <simple name=\"Contoso\" url=\"http://www.contoso.com\" port=\"8080\" />  \n    <urls>  \n      <clear />  \n      <add name=\"Microsoft\" url=\"http://www.microsoft.com\" port=\"0\" />  \n    </urls>  \n  </MyUrls>  \n</configuration>  \n```"
  syntax:
    content: public sealed class ElementInformation
  inheritance:
  - System.Object
  implements: []
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ElementInformation.Errors
  id: Errors
  parent: System.Configuration.ElementInformation
  langs:
  - csharp
  name: Errors
  nameWithType: ElementInformation.Errors
  fullName: System.Configuration.ElementInformation.Errors
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Gets the errors for the associated element and subelements
  remarks: ''
  example:
  - "The following example shows how to use the Errors collection.  \n  \n [!CODE [System.Configuration.ConfigurationElement#89](../CodeSnippet/VS_Snippets_WebNet/System.Configuration.ConfigurationElement#89)]"
  syntax:
    content: public System.Collections.ICollection Errors { get; }
    return:
      type: System.Collections.ICollection
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ElementInformation.IsCollection
  id: IsCollection
  parent: System.Configuration.ElementInformation
  langs:
  - csharp
  name: IsCollection
  nameWithType: ElementInformation.IsCollection
  fullName: System.Configuration.ElementInformation.IsCollection
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Gets a value indicating whether the associated <see cref="T:System.Configuration.ConfigurationElement"> object is a <xref:System.Configuration.ConfigurationElementCollection> collection.
  remarks: ''
  example:
  - "The following example shows how to use the IsCollection property.  \n  \n [!CODE [System.Configuration.ConfigurationElement#81](../CodeSnippet/VS_Snippets_WebNet/System.Configuration.ConfigurationElement#81)]"
  syntax:
    content: public bool IsCollection { get; }
    return:
      type: System.Boolean
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ElementInformation.IsLocked
  id: IsLocked
  parent: System.Configuration.ElementInformation
  langs:
  - csharp
  name: IsLocked
  nameWithType: ElementInformation.IsLocked
  fullName: System.Configuration.ElementInformation.IsLocked
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Gets a value that indicates whether the associated <see cref="T:System.Configuration.ConfigurationElement"> object cannot be modified.
  remarks: The IsLocked property returns `true` when the related element is locked by the <xref:System.Configuration.SectionInformation.AllowOverride%2A>, <xref:System.Configuration.SectionInformation.AllowDefinition%2A>, or <xref:System.Configuration.ConfigurationElement.LockAllAttributesExcept%2A> property.
  example:
  - "The following example shows how to use the IsLocked property.  \n  \n [!CODE [System.Configuration.ConfigurationElement#82](../CodeSnippet/VS_Snippets_WebNet/System.Configuration.ConfigurationElement#82)]"
  syntax:
    content: public bool IsLocked { get; }
    return:
      type: System.Boolean
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ElementInformation.IsPresent
  id: IsPresent
  parent: System.Configuration.ElementInformation
  langs:
  - csharp
  name: IsPresent
  nameWithType: ElementInformation.IsPresent
  fullName: System.Configuration.ElementInformation.IsPresent
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Gets a value indicating whether the associated <see cref="T:System.Configuration.ConfigurationElement"> object is in the configuration file.
  remarks: ''
  example:
  - "The following example shows how to use the IsPresent property.  \n  \n [!CODE [System.Configuration.ConfigurationElement#83](../CodeSnippet/VS_Snippets_WebNet/System.Configuration.ConfigurationElement#83)]"
  syntax:
    content: public bool IsPresent { get; }
    return:
      type: System.Boolean
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ElementInformation.LineNumber
  id: LineNumber
  parent: System.Configuration.ElementInformation
  langs:
  - csharp
  name: LineNumber
  nameWithType: ElementInformation.LineNumber
  fullName: System.Configuration.ElementInformation.LineNumber
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Gets the line number in the configuration file where the associated <see cref="T:System.Configuration.ConfigurationElement"> object is defined.
  remarks: ''
  example:
  - "The following example shows how to use the LineNumber property.  \n  \n [!CODE [System.Configuration.ConfigurationElement#84](../CodeSnippet/VS_Snippets_WebNet/System.Configuration.ConfigurationElement#84)]"
  syntax:
    content: public int LineNumber { get; }
    return:
      type: System.Int32
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ElementInformation.Properties
  id: Properties
  parent: System.Configuration.ElementInformation
  langs:
  - csharp
  name: Properties
  nameWithType: ElementInformation.Properties
  fullName: System.Configuration.ElementInformation.Properties
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Gets a <see cref="T:System.Configuration.PropertyInformationCollection"> collection of the properties in the associated <xref:System.Configuration.ConfigurationElement> object.
  remarks: The properties of a <xref:System.Configuration.ConfigurationElement> object are the attributes and subelements associated with that configuration element in the configuration file.
  example:
  - "The following example shows how to get the Properties collection.  \n  \n [!CODE [System.Configuration.ConfigurationElement#85](../CodeSnippet/VS_Snippets_WebNet/System.Configuration.ConfigurationElement#85)]"
  syntax:
    content: public System.Configuration.PropertyInformationCollection Properties { get; }
    return:
      type: System.Configuration.PropertyInformationCollection
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ElementInformation.Source
  id: Source
  parent: System.Configuration.ElementInformation
  langs:
  - csharp
  name: Source
  nameWithType: ElementInformation.Source
  fullName: System.Configuration.ElementInformation.Source
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Gets the source file where the associated <see cref="T:System.Configuration.ConfigurationElement"> object originated.
  remarks: A <xref:System.Configuration.ConfigurationElement> object may be created in a default state, in which case this property returns `null`.
  example:
  - "The following example shows how to use the Source property.  \n  \n [!CODE [System.Configuration.ConfigurationElement#86](../CodeSnippet/VS_Snippets_WebNet/System.Configuration.ConfigurationElement#86)]"
  syntax:
    content: public string Source { get; }
    return:
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ElementInformation.Type
  id: Type
  parent: System.Configuration.ElementInformation
  langs:
  - csharp
  name: Type
  nameWithType: ElementInformation.Type
  fullName: System.Configuration.ElementInformation.Type
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Gets the type of the associated <see cref="T:System.Configuration.ConfigurationElement"> object.
  remarks: ''
  example:
  - "The following example shows how to use the Type property.  \n  \n [!CODE [System.Configuration.ConfigurationElement#87](../CodeSnippet/VS_Snippets_WebNet/System.Configuration.ConfigurationElement#87)]"
  syntax:
    content: public Type Type { get; }
    return:
      type: System.Type
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ElementInformation.Validator
  id: Validator
  parent: System.Configuration.ElementInformation
  langs:
  - csharp
  name: Validator
  nameWithType: ElementInformation.Validator
  fullName: System.Configuration.ElementInformation.Validator
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Gets the object used to validate the associated <see cref="T:System.Configuration.ConfigurationElement"> object.
  remarks: A validator object is not required, and this property may return `null`.
  example:
  - "The following example shows how to use the Validator property.  \n  \n [!CODE [System.Configuration.ConfigurationElement#88](../CodeSnippet/VS_Snippets_WebNet/System.Configuration.ConfigurationElement#88)]"
  syntax:
    content: public System.Configuration.ConfigurationValidatorBase Validator { get; }
    return:
      type: System.Configuration.ConfigurationValidatorBase
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Configuration.ElementInformation.Errors
  parent: System.Configuration.ElementInformation
  isExternal: false
  name: Errors
  nameWithType: ElementInformation.Errors
  fullName: System.Configuration.ElementInformation.Errors
- uid: System.Collections.ICollection
  parent: System.Collections
  isExternal: false
  name: ICollection
  nameWithType: ICollection
  fullName: System.Collections.ICollection
- uid: System.Configuration.ElementInformation.IsCollection
  parent: System.Configuration.ElementInformation
  isExternal: false
  name: IsCollection
  nameWithType: ElementInformation.IsCollection
  fullName: System.Configuration.ElementInformation.IsCollection
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.ElementInformation.IsLocked
  parent: System.Configuration.ElementInformation
  isExternal: false
  name: IsLocked
  nameWithType: ElementInformation.IsLocked
  fullName: System.Configuration.ElementInformation.IsLocked
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.ElementInformation.IsPresent
  parent: System.Configuration.ElementInformation
  isExternal: false
  name: IsPresent
  nameWithType: ElementInformation.IsPresent
  fullName: System.Configuration.ElementInformation.IsPresent
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.ElementInformation.LineNumber
  parent: System.Configuration.ElementInformation
  isExternal: false
  name: LineNumber
  nameWithType: ElementInformation.LineNumber
  fullName: System.Configuration.ElementInformation.LineNumber
- uid: System.Int32
  parent: System
  isExternal: false
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Configuration.ElementInformation.Properties
  parent: System.Configuration.ElementInformation
  isExternal: false
  name: Properties
  nameWithType: ElementInformation.Properties
  fullName: System.Configuration.ElementInformation.Properties
- uid: System.Configuration.PropertyInformationCollection
  parent: System.Configuration
  isExternal: false
  name: PropertyInformationCollection
  nameWithType: PropertyInformationCollection
  fullName: System.Configuration.PropertyInformationCollection
- uid: System.Configuration.ElementInformation.Source
  parent: System.Configuration.ElementInformation
  isExternal: false
  name: Source
  nameWithType: ElementInformation.Source
  fullName: System.Configuration.ElementInformation.Source
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.ElementInformation.Type
  parent: System.Configuration.ElementInformation
  isExternal: false
  name: Type
  nameWithType: ElementInformation.Type
  fullName: System.Configuration.ElementInformation.Type
- uid: System.Type
  parent: System
  isExternal: false
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Configuration.ElementInformation.Validator
  parent: System.Configuration.ElementInformation
  isExternal: false
  name: Validator
  nameWithType: ElementInformation.Validator
  fullName: System.Configuration.ElementInformation.Validator
- uid: System.Configuration.ConfigurationValidatorBase
  parent: System.Configuration
  isExternal: false
  name: ConfigurationValidatorBase
  nameWithType: ConfigurationValidatorBase
  fullName: System.Configuration.ConfigurationValidatorBase
