### YamlMime:ManagedReference
items:
- uid: System.Configuration.PositiveTimeSpanValidatorAttribute
  id: PositiveTimeSpanValidatorAttribute
  children:
  - System.Configuration.PositiveTimeSpanValidatorAttribute.#ctor
  - System.Configuration.PositiveTimeSpanValidatorAttribute.ValidatorInstance
  langs:
  - csharp
  name: PositiveTimeSpanValidatorAttribute
  nameWithType: PositiveTimeSpanValidatorAttribute
  fullName: System.Configuration.PositiveTimeSpanValidatorAttribute
  type: Class
  summary: Declaratively instructs the .NET Framework to perform time validation on a configuration property. This class cannot be inherited.
  remarks: "You use the PositiveTimeSpanValidatorAttribute attribute to decorate a configuration property. This instructs the .NET Framework to validate the property using a <xref:System.Configuration.PositiveTimeSpanValidator> object and pass the value of the decorating parameters.  \n  \n You can apply PositiveTimeSpanValidatorAttribute objects only to property types."
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property)]

      public sealed class PositiveTimeSpanValidatorAttribute : System.Configuration.ConfigurationValidatorAttribute
  inheritance:
  - System.Object
  - System.Attribute
  - System.Configuration.ConfigurationValidatorAttribute
  implements: []
  inheritedMembers:
  - System.Attribute.Equals(System.Object)
  - System.Attribute.GetCustomAttribute(System.Reflection.Assembly,System.Type)
  - System.Attribute.GetCustomAttribute(System.Reflection.Assembly,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttribute(System.Reflection.MemberInfo,System.Type)
  - System.Attribute.GetCustomAttribute(System.Reflection.MemberInfo,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttribute(System.Reflection.Module,System.Type)
  - System.Attribute.GetCustomAttribute(System.Reflection.Module,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttribute(System.Reflection.ParameterInfo,System.Type)
  - System.Attribute.GetCustomAttribute(System.Reflection.ParameterInfo,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.Assembly)
  - System.Attribute.GetCustomAttributes(System.Reflection.Assembly,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.Assembly,System.Type)
  - System.Attribute.GetCustomAttributes(System.Reflection.Assembly,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.MemberInfo)
  - System.Attribute.GetCustomAttributes(System.Reflection.MemberInfo,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.MemberInfo,System.Type)
  - System.Attribute.GetCustomAttributes(System.Reflection.MemberInfo,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.Module)
  - System.Attribute.GetCustomAttributes(System.Reflection.Module,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.Module,System.Type)
  - System.Attribute.GetCustomAttributes(System.Reflection.Module,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.ParameterInfo)
  - System.Attribute.GetCustomAttributes(System.Reflection.ParameterInfo,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.ParameterInfo,System.Type)
  - System.Attribute.GetCustomAttributes(System.Reflection.ParameterInfo,System.Type,System.Boolean)
  - System.Attribute.GetHashCode
  - System.Attribute.IsDefaultAttribute
  - System.Attribute.IsDefined(System.Reflection.Assembly,System.Type)
  - System.Attribute.IsDefined(System.Reflection.Assembly,System.Type,System.Boolean)
  - System.Attribute.IsDefined(System.Reflection.MemberInfo,System.Type)
  - System.Attribute.IsDefined(System.Reflection.MemberInfo,System.Type,System.Boolean)
  - System.Attribute.IsDefined(System.Reflection.Module,System.Type)
  - System.Attribute.IsDefined(System.Reflection.Module,System.Type,System.Boolean)
  - System.Attribute.IsDefined(System.Reflection.ParameterInfo,System.Type)
  - System.Attribute.IsDefined(System.Reflection.ParameterInfo,System.Type,System.Boolean)
  - System.Attribute.Match(System.Object)
  - System.Attribute.System#Runtime#InteropServices#_Attribute#GetIDsOfNames(System.Guid@,System.IntPtr,System.UInt32,System.UInt32,System.IntPtr)
  - System.Attribute.System#Runtime#InteropServices#_Attribute#GetTypeInfo(System.UInt32,System.UInt32,System.IntPtr)
  - System.Attribute.System#Runtime#InteropServices#_Attribute#GetTypeInfoCount(System.UInt32@)
  - System.Attribute.System#Runtime#InteropServices#_Attribute#Invoke(System.UInt32,System.Guid@,System.UInt32,System.Int16,System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr)
  - System.Attribute.TypeId
  - System.Configuration.ConfigurationValidatorAttribute.ValidatorType
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.PositiveTimeSpanValidatorAttribute.#ctor
  id: '#ctor'
  parent: System.Configuration.PositiveTimeSpanValidatorAttribute
  langs:
  - csharp
  name: PositiveTimeSpanValidatorAttribute()
  nameWithType: PositiveTimeSpanValidatorAttribute.PositiveTimeSpanValidatorAttribute()
  fullName: System.Configuration.PositiveTimeSpanValidatorAttribute.PositiveTimeSpanValidatorAttribute()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Initializes a new instance of the <see cref="T:System.Configuration.PositiveTimeSpanValidatorAttribute"> class.
  remarks: You use this constructor in the attributed model to ensure that the type of the value assigned to the related property is a positive <xref:System.TimeSpan> object.
  syntax:
    content: public PositiveTimeSpanValidatorAttribute ();
    parameters: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.PositiveTimeSpanValidatorAttribute.ValidatorInstance
  id: ValidatorInstance
  parent: System.Configuration.PositiveTimeSpanValidatorAttribute
  langs:
  - csharp
  name: ValidatorInstance
  nameWithType: PositiveTimeSpanValidatorAttribute.ValidatorInstance
  fullName: System.Configuration.PositiveTimeSpanValidatorAttribute.ValidatorInstance
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Gets an instance of the <see cref="T:System.Configuration.PositiveTimeSpanValidator"> class.
  remarks: You use the ValidatorInstance property to perform positive <xref:System.TimeSpan> object validation by calling the <xref:System.Configuration.PositiveTimeSpanValidator.Validate%2A?displayProperty=fullName> method.
  syntax:
    content: public override System.Configuration.ConfigurationValidatorBase ValidatorInstance { get; }
    return:
      type: System.Configuration.ConfigurationValidatorBase
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationValidatorAttribute
  isExternal: false
  name: System.Configuration.ConfigurationValidatorAttribute
- uid: System.Configuration.PositiveTimeSpanValidatorAttribute.#ctor
  parent: System.Configuration.PositiveTimeSpanValidatorAttribute
  isExternal: false
  name: PositiveTimeSpanValidatorAttribute()
  nameWithType: PositiveTimeSpanValidatorAttribute.PositiveTimeSpanValidatorAttribute()
  fullName: System.Configuration.PositiveTimeSpanValidatorAttribute.PositiveTimeSpanValidatorAttribute()
- uid: System.Configuration.PositiveTimeSpanValidatorAttribute.ValidatorInstance
  parent: System.Configuration.PositiveTimeSpanValidatorAttribute
  isExternal: false
  name: ValidatorInstance
  nameWithType: PositiveTimeSpanValidatorAttribute.ValidatorInstance
  fullName: System.Configuration.PositiveTimeSpanValidatorAttribute.ValidatorInstance
- uid: System.Configuration.ConfigurationValidatorBase
  parent: System.Configuration
  isExternal: false
  name: ConfigurationValidatorBase
  nameWithType: ConfigurationValidatorBase
  fullName: System.Configuration.ConfigurationValidatorBase
