### YamlMime:ManagedReference
items:
- uid: System.Configuration.RsaProtectedConfigurationProvider
  id: RsaProtectedConfigurationProvider
  children:
  - System.Configuration.RsaProtectedConfigurationProvider.#ctor
  - System.Configuration.RsaProtectedConfigurationProvider.AddKey(System.Int32,System.Boolean)
  - System.Configuration.RsaProtectedConfigurationProvider.CspProviderName
  - System.Configuration.RsaProtectedConfigurationProvider.Decrypt(System.Xml.XmlNode)
  - System.Configuration.RsaProtectedConfigurationProvider.DeleteKey
  - System.Configuration.RsaProtectedConfigurationProvider.Encrypt(System.Xml.XmlNode)
  - System.Configuration.RsaProtectedConfigurationProvider.ExportKey(System.String,System.Boolean)
  - System.Configuration.RsaProtectedConfigurationProvider.ImportKey(System.String,System.Boolean)
  - System.Configuration.RsaProtectedConfigurationProvider.Initialize(System.String,System.Collections.Specialized.NameValueCollection)
  - System.Configuration.RsaProtectedConfigurationProvider.KeyContainerName
  - System.Configuration.RsaProtectedConfigurationProvider.RsaPublicKey
  - System.Configuration.RsaProtectedConfigurationProvider.UseFIPS
  - System.Configuration.RsaProtectedConfigurationProvider.UseMachineContainer
  - System.Configuration.RsaProtectedConfigurationProvider.UseOAEP
  langs:
  - csharp
  - vb
  name: RsaProtectedConfigurationProvider
  nameWithType: RsaProtectedConfigurationProvider
  fullName: System.Configuration.RsaProtectedConfigurationProvider
  type: Class
  syntax:
    content: 'public sealed class RsaProtectedConfigurationProvider : System.Configuration.ProtectedConfigurationProvider'
  inheritance:
  - System.Object
  - System.Configuration.Provider.ProviderBase
  - System.Configuration.ProtectedConfigurationProvider
  implements: []
  inheritedMembers:
  - System.Configuration.Provider.ProviderBase.Description
  - System.Configuration.Provider.ProviderBase.Name
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: System.Configuration.RsaProtectedConfigurationProvider.#ctor
  id: '#ctor'
  parent: System.Configuration.RsaProtectedConfigurationProvider
  langs:
  - csharp
  - vb
  name: RsaProtectedConfigurationProvider()
  nameWithType: RsaProtectedConfigurationProvider.RsaProtectedConfigurationProvider()
  fullName: System.Configuration.RsaProtectedConfigurationProvider.RsaProtectedConfigurationProvider()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: public RsaProtectedConfigurationProvider ();
    parameters: []
- uid: System.Configuration.RsaProtectedConfigurationProvider.AddKey(System.Int32,System.Boolean)
  id: AddKey(System.Int32,System.Boolean)
  parent: System.Configuration.RsaProtectedConfigurationProvider
  langs:
  - csharp
  - vb
  name: AddKey(Int32,Boolean)
  nameWithType: RsaProtectedConfigurationProvider.AddKey(Int32,Boolean)
  fullName: System.Configuration.RsaProtectedConfigurationProvider.AddKey(Int32,Boolean)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: public void AddKey (int keySize, bool exportable);
    parameters:
    - id: keySize
      type: System.Int32
      description: Parameter description to be filled
    - id: exportable
      type: System.Boolean
      description: Parameter description to be filled
    return:
      type: System.Void
      description: Return description to be filled
- uid: System.Configuration.RsaProtectedConfigurationProvider.CspProviderName
  id: CspProviderName
  parent: System.Configuration.RsaProtectedConfigurationProvider
  langs:
  - csharp
  - vb
  name: CspProviderName
  nameWithType: RsaProtectedConfigurationProvider.CspProviderName
  fullName: System.Configuration.RsaProtectedConfigurationProvider.CspProviderName
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: public string CspProviderName { get; }
    return:
      type: System.String
      description: Return description to be filled
- uid: System.Configuration.RsaProtectedConfigurationProvider.Decrypt(System.Xml.XmlNode)
  id: Decrypt(System.Xml.XmlNode)
  parent: System.Configuration.RsaProtectedConfigurationProvider
  langs:
  - csharp
  - vb
  name: Decrypt(XmlNode)
  nameWithType: RsaProtectedConfigurationProvider.Decrypt(XmlNode)
  fullName: System.Configuration.RsaProtectedConfigurationProvider.Decrypt(XmlNode)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: public override System.Xml.XmlNode Decrypt (System.Xml.XmlNode encryptedNode);
    parameters:
    - id: encryptedNode
      type: System.Xml.XmlNode
      description: Parameter description to be filled
    return:
      type: System.Xml.XmlNode
      description: Return description to be filled
- uid: System.Configuration.RsaProtectedConfigurationProvider.DeleteKey
  id: DeleteKey
  parent: System.Configuration.RsaProtectedConfigurationProvider
  langs:
  - csharp
  - vb
  name: DeleteKey()
  nameWithType: RsaProtectedConfigurationProvider.DeleteKey()
  fullName: System.Configuration.RsaProtectedConfigurationProvider.DeleteKey()
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: public void DeleteKey ();
    parameters: []
    return:
      type: System.Void
      description: Return description to be filled
- uid: System.Configuration.RsaProtectedConfigurationProvider.Encrypt(System.Xml.XmlNode)
  id: Encrypt(System.Xml.XmlNode)
  parent: System.Configuration.RsaProtectedConfigurationProvider
  langs:
  - csharp
  - vb
  name: Encrypt(XmlNode)
  nameWithType: RsaProtectedConfigurationProvider.Encrypt(XmlNode)
  fullName: System.Configuration.RsaProtectedConfigurationProvider.Encrypt(XmlNode)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: public override System.Xml.XmlNode Encrypt (System.Xml.XmlNode node);
    parameters:
    - id: node
      type: System.Xml.XmlNode
      description: Parameter description to be filled
    return:
      type: System.Xml.XmlNode
      description: Return description to be filled
- uid: System.Configuration.RsaProtectedConfigurationProvider.ExportKey(System.String,System.Boolean)
  id: ExportKey(System.String,System.Boolean)
  parent: System.Configuration.RsaProtectedConfigurationProvider
  langs:
  - csharp
  - vb
  name: ExportKey(String,Boolean)
  nameWithType: RsaProtectedConfigurationProvider.ExportKey(String,Boolean)
  fullName: System.Configuration.RsaProtectedConfigurationProvider.ExportKey(String,Boolean)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: public void ExportKey (string xmlFileName, bool includePrivateParameters);
    parameters:
    - id: xmlFileName
      type: System.String
      description: Parameter description to be filled
    - id: includePrivateParameters
      type: System.Boolean
      description: Parameter description to be filled
    return:
      type: System.Void
      description: Return description to be filled
- uid: System.Configuration.RsaProtectedConfigurationProvider.ImportKey(System.String,System.Boolean)
  id: ImportKey(System.String,System.Boolean)
  parent: System.Configuration.RsaProtectedConfigurationProvider
  langs:
  - csharp
  - vb
  name: ImportKey(String,Boolean)
  nameWithType: RsaProtectedConfigurationProvider.ImportKey(String,Boolean)
  fullName: System.Configuration.RsaProtectedConfigurationProvider.ImportKey(String,Boolean)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: public void ImportKey (string xmlFileName, bool exportable);
    parameters:
    - id: xmlFileName
      type: System.String
      description: Parameter description to be filled
    - id: exportable
      type: System.Boolean
      description: Parameter description to be filled
    return:
      type: System.Void
      description: Return description to be filled
- uid: System.Configuration.RsaProtectedConfigurationProvider.Initialize(System.String,System.Collections.Specialized.NameValueCollection)
  id: Initialize(System.String,System.Collections.Specialized.NameValueCollection)
  parent: System.Configuration.RsaProtectedConfigurationProvider
  langs:
  - csharp
  - vb
  name: Initialize(String,NameValueCollection)
  nameWithType: RsaProtectedConfigurationProvider.Initialize(String,NameValueCollection)
  fullName: System.Configuration.RsaProtectedConfigurationProvider.Initialize(String,NameValueCollection)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: public override void Initialize (string name, System.Collections.Specialized.NameValueCollection configurationValues);
    parameters:
    - id: name
      type: System.String
      description: Parameter description to be filled
    - id: configurationValues
      type: System.Collections.Specialized.NameValueCollection
      description: Parameter description to be filled
    return:
      type: System.Void
      description: Return description to be filled
- uid: System.Configuration.RsaProtectedConfigurationProvider.KeyContainerName
  id: KeyContainerName
  parent: System.Configuration.RsaProtectedConfigurationProvider
  langs:
  - csharp
  - vb
  name: KeyContainerName
  nameWithType: RsaProtectedConfigurationProvider.KeyContainerName
  fullName: System.Configuration.RsaProtectedConfigurationProvider.KeyContainerName
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: public string KeyContainerName { get; }
    return:
      type: System.String
      description: Return description to be filled
- uid: System.Configuration.RsaProtectedConfigurationProvider.RsaPublicKey
  id: RsaPublicKey
  parent: System.Configuration.RsaProtectedConfigurationProvider
  langs:
  - csharp
  - vb
  name: RsaPublicKey
  nameWithType: RsaProtectedConfigurationProvider.RsaPublicKey
  fullName: System.Configuration.RsaProtectedConfigurationProvider.RsaPublicKey
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: public System.Security.Cryptography.RSAParameters RsaPublicKey { get; }
    return:
      type: System.Security.Cryptography.RSAParameters
      description: Return description to be filled
- uid: System.Configuration.RsaProtectedConfigurationProvider.UseFIPS
  id: UseFIPS
  parent: System.Configuration.RsaProtectedConfigurationProvider
  langs:
  - csharp
  - vb
  name: UseFIPS
  nameWithType: RsaProtectedConfigurationProvider.UseFIPS
  fullName: System.Configuration.RsaProtectedConfigurationProvider.UseFIPS
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: public bool UseFIPS { get; }
    return:
      type: System.Boolean
      description: Return description to be filled
- uid: System.Configuration.RsaProtectedConfigurationProvider.UseMachineContainer
  id: UseMachineContainer
  parent: System.Configuration.RsaProtectedConfigurationProvider
  langs:
  - csharp
  - vb
  name: UseMachineContainer
  nameWithType: RsaProtectedConfigurationProvider.UseMachineContainer
  fullName: System.Configuration.RsaProtectedConfigurationProvider.UseMachineContainer
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: public bool UseMachineContainer { get; }
    return:
      type: System.Boolean
      description: Return description to be filled
- uid: System.Configuration.RsaProtectedConfigurationProvider.UseOAEP
  id: UseOAEP
  parent: System.Configuration.RsaProtectedConfigurationProvider
  langs:
  - csharp
  - vb
  name: UseOAEP
  nameWithType: RsaProtectedConfigurationProvider.UseOAEP
  fullName: System.Configuration.RsaProtectedConfigurationProvider.UseOAEP
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: public bool UseOAEP { get; }
    return:
      type: System.Boolean
      description: Return description to be filled
references:
- uid: System.Configuration.ProtectedConfigurationProvider
  isExternal: false
  name: System.Configuration.ProtectedConfigurationProvider
- uid: System.Configuration.RsaProtectedConfigurationProvider.#ctor
  parent: System.Configuration.RsaProtectedConfigurationProvider
  isExternal: false
  name: RsaProtectedConfigurationProvider()
  nameWithType: RsaProtectedConfigurationProvider.RsaProtectedConfigurationProvider()
  fullName: System.Configuration.RsaProtectedConfigurationProvider.RsaProtectedConfigurationProvider()
- uid: System.Configuration.RsaProtectedConfigurationProvider.AddKey(System.Int32,System.Boolean)
  parent: System.Configuration.RsaProtectedConfigurationProvider
  isExternal: false
  name: AddKey(Int32,Boolean)
  nameWithType: RsaProtectedConfigurationProvider.AddKey(Int32,Boolean)
  fullName: System.Configuration.RsaProtectedConfigurationProvider.AddKey(Int32,Boolean)
- uid: System.Void
  parent: System
  isExternal: false
  name: Void
  nameWithType: Void
  fullName: System.Void
- uid: System.Int32
  parent: System
  isExternal: false
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.RsaProtectedConfigurationProvider.CspProviderName
  parent: System.Configuration.RsaProtectedConfigurationProvider
  isExternal: false
  name: CspProviderName
  nameWithType: RsaProtectedConfigurationProvider.CspProviderName
  fullName: System.Configuration.RsaProtectedConfigurationProvider.CspProviderName
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.RsaProtectedConfigurationProvider.Decrypt(System.Xml.XmlNode)
  parent: System.Configuration.RsaProtectedConfigurationProvider
  isExternal: false
  name: Decrypt(XmlNode)
  nameWithType: RsaProtectedConfigurationProvider.Decrypt(XmlNode)
  fullName: System.Configuration.RsaProtectedConfigurationProvider.Decrypt(XmlNode)
- uid: System.Configuration.RsaProtectedConfigurationProvider.DeleteKey
  parent: System.Configuration.RsaProtectedConfigurationProvider
  isExternal: false
  name: DeleteKey()
  nameWithType: RsaProtectedConfigurationProvider.DeleteKey()
  fullName: System.Configuration.RsaProtectedConfigurationProvider.DeleteKey()
- uid: System.Void
  parent: System
  isExternal: false
  name: Void
  nameWithType: Void
  fullName: System.Void
- uid: System.Configuration.RsaProtectedConfigurationProvider.Encrypt(System.Xml.XmlNode)
  parent: System.Configuration.RsaProtectedConfigurationProvider
  isExternal: false
  name: Encrypt(XmlNode)
  nameWithType: RsaProtectedConfigurationProvider.Encrypt(XmlNode)
  fullName: System.Configuration.RsaProtectedConfigurationProvider.Encrypt(XmlNode)
- uid: System.Configuration.RsaProtectedConfigurationProvider.ExportKey(System.String,System.Boolean)
  parent: System.Configuration.RsaProtectedConfigurationProvider
  isExternal: false
  name: ExportKey(String,Boolean)
  nameWithType: RsaProtectedConfigurationProvider.ExportKey(String,Boolean)
  fullName: System.Configuration.RsaProtectedConfigurationProvider.ExportKey(String,Boolean)
- uid: System.Void
  parent: System
  isExternal: false
  name: Void
  nameWithType: Void
  fullName: System.Void
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.RsaProtectedConfigurationProvider.ImportKey(System.String,System.Boolean)
  parent: System.Configuration.RsaProtectedConfigurationProvider
  isExternal: false
  name: ImportKey(String,Boolean)
  nameWithType: RsaProtectedConfigurationProvider.ImportKey(String,Boolean)
  fullName: System.Configuration.RsaProtectedConfigurationProvider.ImportKey(String,Boolean)
- uid: System.Void
  parent: System
  isExternal: false
  name: Void
  nameWithType: Void
  fullName: System.Void
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.RsaProtectedConfigurationProvider.Initialize(System.String,System.Collections.Specialized.NameValueCollection)
  parent: System.Configuration.RsaProtectedConfigurationProvider
  isExternal: false
  name: Initialize(String,NameValueCollection)
  nameWithType: RsaProtectedConfigurationProvider.Initialize(String,NameValueCollection)
  fullName: System.Configuration.RsaProtectedConfigurationProvider.Initialize(String,NameValueCollection)
- uid: System.Void
  parent: System
  isExternal: false
  name: Void
  nameWithType: Void
  fullName: System.Void
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.RsaProtectedConfigurationProvider.KeyContainerName
  parent: System.Configuration.RsaProtectedConfigurationProvider
  isExternal: false
  name: KeyContainerName
  nameWithType: RsaProtectedConfigurationProvider.KeyContainerName
  fullName: System.Configuration.RsaProtectedConfigurationProvider.KeyContainerName
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.RsaProtectedConfigurationProvider.RsaPublicKey
  parent: System.Configuration.RsaProtectedConfigurationProvider
  isExternal: false
  name: RsaPublicKey
  nameWithType: RsaProtectedConfigurationProvider.RsaPublicKey
  fullName: System.Configuration.RsaProtectedConfigurationProvider.RsaPublicKey
- uid: System.Security.Cryptography.RSAParameters
  parent: System.Security.Cryptography
  isExternal: false
  name: RSAParameters
  nameWithType: RSAParameters
  fullName: System.Security.Cryptography.RSAParameters
- uid: System.Configuration.RsaProtectedConfigurationProvider.UseFIPS
  parent: System.Configuration.RsaProtectedConfigurationProvider
  isExternal: false
  name: UseFIPS
  nameWithType: RsaProtectedConfigurationProvider.UseFIPS
  fullName: System.Configuration.RsaProtectedConfigurationProvider.UseFIPS
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.RsaProtectedConfigurationProvider.UseMachineContainer
  parent: System.Configuration.RsaProtectedConfigurationProvider
  isExternal: false
  name: UseMachineContainer
  nameWithType: RsaProtectedConfigurationProvider.UseMachineContainer
  fullName: System.Configuration.RsaProtectedConfigurationProvider.UseMachineContainer
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.RsaProtectedConfigurationProvider.UseOAEP
  parent: System.Configuration.RsaProtectedConfigurationProvider
  isExternal: false
  name: UseOAEP
  nameWithType: RsaProtectedConfigurationProvider.UseOAEP
  fullName: System.Configuration.RsaProtectedConfigurationProvider.UseOAEP
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
