### YamlMime:ManagedReference
items:
- uid: System.Configuration.ConfigurationAllowDefinition
  id: ConfigurationAllowDefinition
  children:
  - System.Configuration.ConfigurationAllowDefinition.Everywhere
  - System.Configuration.ConfigurationAllowDefinition.MachineOnly
  - System.Configuration.ConfigurationAllowDefinition.MachineToApplication
  - System.Configuration.ConfigurationAllowDefinition.MachineToWebRoot
  langs:
  - csharp
  - vb
  name: ConfigurationAllowDefinition
  nameWithType: ConfigurationAllowDefinition
  fullName: System.Configuration.ConfigurationAllowDefinition
  type: Enum
  syntax:
    content: public enum ConfigurationAllowDefinition
  inheritance:
  - System.Object
  - System.ValueType
  - System.Enum
  inheritedMembers:
  - System.Enum.CompareTo(System.Object)
  - System.Enum.Equals(System.Object)
  - System.Enum.Format(System.Type,System.Object,System.String)
  - System.Enum.GetHashCode
  - System.Enum.GetName(System.Type,System.Object)
  - System.Enum.GetNames(System.Type)
  - System.Enum.GetTypeCode
  - System.Enum.GetUnderlyingType(System.Type)
  - System.Enum.GetValues(System.Type)
  - System.Enum.HasFlag(System.Enum)
  - System.Enum.IsDefined(System.Type,System.Object)
  - System.Enum.Parse(System.Type,System.String)
  - System.Enum.Parse(System.Type,System.String,System.Boolean)
  - System.Enum.System#IConvertible#ToBoolean(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToByte(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToChar(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToDateTime(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToDecimal(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToDouble(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToInt16(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToInt32(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToInt64(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToSByte(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToSingle(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToType(System.Type,System.IFormatProvider)
  - System.Enum.System#IConvertible#ToUInt16(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToUInt32(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToUInt64(System.IFormatProvider)
  - System.Enum.ToObject(System.Type,System.Byte)
  - System.Enum.ToObject(System.Type,System.Int16)
  - System.Enum.ToObject(System.Type,System.Int32)
  - System.Enum.ToObject(System.Type,System.Int64)
  - System.Enum.ToObject(System.Type,System.Object)
  - System.Enum.ToObject(System.Type,System.SByte)
  - System.Enum.ToObject(System.Type,System.UInt16)
  - System.Enum.ToObject(System.Type,System.UInt32)
  - System.Enum.ToObject(System.Type,System.UInt64)
  - System.Enum.ToString
  - System.Enum.ToString(System.IFormatProvider)
  - System.Enum.ToString(System.String)
  - System.Enum.ToString(System.String,System.IFormatProvider)
  - System.Enum.TryParse``1(System.String,``0@)
  - System.Enum.TryParse``1(System.String,System.Boolean,``0@)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
- uid: System.Configuration.ConfigurationAllowDefinition.Everywhere
  id: Everywhere
  parent: System.Configuration.ConfigurationAllowDefinition
  langs:
  - csharp
  - vb
  name: Everywhere
  nameWithType: ConfigurationAllowDefinition.Everywhere
  fullName: System.Configuration.ConfigurationAllowDefinition.Everywhere
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: Everywhere
    return:
      type: System.Configuration.ConfigurationAllowDefinition
      description: Return description to be filled
- uid: System.Configuration.ConfigurationAllowDefinition.MachineOnly
  id: MachineOnly
  parent: System.Configuration.ConfigurationAllowDefinition
  langs:
  - csharp
  - vb
  name: MachineOnly
  nameWithType: ConfigurationAllowDefinition.MachineOnly
  fullName: System.Configuration.ConfigurationAllowDefinition.MachineOnly
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: MachineOnly
    return:
      type: System.Configuration.ConfigurationAllowDefinition
      description: Return description to be filled
- uid: System.Configuration.ConfigurationAllowDefinition.MachineToApplication
  id: MachineToApplication
  parent: System.Configuration.ConfigurationAllowDefinition
  langs:
  - csharp
  - vb
  name: MachineToApplication
  nameWithType: ConfigurationAllowDefinition.MachineToApplication
  fullName: System.Configuration.ConfigurationAllowDefinition.MachineToApplication
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: MachineToApplication
    return:
      type: System.Configuration.ConfigurationAllowDefinition
      description: Return description to be filled
- uid: System.Configuration.ConfigurationAllowDefinition.MachineToWebRoot
  id: MachineToWebRoot
  parent: System.Configuration.ConfigurationAllowDefinition
  langs:
  - csharp
  - vb
  name: MachineToWebRoot
  nameWithType: ConfigurationAllowDefinition.MachineToWebRoot
  fullName: System.Configuration.ConfigurationAllowDefinition.MachineToWebRoot
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: MachineToWebRoot
    return:
      type: System.Configuration.ConfigurationAllowDefinition
      description: Return description to be filled
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Configuration.ConfigurationAllowDefinition.Everywhere
  parent: System.Configuration.ConfigurationAllowDefinition
  isExternal: false
  name: Everywhere
  nameWithType: ConfigurationAllowDefinition.Everywhere
  fullName: System.Configuration.ConfigurationAllowDefinition.Everywhere
- uid: System.Configuration.ConfigurationAllowDefinition
  parent: System.Configuration
  isExternal: false
  name: ConfigurationAllowDefinition
  nameWithType: ConfigurationAllowDefinition
  fullName: System.Configuration.ConfigurationAllowDefinition
- uid: System.Configuration.ConfigurationAllowDefinition.MachineOnly
  parent: System.Configuration.ConfigurationAllowDefinition
  isExternal: false
  name: MachineOnly
  nameWithType: ConfigurationAllowDefinition.MachineOnly
  fullName: System.Configuration.ConfigurationAllowDefinition.MachineOnly
- uid: System.Configuration.ConfigurationAllowDefinition
  parent: System.Configuration
  isExternal: false
  name: ConfigurationAllowDefinition
  nameWithType: ConfigurationAllowDefinition
  fullName: System.Configuration.ConfigurationAllowDefinition
- uid: System.Configuration.ConfigurationAllowDefinition.MachineToApplication
  parent: System.Configuration.ConfigurationAllowDefinition
  isExternal: false
  name: MachineToApplication
  nameWithType: ConfigurationAllowDefinition.MachineToApplication
  fullName: System.Configuration.ConfigurationAllowDefinition.MachineToApplication
- uid: System.Configuration.ConfigurationAllowDefinition
  parent: System.Configuration
  isExternal: false
  name: ConfigurationAllowDefinition
  nameWithType: ConfigurationAllowDefinition
  fullName: System.Configuration.ConfigurationAllowDefinition
- uid: System.Configuration.ConfigurationAllowDefinition.MachineToWebRoot
  parent: System.Configuration.ConfigurationAllowDefinition
  isExternal: false
  name: MachineToWebRoot
  nameWithType: ConfigurationAllowDefinition.MachineToWebRoot
  fullName: System.Configuration.ConfigurationAllowDefinition.MachineToWebRoot
- uid: System.Configuration.ConfigurationAllowDefinition
  parent: System.Configuration
  isExternal: false
  name: ConfigurationAllowDefinition
  nameWithType: ConfigurationAllowDefinition
  fullName: System.Configuration.ConfigurationAllowDefinition
