### YamlMime:ManagedReference
items:
- uid: System.Configuration.CallbackValidator
  id: CallbackValidator
  children:
  - System.Configuration.CallbackValidator.#ctor(System.Type,System.Configuration.ValidatorCallback)
  - System.Configuration.CallbackValidator.CanValidate(System.Type)
  - System.Configuration.CallbackValidator.Validate(System.Object)
  langs:
  - csharp
  name: CallbackValidator
  nameWithType: CallbackValidator
  fullName: System.Configuration.CallbackValidator
  type: Class
  summary: Provides dynamic validation of an object.
  remarks: To use this class, you need to implement a <xref:System.Configuration.ValidatorCallback> delegate for the type of object you want to validate. When you instantiate this class, you pass in the object type and a reference to the delegate. You can then call <xref:System.Configuration.CallbackValidator.CanValidate%2A> to determine if an object is the correct type or <xref:System.Configuration.CallbackValidator.Validate%2A> to execute the delegate on the object.
  syntax:
    content: 'public sealed class CallbackValidator : System.Configuration.ConfigurationValidatorBase'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationValidatorBase
  implements: []
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.CallbackValidator.#ctor(System.Type,System.Configuration.ValidatorCallback)
  id: '#ctor(System.Type,System.Configuration.ValidatorCallback)'
  parent: System.Configuration.CallbackValidator
  langs:
  - csharp
  name: CallbackValidator(Type,ValidatorCallback)
  nameWithType: CallbackValidator.CallbackValidator(Type,ValidatorCallback)
  fullName: System.Configuration.CallbackValidator.CallbackValidator(Type,ValidatorCallback)
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Initializes a new instance of the <see cref="T:System.Configuration.CallbackValidator"> class.
  remarks: To be added.
  syntax:
    content: public CallbackValidator (Type type, System.Configuration.ValidatorCallback callback);
    parameters:
    - id: type
      type: System.Type
      description: The type of object that will be validated.
    - id: callback
      type: System.Configuration.ValidatorCallback
      description: The <see cref="T:System.Configuration.ValidatorCallback"> used as the delegate.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.CallbackValidator.CanValidate(System.Type)
  id: CanValidate(System.Type)
  parent: System.Configuration.CallbackValidator
  langs:
  - csharp
  name: CanValidate(Type)
  nameWithType: CallbackValidator.CanValidate(Type)
  fullName: System.Configuration.CallbackValidator.CanValidate(Type)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Determines whether the type of the object can be validated.
  remarks: To be added.
  syntax:
    content: public override bool CanValidate (Type type);
    parameters:
    - id: type
      type: System.Type
      description: The type of object.
    return:
      type: System.Boolean
      description: '`true` if the `type` parameter matches the type used as the first parameter when creating an instance of <see cref="T:System.Configuration.CallbackValidator">; otherwise, `false`.'
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.CallbackValidator.Validate(System.Object)
  id: Validate(System.Object)
  parent: System.Configuration.CallbackValidator
  langs:
  - csharp
  name: Validate(Object)
  nameWithType: CallbackValidator.Validate(Object)
  fullName: System.Configuration.CallbackValidator.Validate(Object)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Determines whether the value of an object is valid.
  remarks: The <xref:System.Configuration.CallbackValidator> class contains the type and delegate necessary to validate an object. The type and delegate are established when an instance of the <xref:System.Configuration.CallbackValidator> class is created. The object to validate is passed as a parameter of the Validate method.
  syntax:
    content: public override void Validate (object value);
    parameters:
    - id: value
      type: System.Object
      description: The value of an object.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationValidatorBase
  isExternal: false
  name: System.Configuration.ConfigurationValidatorBase
- uid: System.Configuration.CallbackValidator.#ctor(System.Type,System.Configuration.ValidatorCallback)
  parent: System.Configuration.CallbackValidator
  isExternal: false
  name: CallbackValidator(Type,ValidatorCallback)
  nameWithType: CallbackValidator.CallbackValidator(Type,ValidatorCallback)
  fullName: System.Configuration.CallbackValidator.CallbackValidator(Type,ValidatorCallback)
- uid: System.Type
  parent: System
  isExternal: false
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Configuration.ValidatorCallback
  parent: System.Configuration
  isExternal: false
  name: ValidatorCallback
  nameWithType: ValidatorCallback
  fullName: System.Configuration.ValidatorCallback
- uid: System.Configuration.CallbackValidator.CanValidate(System.Type)
  parent: System.Configuration.CallbackValidator
  isExternal: false
  name: CanValidate(Type)
  nameWithType: CallbackValidator.CanValidate(Type)
  fullName: System.Configuration.CallbackValidator.CanValidate(Type)
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Type
  parent: System
  isExternal: false
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Configuration.CallbackValidator.Validate(System.Object)
  parent: System.Configuration.CallbackValidator
  isExternal: false
  name: Validate(Object)
  nameWithType: CallbackValidator.Validate(Object)
  fullName: System.Configuration.CallbackValidator.Validate(Object)
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
