### YamlMime:ManagedReference
items:
- uid: System.Configuration.InfiniteTimeSpanConverter
  id: InfiniteTimeSpanConverter
  children:
  - System.Configuration.InfiniteTimeSpanConverter.#ctor
  - System.Configuration.InfiniteTimeSpanConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  - System.Configuration.InfiniteTimeSpanConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  langs:
  - csharp
  name: InfiniteTimeSpanConverter
  nameWithType: InfiniteTimeSpanConverter
  fullName: System.Configuration.InfiniteTimeSpanConverter
  type: Class
  summary: Converts between a string and the standard infinite <see cref="T:System.TimeSpan"> value.
  remarks: "This type, like all the other configuration converter types, converts strings found in the configuration file to and from the related strongly typed properties.  \n  \n In particular the InfiniteTimeSpanConverter converts the <xref:System.String> value \"infinite\" assigned to a configuration property to the standard infinite <xref:System.TimeSpan> and vice versa. The infinite <xref:System.TimeSpan> value is represented by the <xref:System.TimeSpan> enumeration value.  \n  \n This converter is used with <xref:System.TimeSpan> properties. An infinite value is persisted as the \"infinite\" string."
  example:
  - "The following code example shows how to define a custom section property that uses the InfiniteTimeSpanConverter class.  \n  \n For the complete example code that implements the custom section, refer to the <xref:System.Configuration.ConfigurationConverterBase> class.  \n  \n [!CODE [System.Configuration.ConfigurationConvertersCustomSection#3](../CodeSnippet/VS_Snippets_WebNet/System.Configuration.ConfigurationConvertersCustomSection#3)]  \n  \n The following example code shows how to access the previous custom section property.  \n  \n [!CODE [System.Configuration.InfiniteTimeSpanConverter#1](../CodeSnippet/VS_Snippets_WebNet/System.Configuration.InfiniteTimeSpanConverter#1)]  \n  \n The following is a configuration excerpt as used by the previous example.  \n  \n```  \n<?xml version=\"1.0\" encoding=\"utf-8\"?>  \n<configuration>  \n  <configSections>  \n    <section name=\"CustomSection\"   \n      type=\"Samples.AspNet.CustomSection,   \n      ConfigurationConverters,   \n      Version=1.0.0.0, Culture=neutral,   \n      PublicKeyToken=null\"   \n      allowDefinition=\"Everywhere\"   \n      allowExeDefinition=\"MachineToApplication\"   \n      restartOnExternalChanges=\"true\" />  \n    </configSections>  \n    <CustomSection fileName=\"default.txt\" maxIdleTime=\"90\" timeDelay=\"infinite\"/>  \n</configuration>  \n```"
  syntax:
    content: 'public sealed class InfiniteTimeSpanConverter : System.Configuration.ConfigurationConverterBase'
  inheritance:
  - System.ComponentModel.TypeConverter
  - System.Configuration.ConfigurationConverterBase
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationConverterBase.CanConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Type)
  - System.Configuration.ConfigurationConverterBase.CanConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Type)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.InfiniteTimeSpanConverter.#ctor
  id: '#ctor'
  parent: System.Configuration.InfiniteTimeSpanConverter
  langs:
  - csharp
  name: InfiniteTimeSpanConverter()
  nameWithType: InfiniteTimeSpanConverter.InfiniteTimeSpanConverter()
  fullName: System.Configuration.InfiniteTimeSpanConverter.InfiniteTimeSpanConverter()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Initializes a new instance of the <see cref="T:System.Configuration.InfiniteTimeSpanConverter"> class.
  remarks: Normally, you use the converter types provided by the system. The only time you need to use the InfiniteTimeSpanConverter constructor is when you create your own conversion type.
  syntax:
    content: public InfiniteTimeSpanConverter ();
    parameters: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.InfiniteTimeSpanConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  id: ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  parent: System.Configuration.InfiniteTimeSpanConverter
  langs:
  - csharp
  name: ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  nameWithType: InfiniteTimeSpanConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  fullName: System.Configuration.InfiniteTimeSpanConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Converts a <see cref="T:System.String"> to a <xref:System.TimeSpan>.
  remarks: The system uses the ConvertFrom method when reading from a configuration file to convert a <xref:System.String> value to <xref:System.TimeSpan> or the <xref:System.String> "infinite" to <xref:System.TimeSpan.MaxValue>.
  syntax:
    content: public override object ConvertFrom (System.ComponentModel.ITypeDescriptorContext ctx, System.Globalization.CultureInfo ci, object data);
    parameters:
    - id: ctx
      type: System.ComponentModel.ITypeDescriptorContext
      description: The <xref:System.ComponentModel.ITypeDescriptorContext> object used for type conversions.
    - id: ci
      type: System.Globalization.CultureInfo
      description: The <see cref="T:System.Globalization.CultureInfo"> object used during conversion.
    - id: data
      type: System.Object
      description: The <see cref="T:System.String"> object to convert.
    return:
      type: System.Object
      description: The <see cref="F:System.TimeSpan.MaxValue">, if the  parameter is the <xref:System.String> infinite; otherwise, the <xref:System.TimeSpan> representing the  parameter in minutes.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.InfiniteTimeSpanConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  id: ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  parent: System.Configuration.InfiniteTimeSpanConverter
  langs:
  - csharp
  name: ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  nameWithType: InfiniteTimeSpanConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  fullName: System.Configuration.InfiniteTimeSpanConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Converts a <see cref="T:System.TimeSpan"> to a <xref:System.String>.
  remarks: "The system uses the ConvertTo method when writing an attribute to a configuration file to convert a <xref:System.TimeSpan> object to a <xref:System.String> object.  \n  \n The system uses the ConvertTo method when writing to a configuration file to convert a <xref:System.TimeSpan> value or <xref:System.TimeSpan.MaxValue> to a <xref:System.String>."
  syntax:
    content: public override object ConvertTo (System.ComponentModel.ITypeDescriptorContext ctx, System.Globalization.CultureInfo ci, object value, Type type);
    parameters:
    - id: ctx
      type: System.ComponentModel.ITypeDescriptorContext
      description: The <xref:System.ComponentModel.ITypeDescriptorContext> object used for type conversions.
    - id: ci
      type: System.Globalization.CultureInfo
      description: The <see cref="T:System.Globalization.CultureInfo"> used during object conversion.
    - id: value
      type: System.Object
      description: The value to convert.
    - id: type
      type: System.Type
      description: The conversion type.
    return:
      type: System.Object
      description: The <see cref="T:System.String"> "infinite", if the  parameter is <xref:System.TimeSpan.MaxValue>; otherwise, the <see cref="T:System.String"> representing the  parameter in minutes.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationConverterBase
  isExternal: false
  name: System.Configuration.ConfigurationConverterBase
- uid: System.Configuration.InfiniteTimeSpanConverter.#ctor
  parent: System.Configuration.InfiniteTimeSpanConverter
  isExternal: false
  name: InfiniteTimeSpanConverter()
  nameWithType: InfiniteTimeSpanConverter.InfiniteTimeSpanConverter()
  fullName: System.Configuration.InfiniteTimeSpanConverter.InfiniteTimeSpanConverter()
- uid: System.Configuration.InfiniteTimeSpanConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  parent: System.Configuration.InfiniteTimeSpanConverter
  isExternal: false
  name: ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  nameWithType: InfiniteTimeSpanConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  fullName: System.Configuration.InfiniteTimeSpanConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.ComponentModel.ITypeDescriptorContext
  parent: System.ComponentModel
  isExternal: true
  name: ITypeDescriptorContext
  nameWithType: ITypeDescriptorContext
  fullName: System.ComponentModel.ITypeDescriptorContext
- uid: System.Globalization.CultureInfo
  parent: System.Globalization
  isExternal: false
  name: CultureInfo
  nameWithType: CultureInfo
  fullName: System.Globalization.CultureInfo
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Configuration.InfiniteTimeSpanConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  parent: System.Configuration.InfiniteTimeSpanConverter
  isExternal: false
  name: ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  nameWithType: InfiniteTimeSpanConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  fullName: System.Configuration.InfiniteTimeSpanConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.ComponentModel.ITypeDescriptorContext
  parent: System.ComponentModel
  isExternal: true
  name: ITypeDescriptorContext
  nameWithType: ITypeDescriptorContext
  fullName: System.ComponentModel.ITypeDescriptorContext
- uid: System.Globalization.CultureInfo
  parent: System.Globalization
  isExternal: false
  name: CultureInfo
  nameWithType: CultureInfo
  fullName: System.Globalization.CultureInfo
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Type
  parent: System
  isExternal: false
  name: Type
  nameWithType: Type
  fullName: System.Type
