### YamlMime:ManagedReference
items:
- uid: System.Configuration.ConfigurationValidatorAttribute
  id: ConfigurationValidatorAttribute
  children:
  - System.Configuration.ConfigurationValidatorAttribute.#ctor
  - System.Configuration.ConfigurationValidatorAttribute.#ctor(System.Type)
  - System.Configuration.ConfigurationValidatorAttribute.ValidatorInstance
  - System.Configuration.ConfigurationValidatorAttribute.ValidatorType
  langs:
  - csharp
  name: ConfigurationValidatorAttribute
  nameWithType: ConfigurationValidatorAttribute
  fullName: System.Configuration.ConfigurationValidatorAttribute
  type: Class
  summary: Serves as the base class for the <see cref="N:System.Configuration"> validator attribute types.
  remarks: All the ASP.NET configuration standard validator attribute types derive from ConfigurationValidatorAttribute. You can use this type to create your own custom validator attribute.
  example:
  - "The following code examples demonstrate how to create two custom validators using the ConfigurationValidatorAttribute type. The first example performs validation using hard-coded parameters; the second example performs validation using the parameters assigned to it at the time it is applied to the related section property. This code example also contains three supporting files. The first file contains the custom section that uses the validators described above, the second file contains a custom converter type, and the third file contains the console application that builds and uses the custom validators and the section that contains them.  \n  \n The following code example shows how to create a fixed validator with hard-coded parameters.  \n  \n [!CODE [System.Configuration.ConfigValidatorAttribute#21](../CodeSnippet/VS_Snippets_WebNet/System.Configuration.ConfigValidatorAttribute#21)]  \n  \n The following code example shows how to create a programmable validator.  \n  \n [!CODE [System.Configuration.ConfigValidatorAttribute#31](../CodeSnippet/VS_Snippets_WebNet/System.Configuration.ConfigValidatorAttribute#31)]  \n  \n The following code example shows how to create a custom section using the previous validators.  \n  \n [!CODE [System.Configuration.ConfigValidatorAttribute#11](../CodeSnippet/VS_Snippets_WebNet/System.Configuration.ConfigValidatorAttribute#11)]  \n  \n The following code example shows how to create a custom converter.  \n  \n [!CODE [System.Configuration.ConfigValidatorAttribute#1](../CodeSnippet/VS_Snippets_WebNet/System.Configuration.ConfigValidatorAttribute#1)]  \n  \n The following code example shows how to create the console application that builds and uses the custom validators and their containing section.  \n  \n [!CODE [System.Configuration.ConfigValidatorAttribute#41](../CodeSnippet/VS_Snippets_WebNet/System.Configuration.ConfigValidatorAttribute#41)]  \n  \n The following code example is a configuration excerpt used by the previous example.  \n  \n```  \n<?xml version=\"1.0\" encoding=\"utf-8\"?>  \n<configuration>  \n    <configSections>  \n        <section name=\"Cars\" type=\"Samples.AspNet.SelectCar, ConfigValidatorAttribute, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null\" allowLocation=\"false\" allowDefinition=\"Everywhere\" allowExeDefinition=\"MachineToApplication\" restartOnExternalChanges=\"true\" requirePermission=\"true\" />  \n    </configSections>  \n    <Cars commute=\"Make:AlfaRomeo Color:Blue Miles:10000 Year:2002\"  \n        dream=\"Make:Ferrari Color:Red Miles:10 Year:2005\" />  \n</configuration>  \n```"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property)]

      public class ConfigurationValidatorAttribute : Attribute
  inheritance:
  - System.Object
  - System.Attribute
  implements: []
  inheritedMembers:
  - System.Attribute.Equals(System.Object)
  - System.Attribute.GetCustomAttribute(System.Reflection.Assembly,System.Type)
  - System.Attribute.GetCustomAttribute(System.Reflection.Assembly,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttribute(System.Reflection.MemberInfo,System.Type)
  - System.Attribute.GetCustomAttribute(System.Reflection.MemberInfo,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttribute(System.Reflection.Module,System.Type)
  - System.Attribute.GetCustomAttribute(System.Reflection.Module,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttribute(System.Reflection.ParameterInfo,System.Type)
  - System.Attribute.GetCustomAttribute(System.Reflection.ParameterInfo,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.Assembly)
  - System.Attribute.GetCustomAttributes(System.Reflection.Assembly,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.Assembly,System.Type)
  - System.Attribute.GetCustomAttributes(System.Reflection.Assembly,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.MemberInfo)
  - System.Attribute.GetCustomAttributes(System.Reflection.MemberInfo,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.MemberInfo,System.Type)
  - System.Attribute.GetCustomAttributes(System.Reflection.MemberInfo,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.Module)
  - System.Attribute.GetCustomAttributes(System.Reflection.Module,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.Module,System.Type)
  - System.Attribute.GetCustomAttributes(System.Reflection.Module,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.ParameterInfo)
  - System.Attribute.GetCustomAttributes(System.Reflection.ParameterInfo,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.ParameterInfo,System.Type)
  - System.Attribute.GetCustomAttributes(System.Reflection.ParameterInfo,System.Type,System.Boolean)
  - System.Attribute.GetHashCode
  - System.Attribute.IsDefaultAttribute
  - System.Attribute.IsDefined(System.Reflection.Assembly,System.Type)
  - System.Attribute.IsDefined(System.Reflection.Assembly,System.Type,System.Boolean)
  - System.Attribute.IsDefined(System.Reflection.MemberInfo,System.Type)
  - System.Attribute.IsDefined(System.Reflection.MemberInfo,System.Type,System.Boolean)
  - System.Attribute.IsDefined(System.Reflection.Module,System.Type)
  - System.Attribute.IsDefined(System.Reflection.Module,System.Type,System.Boolean)
  - System.Attribute.IsDefined(System.Reflection.ParameterInfo,System.Type)
  - System.Attribute.IsDefined(System.Reflection.ParameterInfo,System.Type,System.Boolean)
  - System.Attribute.Match(System.Object)
  - System.Attribute.System#Runtime#InteropServices#_Attribute#GetIDsOfNames(System.Guid@,System.IntPtr,System.UInt32,System.UInt32,System.IntPtr)
  - System.Attribute.System#Runtime#InteropServices#_Attribute#GetTypeInfo(System.UInt32,System.UInt32,System.IntPtr)
  - System.Attribute.System#Runtime#InteropServices#_Attribute#GetTypeInfoCount(System.UInt32@)
  - System.Attribute.System#Runtime#InteropServices#_Attribute#Invoke(System.UInt32,System.Guid@,System.UInt32,System.Int16,System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr)
  - System.Attribute.TypeId
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ConfigurationValidatorAttribute.#ctor
  id: '#ctor'
  parent: System.Configuration.ConfigurationValidatorAttribute
  langs:
  - csharp
  name: ConfigurationValidatorAttribute()
  nameWithType: ConfigurationValidatorAttribute.ConfigurationValidatorAttribute()
  fullName: System.Configuration.ConfigurationValidatorAttribute.ConfigurationValidatorAttribute()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Initializes a new instance of the <see cref="T:System.Configuration.ConfigurationValidatorAttribute"> class.
  remarks: You use this constructor in the attributed model to ensure that the value assigned to the related property is an integer.
  syntax:
    content: protected ConfigurationValidatorAttribute ();
    parameters: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ConfigurationValidatorAttribute.#ctor(System.Type)
  id: '#ctor(System.Type)'
  parent: System.Configuration.ConfigurationValidatorAttribute
  langs:
  - csharp
  name: ConfigurationValidatorAttribute(Type)
  nameWithType: ConfigurationValidatorAttribute.ConfigurationValidatorAttribute(Type)
  fullName: System.Configuration.ConfigurationValidatorAttribute.ConfigurationValidatorAttribute(Type)
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Initializes a new instance of the <see cref="T:System.Configuration.ConfigurationValidatorAttribute"> class using the specified validator type.
  remarks: This constructor determines whether a validator instance can be created from an instance of the specified  type.
  syntax:
    content: public ConfigurationValidatorAttribute (Type validator);
    parameters:
    - id: validator
      type: System.Type
      description: The validator type to use when creating an instance of <see cref="T:System.Configuration.ConfigurationValidatorAttribute">.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ConfigurationValidatorAttribute.ValidatorInstance
  id: ValidatorInstance
  parent: System.Configuration.ConfigurationValidatorAttribute
  langs:
  - csharp
  name: ValidatorInstance
  nameWithType: ConfigurationValidatorAttribute.ValidatorInstance
  fullName: System.Configuration.ConfigurationValidatorAttribute.ValidatorInstance
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Gets the validator attribute instance.
  remarks: To be added.
  syntax:
    content: public virtual System.Configuration.ConfigurationValidatorBase ValidatorInstance { get; }
    return:
      type: System.Configuration.ConfigurationValidatorBase
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ConfigurationValidatorAttribute.ValidatorType
  id: ValidatorType
  parent: System.Configuration.ConfigurationValidatorAttribute
  langs:
  - csharp
  name: ValidatorType
  nameWithType: ConfigurationValidatorAttribute.ValidatorType
  fullName: System.Configuration.ConfigurationValidatorAttribute.ValidatorType
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Gets the type of the validator attribute.
  remarks: To be added.
  syntax:
    content: public Type ValidatorType { get; }
    return:
      type: System.Type
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.Configuration.ConfigurationValidatorAttribute.#ctor
  parent: System.Configuration.ConfigurationValidatorAttribute
  isExternal: false
  name: ConfigurationValidatorAttribute()
  nameWithType: ConfigurationValidatorAttribute.ConfigurationValidatorAttribute()
  fullName: System.Configuration.ConfigurationValidatorAttribute.ConfigurationValidatorAttribute()
- uid: System.Configuration.ConfigurationValidatorAttribute.#ctor(System.Type)
  parent: System.Configuration.ConfigurationValidatorAttribute
  isExternal: false
  name: ConfigurationValidatorAttribute(Type)
  nameWithType: ConfigurationValidatorAttribute.ConfigurationValidatorAttribute(Type)
  fullName: System.Configuration.ConfigurationValidatorAttribute.ConfigurationValidatorAttribute(Type)
- uid: System.Type
  parent: System
  isExternal: false
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Configuration.ConfigurationValidatorAttribute.ValidatorInstance
  parent: System.Configuration.ConfigurationValidatorAttribute
  isExternal: false
  name: ValidatorInstance
  nameWithType: ConfigurationValidatorAttribute.ValidatorInstance
  fullName: System.Configuration.ConfigurationValidatorAttribute.ValidatorInstance
- uid: System.Configuration.ConfigurationValidatorBase
  parent: System.Configuration
  isExternal: false
  name: ConfigurationValidatorBase
  nameWithType: ConfigurationValidatorBase
  fullName: System.Configuration.ConfigurationValidatorBase
- uid: System.Configuration.ConfigurationValidatorAttribute.ValidatorType
  parent: System.Configuration.ConfigurationValidatorAttribute
  isExternal: false
  name: ValidatorType
  nameWithType: ConfigurationValidatorAttribute.ValidatorType
  fullName: System.Configuration.ConfigurationValidatorAttribute.ValidatorType
- uid: System.Type
  parent: System
  isExternal: false
  name: Type
  nameWithType: Type
  fullName: System.Type
