### YamlMime:ManagedReference
items:
- uid: System.Configuration.DefaultValidator
  id: DefaultValidator
  children:
  - System.Configuration.DefaultValidator.#ctor
  - System.Configuration.DefaultValidator.CanValidate(System.Type)
  - System.Configuration.DefaultValidator.Validate(System.Object)
  langs:
  - csharp
  - vb
  name: DefaultValidator
  nameWithType: DefaultValidator
  fullName: System.Configuration.DefaultValidator
  type: Class
  syntax:
    content: 'public sealed class DefaultValidator : System.Configuration.ConfigurationValidatorBase'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationValidatorBase
  implements: []
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: System.Configuration.DefaultValidator.#ctor
  id: '#ctor'
  parent: System.Configuration.DefaultValidator
  langs:
  - csharp
  - vb
  name: .ctor
  nameWithType: DefaultValidator..ctor
  fullName: System.Configuration.DefaultValidator..ctor
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: public DefaultValidator ();
    parameters: []
- uid: System.Configuration.DefaultValidator.CanValidate(System.Type)
  id: CanValidate(System.Type)
  parent: System.Configuration.DefaultValidator
  langs:
  - csharp
  - vb
  name: CanValidate
  nameWithType: DefaultValidator.CanValidate
  fullName: System.Configuration.DefaultValidator.CanValidate
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: public override bool CanValidate (Type type);
    parameters:
    - id: type
      type: System.Type
      description: Parameter description to be filled
    return:
      type: System.Boolean
      description: Return description to be filled
- uid: System.Configuration.DefaultValidator.Validate(System.Object)
  id: Validate(System.Object)
  parent: System.Configuration.DefaultValidator
  langs:
  - csharp
  - vb
  name: Validate
  nameWithType: DefaultValidator.Validate
  fullName: System.Configuration.DefaultValidator.Validate
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: public override void Validate (object value);
    parameters:
    - id: value
      type: System.Object
      description: Parameter description to be filled
    return:
      type: System.Void
      description: Return description to be filled
references:
- uid: System.Configuration.ConfigurationValidatorBase
  isExternal: false
  name: System.Configuration.ConfigurationValidatorBase
- uid: System.Configuration.DefaultValidator.#ctor
  parent: System.Configuration.DefaultValidator
  isExternal: false
  name: .ctor
  nameWithType: DefaultValidator..ctor
  fullName: System.Configuration.DefaultValidator..ctor
- uid: System.Configuration.DefaultValidator.CanValidate(System.Type)
  parent: System.Configuration.DefaultValidator
  isExternal: false
  name: CanValidate
  nameWithType: DefaultValidator.CanValidate
  fullName: System.Configuration.DefaultValidator.CanValidate
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Type
  parent: System
  isExternal: false
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Configuration.DefaultValidator.Validate(System.Object)
  parent: System.Configuration.DefaultValidator
  isExternal: false
  name: Validate
  nameWithType: DefaultValidator.Validate
  fullName: System.Configuration.DefaultValidator.Validate
- uid: System.Void
  parent: System
  isExternal: false
  name: Void
  nameWithType: Void
  fullName: System.Void
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
