### YamlMime:ManagedReference
items:
- uid: System.Configuration.IntegerValidatorAttribute
  id: IntegerValidatorAttribute
  children:
  - System.Configuration.IntegerValidatorAttribute.#ctor
  - System.Configuration.IntegerValidatorAttribute.ExcludeRange
  - System.Configuration.IntegerValidatorAttribute.MaxValue
  - System.Configuration.IntegerValidatorAttribute.MinValue
  - System.Configuration.IntegerValidatorAttribute.ValidatorInstance
  langs:
  - csharp
  name: IntegerValidatorAttribute
  nameWithType: IntegerValidatorAttribute
  fullName: System.Configuration.IntegerValidatorAttribute
  type: Class
  summary: Declaratively instructs the .NET Framework to perform integer validation on a configuration property. This class cannot be inherited.
  remarks: "You use the IntegerValidatorAttribute attribute to decorate a configuration property, which will instruct the .NET Framework to validate the property using the <xref:System.Configuration.IntegerValidator> object and pass to it the value of the decorating parameters.  \n  \n You can apply IntegerValidatorAttribute attributes to property types only."
  example:
  - "The following example shows how to decorate the properties of a custom <xref:System.Configuration.ConfigurationSection> object using the IntegerValidatorAttribute attribute.  \n  \n [!CODE [System.Configuration.ConfigurationValidatorAttributes#6](../CodeSnippet/VS_Snippets_WebNet/System.Configuration.ConfigurationValidatorAttributes#6)]"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property)]

      public sealed class IntegerValidatorAttribute : System.Configuration.ConfigurationValidatorAttribute
  inheritance:
  - System.Object
  - System.Attribute
  - System.Configuration.ConfigurationValidatorAttribute
  implements: []
  inheritedMembers:
  - System.Attribute.Equals(System.Object)
  - System.Attribute.GetCustomAttribute(System.Reflection.Assembly,System.Type)
  - System.Attribute.GetCustomAttribute(System.Reflection.Assembly,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttribute(System.Reflection.MemberInfo,System.Type)
  - System.Attribute.GetCustomAttribute(System.Reflection.MemberInfo,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttribute(System.Reflection.Module,System.Type)
  - System.Attribute.GetCustomAttribute(System.Reflection.Module,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttribute(System.Reflection.ParameterInfo,System.Type)
  - System.Attribute.GetCustomAttribute(System.Reflection.ParameterInfo,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.Assembly)
  - System.Attribute.GetCustomAttributes(System.Reflection.Assembly,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.Assembly,System.Type)
  - System.Attribute.GetCustomAttributes(System.Reflection.Assembly,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.MemberInfo)
  - System.Attribute.GetCustomAttributes(System.Reflection.MemberInfo,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.MemberInfo,System.Type)
  - System.Attribute.GetCustomAttributes(System.Reflection.MemberInfo,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.Module)
  - System.Attribute.GetCustomAttributes(System.Reflection.Module,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.Module,System.Type)
  - System.Attribute.GetCustomAttributes(System.Reflection.Module,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.ParameterInfo)
  - System.Attribute.GetCustomAttributes(System.Reflection.ParameterInfo,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.ParameterInfo,System.Type)
  - System.Attribute.GetCustomAttributes(System.Reflection.ParameterInfo,System.Type,System.Boolean)
  - System.Attribute.GetHashCode
  - System.Attribute.IsDefaultAttribute
  - System.Attribute.IsDefined(System.Reflection.Assembly,System.Type)
  - System.Attribute.IsDefined(System.Reflection.Assembly,System.Type,System.Boolean)
  - System.Attribute.IsDefined(System.Reflection.MemberInfo,System.Type)
  - System.Attribute.IsDefined(System.Reflection.MemberInfo,System.Type,System.Boolean)
  - System.Attribute.IsDefined(System.Reflection.Module,System.Type)
  - System.Attribute.IsDefined(System.Reflection.Module,System.Type,System.Boolean)
  - System.Attribute.IsDefined(System.Reflection.ParameterInfo,System.Type)
  - System.Attribute.IsDefined(System.Reflection.ParameterInfo,System.Type,System.Boolean)
  - System.Attribute.Match(System.Object)
  - System.Attribute.System#Runtime#InteropServices#_Attribute#GetIDsOfNames(System.Guid@,System.IntPtr,System.UInt32,System.UInt32,System.IntPtr)
  - System.Attribute.System#Runtime#InteropServices#_Attribute#GetTypeInfo(System.UInt32,System.UInt32,System.IntPtr)
  - System.Attribute.System#Runtime#InteropServices#_Attribute#GetTypeInfoCount(System.UInt32@)
  - System.Attribute.System#Runtime#InteropServices#_Attribute#Invoke(System.UInt32,System.Guid@,System.UInt32,System.Int16,System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr)
  - System.Attribute.TypeId
  - System.Configuration.ConfigurationValidatorAttribute.ValidatorType
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.IntegerValidatorAttribute.#ctor
  id: '#ctor'
  parent: System.Configuration.IntegerValidatorAttribute
  langs:
  - csharp
  name: IntegerValidatorAttribute()
  nameWithType: IntegerValidatorAttribute.IntegerValidatorAttribute()
  fullName: System.Configuration.IntegerValidatorAttribute.IntegerValidatorAttribute()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Creates a new instance of the <see cref="T:System.Configuration.IntegerValidatorAttribute"> class.
  remarks: You use this constructor in the attributed model to assure that the value assigned to the related property is an integer.
  example:
  - "The following example shows how to use the IntegerValidatorAttribute constructor.  \n  \n [!CODE [System.Configuration.ConfigurationValidatorAttributes#5](../CodeSnippet/VS_Snippets_WebNet/System.Configuration.ConfigurationValidatorAttributes#5)]"
  syntax:
    content: public IntegerValidatorAttribute ();
    parameters: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.IntegerValidatorAttribute.ExcludeRange
  id: ExcludeRange
  parent: System.Configuration.IntegerValidatorAttribute
  langs:
  - csharp
  name: ExcludeRange
  nameWithType: IntegerValidatorAttribute.ExcludeRange
  fullName: System.Configuration.IntegerValidatorAttribute.ExcludeRange
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Gets or sets a value that indicates whether to include or exclude the integers in the range defined by the <xref:System.Configuration.IntegerValidatorAttribute.MinValue%2A> and <xref:System.Configuration.IntegerValidatorAttribute.MaxValue%2A> property values.
  remarks: The range is inclusive of the <xref:System.Configuration.IntegerValidatorAttribute.MinValue%2A> and <xref:System.Configuration.IntegerValidatorAttribute.MaxValue%2A> property values. When the ExcludeRange property value is `true`, the allowed values are outside the range.
  example:
  - "The following example shows how to use the ExcludeRange property.  \n  \n [!CODE [System.Configuration.ConfigurationValidatorAttributes#6](../CodeSnippet/VS_Snippets_WebNet/System.Configuration.ConfigurationValidatorAttributes#6)]"
  syntax:
    content: public bool ExcludeRange { get; set; }
    return:
      type: System.Boolean
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.IntegerValidatorAttribute.MaxValue
  id: MaxValue
  parent: System.Configuration.IntegerValidatorAttribute
  langs:
  - csharp
  name: MaxValue
  nameWithType: IntegerValidatorAttribute.MaxValue
  fullName: System.Configuration.IntegerValidatorAttribute.MaxValue
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Gets or sets the maximum value allowed for the property.
  remarks: The MaxValue property value is included in the allowed range.
  example:
  - "The following example shows how to use the MaxValue property.  \n  \n [!CODE [System.Configuration.ConfigurationValidatorAttributes#6](../CodeSnippet/VS_Snippets_WebNet/System.Configuration.ConfigurationValidatorAttributes#6)]"
  syntax:
    content: public int MaxValue { get; set; }
    return:
      type: System.Int32
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.IntegerValidatorAttribute.MinValue
  id: MinValue
  parent: System.Configuration.IntegerValidatorAttribute
  langs:
  - csharp
  name: MinValue
  nameWithType: IntegerValidatorAttribute.MinValue
  fullName: System.Configuration.IntegerValidatorAttribute.MinValue
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Gets or sets the minimum value allowed for the property.
  remarks: The MinValue property value is included in the allowed range.
  example:
  - "The following example shows how to use the MinValue property.  \n  \n [!CODE [System.Configuration.ConfigurationValidatorAttributes#6](../CodeSnippet/VS_Snippets_WebNet/System.Configuration.ConfigurationValidatorAttributes#6)]"
  syntax:
    content: public int MinValue { get; set; }
    return:
      type: System.Int32
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.IntegerValidatorAttribute.ValidatorInstance
  id: ValidatorInstance
  parent: System.Configuration.IntegerValidatorAttribute
  langs:
  - csharp
  name: ValidatorInstance
  nameWithType: IntegerValidatorAttribute.ValidatorInstance
  fullName: System.Configuration.IntegerValidatorAttribute.ValidatorInstance
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Gets an instance of the <see cref="T:System.Configuration.IntegerValidator"> class.
  remarks: You use the ValidatorInstance property to perform string validation by calling its <xref:System.Configuration.IntegerValidator.Validate%2A> method.
  example:
  - "The following example shows how to use the ValidatorInstance property.  \n  \n [!CODE [System.Configuration.ConfigurationValidatorAttributes#13](../CodeSnippet/VS_Snippets_WebNet/System.Configuration.ConfigurationValidatorAttributes#13)]"
  syntax:
    content: public override System.Configuration.ConfigurationValidatorBase ValidatorInstance { get; }
    return:
      type: System.Configuration.ConfigurationValidatorBase
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationValidatorAttribute
  isExternal: false
  name: System.Configuration.ConfigurationValidatorAttribute
- uid: System.Configuration.IntegerValidatorAttribute.#ctor
  parent: System.Configuration.IntegerValidatorAttribute
  isExternal: false
  name: IntegerValidatorAttribute()
  nameWithType: IntegerValidatorAttribute.IntegerValidatorAttribute()
  fullName: System.Configuration.IntegerValidatorAttribute.IntegerValidatorAttribute()
- uid: System.Configuration.IntegerValidatorAttribute.ExcludeRange
  parent: System.Configuration.IntegerValidatorAttribute
  isExternal: false
  name: ExcludeRange
  nameWithType: IntegerValidatorAttribute.ExcludeRange
  fullName: System.Configuration.IntegerValidatorAttribute.ExcludeRange
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.IntegerValidatorAttribute.MaxValue
  parent: System.Configuration.IntegerValidatorAttribute
  isExternal: false
  name: MaxValue
  nameWithType: IntegerValidatorAttribute.MaxValue
  fullName: System.Configuration.IntegerValidatorAttribute.MaxValue
- uid: System.Int32
  parent: System
  isExternal: false
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Configuration.IntegerValidatorAttribute.MinValue
  parent: System.Configuration.IntegerValidatorAttribute
  isExternal: false
  name: MinValue
  nameWithType: IntegerValidatorAttribute.MinValue
  fullName: System.Configuration.IntegerValidatorAttribute.MinValue
- uid: System.Int32
  parent: System
  isExternal: false
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Configuration.IntegerValidatorAttribute.ValidatorInstance
  parent: System.Configuration.IntegerValidatorAttribute
  isExternal: false
  name: ValidatorInstance
  nameWithType: IntegerValidatorAttribute.ValidatorInstance
  fullName: System.Configuration.IntegerValidatorAttribute.ValidatorInstance
- uid: System.Configuration.ConfigurationValidatorBase
  parent: System.Configuration
  isExternal: false
  name: ConfigurationValidatorBase
  nameWithType: ConfigurationValidatorBase
  fullName: System.Configuration.ConfigurationValidatorBase
