### YamlMime:ManagedReference
items:
- uid: System.Configuration.CommaDelimitedStringCollection
  id: CommaDelimitedStringCollection
  children:
  - System.Configuration.CommaDelimitedStringCollection.#ctor
  - System.Configuration.CommaDelimitedStringCollection.Add(System.String)
  - System.Configuration.CommaDelimitedStringCollection.AddRange(System.String[])
  - System.Configuration.CommaDelimitedStringCollection.Clear
  - System.Configuration.CommaDelimitedStringCollection.Clone
  - System.Configuration.CommaDelimitedStringCollection.Insert(System.Int32,System.String)
  - System.Configuration.CommaDelimitedStringCollection.IsModified
  - System.Configuration.CommaDelimitedStringCollection.IsReadOnly
  - System.Configuration.CommaDelimitedStringCollection.Item(System.Int32)
  - System.Configuration.CommaDelimitedStringCollection.Remove(System.String)
  - System.Configuration.CommaDelimitedStringCollection.SetReadOnly
  - System.Configuration.CommaDelimitedStringCollection.ToString
  langs:
  - csharp
  - vb
  name: CommaDelimitedStringCollection
  nameWithType: CommaDelimitedStringCollection
  fullName: System.Configuration.CommaDelimitedStringCollection
  type: Class
  syntax:
    content: 'public sealed class CommaDelimitedStringCollection : System.Collections.Specialized.StringCollection'
  inheritance:
  - System.Collections.Specialized.StringCollection
  implements: []
  inheritedMembers: []
- uid: System.Configuration.CommaDelimitedStringCollection.#ctor
  id: '#ctor'
  parent: System.Configuration.CommaDelimitedStringCollection
  langs:
  - csharp
  - vb
  name: .ctor
  nameWithType: CommaDelimitedStringCollection..ctor
  fullName: System.Configuration.CommaDelimitedStringCollection..ctor
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: public CommaDelimitedStringCollection ();
    parameters: []
- uid: System.Configuration.CommaDelimitedStringCollection.Add(System.String)
  id: Add(System.String)
  parent: System.Configuration.CommaDelimitedStringCollection
  langs:
  - csharp
  - vb
  name: Add
  nameWithType: CommaDelimitedStringCollection.Add
  fullName: System.Configuration.CommaDelimitedStringCollection.Add
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: public void Add (string value);
    parameters:
    - id: value
      type: System.String
      description: Parameter description to be filled
    return:
      type: System.Void
      description: Return description to be filled
- uid: System.Configuration.CommaDelimitedStringCollection.AddRange(System.String[])
  id: AddRange(System.String[])
  parent: System.Configuration.CommaDelimitedStringCollection
  langs:
  - csharp
  - vb
  name: AddRange
  nameWithType: CommaDelimitedStringCollection.AddRange
  fullName: System.Configuration.CommaDelimitedStringCollection.AddRange
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: public void AddRange (string[] range);
    parameters:
    - id: range
      type: System.String[]
      description: Parameter description to be filled
    return:
      type: System.Void
      description: Return description to be filled
- uid: System.Configuration.CommaDelimitedStringCollection.Clear
  id: Clear
  parent: System.Configuration.CommaDelimitedStringCollection
  langs:
  - csharp
  - vb
  name: Clear
  nameWithType: CommaDelimitedStringCollection.Clear
  fullName: System.Configuration.CommaDelimitedStringCollection.Clear
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: public void Clear ();
    parameters: []
    return:
      type: System.Void
      description: Return description to be filled
- uid: System.Configuration.CommaDelimitedStringCollection.Clone
  id: Clone
  parent: System.Configuration.CommaDelimitedStringCollection
  langs:
  - csharp
  - vb
  name: Clone
  nameWithType: CommaDelimitedStringCollection.Clone
  fullName: System.Configuration.CommaDelimitedStringCollection.Clone
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: public System.Configuration.CommaDelimitedStringCollection Clone ();
    parameters: []
    return:
      type: System.Configuration.CommaDelimitedStringCollection
      description: Return description to be filled
- uid: System.Configuration.CommaDelimitedStringCollection.Insert(System.Int32,System.String)
  id: Insert(System.Int32,System.String)
  parent: System.Configuration.CommaDelimitedStringCollection
  langs:
  - csharp
  - vb
  name: Insert
  nameWithType: CommaDelimitedStringCollection.Insert
  fullName: System.Configuration.CommaDelimitedStringCollection.Insert
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: public void Insert (int index, string value);
    parameters:
    - id: index
      type: System.Int32
      description: Parameter description to be filled
    - id: value
      type: System.String
      description: Parameter description to be filled
    return:
      type: System.Void
      description: Return description to be filled
- uid: System.Configuration.CommaDelimitedStringCollection.IsModified
  id: IsModified
  parent: System.Configuration.CommaDelimitedStringCollection
  langs:
  - csharp
  - vb
  name: IsModified
  nameWithType: CommaDelimitedStringCollection.IsModified
  fullName: System.Configuration.CommaDelimitedStringCollection.IsModified
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: public bool IsModified { get; }
    return:
      type: System.Boolean
      description: Return description to be filled
- uid: System.Configuration.CommaDelimitedStringCollection.IsReadOnly
  id: IsReadOnly
  parent: System.Configuration.CommaDelimitedStringCollection
  langs:
  - csharp
  - vb
  name: IsReadOnly
  nameWithType: CommaDelimitedStringCollection.IsReadOnly
  fullName: System.Configuration.CommaDelimitedStringCollection.IsReadOnly
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: public bool IsReadOnly { get; }
    return:
      type: System.Boolean
      description: Return description to be filled
- uid: System.Configuration.CommaDelimitedStringCollection.Item(System.Int32)
  id: Item(System.Int32)
  parent: System.Configuration.CommaDelimitedStringCollection
  langs:
  - csharp
  - vb
  name: Item
  nameWithType: CommaDelimitedStringCollection.Item
  fullName: System.Configuration.CommaDelimitedStringCollection.Item
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: public string this[int index] { get; set; }
    parameters:
    - id: index
      type: System.Int32
      description: Parameter description to be filled
    return:
      type: System.String
      description: Return description to be filled
- uid: System.Configuration.CommaDelimitedStringCollection.Remove(System.String)
  id: Remove(System.String)
  parent: System.Configuration.CommaDelimitedStringCollection
  langs:
  - csharp
  - vb
  name: Remove
  nameWithType: CommaDelimitedStringCollection.Remove
  fullName: System.Configuration.CommaDelimitedStringCollection.Remove
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: public void Remove (string value);
    parameters:
    - id: value
      type: System.String
      description: Parameter description to be filled
    return:
      type: System.Void
      description: Return description to be filled
- uid: System.Configuration.CommaDelimitedStringCollection.SetReadOnly
  id: SetReadOnly
  parent: System.Configuration.CommaDelimitedStringCollection
  langs:
  - csharp
  - vb
  name: SetReadOnly
  nameWithType: CommaDelimitedStringCollection.SetReadOnly
  fullName: System.Configuration.CommaDelimitedStringCollection.SetReadOnly
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: public void SetReadOnly ();
    parameters: []
    return:
      type: System.Void
      description: Return description to be filled
- uid: System.Configuration.CommaDelimitedStringCollection.ToString
  id: ToString
  parent: System.Configuration.CommaDelimitedStringCollection
  langs:
  - csharp
  - vb
  name: ToString
  nameWithType: CommaDelimitedStringCollection.ToString
  fullName: System.Configuration.CommaDelimitedStringCollection.ToString
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: public override string ToString ();
    parameters: []
    return:
      type: System.String
      description: Return description to be filled
references:
- uid: System.Collections.Specialized.StringCollection
  isExternal: false
  name: System.Collections.Specialized.StringCollection
- uid: System.Configuration.CommaDelimitedStringCollection.#ctor
  parent: System.Configuration.CommaDelimitedStringCollection
  isExternal: false
  name: .ctor
  nameWithType: CommaDelimitedStringCollection..ctor
  fullName: System.Configuration.CommaDelimitedStringCollection..ctor
- uid: System.Configuration.CommaDelimitedStringCollection.Add(System.String)
  parent: System.Configuration.CommaDelimitedStringCollection
  isExternal: false
  name: Add
  nameWithType: CommaDelimitedStringCollection.Add
  fullName: System.Configuration.CommaDelimitedStringCollection.Add
- uid: System.Void
  parent: System
  isExternal: false
  name: Void
  nameWithType: Void
  fullName: System.Void
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.CommaDelimitedStringCollection.AddRange(System.String[])
  parent: System.Configuration.CommaDelimitedStringCollection
  isExternal: false
  name: AddRange
  nameWithType: CommaDelimitedStringCollection.AddRange
  fullName: System.Configuration.CommaDelimitedStringCollection.AddRange
- uid: System.Void
  parent: System
  isExternal: false
  name: Void
  nameWithType: Void
  fullName: System.Void
- uid: System.Configuration.CommaDelimitedStringCollection.Clear
  parent: System.Configuration.CommaDelimitedStringCollection
  isExternal: false
  name: Clear
  nameWithType: CommaDelimitedStringCollection.Clear
  fullName: System.Configuration.CommaDelimitedStringCollection.Clear
- uid: System.Void
  parent: System
  isExternal: false
  name: Void
  nameWithType: Void
  fullName: System.Void
- uid: System.Configuration.CommaDelimitedStringCollection.Clone
  parent: System.Configuration.CommaDelimitedStringCollection
  isExternal: false
  name: Clone
  nameWithType: CommaDelimitedStringCollection.Clone
  fullName: System.Configuration.CommaDelimitedStringCollection.Clone
- uid: System.Configuration.CommaDelimitedStringCollection
  parent: System.Configuration
  isExternal: false
  name: CommaDelimitedStringCollection
  nameWithType: CommaDelimitedStringCollection
  fullName: System.Configuration.CommaDelimitedStringCollection
- uid: System.Configuration.CommaDelimitedStringCollection.Insert(System.Int32,System.String)
  parent: System.Configuration.CommaDelimitedStringCollection
  isExternal: false
  name: Insert
  nameWithType: CommaDelimitedStringCollection.Insert
  fullName: System.Configuration.CommaDelimitedStringCollection.Insert
- uid: System.Void
  parent: System
  isExternal: false
  name: Void
  nameWithType: Void
  fullName: System.Void
- uid: System.Int32
  parent: System
  isExternal: false
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.CommaDelimitedStringCollection.IsModified
  parent: System.Configuration.CommaDelimitedStringCollection
  isExternal: false
  name: IsModified
  nameWithType: CommaDelimitedStringCollection.IsModified
  fullName: System.Configuration.CommaDelimitedStringCollection.IsModified
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.CommaDelimitedStringCollection.IsReadOnly
  parent: System.Configuration.CommaDelimitedStringCollection
  isExternal: false
  name: IsReadOnly
  nameWithType: CommaDelimitedStringCollection.IsReadOnly
  fullName: System.Configuration.CommaDelimitedStringCollection.IsReadOnly
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.CommaDelimitedStringCollection.Item(System.Int32)
  parent: System.Configuration.CommaDelimitedStringCollection
  isExternal: false
  name: Item
  nameWithType: CommaDelimitedStringCollection.Item
  fullName: System.Configuration.CommaDelimitedStringCollection.Item
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Int32
  parent: System
  isExternal: false
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Configuration.CommaDelimitedStringCollection.Remove(System.String)
  parent: System.Configuration.CommaDelimitedStringCollection
  isExternal: false
  name: Remove
  nameWithType: CommaDelimitedStringCollection.Remove
  fullName: System.Configuration.CommaDelimitedStringCollection.Remove
- uid: System.Void
  parent: System
  isExternal: false
  name: Void
  nameWithType: Void
  fullName: System.Void
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.CommaDelimitedStringCollection.SetReadOnly
  parent: System.Configuration.CommaDelimitedStringCollection
  isExternal: false
  name: SetReadOnly
  nameWithType: CommaDelimitedStringCollection.SetReadOnly
  fullName: System.Configuration.CommaDelimitedStringCollection.SetReadOnly
- uid: System.Void
  parent: System
  isExternal: false
  name: Void
  nameWithType: Void
  fullName: System.Void
- uid: System.Configuration.CommaDelimitedStringCollection.ToString
  parent: System.Configuration.CommaDelimitedStringCollection
  isExternal: false
  name: ToString
  nameWithType: CommaDelimitedStringCollection.ToString
  fullName: System.Configuration.CommaDelimitedStringCollection.ToString
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
