### YamlMime:ManagedReference
items:
- uid: System.Configuration.ConfigurationPropertyOptions
  id: ConfigurationPropertyOptions
  children:
  - System.Configuration.ConfigurationPropertyOptions.IsAssemblyStringTransformationRequired
  - System.Configuration.ConfigurationPropertyOptions.IsDefaultCollection
  - System.Configuration.ConfigurationPropertyOptions.IsKey
  - System.Configuration.ConfigurationPropertyOptions.IsRequired
  - System.Configuration.ConfigurationPropertyOptions.IsTypeStringTransformationRequired
  - System.Configuration.ConfigurationPropertyOptions.IsVersionCheckRequired
  - System.Configuration.ConfigurationPropertyOptions.None
  langs:
  - csharp
  - vb
  name: ConfigurationPropertyOptions
  nameWithType: ConfigurationPropertyOptions
  fullName: System.Configuration.ConfigurationPropertyOptions
  type: Enum
  syntax:
    content: >-
      [System.Flags]

      public enum ConfigurationPropertyOptions
  inheritance:
  - System.Object
  - System.ValueType
  - System.Enum
  inheritedMembers:
  - System.Enum.CompareTo(System.Object)
  - System.Enum.Equals(System.Object)
  - System.Enum.Format(System.Type,System.Object,System.String)
  - System.Enum.GetHashCode
  - System.Enum.GetName(System.Type,System.Object)
  - System.Enum.GetNames(System.Type)
  - System.Enum.GetTypeCode
  - System.Enum.GetUnderlyingType(System.Type)
  - System.Enum.GetValues(System.Type)
  - System.Enum.HasFlag(System.Enum)
  - System.Enum.IsDefined(System.Type,System.Object)
  - System.Enum.Parse(System.Type,System.String)
  - System.Enum.Parse(System.Type,System.String,System.Boolean)
  - System.Enum.System#IConvertible#ToBoolean(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToByte(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToChar(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToDateTime(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToDecimal(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToDouble(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToInt16(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToInt32(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToInt64(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToSByte(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToSingle(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToType(System.Type,System.IFormatProvider)
  - System.Enum.System#IConvertible#ToUInt16(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToUInt32(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToUInt64(System.IFormatProvider)
  - System.Enum.ToObject(System.Type,System.Byte)
  - System.Enum.ToObject(System.Type,System.Int16)
  - System.Enum.ToObject(System.Type,System.Int32)
  - System.Enum.ToObject(System.Type,System.Int64)
  - System.Enum.ToObject(System.Type,System.Object)
  - System.Enum.ToObject(System.Type,System.SByte)
  - System.Enum.ToObject(System.Type,System.UInt16)
  - System.Enum.ToObject(System.Type,System.UInt32)
  - System.Enum.ToObject(System.Type,System.UInt64)
  - System.Enum.ToString
  - System.Enum.ToString(System.IFormatProvider)
  - System.Enum.ToString(System.String)
  - System.Enum.ToString(System.String,System.IFormatProvider)
  - System.Enum.TryParse``1(System.String,``0@)
  - System.Enum.TryParse``1(System.String,System.Boolean,``0@)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
- uid: System.Configuration.ConfigurationPropertyOptions.IsAssemblyStringTransformationRequired
  id: IsAssemblyStringTransformationRequired
  parent: System.Configuration.ConfigurationPropertyOptions
  langs:
  - csharp
  - vb
  name: IsAssemblyStringTransformationRequired
  nameWithType: ConfigurationPropertyOptions.IsAssemblyStringTransformationRequired
  fullName: System.Configuration.ConfigurationPropertyOptions.IsAssemblyStringTransformationRequired
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: IsAssemblyStringTransformationRequired
    return:
      type: System.Configuration.ConfigurationPropertyOptions
      description: Return description to be filled
- uid: System.Configuration.ConfigurationPropertyOptions.IsDefaultCollection
  id: IsDefaultCollection
  parent: System.Configuration.ConfigurationPropertyOptions
  langs:
  - csharp
  - vb
  name: IsDefaultCollection
  nameWithType: ConfigurationPropertyOptions.IsDefaultCollection
  fullName: System.Configuration.ConfigurationPropertyOptions.IsDefaultCollection
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: IsDefaultCollection
    return:
      type: System.Configuration.ConfigurationPropertyOptions
      description: Return description to be filled
- uid: System.Configuration.ConfigurationPropertyOptions.IsKey
  id: IsKey
  parent: System.Configuration.ConfigurationPropertyOptions
  langs:
  - csharp
  - vb
  name: IsKey
  nameWithType: ConfigurationPropertyOptions.IsKey
  fullName: System.Configuration.ConfigurationPropertyOptions.IsKey
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: IsKey
    return:
      type: System.Configuration.ConfigurationPropertyOptions
      description: Return description to be filled
- uid: System.Configuration.ConfigurationPropertyOptions.IsRequired
  id: IsRequired
  parent: System.Configuration.ConfigurationPropertyOptions
  langs:
  - csharp
  - vb
  name: IsRequired
  nameWithType: ConfigurationPropertyOptions.IsRequired
  fullName: System.Configuration.ConfigurationPropertyOptions.IsRequired
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: IsRequired
    return:
      type: System.Configuration.ConfigurationPropertyOptions
      description: Return description to be filled
- uid: System.Configuration.ConfigurationPropertyOptions.IsTypeStringTransformationRequired
  id: IsTypeStringTransformationRequired
  parent: System.Configuration.ConfigurationPropertyOptions
  langs:
  - csharp
  - vb
  name: IsTypeStringTransformationRequired
  nameWithType: ConfigurationPropertyOptions.IsTypeStringTransformationRequired
  fullName: System.Configuration.ConfigurationPropertyOptions.IsTypeStringTransformationRequired
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: IsTypeStringTransformationRequired
    return:
      type: System.Configuration.ConfigurationPropertyOptions
      description: Return description to be filled
- uid: System.Configuration.ConfigurationPropertyOptions.IsVersionCheckRequired
  id: IsVersionCheckRequired
  parent: System.Configuration.ConfigurationPropertyOptions
  langs:
  - csharp
  - vb
  name: IsVersionCheckRequired
  nameWithType: ConfigurationPropertyOptions.IsVersionCheckRequired
  fullName: System.Configuration.ConfigurationPropertyOptions.IsVersionCheckRequired
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: IsVersionCheckRequired
    return:
      type: System.Configuration.ConfigurationPropertyOptions
      description: Return description to be filled
- uid: System.Configuration.ConfigurationPropertyOptions.None
  id: None
  parent: System.Configuration.ConfigurationPropertyOptions
  langs:
  - csharp
  - vb
  name: None
  nameWithType: ConfigurationPropertyOptions.None
  fullName: System.Configuration.ConfigurationPropertyOptions.None
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: None
    return:
      type: System.Configuration.ConfigurationPropertyOptions
      description: Return description to be filled
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Configuration.ConfigurationPropertyOptions.IsAssemblyStringTransformationRequired
  parent: System.Configuration.ConfigurationPropertyOptions
  isExternal: false
  name: IsAssemblyStringTransformationRequired
  nameWithType: ConfigurationPropertyOptions.IsAssemblyStringTransformationRequired
  fullName: System.Configuration.ConfigurationPropertyOptions.IsAssemblyStringTransformationRequired
- uid: System.Configuration.ConfigurationPropertyOptions
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyOptions
  nameWithType: ConfigurationPropertyOptions
  fullName: System.Configuration.ConfigurationPropertyOptions
- uid: System.Configuration.ConfigurationPropertyOptions.IsDefaultCollection
  parent: System.Configuration.ConfigurationPropertyOptions
  isExternal: false
  name: IsDefaultCollection
  nameWithType: ConfigurationPropertyOptions.IsDefaultCollection
  fullName: System.Configuration.ConfigurationPropertyOptions.IsDefaultCollection
- uid: System.Configuration.ConfigurationPropertyOptions
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyOptions
  nameWithType: ConfigurationPropertyOptions
  fullName: System.Configuration.ConfigurationPropertyOptions
- uid: System.Configuration.ConfigurationPropertyOptions.IsKey
  parent: System.Configuration.ConfigurationPropertyOptions
  isExternal: false
  name: IsKey
  nameWithType: ConfigurationPropertyOptions.IsKey
  fullName: System.Configuration.ConfigurationPropertyOptions.IsKey
- uid: System.Configuration.ConfigurationPropertyOptions
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyOptions
  nameWithType: ConfigurationPropertyOptions
  fullName: System.Configuration.ConfigurationPropertyOptions
- uid: System.Configuration.ConfigurationPropertyOptions.IsRequired
  parent: System.Configuration.ConfigurationPropertyOptions
  isExternal: false
  name: IsRequired
  nameWithType: ConfigurationPropertyOptions.IsRequired
  fullName: System.Configuration.ConfigurationPropertyOptions.IsRequired
- uid: System.Configuration.ConfigurationPropertyOptions
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyOptions
  nameWithType: ConfigurationPropertyOptions
  fullName: System.Configuration.ConfigurationPropertyOptions
- uid: System.Configuration.ConfigurationPropertyOptions.IsTypeStringTransformationRequired
  parent: System.Configuration.ConfigurationPropertyOptions
  isExternal: false
  name: IsTypeStringTransformationRequired
  nameWithType: ConfigurationPropertyOptions.IsTypeStringTransformationRequired
  fullName: System.Configuration.ConfigurationPropertyOptions.IsTypeStringTransformationRequired
- uid: System.Configuration.ConfigurationPropertyOptions
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyOptions
  nameWithType: ConfigurationPropertyOptions
  fullName: System.Configuration.ConfigurationPropertyOptions
- uid: System.Configuration.ConfigurationPropertyOptions.IsVersionCheckRequired
  parent: System.Configuration.ConfigurationPropertyOptions
  isExternal: false
  name: IsVersionCheckRequired
  nameWithType: ConfigurationPropertyOptions.IsVersionCheckRequired
  fullName: System.Configuration.ConfigurationPropertyOptions.IsVersionCheckRequired
- uid: System.Configuration.ConfigurationPropertyOptions
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyOptions
  nameWithType: ConfigurationPropertyOptions
  fullName: System.Configuration.ConfigurationPropertyOptions
- uid: System.Configuration.ConfigurationPropertyOptions.None
  parent: System.Configuration.ConfigurationPropertyOptions
  isExternal: false
  name: None
  nameWithType: ConfigurationPropertyOptions.None
  fullName: System.Configuration.ConfigurationPropertyOptions.None
- uid: System.Configuration.ConfigurationPropertyOptions
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyOptions
  nameWithType: ConfigurationPropertyOptions
  fullName: System.Configuration.ConfigurationPropertyOptions
