### YamlMime:ManagedReference
items:
- uid: System.Configuration.ProtectedConfigurationProviderCollection
  id: ProtectedConfigurationProviderCollection
  children:
  - System.Configuration.ProtectedConfigurationProviderCollection.#ctor
  - System.Configuration.ProtectedConfigurationProviderCollection.Add(System.Configuration.Provider.ProviderBase)
  - System.Configuration.ProtectedConfigurationProviderCollection.Item(System.String)
  langs:
  - csharp
  - vb
  name: ProtectedConfigurationProviderCollection
  nameWithType: ProtectedConfigurationProviderCollection
  fullName: System.Configuration.ProtectedConfigurationProviderCollection
  type: Class
  syntax:
    content: 'public class ProtectedConfigurationProviderCollection : System.Configuration.Provider.ProviderCollection'
  inheritance:
  - System.Object
  - System.Configuration.Provider.ProviderCollection
  implements: []
  inheritedMembers:
  - System.Configuration.Provider.ProviderCollection.Clear
  - System.Configuration.Provider.ProviderCollection.CopyTo(System.Configuration.Provider.ProviderBase[],System.Int32)
  - System.Configuration.Provider.ProviderCollection.Count
  - System.Configuration.Provider.ProviderCollection.GetEnumerator
  - System.Configuration.Provider.ProviderCollection.IsSynchronized
  - System.Configuration.Provider.ProviderCollection.Remove(System.String)
  - System.Configuration.Provider.ProviderCollection.SetReadOnly
  - System.Configuration.Provider.ProviderCollection.SyncRoot
  - System.Configuration.Provider.ProviderCollection.System#Collections#ICollection#CopyTo(System.Array,System.Int32)
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: System.Configuration.ProtectedConfigurationProviderCollection.#ctor
  id: '#ctor'
  parent: System.Configuration.ProtectedConfigurationProviderCollection
  langs:
  - csharp
  - vb
  name: .ctor
  nameWithType: ProtectedConfigurationProviderCollection..ctor
  fullName: System.Configuration.ProtectedConfigurationProviderCollection..ctor
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: public ProtectedConfigurationProviderCollection ();
    parameters: []
- uid: System.Configuration.ProtectedConfigurationProviderCollection.Add(System.Configuration.Provider.ProviderBase)
  id: Add(System.Configuration.Provider.ProviderBase)
  parent: System.Configuration.ProtectedConfigurationProviderCollection
  langs:
  - csharp
  - vb
  name: Add
  nameWithType: ProtectedConfigurationProviderCollection.Add
  fullName: System.Configuration.ProtectedConfigurationProviderCollection.Add
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: public override void Add (System.Configuration.Provider.ProviderBase provider);
    parameters:
    - id: provider
      type: System.Configuration.Provider.ProviderBase
      description: Parameter description to be filled
    return:
      type: System.Void
      description: Return description to be filled
- uid: System.Configuration.ProtectedConfigurationProviderCollection.Item(System.String)
  id: Item(System.String)
  parent: System.Configuration.ProtectedConfigurationProviderCollection
  langs:
  - csharp
  - vb
  name: Item
  nameWithType: ProtectedConfigurationProviderCollection.Item
  fullName: System.Configuration.ProtectedConfigurationProviderCollection.Item
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: public System.Configuration.ProtectedConfigurationProvider this[string name] { get; }
    parameters:
    - id: name
      type: System.String
      description: Parameter description to be filled
    return:
      type: System.Configuration.ProtectedConfigurationProvider
      description: Return description to be filled
references:
- uid: System.Configuration.Provider.ProviderCollection
  isExternal: false
  name: System.Configuration.Provider.ProviderCollection
- uid: System.Configuration.ProtectedConfigurationProviderCollection.#ctor
  parent: System.Configuration.ProtectedConfigurationProviderCollection
  isExternal: false
  name: .ctor
  nameWithType: ProtectedConfigurationProviderCollection..ctor
  fullName: System.Configuration.ProtectedConfigurationProviderCollection..ctor
- uid: System.Configuration.ProtectedConfigurationProviderCollection.Add(System.Configuration.Provider.ProviderBase)
  parent: System.Configuration.ProtectedConfigurationProviderCollection
  isExternal: false
  name: Add
  nameWithType: ProtectedConfigurationProviderCollection.Add
  fullName: System.Configuration.ProtectedConfigurationProviderCollection.Add
- uid: System.Void
  parent: System
  isExternal: false
  name: Void
  nameWithType: Void
  fullName: System.Void
- uid: System.Configuration.Provider.ProviderBase
  parent: System.Configuration.Provider
  isExternal: false
  name: ProviderBase
  nameWithType: ProviderBase
  fullName: System.Configuration.Provider.ProviderBase
- uid: System.Configuration.ProtectedConfigurationProviderCollection.Item(System.String)
  parent: System.Configuration.ProtectedConfigurationProviderCollection
  isExternal: false
  name: Item
  nameWithType: ProtectedConfigurationProviderCollection.Item
  fullName: System.Configuration.ProtectedConfigurationProviderCollection.Item
- uid: System.Configuration.ProtectedConfigurationProvider
  parent: System.Configuration
  isExternal: false
  name: ProtectedConfigurationProvider
  nameWithType: ProtectedConfigurationProvider
  fullName: System.Configuration.ProtectedConfigurationProvider
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
