### YamlMime:ManagedReference
items:
- uid: System.Configuration.GenericEnumConverter
  id: GenericEnumConverter
  children:
  - System.Configuration.GenericEnumConverter.#ctor(System.Type)
  - System.Configuration.GenericEnumConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  - System.Configuration.GenericEnumConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  langs:
  - csharp
  - vb
  name: GenericEnumConverter
  nameWithType: GenericEnumConverter
  fullName: System.Configuration.GenericEnumConverter
  type: Class
  syntax:
    content: 'public sealed class GenericEnumConverter : System.Configuration.ConfigurationConverterBase'
  inheritance:
  - System.ComponentModel.TypeConverter
  - System.Configuration.ConfigurationConverterBase
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationConverterBase.CanConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Type)
  - System.Configuration.ConfigurationConverterBase.CanConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Type)
- uid: System.Configuration.GenericEnumConverter.#ctor(System.Type)
  id: '#ctor(System.Type)'
  parent: System.Configuration.GenericEnumConverter
  langs:
  - csharp
  - vb
  name: .ctor
  nameWithType: GenericEnumConverter..ctor
  fullName: System.Configuration.GenericEnumConverter..ctor
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: public GenericEnumConverter (Type typeEnum);
    parameters:
    - id: typeEnum
      type: System.Type
      description: Parameter description to be filled
- uid: System.Configuration.GenericEnumConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  id: ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  parent: System.Configuration.GenericEnumConverter
  langs:
  - csharp
  - vb
  name: ConvertFrom
  nameWithType: GenericEnumConverter.ConvertFrom
  fullName: System.Configuration.GenericEnumConverter.ConvertFrom
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: public override object ConvertFrom (System.ComponentModel.ITypeDescriptorContext ctx, System.Globalization.CultureInfo ci, object data);
    parameters:
    - id: ctx
      type: System.ComponentModel.ITypeDescriptorContext
      description: Parameter description to be filled
    - id: ci
      type: System.Globalization.CultureInfo
      description: Parameter description to be filled
    - id: data
      type: System.Object
      description: Parameter description to be filled
    return:
      type: System.Object
      description: Return description to be filled
- uid: System.Configuration.GenericEnumConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  id: ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  parent: System.Configuration.GenericEnumConverter
  langs:
  - csharp
  - vb
  name: ConvertTo
  nameWithType: GenericEnumConverter.ConvertTo
  fullName: System.Configuration.GenericEnumConverter.ConvertTo
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: public override object ConvertTo (System.ComponentModel.ITypeDescriptorContext ctx, System.Globalization.CultureInfo ci, object value, Type type);
    parameters:
    - id: ctx
      type: System.ComponentModel.ITypeDescriptorContext
      description: Parameter description to be filled
    - id: ci
      type: System.Globalization.CultureInfo
      description: Parameter description to be filled
    - id: value
      type: System.Object
      description: Parameter description to be filled
    - id: type
      type: System.Type
      description: Parameter description to be filled
    return:
      type: System.Object
      description: Return description to be filled
references:
- uid: System.Configuration.ConfigurationConverterBase
  isExternal: false
  name: System.Configuration.ConfigurationConverterBase
- uid: System.Configuration.GenericEnumConverter.#ctor(System.Type)
  parent: System.Configuration.GenericEnumConverter
  isExternal: false
  name: .ctor
  nameWithType: GenericEnumConverter..ctor
  fullName: System.Configuration.GenericEnumConverter..ctor
- uid: System.Type
  parent: System
  isExternal: false
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Configuration.GenericEnumConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  parent: System.Configuration.GenericEnumConverter
  isExternal: false
  name: ConvertFrom
  nameWithType: GenericEnumConverter.ConvertFrom
  fullName: System.Configuration.GenericEnumConverter.ConvertFrom
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Globalization.CultureInfo
  parent: System.Globalization
  isExternal: false
  name: CultureInfo
  nameWithType: CultureInfo
  fullName: System.Globalization.CultureInfo
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Configuration.GenericEnumConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  parent: System.Configuration.GenericEnumConverter
  isExternal: false
  name: ConvertTo
  nameWithType: GenericEnumConverter.ConvertTo
  fullName: System.Configuration.GenericEnumConverter.ConvertTo
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Globalization.CultureInfo
  parent: System.Globalization
  isExternal: false
  name: CultureInfo
  nameWithType: CultureInfo
  fullName: System.Globalization.CultureInfo
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Type
  parent: System
  isExternal: false
  name: Type
  nameWithType: Type
  fullName: System.Type
