### YamlMime:ManagedReference
items:
- uid: System.Configuration.TimeSpanValidator
  id: TimeSpanValidator
  children:
  - System.Configuration.TimeSpanValidator.#ctor(System.TimeSpan,System.TimeSpan)
  - System.Configuration.TimeSpanValidator.#ctor(System.TimeSpan,System.TimeSpan,System.Boolean)
  - System.Configuration.TimeSpanValidator.#ctor(System.TimeSpan,System.TimeSpan,System.Boolean,System.Int64)
  - System.Configuration.TimeSpanValidator.CanValidate(System.Type)
  - System.Configuration.TimeSpanValidator.Validate(System.Object)
  langs:
  - csharp
  name: TimeSpanValidator
  nameWithType: TimeSpanValidator
  fullName: System.Configuration.TimeSpanValidator
  type: Class
  summary: Provides validation of a <see cref="T:System.TimeSpan"> object.
  remarks: "The TimeSpanValidator class is used to ensure that a <xref:System.TimeSpan> object meets specific criteria. The <xref:System.Configuration.TimeSpanValidator.%23ctor%2A> constructor with two parameters ensures that both a minimum and a maximum <xref:System.TimeSpan> value are adhered to. The <xref:System.Configuration.TimeSpanValidator.%23ctor%2A> constructor with three parameters checks both the minimum and maximum <xref:System.TimeSpan> values, as well as whether the validation range is exclusive. The <xref:System.Configuration.TimeSpanValidator.%23ctor%2A> constructor with four parameters checks the previous three parameters and also checks whether the <xref:System.TimeSpan> value is equal to a specific number of seconds.  \n  \n The <xref:System.Configuration.TimeSpanValidator.CanValidate%2A> method determines whether the object type being validated matches the expected type. The object being validated is passed as a parameter of the <xref:System.Configuration.TimeSpanValidator.Validate%2A> method."
  example:
  - "The following code example demonstrates how to use the TimeSpanValidator type.  \n  \n [!CODE [System.Configuration.TimeSpanValidator#1](../CodeSnippet/VS_Snippets_WebNet/System.Configuration.TimeSpanValidator#1)]"
  syntax:
    content: 'public class TimeSpanValidator : System.Configuration.ConfigurationValidatorBase'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationValidatorBase
  implements: []
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.TimeSpanValidator.#ctor(System.TimeSpan,System.TimeSpan)
  id: '#ctor(System.TimeSpan,System.TimeSpan)'
  parent: System.Configuration.TimeSpanValidator
  langs:
  - csharp
  name: TimeSpanValidator(TimeSpan,TimeSpan)
  nameWithType: TimeSpanValidator.TimeSpanValidator(TimeSpan,TimeSpan)
  fullName: System.Configuration.TimeSpanValidator.TimeSpanValidator(TimeSpan,TimeSpan)
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Initializes a new instance of the <see cref="T:System.Configuration.TimeSpanValidator"> class, based on supplied parameters.
  remarks: When the TimeSpanValidator constructor with two parameters is used, the <xref:System.Configuration.TimeSpanValidator> object validates that a <xref:System.TimeSpan> value adheres to a specific range.
  syntax:
    content: public TimeSpanValidator (TimeSpan minValue, TimeSpan maxValue);
    parameters:
    - id: minValue
      type: System.TimeSpan
      description: A <see cref="T:System.TimeSpan"> object that specifies the minimum time allowed to pass validation.
    - id: maxValue
      type: System.TimeSpan
      description: A <see cref="T:System.TimeSpan"> object that specifies the maximum time allowed to pass validation.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.TimeSpanValidator.#ctor(System.TimeSpan,System.TimeSpan,System.Boolean)
  id: '#ctor(System.TimeSpan,System.TimeSpan,System.Boolean)'
  parent: System.Configuration.TimeSpanValidator
  langs:
  - csharp
  name: TimeSpanValidator(TimeSpan,TimeSpan,Boolean)
  nameWithType: TimeSpanValidator.TimeSpanValidator(TimeSpan,TimeSpan,Boolean)
  fullName: System.Configuration.TimeSpanValidator.TimeSpanValidator(TimeSpan,TimeSpan,Boolean)
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Initializes a new instance of the <see cref="T:System.Configuration.TimeSpanValidator"> class, based on supplied parameters.
  remarks: The TimeSpanValidator constructor checks both the minimum and maximum <xref:System.TimeSpan> values, as well as whether the validation range is exclusive. When the  parameter is set to `true`, the <xref:System.TimeSpan> value must not be between the  and  values.
  syntax:
    content: public TimeSpanValidator (TimeSpan minValue, TimeSpan maxValue, bool rangeIsExclusive);
    parameters:
    - id: minValue
      type: System.TimeSpan
      description: A <see cref="T:System.TimeSpan"> object that specifies the minimum time allowed to pass validation.
    - id: maxValue
      type: System.TimeSpan
      description: A <see cref="T:System.TimeSpan"> object that specifies the maximum time allowed to pass validation.
    - id: rangeIsExclusive
      type: System.Boolean
      description: A <see cref="T:System.Boolean"> value that specifies whether the validation range is exclusive.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.TimeSpanValidator.#ctor(System.TimeSpan,System.TimeSpan,System.Boolean,System.Int64)
  id: '#ctor(System.TimeSpan,System.TimeSpan,System.Boolean,System.Int64)'
  parent: System.Configuration.TimeSpanValidator
  langs:
  - csharp
  name: TimeSpanValidator(TimeSpan,TimeSpan,Boolean,Int64)
  nameWithType: TimeSpanValidator.TimeSpanValidator(TimeSpan,TimeSpan,Boolean,Int64)
  fullName: System.Configuration.TimeSpanValidator.TimeSpanValidator(TimeSpan,TimeSpan,Boolean,Int64)
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Initializes a new instance of the <see cref="T:System.Configuration.TimeSpanValidator"> class, based on supplied parameters.
  remarks: When the  parameter is specified, the <xref:System.TimeSpan> object being validated must be equal to this value in order to pass validation.
  example:
  - "The following code example demonstrates how to use the TimeSpanValidator constructor. This code example is part of a larger example provided for the <xref:System.Configuration.TimeSpanValidator> class.  \n  \n [!CODE [System.Configuration.TimeSpanValidator#2](../CodeSnippet/VS_Snippets_WebNet/System.Configuration.TimeSpanValidator#2)]"
  syntax:
    content: public TimeSpanValidator (TimeSpan minValue, TimeSpan maxValue, bool rangeIsExclusive, long resolutionInSeconds);
    parameters:
    - id: minValue
      type: System.TimeSpan
      description: A <see cref="T:System.TimeSpan"> object that specifies the minimum time allowed to pass validation.
    - id: maxValue
      type: System.TimeSpan
      description: A <see cref="T:System.TimeSpan"> object that specifies the maximum time allowed to pass validation.
    - id: rangeIsExclusive
      type: System.Boolean
      description: A <see cref="T:System.Boolean"> value that specifies whether the validation range is exclusive.
    - id: resolutionInSeconds
      type: System.Int64
      description: An <see cref="T:System.Int64"> value that specifies a number of seconds.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.TimeSpanValidator.CanValidate(System.Type)
  id: CanValidate(System.Type)
  parent: System.Configuration.TimeSpanValidator
  langs:
  - csharp
  name: CanValidate(Type)
  nameWithType: TimeSpanValidator.CanValidate(Type)
  fullName: System.Configuration.TimeSpanValidator.CanValidate(Type)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Determines whether the type of the object can be validated.
  remarks: ''
  example:
  - "The following code example demonstrates how to use the CanValidate method. This code example is part of a larger example provided for the <xref:System.Configuration.TimeSpanValidator> class.  \n  \n [!CODE [System.Configuration.TimeSpanValidator#3](../CodeSnippet/VS_Snippets_WebNet/System.Configuration.TimeSpanValidator#3)]"
  syntax:
    content: public override bool CanValidate (Type type);
    parameters:
    - id: type
      type: System.Type
      description: The type of the object.
    return:
      type: System.Boolean
      description: '`true` if the  parameter matches a <see cref="T:System.TimeSpan"> value; otherwise, `false`.'
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.TimeSpanValidator.Validate(System.Object)
  id: Validate(System.Object)
  parent: System.Configuration.TimeSpanValidator
  langs:
  - csharp
  name: Validate(Object)
  nameWithType: TimeSpanValidator.Validate(Object)
  fullName: System.Configuration.TimeSpanValidator.Validate(Object)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Determines whether the value of an object is valid.
  remarks: The <xref:System.Configuration.TimeSpanValidator> object contains the rules necessary to validate a <xref:System.TimeSpan> object. The rules are established when an instance of the <xref:System.Configuration.TimeSpanValidator> class is created. The object to validate is passed as a parameter of the Validate method.
  example:
  - "The following code example demonstrates how to use the Validate method. This code example is part of a larger example provided for the <xref:System.Configuration.TimeSpanValidator> class.  \n  \n [!CODE [System.Configuration.TimeSpanValidator#4](../CodeSnippet/VS_Snippets_WebNet/System.Configuration.TimeSpanValidator#4)]"
  syntax:
    content: public override void Validate (object value);
    parameters:
    - id: value
      type: System.Object
      description: The value of an object.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationValidatorBase
  isExternal: false
  name: System.Configuration.ConfigurationValidatorBase
- uid: System.Configuration.TimeSpanValidator.#ctor(System.TimeSpan,System.TimeSpan)
  parent: System.Configuration.TimeSpanValidator
  isExternal: false
  name: TimeSpanValidator(TimeSpan,TimeSpan)
  nameWithType: TimeSpanValidator.TimeSpanValidator(TimeSpan,TimeSpan)
  fullName: System.Configuration.TimeSpanValidator.TimeSpanValidator(TimeSpan,TimeSpan)
- uid: System.TimeSpan
  parent: System
  isExternal: false
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.TimeSpan
  parent: System
  isExternal: false
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.Configuration.TimeSpanValidator.#ctor(System.TimeSpan,System.TimeSpan,System.Boolean)
  parent: System.Configuration.TimeSpanValidator
  isExternal: false
  name: TimeSpanValidator(TimeSpan,TimeSpan,Boolean)
  nameWithType: TimeSpanValidator.TimeSpanValidator(TimeSpan,TimeSpan,Boolean)
  fullName: System.Configuration.TimeSpanValidator.TimeSpanValidator(TimeSpan,TimeSpan,Boolean)
- uid: System.TimeSpan
  parent: System
  isExternal: false
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.TimeSpan
  parent: System
  isExternal: false
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.TimeSpanValidator.#ctor(System.TimeSpan,System.TimeSpan,System.Boolean,System.Int64)
  parent: System.Configuration.TimeSpanValidator
  isExternal: false
  name: TimeSpanValidator(TimeSpan,TimeSpan,Boolean,Int64)
  nameWithType: TimeSpanValidator.TimeSpanValidator(TimeSpan,TimeSpan,Boolean,Int64)
  fullName: System.Configuration.TimeSpanValidator.TimeSpanValidator(TimeSpan,TimeSpan,Boolean,Int64)
- uid: System.TimeSpan
  parent: System
  isExternal: false
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.TimeSpan
  parent: System
  isExternal: false
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Int64
  parent: System
  isExternal: false
  name: Int64
  nameWithType: Int64
  fullName: System.Int64
- uid: System.Configuration.TimeSpanValidator.CanValidate(System.Type)
  parent: System.Configuration.TimeSpanValidator
  isExternal: false
  name: CanValidate(Type)
  nameWithType: TimeSpanValidator.CanValidate(Type)
  fullName: System.Configuration.TimeSpanValidator.CanValidate(Type)
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Type
  parent: System
  isExternal: false
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Configuration.TimeSpanValidator.Validate(System.Object)
  parent: System.Configuration.TimeSpanValidator
  isExternal: false
  name: Validate(Object)
  nameWithType: TimeSpanValidator.Validate(Object)
  fullName: System.Configuration.TimeSpanValidator.Validate(Object)
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
