### YamlMime:ManagedReference
items:
- uid: System.Configuration.ContextInformation
  id: ContextInformation
  children:
  - System.Configuration.ContextInformation.GetSection(System.String)
  - System.Configuration.ContextInformation.HostingContext
  - System.Configuration.ContextInformation.IsMachineLevel
  langs:
  - csharp
  name: ContextInformation
  nameWithType: ContextInformation
  fullName: System.Configuration.ContextInformation
  type: Class
  summary: Encapsulates the context information that is associated with a <see cref="T:System.Configuration.ConfigurationElement"> object. This class cannot be inherited.
  remarks: The ContextInformation object provides environment details related to an element of the configuration. For instance, you can use the <xref:System.Configuration.ContextInformation.IsMachineLevel%2A> property to determine whether a <xref:System.Configuration.ConfigurationElement> was set in Machine.config, or you can determine which hierarchy a <xref:System.Configuration.ConfigurationElement> belongs to by using the <xref:System.Configuration.ContextInformation.HostingContext%2A> property.
  example:
  - "The following code example demonstrates how to use the ContextInformation type.  \n  \n [!CODE [System.Configuration.ContextInformation#1](../CodeSnippet/VS_Snippets_WebNet/System.Configuration.ContextInformation#1)]"
  syntax:
    content: public sealed class ContextInformation
  inheritance:
  - System.Object
  implements: []
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ContextInformation.GetSection(System.String)
  id: GetSection(System.String)
  parent: System.Configuration.ContextInformation
  langs:
  - csharp
  name: GetSection(String)
  nameWithType: ContextInformation.GetSection(String)
  fullName: System.Configuration.ContextInformation.GetSection(String)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Provides an object containing configuration-section information based on the specified section name.
  remarks: When specifying a section within the configuration, note that the name of the configuration section is case-sensitive.
  syntax:
    content: public object GetSection (string sectionName);
    parameters:
    - id: sectionName
      type: System.String
      description: The name of the configuration section.
    return:
      type: System.Object
      description: An object containing the specified section within the configuration.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ContextInformation.HostingContext
  id: HostingContext
  parent: System.Configuration.ContextInformation
  langs:
  - csharp
  name: HostingContext
  nameWithType: ContextInformation.HostingContext
  fullName: System.Configuration.ContextInformation.HostingContext
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Gets the context of the environment where the configuration property is being evaluated.
  remarks: The possible HostingContext value is <xref:System.Web.Configuration.WebContext>, <xref:System.Configuration.ExeContext>, or `null`.
  example:
  - "The following code example demonstrates how to use the HostingContext property.  \n  \n [!CODE [System.Configuration.ContextInformation#3](../CodeSnippet/VS_Snippets_WebNet/System.Configuration.ContextInformation#3)]"
  syntax:
    content: public object HostingContext { get; }
    return:
      type: System.Object
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ContextInformation.IsMachineLevel
  id: IsMachineLevel
  parent: System.Configuration.ContextInformation
  langs:
  - csharp
  name: IsMachineLevel
  nameWithType: ContextInformation.IsMachineLevel
  fullName: System.Configuration.ContextInformation.IsMachineLevel
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Gets a value specifying whether the configuration property is being evaluated at the machine configuration level.
  remarks: When the returned value of IsMachineLevel is `false`, use the <xref:System.Configuration.ContextInformation.HostingContext%2A> property to determine the level within the configuration hierarchy.
  example:
  - "The following code example demonstrates how to use the <xref:System.Configuration.ContextInformation.HostingContext%2A> property.  \n  \n [!CODE [System.Configuration.ContextInformation#2](../CodeSnippet/VS_Snippets_WebNet/System.Configuration.ContextInformation#2)]"
  syntax:
    content: public bool IsMachineLevel { get; }
    return:
      type: System.Boolean
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Configuration.ContextInformation.GetSection(System.String)
  parent: System.Configuration.ContextInformation
  isExternal: false
  name: GetSection(String)
  nameWithType: ContextInformation.GetSection(String)
  fullName: System.Configuration.ContextInformation.GetSection(String)
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.ContextInformation.HostingContext
  parent: System.Configuration.ContextInformation
  isExternal: false
  name: HostingContext
  nameWithType: ContextInformation.HostingContext
  fullName: System.Configuration.ContextInformation.HostingContext
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Configuration.ContextInformation.IsMachineLevel
  parent: System.Configuration.ContextInformation
  isExternal: false
  name: IsMachineLevel
  nameWithType: ContextInformation.IsMachineLevel
  fullName: System.Configuration.ContextInformation.IsMachineLevel
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
