### YamlMime:ManagedReference
items:
- uid: System.Configuration.ProtectedConfigurationSection
  id: ProtectedConfigurationSection
  children:
  - System.Configuration.ProtectedConfigurationSection.#ctor
  - System.Configuration.ProtectedConfigurationSection.DefaultProvider
  - System.Configuration.ProtectedConfigurationSection.Properties
  - System.Configuration.ProtectedConfigurationSection.Providers
  langs:
  - csharp
  name: ProtectedConfigurationSection
  nameWithType: ProtectedConfigurationSection
  fullName: System.Configuration.ProtectedConfigurationSection
  type: Class
  summary: Provides programmatic access to the `configProtectedData` configuration section. This class cannot be inherited.
  remarks: "The `configProtectedData` configuration file section contains a collection of protected data providers in its `providers` element.  \n  \n> [!NOTE]\n>  You can use the Aspnet_regiis.exe tool to encrypt and decrypt configuration sections. See [Encrypting Configuration Information Using Protected Configuration](../Topic/Encrypting%20Configuration%20Information%20Using%20Protected%20Configuration.md)."
  example:
  - "The following configuration file excerpt shows how to declaratively specify protected data providers.  \n  \n```  \n<configProtectedData defaultProvider=\"RsaProtectedConfigurationProvider\">  \n  <providers>  \n    <clear />  \n      <add keyContainerName=\"NetFrameworkConfigurationKey\" cspProviderName=\"\" useMachineContainer=\"true\" useOAEP=\"false\" description=\"Uses RsaCryptoServiceProvider to encrypt and decrypt\" name=\"RsaProtectedConfigurationProvider\" type=\"System.Configuration.RsaProtectedConfigurationProvider,System.Configuration, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a\" />  \n  \n      <add useMachineProtection=\"true\" description=\"Uses CryptProtectData and CryptUnProtectData Windows APIs to encrypt and decrypt\" keyEntropy=\"\" name=\"DataProtectionConfigurationProvider\" type=\"System.Configuration.DpapiProtectedConfigurationProvider,System.Configuration, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a\" />  \n  \n  </providers>  \n</configProtectedData>  \n```  \n  \n The following code example shows how to use the ProtectedConfigurationSection class to programmatically access values in the `configProtectedData` configuration file section.  \n  \n [!CODE [System.Configuration.ProtectedConfigurationSection#1](../CodeSnippet/VS_Snippets_WebNet/System.Configuration.ProtectedConfigurationSection#1)]"
  syntax:
    content: 'public sealed class ProtectedConfigurationSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ProtectedConfigurationSection.#ctor
  id: '#ctor'
  parent: System.Configuration.ProtectedConfigurationSection
  langs:
  - csharp
  name: ProtectedConfigurationSection()
  nameWithType: ProtectedConfigurationSection.ProtectedConfigurationSection()
  fullName: System.Configuration.ProtectedConfigurationSection.ProtectedConfigurationSection()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Initializes a new instance of the <see cref="T:System.Configuration.ProtectedConfigurationSection"> class using default settings.
  remarks: The ProtectedConfigurationSection constructor is not intended to be used directly from your code. It is called by the ASP.NET configuration system.
  syntax:
    content: public ProtectedConfigurationSection ();
    parameters: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ProtectedConfigurationSection.DefaultProvider
  id: DefaultProvider
  parent: System.Configuration.ProtectedConfigurationSection
  langs:
  - csharp
  name: DefaultProvider
  nameWithType: ProtectedConfigurationSection.DefaultProvider
  fullName: System.Configuration.ProtectedConfigurationSection.DefaultProvider
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Gets or sets the name of the default <see cref="T:System.Configuration.ProtectedConfigurationProvider"> object in the <xref:System.Configuration.ProtectedConfigurationSection.Providers%2A> collection property.
  remarks: ''
  example:
  - "The following code example shows how to use the DefaultProvider property.  \n  \n [!CODE [System.Configuration.ProtectedConfigurationSection#2](../CodeSnippet/VS_Snippets_WebNet/System.Configuration.ProtectedConfigurationSection#2)]"
  syntax:
    content: public string DefaultProvider { get; set; }
    return:
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ProtectedConfigurationSection.Properties
  id: Properties
  parent: System.Configuration.ProtectedConfigurationSection
  langs:
  - csharp
  name: Properties
  nameWithType: ProtectedConfigurationSection.Properties
  fullName: System.Configuration.ProtectedConfigurationSection.Properties
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: To be added.
  remarks: To be added.
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ProtectedConfigurationSection.Providers
  id: Providers
  parent: System.Configuration.ProtectedConfigurationSection
  langs:
  - csharp
  name: Providers
  nameWithType: ProtectedConfigurationSection.Providers
  fullName: System.Configuration.ProtectedConfigurationSection.Providers
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Gets a <see cref="T:System.Configuration.ProviderSettingsCollection"> collection of all the <xref:System.Configuration.ProtectedConfigurationProvider> objects in all participating configuration files.
  remarks: ''
  example:
  - "The following code example shows how to use the Providers property.  \n  \n [!CODE [System.Configuration.ProtectedConfigurationSection#3](../CodeSnippet/VS_Snippets_WebNet/System.Configuration.ProtectedConfigurationSection#3)]"
  syntax:
    content: public System.Configuration.ProviderSettingsCollection Providers { get; }
    return:
      type: System.Configuration.ProviderSettingsCollection
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.Configuration.ProtectedConfigurationSection.#ctor
  parent: System.Configuration.ProtectedConfigurationSection
  isExternal: false
  name: ProtectedConfigurationSection()
  nameWithType: ProtectedConfigurationSection.ProtectedConfigurationSection()
  fullName: System.Configuration.ProtectedConfigurationSection.ProtectedConfigurationSection()
- uid: System.Configuration.ProtectedConfigurationSection.DefaultProvider
  parent: System.Configuration.ProtectedConfigurationSection
  isExternal: false
  name: DefaultProvider
  nameWithType: ProtectedConfigurationSection.DefaultProvider
  fullName: System.Configuration.ProtectedConfigurationSection.DefaultProvider
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.ProtectedConfigurationSection.Properties
  parent: System.Configuration.ProtectedConfigurationSection
  isExternal: false
  name: Properties
  nameWithType: ProtectedConfigurationSection.Properties
  fullName: System.Configuration.ProtectedConfigurationSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Configuration.ProtectedConfigurationSection.Providers
  parent: System.Configuration.ProtectedConfigurationSection
  isExternal: false
  name: Providers
  nameWithType: ProtectedConfigurationSection.Providers
  fullName: System.Configuration.ProtectedConfigurationSection.Providers
- uid: System.Configuration.ProviderSettingsCollection
  parent: System.Configuration
  isExternal: false
  name: ProviderSettingsCollection
  nameWithType: ProviderSettingsCollection
  fullName: System.Configuration.ProviderSettingsCollection
