### YamlMime:ManagedReference
items:
- uid: System.Configuration.CommaDelimitedStringCollectionConverter
  id: CommaDelimitedStringCollectionConverter
  children:
  - System.Configuration.CommaDelimitedStringCollectionConverter.#ctor
  - System.Configuration.CommaDelimitedStringCollectionConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  - System.Configuration.CommaDelimitedStringCollectionConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  langs:
  - csharp
  name: CommaDelimitedStringCollectionConverter
  nameWithType: CommaDelimitedStringCollectionConverter
  fullName: System.Configuration.CommaDelimitedStringCollectionConverter
  type: Class
  summary: Converts a comma-delimited string value to and from a <see cref="T:System.Configuration.CommaDelimitedStringCollection"> object. This class cannot be inherited.
  remarks: To be added.
  syntax:
    content: 'public sealed class CommaDelimitedStringCollectionConverter : System.Configuration.ConfigurationConverterBase'
  inheritance:
  - System.ComponentModel.TypeConverter
  - System.Configuration.ConfigurationConverterBase
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationConverterBase.CanConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Type)
  - System.Configuration.ConfigurationConverterBase.CanConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Type)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.CommaDelimitedStringCollectionConverter.#ctor
  id: '#ctor'
  parent: System.Configuration.CommaDelimitedStringCollectionConverter
  langs:
  - csharp
  name: CommaDelimitedStringCollectionConverter()
  nameWithType: CommaDelimitedStringCollectionConverter.CommaDelimitedStringCollectionConverter()
  fullName: System.Configuration.CommaDelimitedStringCollectionConverter.CommaDelimitedStringCollectionConverter()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Initializes a new instance of the <see cref="T:System.Configuration.CommaDelimitedStringCollectionConverter"> class.
  remarks: To be added.
  syntax:
    content: public CommaDelimitedStringCollectionConverter ();
    parameters: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.CommaDelimitedStringCollectionConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  id: ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  parent: System.Configuration.CommaDelimitedStringCollectionConverter
  langs:
  - csharp
  name: ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  nameWithType: CommaDelimitedStringCollectionConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  fullName: System.Configuration.CommaDelimitedStringCollectionConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Converts a <see cref="T:System.String"> object to a <xref:System.Configuration.CommaDelimitedStringCollection> object.
  remarks: To be added.
  syntax:
    content: public override object ConvertFrom (System.ComponentModel.ITypeDescriptorContext ctx, System.Globalization.CultureInfo ci, object data);
    parameters:
    - id: ctx
      type: System.ComponentModel.ITypeDescriptorContext
      description: The <xref:System.ComponentModel.ITypeDescriptorContext> used for type conversions.
    - id: ci
      type: System.Globalization.CultureInfo
      description: The <see cref="T:System.Globalization.CultureInfo"> used during conversion.
    - id: data
      type: System.Object
      description: The comma-separated <see cref="T:System.String"> to convert.
    return:
      type: System.Object
      description: A <see cref="T:System.Configuration.CommaDelimitedStringCollection"> containing the converted value.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.CommaDelimitedStringCollectionConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  id: ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  parent: System.Configuration.CommaDelimitedStringCollectionConverter
  langs:
  - csharp
  name: ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  nameWithType: CommaDelimitedStringCollectionConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  fullName: System.Configuration.CommaDelimitedStringCollectionConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Converts a <see cref="T:System.Configuration.CommaDelimitedStringCollection"> object to a <xref:System.String> object.
  remarks: To be added.
  syntax:
    content: public override object ConvertTo (System.ComponentModel.ITypeDescriptorContext ctx, System.Globalization.CultureInfo ci, object value, Type type);
    parameters:
    - id: ctx
      type: System.ComponentModel.ITypeDescriptorContext
      description: The <xref:System.ComponentModel.ITypeDescriptorContext> used for type conversions.
    - id: ci
      type: System.Globalization.CultureInfo
      description: The <see cref="T:System.Globalization.CultureInfo"> used during conversion.
    - id: value
      type: System.Object
      description: The value to convert.
    - id: type
      type: System.Type
      description: The conversion type.
    return:
      type: System.Object
      description: The <see cref="T:System.String"> representing the converted  parameter, which is a <xref:System.Configuration.CommaDelimitedStringCollection>.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationConverterBase
  isExternal: false
  name: System.Configuration.ConfigurationConverterBase
- uid: System.Configuration.CommaDelimitedStringCollectionConverter.#ctor
  parent: System.Configuration.CommaDelimitedStringCollectionConverter
  isExternal: false
  name: CommaDelimitedStringCollectionConverter()
  nameWithType: CommaDelimitedStringCollectionConverter.CommaDelimitedStringCollectionConverter()
  fullName: System.Configuration.CommaDelimitedStringCollectionConverter.CommaDelimitedStringCollectionConverter()
- uid: System.Configuration.CommaDelimitedStringCollectionConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  parent: System.Configuration.CommaDelimitedStringCollectionConverter
  isExternal: false
  name: ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  nameWithType: CommaDelimitedStringCollectionConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  fullName: System.Configuration.CommaDelimitedStringCollectionConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.ComponentModel.ITypeDescriptorContext
  parent: System.ComponentModel
  isExternal: true
  name: ITypeDescriptorContext
  nameWithType: ITypeDescriptorContext
  fullName: System.ComponentModel.ITypeDescriptorContext
- uid: System.Globalization.CultureInfo
  parent: System.Globalization
  isExternal: false
  name: CultureInfo
  nameWithType: CultureInfo
  fullName: System.Globalization.CultureInfo
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Configuration.CommaDelimitedStringCollectionConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  parent: System.Configuration.CommaDelimitedStringCollectionConverter
  isExternal: false
  name: ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  nameWithType: CommaDelimitedStringCollectionConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  fullName: System.Configuration.CommaDelimitedStringCollectionConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.ComponentModel.ITypeDescriptorContext
  parent: System.ComponentModel
  isExternal: true
  name: ITypeDescriptorContext
  nameWithType: ITypeDescriptorContext
  fullName: System.ComponentModel.ITypeDescriptorContext
- uid: System.Globalization.CultureInfo
  parent: System.Globalization
  isExternal: false
  name: CultureInfo
  nameWithType: CultureInfo
  fullName: System.Globalization.CultureInfo
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Type
  parent: System
  isExternal: false
  name: Type
  nameWithType: Type
  fullName: System.Type
