### YamlMime:ManagedReference
items:
- uid: System.Configuration.ExeConfigurationFileMap
  id: ExeConfigurationFileMap
  children:
  - System.Configuration.ExeConfigurationFileMap.#ctor
  - System.Configuration.ExeConfigurationFileMap.#ctor(System.String)
  - System.Configuration.ExeConfigurationFileMap.Clone
  - System.Configuration.ExeConfigurationFileMap.ExeConfigFilename
  - System.Configuration.ExeConfigurationFileMap.LocalUserConfigFilename
  - System.Configuration.ExeConfigurationFileMap.RoamingUserConfigFilename
  langs:
  - csharp
  - vb
  name: ExeConfigurationFileMap
  nameWithType: ExeConfigurationFileMap
  fullName: System.Configuration.ExeConfigurationFileMap
  type: Class
  syntax:
    content: 'public sealed class ExeConfigurationFileMap : System.Configuration.ConfigurationFileMap'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationFileMap
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationFileMap.MachineConfigFilename
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: System.Configuration.ExeConfigurationFileMap.#ctor
  id: '#ctor'
  parent: System.Configuration.ExeConfigurationFileMap
  langs:
  - csharp
  - vb
  name: .ctor
  nameWithType: ExeConfigurationFileMap..ctor
  fullName: System.Configuration.ExeConfigurationFileMap..ctor
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: public ExeConfigurationFileMap ();
    parameters: []
- uid: System.Configuration.ExeConfigurationFileMap.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Configuration.ExeConfigurationFileMap
  langs:
  - csharp
  - vb
  name: .ctor
  nameWithType: ExeConfigurationFileMap..ctor
  fullName: System.Configuration.ExeConfigurationFileMap..ctor
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: public ExeConfigurationFileMap (string machineConfigFileName);
    parameters:
    - id: machineConfigFileName
      type: System.String
      description: Parameter description to be filled
- uid: System.Configuration.ExeConfigurationFileMap.Clone
  id: Clone
  parent: System.Configuration.ExeConfigurationFileMap
  langs:
  - csharp
  - vb
  name: Clone
  nameWithType: ExeConfigurationFileMap.Clone
  fullName: System.Configuration.ExeConfigurationFileMap.Clone
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: public override object Clone ();
    parameters: []
    return:
      type: System.Object
      description: Return description to be filled
- uid: System.Configuration.ExeConfigurationFileMap.ExeConfigFilename
  id: ExeConfigFilename
  parent: System.Configuration.ExeConfigurationFileMap
  langs:
  - csharp
  - vb
  name: ExeConfigFilename
  nameWithType: ExeConfigurationFileMap.ExeConfigFilename
  fullName: System.Configuration.ExeConfigurationFileMap.ExeConfigFilename
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: public string ExeConfigFilename { get; set; }
    return:
      type: System.String
      description: Return description to be filled
- uid: System.Configuration.ExeConfigurationFileMap.LocalUserConfigFilename
  id: LocalUserConfigFilename
  parent: System.Configuration.ExeConfigurationFileMap
  langs:
  - csharp
  - vb
  name: LocalUserConfigFilename
  nameWithType: ExeConfigurationFileMap.LocalUserConfigFilename
  fullName: System.Configuration.ExeConfigurationFileMap.LocalUserConfigFilename
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: public string LocalUserConfigFilename { get; set; }
    return:
      type: System.String
      description: Return description to be filled
- uid: System.Configuration.ExeConfigurationFileMap.RoamingUserConfigFilename
  id: RoamingUserConfigFilename
  parent: System.Configuration.ExeConfigurationFileMap
  langs:
  - csharp
  - vb
  name: RoamingUserConfigFilename
  nameWithType: ExeConfigurationFileMap.RoamingUserConfigFilename
  fullName: System.Configuration.ExeConfigurationFileMap.RoamingUserConfigFilename
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: public string RoamingUserConfigFilename { get; set; }
    return:
      type: System.String
      description: Return description to be filled
references:
- uid: System.Configuration.ConfigurationFileMap
  isExternal: false
  name: System.Configuration.ConfigurationFileMap
- uid: System.Configuration.ExeConfigurationFileMap.#ctor
  parent: System.Configuration.ExeConfigurationFileMap
  isExternal: false
  name: .ctor
  nameWithType: ExeConfigurationFileMap..ctor
  fullName: System.Configuration.ExeConfigurationFileMap..ctor
- uid: System.Configuration.ExeConfigurationFileMap.#ctor(System.String)
  parent: System.Configuration.ExeConfigurationFileMap
  isExternal: false
  name: .ctor
  nameWithType: ExeConfigurationFileMap..ctor
  fullName: System.Configuration.ExeConfigurationFileMap..ctor
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.ExeConfigurationFileMap.Clone
  parent: System.Configuration.ExeConfigurationFileMap
  isExternal: false
  name: Clone
  nameWithType: ExeConfigurationFileMap.Clone
  fullName: System.Configuration.ExeConfigurationFileMap.Clone
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Configuration.ExeConfigurationFileMap.ExeConfigFilename
  parent: System.Configuration.ExeConfigurationFileMap
  isExternal: false
  name: ExeConfigFilename
  nameWithType: ExeConfigurationFileMap.ExeConfigFilename
  fullName: System.Configuration.ExeConfigurationFileMap.ExeConfigFilename
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.ExeConfigurationFileMap.LocalUserConfigFilename
  parent: System.Configuration.ExeConfigurationFileMap
  isExternal: false
  name: LocalUserConfigFilename
  nameWithType: ExeConfigurationFileMap.LocalUserConfigFilename
  fullName: System.Configuration.ExeConfigurationFileMap.LocalUserConfigFilename
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.ExeConfigurationFileMap.RoamingUserConfigFilename
  parent: System.Configuration.ExeConfigurationFileMap
  isExternal: false
  name: RoamingUserConfigFilename
  nameWithType: ExeConfigurationFileMap.RoamingUserConfigFilename
  fullName: System.Configuration.ExeConfigurationFileMap.RoamingUserConfigFilename
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
