### YamlMime:ManagedReference
items:
- uid: System.Configuration.TimeSpanSecondsConverter
  id: TimeSpanSecondsConverter
  children:
  - System.Configuration.TimeSpanSecondsConverter.#ctor
  - System.Configuration.TimeSpanSecondsConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  - System.Configuration.TimeSpanSecondsConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  langs:
  - csharp
  name: TimeSpanSecondsConverter
  nameWithType: TimeSpanSecondsConverter
  fullName: System.Configuration.TimeSpanSecondsConverter
  type: Class
  summary: Converts a time span expressed in seconds.
  remarks: "This type, like all the other configuration converter types, converts strings found in the configuration file to and from the related strongly typed properties.  \n  \n In particular, the TimeSpanSecondsConverter converts <xref:System.String> seconds, assigned to a configuration property, to <xref:System.TimeSpan> seconds and vice versa.  \n  \n The <xref:System.Configuration.TimeSpanMinutesConverter> persists values of type `long` that represent a number of seconds."
  example:
  - Refer to the code examples in <xref:System.Configuration.InfiniteTimeSpanConverter> and <xref:System.Configuration.TimeSpanMinutesConverter>.
  syntax:
    content: 'public class TimeSpanSecondsConverter : System.Configuration.ConfigurationConverterBase'
  inheritance:
  - System.ComponentModel.TypeConverter
  - System.Configuration.ConfigurationConverterBase
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationConverterBase.CanConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Type)
  - System.Configuration.ConfigurationConverterBase.CanConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Type)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.TimeSpanSecondsConverter.#ctor
  id: '#ctor'
  parent: System.Configuration.TimeSpanSecondsConverter
  langs:
  - csharp
  name: TimeSpanSecondsConverter()
  nameWithType: TimeSpanSecondsConverter.TimeSpanSecondsConverter()
  fullName: System.Configuration.TimeSpanSecondsConverter.TimeSpanSecondsConverter()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Initializes a new instance of the <see cref="T:System.Configuration.TimeSpanSecondsConverter"> class.
  remarks: Normally, you use the converter types provided by the system. The only time you need to use the TimeSpanSecondsConverter constructor is when you create your own conversion type.
  syntax:
    content: public TimeSpanSecondsConverter ();
    parameters: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.TimeSpanSecondsConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  id: ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  parent: System.Configuration.TimeSpanSecondsConverter
  langs:
  - csharp
  name: ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  nameWithType: TimeSpanSecondsConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  fullName: System.Configuration.TimeSpanSecondsConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Converts a <see cref="T:System.String"> to a <xref:System.TimeSpan>.
  remarks: The system uses the ConvertFrom method when it reads from a configuration file to convert a <xref:System.String> value to <xref:System.TimeSpan>.
  syntax:
    content: public override object ConvertFrom (System.ComponentModel.ITypeDescriptorContext ctx, System.Globalization.CultureInfo ci, object data);
    parameters:
    - id: ctx
      type: System.ComponentModel.ITypeDescriptorContext
      description: The <xref:System.ComponentModel.ITypeDescriptorContext> object used for type conversions.
    - id: ci
      type: System.Globalization.CultureInfo
      description: The <see cref="T:System.Globalization.CultureInfo"> object used during conversion.
    - id: data
      type: System.Object
      description: The <see cref="T:System.String"> object to convert.
    return:
      type: System.Object
      description: The <see cref="T:System.TimeSpan"> representing the  parameter in seconds.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.TimeSpanSecondsConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  id: ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  parent: System.Configuration.TimeSpanSecondsConverter
  langs:
  - csharp
  name: ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  nameWithType: TimeSpanSecondsConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  fullName: System.Configuration.TimeSpanSecondsConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Converts a <see cref="T:System.TimeSpan"> to a <xref:System.String>.
  remarks: The system uses the ConvertTo method when it writes to a configuration file to convert a <xref:System.TimeSpan> to a <xref:System.String>.
  syntax:
    content: public override object ConvertTo (System.ComponentModel.ITypeDescriptorContext ctx, System.Globalization.CultureInfo ci, object value, Type type);
    parameters:
    - id: ctx
      type: System.ComponentModel.ITypeDescriptorContext
      description: The <xref:System.ComponentModel.ITypeDescriptorContext> object used for type conversions.
    - id: ci
      type: System.Globalization.CultureInfo
      description: The <see cref="T:System.Globalization.CultureInfo"> object used during conversion.
    - id: value
      type: System.Object
      description: The value to convert to.
    - id: type
      type: System.Type
      description: The type to convert to.
    return:
      type: System.Object
      description: The <see cref="T:System.String"> that represents the  parameter in minutes.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationConverterBase
  isExternal: false
  name: System.Configuration.ConfigurationConverterBase
- uid: System.Configuration.TimeSpanSecondsConverter.#ctor
  parent: System.Configuration.TimeSpanSecondsConverter
  isExternal: false
  name: TimeSpanSecondsConverter()
  nameWithType: TimeSpanSecondsConverter.TimeSpanSecondsConverter()
  fullName: System.Configuration.TimeSpanSecondsConverter.TimeSpanSecondsConverter()
- uid: System.Configuration.TimeSpanSecondsConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  parent: System.Configuration.TimeSpanSecondsConverter
  isExternal: false
  name: ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  nameWithType: TimeSpanSecondsConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  fullName: System.Configuration.TimeSpanSecondsConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.ComponentModel.ITypeDescriptorContext
  parent: System.ComponentModel
  isExternal: true
  name: ITypeDescriptorContext
  nameWithType: ITypeDescriptorContext
  fullName: System.ComponentModel.ITypeDescriptorContext
- uid: System.Globalization.CultureInfo
  parent: System.Globalization
  isExternal: false
  name: CultureInfo
  nameWithType: CultureInfo
  fullName: System.Globalization.CultureInfo
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Configuration.TimeSpanSecondsConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  parent: System.Configuration.TimeSpanSecondsConverter
  isExternal: false
  name: ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  nameWithType: TimeSpanSecondsConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  fullName: System.Configuration.TimeSpanSecondsConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.ComponentModel.ITypeDescriptorContext
  parent: System.ComponentModel
  isExternal: true
  name: ITypeDescriptorContext
  nameWithType: ITypeDescriptorContext
  fullName: System.ComponentModel.ITypeDescriptorContext
- uid: System.Globalization.CultureInfo
  parent: System.Globalization
  isExternal: false
  name: CultureInfo
  nameWithType: CultureInfo
  fullName: System.Globalization.CultureInfo
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Type
  parent: System
  isExternal: false
  name: Type
  nameWithType: Type
  fullName: System.Type
