### YamlMime:ManagedReference
items:
- uid: System.Configuration.PropertyInformationCollection
  id: PropertyInformationCollection
  children:
  - System.Configuration.PropertyInformationCollection.CopyTo(System.Configuration.PropertyInformation[],System.Int32)
  - System.Configuration.PropertyInformationCollection.GetEnumerator
  - System.Configuration.PropertyInformationCollection.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Configuration.PropertyInformationCollection.Item(System.String)
  langs:
  - csharp
  name: PropertyInformationCollection
  nameWithType: PropertyInformationCollection
  fullName: System.Configuration.PropertyInformationCollection
  type: Class
  summary: Contains a collection of <see cref="T:System.Configuration.PropertyInformation"> objects. This class cannot be inherited.
  remarks: The PropertyInformationCollection object contains a collection of <xref:System.Configuration.PropertyInformation> objects. A <xref:System.Configuration.PropertyInformation> object contains the details of an individual attribute within the configuration. The PropertyInformationCollection object is derived from the associated <xref:System.Collections.Specialized.NameObjectCollectionBase> object.
  example:
  - "The following code example demonstrates how to use the PropertyInformationCollection class.  \n  \n [!CODE [System.Configuration.PropertyInformation#14](../CodeSnippet/VS_Snippets_WebNet/System.Configuration.PropertyInformation#14)]"
  syntax:
    content: 'public sealed class PropertyInformationCollection : System.Collections.Specialized.NameObjectCollectionBase'
  inheritance:
  - System.Collections.Specialized.NameObjectCollectionBase
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.PropertyInformationCollection.CopyTo(System.Configuration.PropertyInformation[],System.Int32)
  id: CopyTo(System.Configuration.PropertyInformation[],System.Int32)
  parent: System.Configuration.PropertyInformationCollection
  langs:
  - csharp
  name: CopyTo(PropertyInformation[],Int32)
  nameWithType: PropertyInformationCollection.CopyTo(PropertyInformation[],Int32)
  fullName: System.Configuration.PropertyInformationCollection.CopyTo(PropertyInformation[],Int32)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Copies the entire <see cref="T:System.Configuration.PropertyInformationCollection"> collection to a compatible one-dimensional <xref:System.Array>, starting at the specified index of the target array.
  remarks: To be added.
  syntax:
    content: public void CopyTo (System.Configuration.PropertyInformation[] array, int index);
    parameters:
    - id: array
      type: System.Configuration.PropertyInformation[]
      description: A one-dimensional <see cref="T:System.Array"> that is the destination of the elements copied from the <xref:System.Configuration.PropertyInformationCollection> collection. The <see cref="T:System.Array"> must have zero-based indexing.
    - id: index
      type: System.Int32
      description: The zero-based index in  at which copying begins.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.PropertyInformationCollection.GetEnumerator
  id: GetEnumerator
  parent: System.Configuration.PropertyInformationCollection
  langs:
  - csharp
  name: GetEnumerator()
  nameWithType: PropertyInformationCollection.GetEnumerator()
  fullName: System.Configuration.PropertyInformationCollection.GetEnumerator()
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Gets an <see cref="T:System.Collections.IEnumerator"> object, which is used to iterate through this <xref:System.Configuration.PropertyInformationCollection> collection.
  remarks: To be added.
  syntax:
    content: public override System.Collections.IEnumerator GetEnumerator ();
    parameters: []
    return:
      type: System.Collections.IEnumerator
      description: An <see cref="T:System.Collections.IEnumerator"> object, which is used to iterate through this <xref:System.Configuration.PropertyInformationCollection>.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.PropertyInformationCollection.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Configuration.PropertyInformationCollection
  langs:
  - csharp
  name: GetObjectData(SerializationInfo,StreamingContext)
  nameWithType: PropertyInformationCollection.GetObjectData(SerializationInfo,StreamingContext)
  fullName: System.Configuration.PropertyInformationCollection.GetObjectData(SerializationInfo,StreamingContext)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Populates a <see cref="T:System.Runtime.Serialization.SerializationInfo"> object with the data needed to serialize the <xref:System.Configuration.PropertyInformationCollection> instance.
  remarks: To be added.
  syntax:
    content: public override void GetObjectData (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: A <see cref="T:System.Runtime.Serialization.SerializationInfo"> object that contains the information required to serialize the <xref:System.Configuration.PropertyInformationCollection> instance.
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: A <see cref="T:System.Runtime.Serialization.StreamingContext"> object that contains the source and destination of the serialized stream associated with the <xref:System.Configuration.PropertyInformationCollection> instance.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.PropertyInformationCollection.Item(System.String)
  id: Item(System.String)
  parent: System.Configuration.PropertyInformationCollection
  langs:
  - csharp
  name: Item(String)
  nameWithType: PropertyInformationCollection.Item(String)
  fullName: System.Configuration.PropertyInformationCollection.Item(String)
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Gets the <see cref="T:System.Configuration.PropertyInformation"> object in the collection, based on the specified property name.
  remarks: To be added.
  syntax:
    content: public System.Configuration.PropertyInformation this[string propertyName] { get; }
    parameters:
    - id: propertyName
      type: System.String
      description: "The name of the configuration attribute contained in the <see cref=\"T:System.Configuration.PropertyInformationCollection\">  \n  \n object."
    return:
      type: System.Configuration.PropertyInformation
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Collections.Specialized.NameObjectCollectionBase
  isExternal: false
  name: System.Collections.Specialized.NameObjectCollectionBase
- uid: System.Configuration.PropertyInformationCollection.CopyTo(System.Configuration.PropertyInformation[],System.Int32)
  parent: System.Configuration.PropertyInformationCollection
  isExternal: false
  name: CopyTo(PropertyInformation[],Int32)
  nameWithType: PropertyInformationCollection.CopyTo(PropertyInformation[],Int32)
  fullName: System.Configuration.PropertyInformationCollection.CopyTo(PropertyInformation[],Int32)
- uid: System.Configuration.PropertyInformation
  parent: System.Configuration
  isExternal: false
  name: PropertyInformation
  nameWithType: PropertyInformation
  fullName: System.Configuration.PropertyInformation[]
- uid: System.Int32
  parent: System
  isExternal: false
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Configuration.PropertyInformationCollection.GetEnumerator
  parent: System.Configuration.PropertyInformationCollection
  isExternal: false
  name: GetEnumerator()
  nameWithType: PropertyInformationCollection.GetEnumerator()
  fullName: System.Configuration.PropertyInformationCollection.GetEnumerator()
- uid: System.Collections.IEnumerator
  parent: System.Collections
  isExternal: false
  name: IEnumerator
  nameWithType: IEnumerator
  fullName: System.Collections.IEnumerator
- uid: System.Configuration.PropertyInformationCollection.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Configuration.PropertyInformationCollection
  isExternal: false
  name: GetObjectData(SerializationInfo,StreamingContext)
  nameWithType: PropertyInformationCollection.GetObjectData(SerializationInfo,StreamingContext)
  fullName: System.Configuration.PropertyInformationCollection.GetObjectData(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: false
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.Configuration.PropertyInformationCollection.Item(System.String)
  parent: System.Configuration.PropertyInformationCollection
  isExternal: false
  name: Item(String)
  nameWithType: PropertyInformationCollection.Item(String)
  fullName: System.Configuration.PropertyInformationCollection.Item(String)
- uid: System.Configuration.PropertyInformation
  parent: System.Configuration
  isExternal: false
  name: PropertyInformation
  nameWithType: PropertyInformation
  fullName: System.Configuration.PropertyInformation
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
