### YamlMime:ManagedReference
items:
- uid: System.Configuration.ConfigurationPermission
  id: ConfigurationPermission
  children:
  - System.Configuration.ConfigurationPermission.#ctor(System.Security.Permissions.PermissionState)
  - System.Configuration.ConfigurationPermission.Copy
  - System.Configuration.ConfigurationPermission.FromXml(System.Security.SecurityElement)
  - System.Configuration.ConfigurationPermission.Intersect(System.Security.IPermission)
  - System.Configuration.ConfigurationPermission.IsSubsetOf(System.Security.IPermission)
  - System.Configuration.ConfigurationPermission.IsUnrestricted
  - System.Configuration.ConfigurationPermission.ToXml
  - System.Configuration.ConfigurationPermission.Union(System.Security.IPermission)
  langs:
  - csharp
  - vb
  name: ConfigurationPermission
  nameWithType: ConfigurationPermission
  fullName: System.Configuration.ConfigurationPermission
  type: Class
  syntax:
    content: 'public sealed class ConfigurationPermission : System.Security.CodeAccessPermission, System.Security.Permissions.IUnrestrictedPermission'
  inheritance:
  - System.Object
  - System.Security.CodeAccessPermission
  implements:
  - System.Security.Permissions.IUnrestrictedPermission
  inheritedMembers:
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Security.CodeAccessPermission.Assert
  - System.Security.CodeAccessPermission.Demand
  - System.Security.CodeAccessPermission.Deny
  - System.Security.CodeAccessPermission.Equals(System.Object)
  - System.Security.CodeAccessPermission.GetHashCode
  - System.Security.CodeAccessPermission.PermitOnly
  - System.Security.CodeAccessPermission.RevertAll
  - System.Security.CodeAccessPermission.RevertAssert
  - System.Security.CodeAccessPermission.RevertDeny
  - System.Security.CodeAccessPermission.RevertPermitOnly
  - System.Security.CodeAccessPermission.ToString
- uid: System.Configuration.ConfigurationPermission.#ctor(System.Security.Permissions.PermissionState)
  id: '#ctor(System.Security.Permissions.PermissionState)'
  parent: System.Configuration.ConfigurationPermission
  langs:
  - csharp
  - vb
  name: .ctor
  nameWithType: ConfigurationPermission..ctor
  fullName: System.Configuration.ConfigurationPermission..ctor
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: public ConfigurationPermission (System.Security.Permissions.PermissionState state);
    parameters:
    - id: state
      type: System.Security.Permissions.PermissionState
      description: Parameter description to be filled
- uid: System.Configuration.ConfigurationPermission.Copy
  id: Copy
  parent: System.Configuration.ConfigurationPermission
  langs:
  - csharp
  - vb
  name: Copy
  nameWithType: ConfigurationPermission.Copy
  fullName: System.Configuration.ConfigurationPermission.Copy
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: public override System.Security.IPermission Copy ();
    parameters: []
    return:
      type: System.Security.IPermission
      description: Return description to be filled
- uid: System.Configuration.ConfigurationPermission.FromXml(System.Security.SecurityElement)
  id: FromXml(System.Security.SecurityElement)
  parent: System.Configuration.ConfigurationPermission
  langs:
  - csharp
  - vb
  name: FromXml
  nameWithType: ConfigurationPermission.FromXml
  fullName: System.Configuration.ConfigurationPermission.FromXml
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: public override void FromXml (System.Security.SecurityElement securityElement);
    parameters:
    - id: securityElement
      type: System.Security.SecurityElement
      description: Parameter description to be filled
    return:
      type: System.Void
      description: Return description to be filled
- uid: System.Configuration.ConfigurationPermission.Intersect(System.Security.IPermission)
  id: Intersect(System.Security.IPermission)
  parent: System.Configuration.ConfigurationPermission
  langs:
  - csharp
  - vb
  name: Intersect
  nameWithType: ConfigurationPermission.Intersect
  fullName: System.Configuration.ConfigurationPermission.Intersect
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: public override System.Security.IPermission Intersect (System.Security.IPermission target);
    parameters:
    - id: target
      type: System.Security.IPermission
      description: Parameter description to be filled
    return:
      type: System.Security.IPermission
      description: Return description to be filled
- uid: System.Configuration.ConfigurationPermission.IsSubsetOf(System.Security.IPermission)
  id: IsSubsetOf(System.Security.IPermission)
  parent: System.Configuration.ConfigurationPermission
  langs:
  - csharp
  - vb
  name: IsSubsetOf
  nameWithType: ConfigurationPermission.IsSubsetOf
  fullName: System.Configuration.ConfigurationPermission.IsSubsetOf
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: public override bool IsSubsetOf (System.Security.IPermission target);
    parameters:
    - id: target
      type: System.Security.IPermission
      description: Parameter description to be filled
    return:
      type: System.Boolean
      description: Return description to be filled
- uid: System.Configuration.ConfigurationPermission.IsUnrestricted
  id: IsUnrestricted
  parent: System.Configuration.ConfigurationPermission
  langs:
  - csharp
  - vb
  name: IsUnrestricted
  nameWithType: ConfigurationPermission.IsUnrestricted
  fullName: System.Configuration.ConfigurationPermission.IsUnrestricted
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: public bool IsUnrestricted ();
    parameters: []
    return:
      type: System.Boolean
      description: Return description to be filled
- uid: System.Configuration.ConfigurationPermission.ToXml
  id: ToXml
  parent: System.Configuration.ConfigurationPermission
  langs:
  - csharp
  - vb
  name: ToXml
  nameWithType: ConfigurationPermission.ToXml
  fullName: System.Configuration.ConfigurationPermission.ToXml
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: public override System.Security.SecurityElement ToXml ();
    parameters: []
    return:
      type: System.Security.SecurityElement
      description: Return description to be filled
- uid: System.Configuration.ConfigurationPermission.Union(System.Security.IPermission)
  id: Union(System.Security.IPermission)
  parent: System.Configuration.ConfigurationPermission
  langs:
  - csharp
  - vb
  name: Union
  nameWithType: ConfigurationPermission.Union
  fullName: System.Configuration.ConfigurationPermission.Union
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: public override System.Security.IPermission Union (System.Security.IPermission target);
    parameters:
    - id: target
      type: System.Security.IPermission
      description: Parameter description to be filled
    return:
      type: System.Security.IPermission
      description: Return description to be filled
references:
- uid: System.Security.CodeAccessPermission
  isExternal: false
  name: System.Security.CodeAccessPermission
- uid: System.Configuration.ConfigurationPermission.#ctor(System.Security.Permissions.PermissionState)
  parent: System.Configuration.ConfigurationPermission
  isExternal: false
  name: .ctor
  nameWithType: ConfigurationPermission..ctor
  fullName: System.Configuration.ConfigurationPermission..ctor
- uid: System.Security.Permissions.PermissionState
  parent: System.Security.Permissions
  isExternal: false
  name: PermissionState
  nameWithType: PermissionState
  fullName: System.Security.Permissions.PermissionState
- uid: System.Configuration.ConfigurationPermission.Copy
  parent: System.Configuration.ConfigurationPermission
  isExternal: false
  name: Copy
  nameWithType: ConfigurationPermission.Copy
  fullName: System.Configuration.ConfigurationPermission.Copy
- uid: System.Security.IPermission
  parent: System.Security
  isExternal: false
  name: IPermission
  nameWithType: IPermission
  fullName: System.Security.IPermission
- uid: System.Configuration.ConfigurationPermission.FromXml(System.Security.SecurityElement)
  parent: System.Configuration.ConfigurationPermission
  isExternal: false
  name: FromXml
  nameWithType: ConfigurationPermission.FromXml
  fullName: System.Configuration.ConfigurationPermission.FromXml
- uid: System.Void
  parent: System
  isExternal: false
  name: Void
  nameWithType: Void
  fullName: System.Void
- uid: System.Security.SecurityElement
  parent: System.Security
  isExternal: false
  name: SecurityElement
  nameWithType: SecurityElement
  fullName: System.Security.SecurityElement
- uid: System.Configuration.ConfigurationPermission.Intersect(System.Security.IPermission)
  parent: System.Configuration.ConfigurationPermission
  isExternal: false
  name: Intersect
  nameWithType: ConfigurationPermission.Intersect
  fullName: System.Configuration.ConfigurationPermission.Intersect
- uid: System.Security.IPermission
  parent: System.Security
  isExternal: false
  name: IPermission
  nameWithType: IPermission
  fullName: System.Security.IPermission
- uid: System.Security.IPermission
  parent: System.Security
  isExternal: false
  name: IPermission
  nameWithType: IPermission
  fullName: System.Security.IPermission
- uid: System.Configuration.ConfigurationPermission.IsSubsetOf(System.Security.IPermission)
  parent: System.Configuration.ConfigurationPermission
  isExternal: false
  name: IsSubsetOf
  nameWithType: ConfigurationPermission.IsSubsetOf
  fullName: System.Configuration.ConfigurationPermission.IsSubsetOf
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Security.IPermission
  parent: System.Security
  isExternal: false
  name: IPermission
  nameWithType: IPermission
  fullName: System.Security.IPermission
- uid: System.Configuration.ConfigurationPermission.IsUnrestricted
  parent: System.Configuration.ConfigurationPermission
  isExternal: false
  name: IsUnrestricted
  nameWithType: ConfigurationPermission.IsUnrestricted
  fullName: System.Configuration.ConfigurationPermission.IsUnrestricted
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.ConfigurationPermission.ToXml
  parent: System.Configuration.ConfigurationPermission
  isExternal: false
  name: ToXml
  nameWithType: ConfigurationPermission.ToXml
  fullName: System.Configuration.ConfigurationPermission.ToXml
- uid: System.Security.SecurityElement
  parent: System.Security
  isExternal: false
  name: SecurityElement
  nameWithType: SecurityElement
  fullName: System.Security.SecurityElement
- uid: System.Configuration.ConfigurationPermission.Union(System.Security.IPermission)
  parent: System.Configuration.ConfigurationPermission
  isExternal: false
  name: Union
  nameWithType: ConfigurationPermission.Union
  fullName: System.Configuration.ConfigurationPermission.Union
- uid: System.Security.IPermission
  parent: System.Security
  isExternal: false
  name: IPermission
  nameWithType: IPermission
  fullName: System.Security.IPermission
- uid: System.Security.IPermission
  parent: System.Security
  isExternal: false
  name: IPermission
  nameWithType: IPermission
  fullName: System.Security.IPermission
