### YamlMime:ManagedReference
items:
- uid: System.Configuration.CallbackValidator
  id: CallbackValidator
  children:
  - System.Configuration.CallbackValidator.#ctor(System.Type,System.Configuration.ValidatorCallback)
  - System.Configuration.CallbackValidator.CanValidate(System.Type)
  - System.Configuration.CallbackValidator.Validate(System.Object)
  langs:
  - csharp
  - vb
  name: CallbackValidator
  nameWithType: CallbackValidator
  fullName: System.Configuration.CallbackValidator
  type: Class
  syntax:
    content: 'public sealed class CallbackValidator : System.Configuration.ConfigurationValidatorBase'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationValidatorBase
  implements: []
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: System.Configuration.CallbackValidator.#ctor(System.Type,System.Configuration.ValidatorCallback)
  id: '#ctor(System.Type,System.Configuration.ValidatorCallback)'
  parent: System.Configuration.CallbackValidator
  langs:
  - csharp
  - vb
  name: CallbackValidator(Type,ValidatorCallback)
  nameWithType: CallbackValidator.CallbackValidator(Type,ValidatorCallback)
  fullName: System.Configuration.CallbackValidator.CallbackValidator(Type,ValidatorCallback)
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: public CallbackValidator (Type type, System.Configuration.ValidatorCallback callback);
    parameters:
    - id: type
      type: System.Type
      description: Parameter description to be filled
    - id: callback
      type: System.Configuration.ValidatorCallback
      description: Parameter description to be filled
- uid: System.Configuration.CallbackValidator.CanValidate(System.Type)
  id: CanValidate(System.Type)
  parent: System.Configuration.CallbackValidator
  langs:
  - csharp
  - vb
  name: CanValidate(Type)
  nameWithType: CallbackValidator.CanValidate(Type)
  fullName: System.Configuration.CallbackValidator.CanValidate(Type)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: public override bool CanValidate (Type type);
    parameters:
    - id: type
      type: System.Type
      description: Parameter description to be filled
    return:
      type: System.Boolean
      description: Return description to be filled
- uid: System.Configuration.CallbackValidator.Validate(System.Object)
  id: Validate(System.Object)
  parent: System.Configuration.CallbackValidator
  langs:
  - csharp
  - vb
  name: Validate(Object)
  nameWithType: CallbackValidator.Validate(Object)
  fullName: System.Configuration.CallbackValidator.Validate(Object)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: public override void Validate (object value);
    parameters:
    - id: value
      type: System.Object
      description: Parameter description to be filled
    return:
      type: System.Void
      description: Return description to be filled
references:
- uid: System.Configuration.ConfigurationValidatorBase
  isExternal: false
  name: System.Configuration.ConfigurationValidatorBase
- uid: System.Configuration.CallbackValidator.#ctor(System.Type,System.Configuration.ValidatorCallback)
  parent: System.Configuration.CallbackValidator
  isExternal: false
  name: CallbackValidator(Type,ValidatorCallback)
  nameWithType: CallbackValidator.CallbackValidator(Type,ValidatorCallback)
  fullName: System.Configuration.CallbackValidator.CallbackValidator(Type,ValidatorCallback)
- uid: System.Type
  parent: System
  isExternal: false
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Configuration.ValidatorCallback
  parent: System.Configuration
  isExternal: false
  name: ValidatorCallback
  nameWithType: ValidatorCallback
  fullName: System.Configuration.ValidatorCallback
- uid: System.Configuration.CallbackValidator.CanValidate(System.Type)
  parent: System.Configuration.CallbackValidator
  isExternal: false
  name: CanValidate(Type)
  nameWithType: CallbackValidator.CanValidate(Type)
  fullName: System.Configuration.CallbackValidator.CanValidate(Type)
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Type
  parent: System
  isExternal: false
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Configuration.CallbackValidator.Validate(System.Object)
  parent: System.Configuration.CallbackValidator
  isExternal: false
  name: Validate(Object)
  nameWithType: CallbackValidator.Validate(Object)
  fullName: System.Configuration.CallbackValidator.Validate(Object)
- uid: System.Void
  parent: System
  isExternal: false
  name: Void
  nameWithType: Void
  fullName: System.Void
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
