### YamlMime:ManagedReference
items:
- uid: System.Configuration.ConfigurationPropertyCollection
  id: ConfigurationPropertyCollection
  children:
  - System.Configuration.ConfigurationPropertyCollection.#ctor
  - System.Configuration.ConfigurationPropertyCollection.Add(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationPropertyCollection.Clear
  - System.Configuration.ConfigurationPropertyCollection.Contains(System.String)
  - System.Configuration.ConfigurationPropertyCollection.CopyTo(System.Configuration.ConfigurationProperty[],System.Int32)
  - System.Configuration.ConfigurationPropertyCollection.Count
  - System.Configuration.ConfigurationPropertyCollection.GetEnumerator
  - System.Configuration.ConfigurationPropertyCollection.IsSynchronized
  - System.Configuration.ConfigurationPropertyCollection.Item(System.String)
  - System.Configuration.ConfigurationPropertyCollection.Remove(System.String)
  - System.Configuration.ConfigurationPropertyCollection.SyncRoot
  - System.Configuration.ConfigurationPropertyCollection.System#Collections#ICollection#CopyTo(System.Array,System.Int32)
  langs:
  - csharp
  - vb
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
  type: Class
  syntax:
    content: 'public class ConfigurationPropertyCollection : System.Collections.ICollection'
  inheritance:
  - System.Object
  implements:
  - System.Collections.ICollection
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: System.Configuration.ConfigurationPropertyCollection.#ctor
  id: '#ctor'
  parent: System.Configuration.ConfigurationPropertyCollection
  langs:
  - csharp
  - vb
  name: .ctor
  nameWithType: ConfigurationPropertyCollection..ctor
  fullName: System.Configuration.ConfigurationPropertyCollection..ctor
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: public ConfigurationPropertyCollection ();
    parameters: []
- uid: System.Configuration.ConfigurationPropertyCollection.Add(System.Configuration.ConfigurationProperty)
  id: Add(System.Configuration.ConfigurationProperty)
  parent: System.Configuration.ConfigurationPropertyCollection
  langs:
  - csharp
  - vb
  name: Add
  nameWithType: ConfigurationPropertyCollection.Add
  fullName: System.Configuration.ConfigurationPropertyCollection.Add
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: public void Add (System.Configuration.ConfigurationProperty property);
    parameters:
    - id: property
      type: System.Configuration.ConfigurationProperty
      description: Parameter description to be filled
    return:
      type: System.Void
      description: Return description to be filled
- uid: System.Configuration.ConfigurationPropertyCollection.Clear
  id: Clear
  parent: System.Configuration.ConfigurationPropertyCollection
  langs:
  - csharp
  - vb
  name: Clear
  nameWithType: ConfigurationPropertyCollection.Clear
  fullName: System.Configuration.ConfigurationPropertyCollection.Clear
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: public void Clear ();
    parameters: []
    return:
      type: System.Void
      description: Return description to be filled
- uid: System.Configuration.ConfigurationPropertyCollection.Contains(System.String)
  id: Contains(System.String)
  parent: System.Configuration.ConfigurationPropertyCollection
  langs:
  - csharp
  - vb
  name: Contains
  nameWithType: ConfigurationPropertyCollection.Contains
  fullName: System.Configuration.ConfigurationPropertyCollection.Contains
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: public bool Contains (string name);
    parameters:
    - id: name
      type: System.String
      description: Parameter description to be filled
    return:
      type: System.Boolean
      description: Return description to be filled
- uid: System.Configuration.ConfigurationPropertyCollection.CopyTo(System.Configuration.ConfigurationProperty[],System.Int32)
  id: CopyTo(System.Configuration.ConfigurationProperty[],System.Int32)
  parent: System.Configuration.ConfigurationPropertyCollection
  langs:
  - csharp
  - vb
  name: CopyTo
  nameWithType: ConfigurationPropertyCollection.CopyTo
  fullName: System.Configuration.ConfigurationPropertyCollection.CopyTo
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: public void CopyTo (System.Configuration.ConfigurationProperty[] array, int index);
    parameters:
    - id: array
      type: System.Configuration.ConfigurationProperty[]
      description: Parameter description to be filled
    - id: index
      type: System.Int32
      description: Parameter description to be filled
    return:
      type: System.Void
      description: Return description to be filled
- uid: System.Configuration.ConfigurationPropertyCollection.Count
  id: Count
  parent: System.Configuration.ConfigurationPropertyCollection
  langs:
  - csharp
  - vb
  name: Count
  nameWithType: ConfigurationPropertyCollection.Count
  fullName: System.Configuration.ConfigurationPropertyCollection.Count
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: public int Count { get; }
    return:
      type: System.Int32
      description: Return description to be filled
- uid: System.Configuration.ConfigurationPropertyCollection.GetEnumerator
  id: GetEnumerator
  parent: System.Configuration.ConfigurationPropertyCollection
  langs:
  - csharp
  - vb
  name: GetEnumerator
  nameWithType: ConfigurationPropertyCollection.GetEnumerator
  fullName: System.Configuration.ConfigurationPropertyCollection.GetEnumerator
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: public System.Collections.IEnumerator GetEnumerator ();
    parameters: []
    return:
      type: System.Collections.IEnumerator
      description: Return description to be filled
- uid: System.Configuration.ConfigurationPropertyCollection.IsSynchronized
  id: IsSynchronized
  parent: System.Configuration.ConfigurationPropertyCollection
  langs:
  - csharp
  - vb
  name: IsSynchronized
  nameWithType: ConfigurationPropertyCollection.IsSynchronized
  fullName: System.Configuration.ConfigurationPropertyCollection.IsSynchronized
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: public bool IsSynchronized { get; }
    return:
      type: System.Boolean
      description: Return description to be filled
- uid: System.Configuration.ConfigurationPropertyCollection.Item(System.String)
  id: Item(System.String)
  parent: System.Configuration.ConfigurationPropertyCollection
  langs:
  - csharp
  - vb
  name: Item
  nameWithType: ConfigurationPropertyCollection.Item
  fullName: System.Configuration.ConfigurationPropertyCollection.Item
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: public System.Configuration.ConfigurationProperty this[string name] { get; }
    parameters:
    - id: name
      type: System.String
      description: Parameter description to be filled
    return:
      type: System.Configuration.ConfigurationProperty
      description: Return description to be filled
- uid: System.Configuration.ConfigurationPropertyCollection.Remove(System.String)
  id: Remove(System.String)
  parent: System.Configuration.ConfigurationPropertyCollection
  langs:
  - csharp
  - vb
  name: Remove
  nameWithType: ConfigurationPropertyCollection.Remove
  fullName: System.Configuration.ConfigurationPropertyCollection.Remove
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: public bool Remove (string name);
    parameters:
    - id: name
      type: System.String
      description: Parameter description to be filled
    return:
      type: System.Boolean
      description: Return description to be filled
- uid: System.Configuration.ConfigurationPropertyCollection.SyncRoot
  id: SyncRoot
  parent: System.Configuration.ConfigurationPropertyCollection
  langs:
  - csharp
  - vb
  name: SyncRoot
  nameWithType: ConfigurationPropertyCollection.SyncRoot
  fullName: System.Configuration.ConfigurationPropertyCollection.SyncRoot
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: public object SyncRoot { get; }
    return:
      type: System.Object
      description: Return description to be filled
- uid: System.Configuration.ConfigurationPropertyCollection.System#Collections#ICollection#CopyTo(System.Array,System.Int32)
  id: System#Collections#ICollection#CopyTo(System.Array,System.Int32)
  isEii: true
  parent: System.Configuration.ConfigurationPropertyCollection
  langs:
  - csharp
  - vb
  name: System.Collections.ICollection.CopyTo
  nameWithType: ConfigurationPropertyCollection.System.Collections.ICollection.CopyTo
  fullName: System.Configuration.ConfigurationPropertyCollection.System.Collections.ICollection.CopyTo
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: void ICollection.CopyTo (Array array, int index);
    parameters:
    - id: array
      type: System.Array
      description: Parameter description to be filled
    - id: index
      type: System.Int32
      description: Parameter description to be filled
    return:
      type: System.Void
      description: Return description to be filled
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Configuration.ConfigurationPropertyCollection.#ctor
  parent: System.Configuration.ConfigurationPropertyCollection
  isExternal: false
  name: .ctor
  nameWithType: ConfigurationPropertyCollection..ctor
  fullName: System.Configuration.ConfigurationPropertyCollection..ctor
- uid: System.Configuration.ConfigurationPropertyCollection.Add(System.Configuration.ConfigurationProperty)
  parent: System.Configuration.ConfigurationPropertyCollection
  isExternal: false
  name: Add
  nameWithType: ConfigurationPropertyCollection.Add
  fullName: System.Configuration.ConfigurationPropertyCollection.Add
- uid: System.Void
  parent: System
  isExternal: false
  name: Void
  nameWithType: Void
  fullName: System.Void
- uid: System.Configuration.ConfigurationProperty
  parent: System.Configuration
  isExternal: false
  name: ConfigurationProperty
  nameWithType: ConfigurationProperty
  fullName: System.Configuration.ConfigurationProperty
- uid: System.Configuration.ConfigurationPropertyCollection.Clear
  parent: System.Configuration.ConfigurationPropertyCollection
  isExternal: false
  name: Clear
  nameWithType: ConfigurationPropertyCollection.Clear
  fullName: System.Configuration.ConfigurationPropertyCollection.Clear
- uid: System.Void
  parent: System
  isExternal: false
  name: Void
  nameWithType: Void
  fullName: System.Void
- uid: System.Configuration.ConfigurationPropertyCollection.Contains(System.String)
  parent: System.Configuration.ConfigurationPropertyCollection
  isExternal: false
  name: Contains
  nameWithType: ConfigurationPropertyCollection.Contains
  fullName: System.Configuration.ConfigurationPropertyCollection.Contains
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.ConfigurationPropertyCollection.CopyTo(System.Configuration.ConfigurationProperty[],System.Int32)
  parent: System.Configuration.ConfigurationPropertyCollection
  isExternal: false
  name: CopyTo
  nameWithType: ConfigurationPropertyCollection.CopyTo
  fullName: System.Configuration.ConfigurationPropertyCollection.CopyTo
- uid: System.Void
  parent: System
  isExternal: false
  name: Void
  nameWithType: Void
  fullName: System.Void
- uid: System.Int32
  parent: System
  isExternal: false
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Configuration.ConfigurationPropertyCollection.Count
  parent: System.Configuration.ConfigurationPropertyCollection
  isExternal: false
  name: Count
  nameWithType: ConfigurationPropertyCollection.Count
  fullName: System.Configuration.ConfigurationPropertyCollection.Count
- uid: System.Int32
  parent: System
  isExternal: false
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Configuration.ConfigurationPropertyCollection.GetEnumerator
  parent: System.Configuration.ConfigurationPropertyCollection
  isExternal: false
  name: GetEnumerator
  nameWithType: ConfigurationPropertyCollection.GetEnumerator
  fullName: System.Configuration.ConfigurationPropertyCollection.GetEnumerator
- uid: System.Collections.IEnumerator
  parent: System.Collections
  isExternal: false
  name: IEnumerator
  nameWithType: IEnumerator
  fullName: System.Collections.IEnumerator
- uid: System.Configuration.ConfigurationPropertyCollection.IsSynchronized
  parent: System.Configuration.ConfigurationPropertyCollection
  isExternal: false
  name: IsSynchronized
  nameWithType: ConfigurationPropertyCollection.IsSynchronized
  fullName: System.Configuration.ConfigurationPropertyCollection.IsSynchronized
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.ConfigurationPropertyCollection.Item(System.String)
  parent: System.Configuration.ConfigurationPropertyCollection
  isExternal: false
  name: Item
  nameWithType: ConfigurationPropertyCollection.Item
  fullName: System.Configuration.ConfigurationPropertyCollection.Item
- uid: System.Configuration.ConfigurationProperty
  parent: System.Configuration
  isExternal: false
  name: ConfigurationProperty
  nameWithType: ConfigurationProperty
  fullName: System.Configuration.ConfigurationProperty
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.ConfigurationPropertyCollection.Remove(System.String)
  parent: System.Configuration.ConfigurationPropertyCollection
  isExternal: false
  name: Remove
  nameWithType: ConfigurationPropertyCollection.Remove
  fullName: System.Configuration.ConfigurationPropertyCollection.Remove
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.ConfigurationPropertyCollection.SyncRoot
  parent: System.Configuration.ConfigurationPropertyCollection
  isExternal: false
  name: SyncRoot
  nameWithType: ConfigurationPropertyCollection.SyncRoot
  fullName: System.Configuration.ConfigurationPropertyCollection.SyncRoot
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Configuration.ConfigurationPropertyCollection.System#Collections#ICollection#CopyTo(System.Array,System.Int32)
  parent: System.Configuration.ConfigurationPropertyCollection
  isExternal: false
  name: System.Collections.ICollection.CopyTo
  nameWithType: ConfigurationPropertyCollection.System.Collections.ICollection.CopyTo
  fullName: System.Configuration.ConfigurationPropertyCollection.System.Collections.ICollection.CopyTo
- uid: System.Void
  parent: System
  isExternal: false
  name: Void
  nameWithType: Void
  fullName: System.Void
- uid: System.Array
  parent: System
  isExternal: false
  name: Array
  nameWithType: Array
  fullName: System.Array
- uid: System.Int32
  parent: System
  isExternal: false
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
