### YamlMime:ManagedReference
items:
- uid: System.Configuration.ConfigurationLocation
  id: ConfigurationLocation
  children:
  - System.Configuration.ConfigurationLocation.OpenConfiguration
  - System.Configuration.ConfigurationLocation.Path
  langs:
  - csharp
  name: ConfigurationLocation
  nameWithType: ConfigurationLocation
  fullName: System.Configuration.ConfigurationLocation
  type: Class
  summary: Represents a `location` element within a configuration file.
  remarks: An instance of the ConfigurationLocation class represents a single `location` element within a configuration file. Locations are used to specify configuration settings that apply only to a specified resource, such as a specific page, file, or subdirectory, within your Web application. Use the ConfigurationLocation class to obtain the path and the <xref:System.Configuration.Configuration> object that applies to the specified resource.
  example:
  - "In the following code example, the Web configuration for the application `MySampleApp` is loaded, and then the locations defined in the configuration are displayed.  \n  \n [!CODE [ConfigurationLocationCollection#1](../CodeSnippet/VS_Snippets_WebNet/ConfigurationLocationCollection#1)]"
  syntax:
    content: public class ConfigurationLocation
  inheritance:
  - System.Object
  implements: []
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ConfigurationLocation.OpenConfiguration
  id: OpenConfiguration
  parent: System.Configuration.ConfigurationLocation
  langs:
  - csharp
  name: OpenConfiguration()
  nameWithType: ConfigurationLocation.OpenConfiguration()
  fullName: System.Configuration.ConfigurationLocation.OpenConfiguration()
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Creates an instance of a Configuration object.
  remarks: To be added.
  syntax:
    content: public System.Configuration.Configuration OpenConfiguration ();
    parameters: []
    return:
      type: System.Configuration.Configuration
      description: A Configuration object.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ConfigurationLocation.Path
  id: Path
  parent: System.Configuration.ConfigurationLocation
  langs:
  - csharp
  name: Path
  nameWithType: ConfigurationLocation.Path
  fullName: System.Configuration.ConfigurationLocation.Path
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Gets the relative path to the resource whose configuration settings are represented by this <see cref="T:System.Configuration.ConfigurationLocation"> object.
  remarks: "The path that is returned by the Path property is relative to the root of your Web site.  \n  \n> [!NOTE]\n>  The Path property might contain a comma-delimited list of paths to which the configuration setting applies."
  example:
  - "The following code example shows how to access the Path property and display the value returned to the console.  \n  \n [!CODE [ConfigurationLocationCollection#2](../CodeSnippet/VS_Snippets_WebNet/ConfigurationLocationCollection#2)]"
  syntax:
    content: public string Path { get; }
    return:
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Configuration.ConfigurationLocation.OpenConfiguration
  parent: System.Configuration.ConfigurationLocation
  isExternal: false
  name: OpenConfiguration()
  nameWithType: ConfigurationLocation.OpenConfiguration()
  fullName: System.Configuration.ConfigurationLocation.OpenConfiguration()
- uid: System.Configuration.Configuration
  parent: System.Configuration
  isExternal: false
  name: Configuration
  nameWithType: Configuration
  fullName: System.Configuration.Configuration
- uid: System.Configuration.ConfigurationLocation.Path
  parent: System.Configuration.ConfigurationLocation
  isExternal: false
  name: Path
  nameWithType: ConfigurationLocation.Path
  fullName: System.Configuration.ConfigurationLocation.Path
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
