### YamlMime:ManagedReference
items:
- uid: System.Configuration.TimeSpanValidatorAttribute
  id: TimeSpanValidatorAttribute
  children:
  - System.Configuration.TimeSpanValidatorAttribute.#ctor
  - System.Configuration.TimeSpanValidatorAttribute.ExcludeRange
  - System.Configuration.TimeSpanValidatorAttribute.MaxValue
  - System.Configuration.TimeSpanValidatorAttribute.MaxValueString
  - System.Configuration.TimeSpanValidatorAttribute.MinValue
  - System.Configuration.TimeSpanValidatorAttribute.MinValueString
  - System.Configuration.TimeSpanValidatorAttribute.TimeSpanMaxValue
  - System.Configuration.TimeSpanValidatorAttribute.TimeSpanMinValue
  - System.Configuration.TimeSpanValidatorAttribute.ValidatorInstance
  langs:
  - csharp
  name: TimeSpanValidatorAttribute
  nameWithType: TimeSpanValidatorAttribute
  fullName: System.Configuration.TimeSpanValidatorAttribute
  type: Class
  summary: Declaratively instructs the .NET Framework to perform time validation on a configuration property. This class cannot be inherited.
  remarks: "You use the TimeSpanValidatorAttribute attribute to decorate a configuration property. This is to instruct the .NET Framework to validate the property using the <xref:System.Configuration.TimeSpanValidator> class and pass to it the value of the decorating parameters.  \n  \n You can apply TimeSpanValidatorAttribute objects to property types only."
  example:
  - "The following example shows how to decorate the properties of a custom <xref:System.Configuration.ConfigurationSection> object using the TimeSpanValidatorAttribute attribute.  \n  \n [!CODE [System.Configuration.ConfigurationValidatorAttributes#8](../CodeSnippet/VS_Snippets_WebNet/System.Configuration.ConfigurationValidatorAttributes#8)]  \n  \n The following example is an excerpt of the configuration file that contains the custom section used by the previous sample.  \n  \n```  \n<configuration xmlns=\"http://schemas.microsoft.com/.NetConfiguration/v2.0\">  \n  <configSections>  \n    <section name=\"custom\" type=\"Microsoft.Samples.AspNet.Configuration.SampleSection, ConfigurationValidatorAttribute\" />  \n  </configSections>  \n  <custom fileName=\"NewFile.txt\" maxSize=\"1000\" maxAttempts=\"101\" maxUsers=\"2500\" maxIdleTime=\"00:15:00\" />  \n</configuration>  \n```"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property)]

      public sealed class TimeSpanValidatorAttribute : System.Configuration.ConfigurationValidatorAttribute
  inheritance:
  - System.Object
  - System.Attribute
  - System.Configuration.ConfigurationValidatorAttribute
  implements: []
  inheritedMembers:
  - System.Attribute.Equals(System.Object)
  - System.Attribute.GetCustomAttribute(System.Reflection.Assembly,System.Type)
  - System.Attribute.GetCustomAttribute(System.Reflection.Assembly,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttribute(System.Reflection.MemberInfo,System.Type)
  - System.Attribute.GetCustomAttribute(System.Reflection.MemberInfo,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttribute(System.Reflection.Module,System.Type)
  - System.Attribute.GetCustomAttribute(System.Reflection.Module,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttribute(System.Reflection.ParameterInfo,System.Type)
  - System.Attribute.GetCustomAttribute(System.Reflection.ParameterInfo,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.Assembly)
  - System.Attribute.GetCustomAttributes(System.Reflection.Assembly,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.Assembly,System.Type)
  - System.Attribute.GetCustomAttributes(System.Reflection.Assembly,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.MemberInfo)
  - System.Attribute.GetCustomAttributes(System.Reflection.MemberInfo,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.MemberInfo,System.Type)
  - System.Attribute.GetCustomAttributes(System.Reflection.MemberInfo,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.Module)
  - System.Attribute.GetCustomAttributes(System.Reflection.Module,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.Module,System.Type)
  - System.Attribute.GetCustomAttributes(System.Reflection.Module,System.Type,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.ParameterInfo)
  - System.Attribute.GetCustomAttributes(System.Reflection.ParameterInfo,System.Boolean)
  - System.Attribute.GetCustomAttributes(System.Reflection.ParameterInfo,System.Type)
  - System.Attribute.GetCustomAttributes(System.Reflection.ParameterInfo,System.Type,System.Boolean)
  - System.Attribute.GetHashCode
  - System.Attribute.IsDefaultAttribute
  - System.Attribute.IsDefined(System.Reflection.Assembly,System.Type)
  - System.Attribute.IsDefined(System.Reflection.Assembly,System.Type,System.Boolean)
  - System.Attribute.IsDefined(System.Reflection.MemberInfo,System.Type)
  - System.Attribute.IsDefined(System.Reflection.MemberInfo,System.Type,System.Boolean)
  - System.Attribute.IsDefined(System.Reflection.Module,System.Type)
  - System.Attribute.IsDefined(System.Reflection.Module,System.Type,System.Boolean)
  - System.Attribute.IsDefined(System.Reflection.ParameterInfo,System.Type)
  - System.Attribute.IsDefined(System.Reflection.ParameterInfo,System.Type,System.Boolean)
  - System.Attribute.Match(System.Object)
  - System.Attribute.System#Runtime#InteropServices#_Attribute#GetIDsOfNames(System.Guid@,System.IntPtr,System.UInt32,System.UInt32,System.IntPtr)
  - System.Attribute.System#Runtime#InteropServices#_Attribute#GetTypeInfo(System.UInt32,System.UInt32,System.IntPtr)
  - System.Attribute.System#Runtime#InteropServices#_Attribute#GetTypeInfoCount(System.UInt32@)
  - System.Attribute.System#Runtime#InteropServices#_Attribute#Invoke(System.UInt32,System.Guid@,System.UInt32,System.Int16,System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr)
  - System.Attribute.TypeId
  - System.Configuration.ConfigurationValidatorAttribute.ValidatorType
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.TimeSpanValidatorAttribute.#ctor
  id: '#ctor'
  parent: System.Configuration.TimeSpanValidatorAttribute
  langs:
  - csharp
  name: TimeSpanValidatorAttribute()
  nameWithType: TimeSpanValidatorAttribute.TimeSpanValidatorAttribute()
  fullName: System.Configuration.TimeSpanValidatorAttribute.TimeSpanValidatorAttribute()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Initializes a new instance of the <see cref="T:System.Configuration.TimeSpanValidatorAttribute"> class.
  remarks: You use this constructor in the attributed model to ensure that the type of the value assigned to the related property is a <xref:System.TimeSpan> object.
  example:
  - "The following example shows how to use the <xref:System.Configuration.StringValidatorAttribute.%23ctor%2A> constructor.  \n  \n [!CODE [System.Configuration.ConfigurationValidatorAttributes#12](../CodeSnippet/VS_Snippets_WebNet/System.Configuration.ConfigurationValidatorAttributes#12)]"
  syntax:
    content: public TimeSpanValidatorAttribute ();
    parameters: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.TimeSpanValidatorAttribute.ExcludeRange
  id: ExcludeRange
  parent: System.Configuration.TimeSpanValidatorAttribute
  langs:
  - csharp
  name: ExcludeRange
  nameWithType: TimeSpanValidatorAttribute.ExcludeRange
  fullName: System.Configuration.TimeSpanValidatorAttribute.ExcludeRange
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Gets or sets a value that indicates whether to include or exclude the integers in the range as defined by <xref:System.Configuration.TimeSpanValidatorAttribute.MinValueString%2A> and <xref:System.Configuration.TimeSpanValidatorAttribute.MaxValueString%2A>.
  remarks: The range is inclusive of the <xref:System.Configuration.TimeSpanValidatorAttribute.MinValueString%2A> and <xref:System.Configuration.TimeSpanValidatorAttribute.MaxValueString%2A> properties. When the ExcludeRange property is `false`, the allowed values are outside the range.
  example:
  - "The following example shows how to use the ExcludeRange property.  \n  \n [!CODE [System.Configuration.ConfigurationValidatorAttributes#8](../CodeSnippet/VS_Snippets_WebNet/System.Configuration.ConfigurationValidatorAttributes#8)]"
  syntax:
    content: public bool ExcludeRange { get; set; }
    return:
      type: System.Boolean
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.TimeSpanValidatorAttribute.MaxValue
  id: MaxValue
  parent: System.Configuration.TimeSpanValidatorAttribute
  langs:
  - csharp
  name: MaxValue
  nameWithType: TimeSpanValidatorAttribute.MaxValue
  fullName: System.Configuration.TimeSpanValidatorAttribute.MaxValue
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Gets the absolute maximum <see cref="T:System.TimeSpan"> value.
  remarks: This is the absolute maximum value allowed by the .NET Framework. Its value is defined by the <xref:System.TimeSpan> field.
  syntax:
    content: public TimeSpan MaxValue { get; }
    return:
      type: System.TimeSpan
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.TimeSpanValidatorAttribute.MaxValueString
  id: MaxValueString
  parent: System.Configuration.TimeSpanValidatorAttribute
  langs:
  - csharp
  name: MaxValueString
  nameWithType: TimeSpanValidatorAttribute.MaxValueString
  fullName: System.Configuration.TimeSpanValidatorAttribute.MaxValueString
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Gets or sets the relative maximum <see cref="T:System.TimeSpan"> value.
  remarks: This is the relative maximum value as set by the user.
  example:
  - "The following example shows how to use the MaxValueString property.  \n  \n [!CODE [System.Configuration.ConfigurationValidatorAttributes#8](../CodeSnippet/VS_Snippets_WebNet/System.Configuration.ConfigurationValidatorAttributes#8)]"
  syntax:
    content: public string MaxValueString { get; set; }
    return:
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.TimeSpanValidatorAttribute.MinValue
  id: MinValue
  parent: System.Configuration.TimeSpanValidatorAttribute
  langs:
  - csharp
  name: MinValue
  nameWithType: TimeSpanValidatorAttribute.MinValue
  fullName: System.Configuration.TimeSpanValidatorAttribute.MinValue
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Gets the absolute minimum <see cref="T:System.TimeSpan"> value.
  remarks: This is the absolute minimum value allowed by the .NET Framework. Its value is defined by the <xref:System.TimeSpan> field.
  syntax:
    content: public TimeSpan MinValue { get; }
    return:
      type: System.TimeSpan
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.TimeSpanValidatorAttribute.MinValueString
  id: MinValueString
  parent: System.Configuration.TimeSpanValidatorAttribute
  langs:
  - csharp
  name: MinValueString
  nameWithType: TimeSpanValidatorAttribute.MinValueString
  fullName: System.Configuration.TimeSpanValidatorAttribute.MinValueString
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Gets or sets the relative minimum <see cref="T:System.TimeSpan"> value.
  remarks: This is the relative minimum value as set by the user.
  example:
  - "The following example shows how to use the MinValueString property.  \n  \n [!CODE [System.Configuration.ConfigurationValidatorAttributes#8](../CodeSnippet/VS_Snippets_WebNet/System.Configuration.ConfigurationValidatorAttributes#8)]"
  syntax:
    content: public string MinValueString { get; set; }
    return:
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.TimeSpanValidatorAttribute.TimeSpanMaxValue
  id: TimeSpanMaxValue
  parent: System.Configuration.TimeSpanValidatorAttribute
  langs:
  - csharp
  name: TimeSpanMaxValue
  nameWithType: TimeSpanValidatorAttribute.TimeSpanMaxValue
  fullName: System.Configuration.TimeSpanValidatorAttribute.TimeSpanMaxValue
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Gets the absolute maximum value allowed.
  remarks: The string that contains the maximum allowed value for the time interval.
  example:
  - "The following example shows how to use the TimeSpanMaxValue field.  \n  \n [!CODE [System.Configuration.ConfigurationValidatorAttributes#10](../CodeSnippet/VS_Snippets_WebNet/System.Configuration.ConfigurationValidatorAttributes#10)]"
  syntax:
    content: public const string TimeSpanMaxValue;
    return:
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.TimeSpanValidatorAttribute.TimeSpanMinValue
  id: TimeSpanMinValue
  parent: System.Configuration.TimeSpanValidatorAttribute
  langs:
  - csharp
  name: TimeSpanMinValue
  nameWithType: TimeSpanValidatorAttribute.TimeSpanMinValue
  fullName: System.Configuration.TimeSpanValidatorAttribute.TimeSpanMinValue
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Gets the absolute minimum value allowed.
  remarks: The string that contains the minimum allowed value for the time interval.
  example:
  - "The following example shows how to use the TimeSpanMinValue field.  \n  \n [!CODE [System.Configuration.ConfigurationValidatorAttributes#11](../CodeSnippet/VS_Snippets_WebNet/System.Configuration.ConfigurationValidatorAttributes#11)]"
  syntax:
    content: public const string TimeSpanMinValue;
    return:
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.TimeSpanValidatorAttribute.ValidatorInstance
  id: ValidatorInstance
  parent: System.Configuration.TimeSpanValidatorAttribute
  langs:
  - csharp
  name: ValidatorInstance
  nameWithType: TimeSpanValidatorAttribute.ValidatorInstance
  fullName: System.Configuration.TimeSpanValidatorAttribute.ValidatorInstance
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Gets an instance of the <see cref="T:System.Configuration.TimeSpanValidator"> class.
  remarks: You use the ValidatorInstance property to perform string validation by calling its <xref:System.Configuration.TimeSpanValidator.Validate%2A> method.
  syntax:
    content: public override System.Configuration.ConfigurationValidatorBase ValidatorInstance { get; }
    return:
      type: System.Configuration.ConfigurationValidatorBase
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationValidatorAttribute
  isExternal: false
  name: System.Configuration.ConfigurationValidatorAttribute
- uid: System.Configuration.TimeSpanValidatorAttribute.#ctor
  parent: System.Configuration.TimeSpanValidatorAttribute
  isExternal: false
  name: TimeSpanValidatorAttribute()
  nameWithType: TimeSpanValidatorAttribute.TimeSpanValidatorAttribute()
  fullName: System.Configuration.TimeSpanValidatorAttribute.TimeSpanValidatorAttribute()
- uid: System.Configuration.TimeSpanValidatorAttribute.ExcludeRange
  parent: System.Configuration.TimeSpanValidatorAttribute
  isExternal: false
  name: ExcludeRange
  nameWithType: TimeSpanValidatorAttribute.ExcludeRange
  fullName: System.Configuration.TimeSpanValidatorAttribute.ExcludeRange
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.TimeSpanValidatorAttribute.MaxValue
  parent: System.Configuration.TimeSpanValidatorAttribute
  isExternal: false
  name: MaxValue
  nameWithType: TimeSpanValidatorAttribute.MaxValue
  fullName: System.Configuration.TimeSpanValidatorAttribute.MaxValue
- uid: System.TimeSpan
  parent: System
  isExternal: false
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.Configuration.TimeSpanValidatorAttribute.MaxValueString
  parent: System.Configuration.TimeSpanValidatorAttribute
  isExternal: false
  name: MaxValueString
  nameWithType: TimeSpanValidatorAttribute.MaxValueString
  fullName: System.Configuration.TimeSpanValidatorAttribute.MaxValueString
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.TimeSpanValidatorAttribute.MinValue
  parent: System.Configuration.TimeSpanValidatorAttribute
  isExternal: false
  name: MinValue
  nameWithType: TimeSpanValidatorAttribute.MinValue
  fullName: System.Configuration.TimeSpanValidatorAttribute.MinValue
- uid: System.TimeSpan
  parent: System
  isExternal: false
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.Configuration.TimeSpanValidatorAttribute.MinValueString
  parent: System.Configuration.TimeSpanValidatorAttribute
  isExternal: false
  name: MinValueString
  nameWithType: TimeSpanValidatorAttribute.MinValueString
  fullName: System.Configuration.TimeSpanValidatorAttribute.MinValueString
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.TimeSpanValidatorAttribute.TimeSpanMaxValue
  parent: System.Configuration.TimeSpanValidatorAttribute
  isExternal: false
  name: TimeSpanMaxValue
  nameWithType: TimeSpanValidatorAttribute.TimeSpanMaxValue
  fullName: System.Configuration.TimeSpanValidatorAttribute.TimeSpanMaxValue
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.TimeSpanValidatorAttribute.TimeSpanMinValue
  parent: System.Configuration.TimeSpanValidatorAttribute
  isExternal: false
  name: TimeSpanMinValue
  nameWithType: TimeSpanValidatorAttribute.TimeSpanMinValue
  fullName: System.Configuration.TimeSpanValidatorAttribute.TimeSpanMinValue
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.TimeSpanValidatorAttribute.ValidatorInstance
  parent: System.Configuration.TimeSpanValidatorAttribute
  isExternal: false
  name: ValidatorInstance
  nameWithType: TimeSpanValidatorAttribute.ValidatorInstance
  fullName: System.Configuration.TimeSpanValidatorAttribute.ValidatorInstance
- uid: System.Configuration.ConfigurationValidatorBase
  parent: System.Configuration
  isExternal: false
  name: ConfigurationValidatorBase
  nameWithType: ConfigurationValidatorBase
  fullName: System.Configuration.ConfigurationValidatorBase
