### YamlMime:ManagedReference
items:
- uid: System.Configuration.TimeSpanSecondsOrInfiniteConverter
  id: TimeSpanSecondsOrInfiniteConverter
  children:
  - System.Configuration.TimeSpanSecondsOrInfiniteConverter.#ctor
  - System.Configuration.TimeSpanSecondsOrInfiniteConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  - System.Configuration.TimeSpanSecondsOrInfiniteConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  langs:
  - csharp
  name: TimeSpanSecondsOrInfiniteConverter
  nameWithType: TimeSpanSecondsOrInfiniteConverter
  fullName: System.Configuration.TimeSpanSecondsOrInfiniteConverter
  type: Class
  summary: Converts a <see cref="T:System.TimeSpan"> expressed in seconds or as a standard infinite time span.
  remarks: "This type, like all the other configuration converter types, converts strings found in the configuration file to and from the related strongly typed properties.  \n  \n In particular, the TimeSpanSecondsOrInfiniteConverter converts <xref:System.String> seconds, assigned to a configuration property, to <xref:System.TimeSpan> seconds, and vice versa. If the configuration property has a <xref:System.String> value of \"infinite\", it converts this value to <xref:System.TimeSpan> and vice versa.  \n  \n The infinite <xref:System.TimeSpan> value is represented by the <xref:System.TimeSpan.MaxValue> enumeration value."
  example:
  - Refer to the code examples in the <xref:System.Configuration.InfiniteTimeSpanConverter> and <xref:System.Configuration.TimeSpanMinutesConverter> classes.
  syntax:
    content: 'public sealed class TimeSpanSecondsOrInfiniteConverter : System.Configuration.TimeSpanSecondsConverter'
  inheritance:
  - System.ComponentModel.TypeConverter
  - System.Configuration.ConfigurationConverterBase
  - System.Configuration.TimeSpanSecondsConverter
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationConverterBase.CanConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Type)
  - System.Configuration.ConfigurationConverterBase.CanConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Type)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.TimeSpanSecondsOrInfiniteConverter.#ctor
  id: '#ctor'
  parent: System.Configuration.TimeSpanSecondsOrInfiniteConverter
  langs:
  - csharp
  name: TimeSpanSecondsOrInfiniteConverter()
  nameWithType: TimeSpanSecondsOrInfiniteConverter.TimeSpanSecondsOrInfiniteConverter()
  fullName: System.Configuration.TimeSpanSecondsOrInfiniteConverter.TimeSpanSecondsOrInfiniteConverter()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Initializes a new instance of the <see cref="T:System.Configuration.TimeSpanSecondsOrInfiniteConverter"> class.
  remarks: Normally, you use the converter types provided by the system. The only time you need to use the TimeSpanSecondsOrInfiniteConverter constructor is when you create your own conversion type.
  syntax:
    content: public TimeSpanSecondsOrInfiniteConverter ();
    parameters: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.TimeSpanSecondsOrInfiniteConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  id: ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  parent: System.Configuration.TimeSpanSecondsOrInfiniteConverter
  langs:
  - csharp
  name: ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  nameWithType: TimeSpanSecondsOrInfiniteConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  fullName: System.Configuration.TimeSpanSecondsOrInfiniteConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Converts a <see cref="T:System.String"> to a <xref:System.TimeSpan>.
  remarks: The system uses ConvertFrom when reading from a configuration file to convert a <xref:System.String> value to <xref:System.TimeSpan>, or the <xref:System.String> "infinite" to <xref:System.TimeSpan.MaxValue>.
  example:
  - Refer to the code examples in the <xref:System.Configuration.InfiniteTimeSpanConverter> and <xref:System.Configuration.TimeSpanMinutesConverter> classes.
  syntax:
    content: public override object ConvertFrom (System.ComponentModel.ITypeDescriptorContext ctx, System.Globalization.CultureInfo ci, object data);
    parameters:
    - id: ctx
      type: System.ComponentModel.ITypeDescriptorContext
      description: The <xref:System.ComponentModel.ITypeDescriptorContext> object used for type conversions.
    - id: ci
      type: System.Globalization.CultureInfo
      description: The <see cref="T:System.Globalization.CultureInfo"> object used during conversion.
    - id: data
      type: System.Object
      description: The <see cref="T:System.String"> object to convert.
    return:
      type: System.Object
      description: The <see cref="F:System.TimeSpan.MaxValue">, if the  parameter is the <xref:System.String> "infinite"; otherwise, the <xref:System.TimeSpan> representing the  parameter in seconds.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.TimeSpanSecondsOrInfiniteConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  id: ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  parent: System.Configuration.TimeSpanSecondsOrInfiniteConverter
  langs:
  - csharp
  name: ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  nameWithType: TimeSpanSecondsOrInfiniteConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  fullName: System.Configuration.TimeSpanSecondsOrInfiniteConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: Converts a <see cref="T:System.TimeSpan"> to a. <xref:System.String>.
  remarks: The system uses ConvertTo when writing to a configuration file to convert a <xref:System.TimeSpan> value or <xref:System.TimeSpan.MaxValue> to a <xref:System.String>.
  example:
  - Refer to the code examples in the <xref:System.Configuration.InfiniteTimeSpanConverter> and <xref:System.Configuration.TimeSpanMinutesConverter> classes.
  syntax:
    content: public override object ConvertTo (System.ComponentModel.ITypeDescriptorContext ctx, System.Globalization.CultureInfo ci, object value, Type type);
    parameters:
    - id: ctx
      type: System.ComponentModel.ITypeDescriptorContext
      description: The <xref:System.ComponentModel.ITypeDescriptorContext> object used for type conversions.
    - id: ci
      type: System.Globalization.CultureInfo
      description: The <see cref="T:System.Globalization.CultureInfo"> object used during conversion.
    - id: value
      type: System.Object
      description: The value to convert.
    - id: type
      type: System.Type
      description: The conversion type.
    return:
      type: System.Object
      description: The <see cref="T:System.String"> "infinite", if the  parameter is <xref:System.TimeSpan.MaxValue>; otherwise, the <see cref="T:System.String"> representing the  parameter in seconds.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.TimeSpanSecondsConverter
  isExternal: false
  name: System.Configuration.TimeSpanSecondsConverter
- uid: System.Configuration.TimeSpanSecondsOrInfiniteConverter.#ctor
  parent: System.Configuration.TimeSpanSecondsOrInfiniteConverter
  isExternal: false
  name: TimeSpanSecondsOrInfiniteConverter()
  nameWithType: TimeSpanSecondsOrInfiniteConverter.TimeSpanSecondsOrInfiniteConverter()
  fullName: System.Configuration.TimeSpanSecondsOrInfiniteConverter.TimeSpanSecondsOrInfiniteConverter()
- uid: System.Configuration.TimeSpanSecondsOrInfiniteConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  parent: System.Configuration.TimeSpanSecondsOrInfiniteConverter
  isExternal: false
  name: ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  nameWithType: TimeSpanSecondsOrInfiniteConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  fullName: System.Configuration.TimeSpanSecondsOrInfiniteConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.ComponentModel.ITypeDescriptorContext
  parent: System.ComponentModel
  isExternal: true
  name: ITypeDescriptorContext
  nameWithType: ITypeDescriptorContext
  fullName: System.ComponentModel.ITypeDescriptorContext
- uid: System.Globalization.CultureInfo
  parent: System.Globalization
  isExternal: false
  name: CultureInfo
  nameWithType: CultureInfo
  fullName: System.Globalization.CultureInfo
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Configuration.TimeSpanSecondsOrInfiniteConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  parent: System.Configuration.TimeSpanSecondsOrInfiniteConverter
  isExternal: false
  name: ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  nameWithType: TimeSpanSecondsOrInfiniteConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  fullName: System.Configuration.TimeSpanSecondsOrInfiniteConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.ComponentModel.ITypeDescriptorContext
  parent: System.ComponentModel
  isExternal: true
  name: ITypeDescriptorContext
  nameWithType: ITypeDescriptorContext
  fullName: System.ComponentModel.ITypeDescriptorContext
- uid: System.Globalization.CultureInfo
  parent: System.Globalization
  isExternal: false
  name: CultureInfo
  nameWithType: CultureInfo
  fullName: System.Globalization.CultureInfo
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Type
  parent: System
  isExternal: false
  name: Type
  nameWithType: Type
  fullName: System.Type
