### YamlMime:ManagedReference
items:
- uid: System.Configuration.TimeSpanSecondsOrInfiniteConverter
  id: TimeSpanSecondsOrInfiniteConverter
  children:
  - System.Configuration.TimeSpanSecondsOrInfiniteConverter.#ctor
  - System.Configuration.TimeSpanSecondsOrInfiniteConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  - System.Configuration.TimeSpanSecondsOrInfiniteConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  langs:
  - csharp
  - vb
  name: TimeSpanSecondsOrInfiniteConverter
  nameWithType: TimeSpanSecondsOrInfiniteConverter
  fullName: System.Configuration.TimeSpanSecondsOrInfiniteConverter
  type: Class
  syntax:
    content: 'public sealed class TimeSpanSecondsOrInfiniteConverter : System.Configuration.TimeSpanSecondsConverter'
  inheritance:
  - System.ComponentModel.TypeConverter
  - System.Configuration.ConfigurationConverterBase
  - System.Configuration.TimeSpanSecondsConverter
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationConverterBase.CanConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Type)
  - System.Configuration.ConfigurationConverterBase.CanConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Type)
- uid: System.Configuration.TimeSpanSecondsOrInfiniteConverter.#ctor
  id: '#ctor'
  parent: System.Configuration.TimeSpanSecondsOrInfiniteConverter
  langs:
  - csharp
  - vb
  name: .ctor
  nameWithType: TimeSpanSecondsOrInfiniteConverter..ctor
  fullName: System.Configuration.TimeSpanSecondsOrInfiniteConverter..ctor
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: public TimeSpanSecondsOrInfiniteConverter ();
    parameters: []
- uid: System.Configuration.TimeSpanSecondsOrInfiniteConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  id: ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  parent: System.Configuration.TimeSpanSecondsOrInfiniteConverter
  langs:
  - csharp
  - vb
  name: ConvertFrom
  nameWithType: TimeSpanSecondsOrInfiniteConverter.ConvertFrom
  fullName: System.Configuration.TimeSpanSecondsOrInfiniteConverter.ConvertFrom
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: public override object ConvertFrom (System.ComponentModel.ITypeDescriptorContext ctx, System.Globalization.CultureInfo ci, object data);
    parameters:
    - id: ctx
      type: System.ComponentModel.ITypeDescriptorContext
      description: Parameter description to be filled
    - id: ci
      type: System.Globalization.CultureInfo
      description: Parameter description to be filled
    - id: data
      type: System.Object
      description: Parameter description to be filled
    return:
      type: System.Object
      description: Return description to be filled
- uid: System.Configuration.TimeSpanSecondsOrInfiniteConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  id: ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  parent: System.Configuration.TimeSpanSecondsOrInfiniteConverter
  langs:
  - csharp
  - vb
  name: ConvertTo
  nameWithType: TimeSpanSecondsOrInfiniteConverter.ConvertTo
  fullName: System.Configuration.TimeSpanSecondsOrInfiniteConverter.ConvertTo
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: public override object ConvertTo (System.ComponentModel.ITypeDescriptorContext ctx, System.Globalization.CultureInfo ci, object value, Type type);
    parameters:
    - id: ctx
      type: System.ComponentModel.ITypeDescriptorContext
      description: Parameter description to be filled
    - id: ci
      type: System.Globalization.CultureInfo
      description: Parameter description to be filled
    - id: value
      type: System.Object
      description: Parameter description to be filled
    - id: type
      type: System.Type
      description: Parameter description to be filled
    return:
      type: System.Object
      description: Return description to be filled
references:
- uid: System.Configuration.TimeSpanSecondsConverter
  isExternal: false
  name: System.Configuration.TimeSpanSecondsConverter
- uid: System.Configuration.TimeSpanSecondsOrInfiniteConverter.#ctor
  parent: System.Configuration.TimeSpanSecondsOrInfiniteConverter
  isExternal: false
  name: .ctor
  nameWithType: TimeSpanSecondsOrInfiniteConverter..ctor
  fullName: System.Configuration.TimeSpanSecondsOrInfiniteConverter..ctor
- uid: System.Configuration.TimeSpanSecondsOrInfiniteConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  parent: System.Configuration.TimeSpanSecondsOrInfiniteConverter
  isExternal: false
  name: ConvertFrom
  nameWithType: TimeSpanSecondsOrInfiniteConverter.ConvertFrom
  fullName: System.Configuration.TimeSpanSecondsOrInfiniteConverter.ConvertFrom
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Globalization.CultureInfo
  parent: System.Globalization
  isExternal: false
  name: CultureInfo
  nameWithType: CultureInfo
  fullName: System.Globalization.CultureInfo
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Configuration.TimeSpanSecondsOrInfiniteConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  parent: System.Configuration.TimeSpanSecondsOrInfiniteConverter
  isExternal: false
  name: ConvertTo
  nameWithType: TimeSpanSecondsOrInfiniteConverter.ConvertTo
  fullName: System.Configuration.TimeSpanSecondsOrInfiniteConverter.ConvertTo
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Globalization.CultureInfo
  parent: System.Globalization
  isExternal: false
  name: CultureInfo
  nameWithType: CultureInfo
  fullName: System.Globalization.CultureInfo
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Type
  parent: System
  isExternal: false
  name: Type
  nameWithType: Type
  fullName: System.Type
