### YamlMime:ManagedReference
items:
- uid: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs
  id: StartupEventArgs
  children:
  - Microsoft.VisualBasic.ApplicationServices.StartupEventArgs.#ctor(System.Collections.ObjectModel.ReadOnlyCollection{System.String})
  - Microsoft.VisualBasic.ApplicationServices.StartupEventArgs.CommandLine
  langs:
  - csharp
  - vb
  name: StartupEventArgs
  nameWithType: StartupEventArgs
  fullName: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs
  type: Class
  syntax:
    content: >-
      [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]

      [System.Runtime.InteropServices.ComVisible(false)]

      public class StartupEventArgs : System.ComponentModel.CancelEventArgs
  inheritance:
  - System.ComponentModel.CancelEventArgs
  implements: []
  inheritedMembers: []
- uid: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs.#ctor(System.Collections.ObjectModel.ReadOnlyCollection{System.String})
  id: '#ctor(System.Collections.ObjectModel.ReadOnlyCollection{System.String})'
  parent: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs
  langs:
  - csharp
  - vb
  name: .ctor
  nameWithType: StartupEventArgs..ctor
  fullName: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs..ctor
  type: Constructor
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  syntax:
    content: public StartupEventArgs (System.Collections.ObjectModel.ReadOnlyCollection<string> args);
    parameters:
    - id: args
      type: System.Collections.ObjectModel.ReadOnlyCollection{System.String}
      description: Parameter description to be filled
- uid: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs.CommandLine
  id: CommandLine
  parent: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs
  langs:
  - csharp
  - vb
  name: CommandLine
  nameWithType: StartupEventArgs.CommandLine
  fullName: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs.CommandLine
  type: Property
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  syntax:
    content: public System.Collections.ObjectModel.ReadOnlyCollection<string> CommandLine { get; }
    return:
      type: System.Collections.ObjectModel.ReadOnlyCollection{System.String}
      description: Return description to be filled
references:
- uid: System.ComponentModel.CancelEventArgs
  isExternal: false
  name: System.ComponentModel.CancelEventArgs
- uid: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs.#ctor(System.Collections.ObjectModel.ReadOnlyCollection{System.String})
  parent: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs
  isExternal: false
  name: .ctor
  nameWithType: StartupEventArgs..ctor
  fullName: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs..ctor
- uid: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs.CommandLine
  parent: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs
  isExternal: false
  name: CommandLine
  nameWithType: StartupEventArgs.CommandLine
  fullName: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs.CommandLine
