### YamlMime:ManagedReference
items:
- uid: Microsoft.VisualBasic.ApplicationServices.ShutdownEventHandler
  id: ShutdownEventHandler
  langs:
  - csharp
  - vb
  name: ShutdownEventHandler
  nameWithType: ShutdownEventHandler
  fullName: Microsoft.VisualBasic.ApplicationServices.ShutdownEventHandler
  type: Delegate
  syntax:
    content: >-
      [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]

      public delegate void ShutdownEventHandler(object sender, EventArgs e);
  inheritance:
  - System.Object
  - System.Delegate
references:
- uid: System.Delegate
  isExternal: false
  name: System.Delegate
