### YamlMime:ManagedReference
items:
- uid: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventHandler
  id: StartupNextInstanceEventHandler
  langs:
  - csharp
  name: StartupNextInstanceEventHandler
  nameWithType: StartupNextInstanceEventHandler
  fullName: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventHandler
  type: Delegate
  syntax:
    content: >-
      [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]

      public delegate void StartupNextInstanceEventHandler(object sender, StartupNextInstanceEventArgs e);
  inheritance:
  - System.Object
  - System.Delegate
  platform:
  - net-1.1
  - net-2.0
  - netcore-1.0
references:
- uid: System.Delegate
  isExternal: false
  name: System.Delegate
