### YamlMime:ManagedReference
items:
- uid: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException
  id: NoStartupFormException
  children:
  - Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor
  - Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor(System.String)
  - Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  - vb
  name: NoStartupFormException
  nameWithType: NoStartupFormException
  fullName: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException
  type: Class
  syntax:
    content: >-
      [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]

      public class NoStartupFormException : Exception
  inheritance:
  - System.Object
  - System.Exception
  implements: []
  inheritedMembers:
  - System.Exception.Data
  - System.Exception.GetBaseException
  - System.Exception.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Exception.GetType
  - System.Exception.HelpLink
  - System.Exception.HResult
  - System.Exception.InnerException
  - System.Exception.Message
  - System.Exception.SerializeObjectState
  - System.Exception.Source
  - System.Exception.StackTrace
  - System.Exception.TargetSite
  - System.Exception.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
- uid: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor
  id: '#ctor'
  parent: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException
  langs:
  - csharp
  - vb
  name: .ctor
  nameWithType: NoStartupFormException..ctor
  fullName: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException..ctor
  type: Constructor
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  syntax:
    content: public NoStartupFormException ();
    parameters: []
- uid: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException
  langs:
  - csharp
  - vb
  name: .ctor
  nameWithType: NoStartupFormException..ctor
  fullName: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException..ctor
  type: Constructor
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  syntax:
    content: public NoStartupFormException (string message);
    parameters:
    - id: message
      type: System.String
      description: Parameter description to be filled
- uid: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException
  langs:
  - csharp
  - vb
  name: .ctor
  nameWithType: NoStartupFormException..ctor
  fullName: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException..ctor
  type: Constructor
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  syntax:
    content: protected NoStartupFormException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: Parameter description to be filled
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: Parameter description to be filled
- uid: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException
  langs:
  - csharp
  - vb
  name: .ctor
  nameWithType: NoStartupFormException..ctor
  fullName: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException..ctor
  type: Constructor
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  syntax:
    content: public NoStartupFormException (string message, Exception inner);
    parameters:
    - id: message
      type: System.String
      description: Parameter description to be filled
    - id: inner
      type: System.Exception
      description: Parameter description to be filled
references:
- uid: System.Exception
  isExternal: false
  name: System.Exception
- uid: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor
  parent: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException
  isExternal: false
  name: .ctor
  nameWithType: NoStartupFormException..ctor
  fullName: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException..ctor
- uid: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor(System.String)
  parent: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException
  isExternal: false
  name: .ctor
  nameWithType: NoStartupFormException..ctor
  fullName: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException..ctor
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException
  isExternal: false
  name: .ctor
  nameWithType: NoStartupFormException..ctor
  fullName: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException..ctor
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: false
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor(System.String,System.Exception)
  parent: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException
  isExternal: false
  name: .ctor
  nameWithType: NoStartupFormException..ctor
  fullName: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException..ctor
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Exception
  parent: System
  isExternal: false
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
