### YamlMime:ManagedReference
items:
- uid: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase
  id: ConsoleApplicationBase
  children:
  - Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.#ctor
  - Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.CommandLineArgs
  - Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.Deployment
  - Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.InternalCommandLine
  - Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.IsNetworkDeployed
  langs:
  - csharp
  - vb
  name: ConsoleApplicationBase
  nameWithType: ConsoleApplicationBase
  fullName: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase
  type: Class
  syntax:
    content: 'public class ConsoleApplicationBase : Microsoft.VisualBasic.ApplicationServices.ApplicationBase'
  inheritance:
  - System.Object
  - Microsoft.VisualBasic.ApplicationServices.ApplicationBase
  implements: []
  inheritedMembers:
  - Microsoft.VisualBasic.ApplicationServices.ApplicationBase.ChangeCulture(System.String)
  - Microsoft.VisualBasic.ApplicationServices.ApplicationBase.ChangeUICulture(System.String)
  - Microsoft.VisualBasic.ApplicationServices.ApplicationBase.Culture
  - Microsoft.VisualBasic.ApplicationServices.ApplicationBase.GetEnvironmentVariable(System.String)
  - Microsoft.VisualBasic.ApplicationServices.ApplicationBase.Info
  - Microsoft.VisualBasic.ApplicationServices.ApplicationBase.Log
  - Microsoft.VisualBasic.ApplicationServices.ApplicationBase.UICulture
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.#ctor
  id: '#ctor'
  parent: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase
  langs:
  - csharp
  - vb
  name: .ctor
  nameWithType: ConsoleApplicationBase..ctor
  fullName: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase..ctor
  type: Constructor
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  syntax:
    content: public ConsoleApplicationBase ();
    parameters: []
- uid: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.CommandLineArgs
  id: CommandLineArgs
  parent: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase
  langs:
  - csharp
  - vb
  name: CommandLineArgs
  nameWithType: ConsoleApplicationBase.CommandLineArgs
  fullName: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.CommandLineArgs
  type: Property
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  syntax:
    content: public System.Collections.ObjectModel.ReadOnlyCollection<string> CommandLineArgs { get; }
    return:
      type: System.Collections.ObjectModel.ReadOnlyCollection{System.String}
      description: Return description to be filled
- uid: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.Deployment
  id: Deployment
  parent: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase
  langs:
  - csharp
  - vb
  name: Deployment
  nameWithType: ConsoleApplicationBase.Deployment
  fullName: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.Deployment
  type: Property
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  syntax:
    content: public System.Deployment.Application.ApplicationDeployment Deployment { get; }
    return:
      type: System.Deployment.Application.ApplicationDeployment
      description: Return description to be filled
- uid: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.InternalCommandLine
  id: InternalCommandLine
  parent: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase
  langs:
  - csharp
  - vb
  name: InternalCommandLine
  nameWithType: ConsoleApplicationBase.InternalCommandLine
  fullName: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.InternalCommandLine
  type: Property
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  syntax:
    content: protected System.Collections.ObjectModel.ReadOnlyCollection<string> InternalCommandLine { set; }
    return:
      type: System.Collections.ObjectModel.ReadOnlyCollection{System.String}
      description: Return description to be filled
- uid: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.IsNetworkDeployed
  id: IsNetworkDeployed
  parent: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase
  langs:
  - csharp
  - vb
  name: IsNetworkDeployed
  nameWithType: ConsoleApplicationBase.IsNetworkDeployed
  fullName: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.IsNetworkDeployed
  type: Property
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  syntax:
    content: public bool IsNetworkDeployed { get; }
    return:
      type: System.Boolean
      description: Return description to be filled
references:
- uid: Microsoft.VisualBasic.ApplicationServices.ApplicationBase
  isExternal: false
  name: Microsoft.VisualBasic.ApplicationServices.ApplicationBase
- uid: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.#ctor
  parent: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase
  isExternal: false
  name: .ctor
  nameWithType: ConsoleApplicationBase..ctor
  fullName: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase..ctor
- uid: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.CommandLineArgs
  parent: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase
  isExternal: false
  name: CommandLineArgs
  nameWithType: ConsoleApplicationBase.CommandLineArgs
  fullName: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.CommandLineArgs
- uid: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.Deployment
  parent: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase
  isExternal: false
  name: Deployment
  nameWithType: ConsoleApplicationBase.Deployment
  fullName: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.Deployment
- uid: System.Deployment.Application.ApplicationDeployment
  parent: System.Deployment.Application
  isExternal: false
  name: ApplicationDeployment
  nameWithType: ApplicationDeployment
  fullName: System.Deployment.Application.ApplicationDeployment
- uid: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.InternalCommandLine
  parent: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase
  isExternal: false
  name: InternalCommandLine
  nameWithType: ConsoleApplicationBase.InternalCommandLine
  fullName: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.InternalCommandLine
- uid: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.IsNetworkDeployed
  parent: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase
  isExternal: false
  name: IsNetworkDeployed
  nameWithType: ConsoleApplicationBase.IsNetworkDeployed
  fullName: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.IsNetworkDeployed
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
