### YamlMime:ManagedReference
items:
- uid: Microsoft.Build.Evaluation.ProjectLoadSettings
  id: ProjectLoadSettings
  children:
  - Microsoft.Build.Evaluation.ProjectLoadSettings.Default
  - Microsoft.Build.Evaluation.ProjectLoadSettings.IgnoreMissingImports
  - Microsoft.Build.Evaluation.ProjectLoadSettings.RecordDuplicateButNotCircularImports
  - Microsoft.Build.Evaluation.ProjectLoadSettings.RejectCircularImports
  langs:
  - csharp
  - vb
  name: ProjectLoadSettings
  nameWithType: ProjectLoadSettings
  fullName: Microsoft.Build.Evaluation.ProjectLoadSettings
  type: Enum
  syntax:
    content: >-
      [System.Flags]

      public enum ProjectLoadSettings
  inheritance:
  - System.Object
  - System.ValueType
  - System.Enum
  inheritedMembers:
  - System.Enum.CompareTo(System.Object)
  - System.Enum.Equals(System.Object)
  - System.Enum.Format(System.Type,System.Object,System.String)
  - System.Enum.GetHashCode
  - System.Enum.GetName(System.Type,System.Object)
  - System.Enum.GetNames(System.Type)
  - System.Enum.GetTypeCode
  - System.Enum.GetUnderlyingType(System.Type)
  - System.Enum.GetValues(System.Type)
  - System.Enum.HasFlag(System.Enum)
  - System.Enum.IsDefined(System.Type,System.Object)
  - System.Enum.Parse(System.Type,System.String)
  - System.Enum.Parse(System.Type,System.String,System.Boolean)
  - System.Enum.System#IConvertible#ToBoolean(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToByte(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToChar(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToDateTime(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToDecimal(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToDouble(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToInt16(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToInt32(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToInt64(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToSByte(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToSingle(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToType(System.Type,System.IFormatProvider)
  - System.Enum.System#IConvertible#ToUInt16(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToUInt32(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToUInt64(System.IFormatProvider)
  - System.Enum.ToObject(System.Type,System.Byte)
  - System.Enum.ToObject(System.Type,System.Int16)
  - System.Enum.ToObject(System.Type,System.Int32)
  - System.Enum.ToObject(System.Type,System.Int64)
  - System.Enum.ToObject(System.Type,System.Object)
  - System.Enum.ToObject(System.Type,System.SByte)
  - System.Enum.ToObject(System.Type,System.UInt16)
  - System.Enum.ToObject(System.Type,System.UInt32)
  - System.Enum.ToObject(System.Type,System.UInt64)
  - System.Enum.ToString
  - System.Enum.ToString(System.IFormatProvider)
  - System.Enum.ToString(System.String)
  - System.Enum.ToString(System.String,System.IFormatProvider)
  - System.Enum.TryParse``1(System.String,``0@)
  - System.Enum.TryParse``1(System.String,System.Boolean,``0@)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
- uid: Microsoft.Build.Evaluation.ProjectLoadSettings.Default
  id: Default
  parent: Microsoft.Build.Evaluation.ProjectLoadSettings
  langs:
  - csharp
  - vb
  name: Default
  nameWithType: ProjectLoadSettings.Default
  fullName: Microsoft.Build.Evaluation.ProjectLoadSettings.Default
  type: Field
  assemblies:
  - Microsoft.Build
  namespace: Microsoft.Build.Evaluation
  syntax:
    content: Default
    return:
      type: Microsoft.Build.Evaluation.ProjectLoadSettings
      description: Return description to be filled
- uid: Microsoft.Build.Evaluation.ProjectLoadSettings.IgnoreMissingImports
  id: IgnoreMissingImports
  parent: Microsoft.Build.Evaluation.ProjectLoadSettings
  langs:
  - csharp
  - vb
  name: IgnoreMissingImports
  nameWithType: ProjectLoadSettings.IgnoreMissingImports
  fullName: Microsoft.Build.Evaluation.ProjectLoadSettings.IgnoreMissingImports
  type: Field
  assemblies:
  - Microsoft.Build
  namespace: Microsoft.Build.Evaluation
  syntax:
    content: IgnoreMissingImports
    return:
      type: Microsoft.Build.Evaluation.ProjectLoadSettings
      description: Return description to be filled
- uid: Microsoft.Build.Evaluation.ProjectLoadSettings.RecordDuplicateButNotCircularImports
  id: RecordDuplicateButNotCircularImports
  parent: Microsoft.Build.Evaluation.ProjectLoadSettings
  langs:
  - csharp
  - vb
  name: RecordDuplicateButNotCircularImports
  nameWithType: ProjectLoadSettings.RecordDuplicateButNotCircularImports
  fullName: Microsoft.Build.Evaluation.ProjectLoadSettings.RecordDuplicateButNotCircularImports
  type: Field
  assemblies:
  - Microsoft.Build
  namespace: Microsoft.Build.Evaluation
  syntax:
    content: RecordDuplicateButNotCircularImports
    return:
      type: Microsoft.Build.Evaluation.ProjectLoadSettings
      description: Return description to be filled
- uid: Microsoft.Build.Evaluation.ProjectLoadSettings.RejectCircularImports
  id: RejectCircularImports
  parent: Microsoft.Build.Evaluation.ProjectLoadSettings
  langs:
  - csharp
  - vb
  name: RejectCircularImports
  nameWithType: ProjectLoadSettings.RejectCircularImports
  fullName: Microsoft.Build.Evaluation.ProjectLoadSettings.RejectCircularImports
  type: Field
  assemblies:
  - Microsoft.Build
  namespace: Microsoft.Build.Evaluation
  syntax:
    content: RejectCircularImports
    return:
      type: Microsoft.Build.Evaluation.ProjectLoadSettings
      description: Return description to be filled
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: Microsoft.Build.Evaluation.ProjectLoadSettings.Default
  parent: Microsoft.Build.Evaluation.ProjectLoadSettings
  isExternal: false
  name: Default
  nameWithType: ProjectLoadSettings.Default
  fullName: Microsoft.Build.Evaluation.ProjectLoadSettings.Default
- uid: Microsoft.Build.Evaluation.ProjectLoadSettings
  parent: Microsoft.Build.Evaluation
  isExternal: false
  name: ProjectLoadSettings
  nameWithType: ProjectLoadSettings
  fullName: Microsoft.Build.Evaluation.ProjectLoadSettings
- uid: Microsoft.Build.Evaluation.ProjectLoadSettings.IgnoreMissingImports
  parent: Microsoft.Build.Evaluation.ProjectLoadSettings
  isExternal: false
  name: IgnoreMissingImports
  nameWithType: ProjectLoadSettings.IgnoreMissingImports
  fullName: Microsoft.Build.Evaluation.ProjectLoadSettings.IgnoreMissingImports
- uid: Microsoft.Build.Evaluation.ProjectLoadSettings
  parent: Microsoft.Build.Evaluation
  isExternal: false
  name: ProjectLoadSettings
  nameWithType: ProjectLoadSettings
  fullName: Microsoft.Build.Evaluation.ProjectLoadSettings
- uid: Microsoft.Build.Evaluation.ProjectLoadSettings.RecordDuplicateButNotCircularImports
  parent: Microsoft.Build.Evaluation.ProjectLoadSettings
  isExternal: false
  name: RecordDuplicateButNotCircularImports
  nameWithType: ProjectLoadSettings.RecordDuplicateButNotCircularImports
  fullName: Microsoft.Build.Evaluation.ProjectLoadSettings.RecordDuplicateButNotCircularImports
- uid: Microsoft.Build.Evaluation.ProjectLoadSettings
  parent: Microsoft.Build.Evaluation
  isExternal: false
  name: ProjectLoadSettings
  nameWithType: ProjectLoadSettings
  fullName: Microsoft.Build.Evaluation.ProjectLoadSettings
- uid: Microsoft.Build.Evaluation.ProjectLoadSettings.RejectCircularImports
  parent: Microsoft.Build.Evaluation.ProjectLoadSettings
  isExternal: false
  name: RejectCircularImports
  nameWithType: ProjectLoadSettings.RejectCircularImports
  fullName: Microsoft.Build.Evaluation.ProjectLoadSettings.RejectCircularImports
- uid: Microsoft.Build.Evaluation.ProjectLoadSettings
  parent: Microsoft.Build.Evaluation
  isExternal: false
  name: ProjectLoadSettings
  nameWithType: ProjectLoadSettings
  fullName: Microsoft.Build.Evaluation.ProjectLoadSettings
