### YamlMime:ManagedReference
items:
- uid: System.Data.Common.DbProviderConfigurationHandler
  id: DbProviderConfigurationHandler
  children:
  - System.Data.Common.DbProviderConfigurationHandler.#ctor
  - System.Data.Common.DbProviderConfigurationHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  langs:
  - csharp
  - vb
  name: DbProviderConfigurationHandler
  nameWithType: DbProviderConfigurationHandler
  fullName: System.Data.Common.DbProviderConfigurationHandler
  type: Class
  syntax:
    content: 'public class DbProviderConfigurationHandler : System.Configuration.IConfigurationSectionHandler'
  inheritance:
  - System.Object
  implements:
  - System.Configuration.IConfigurationSectionHandler
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: System.Data.Common.DbProviderConfigurationHandler.#ctor
  id: '#ctor'
  parent: System.Data.Common.DbProviderConfigurationHandler
  langs:
  - csharp
  - vb
  name: .ctor
  nameWithType: DbProviderConfigurationHandler..ctor
  fullName: System.Data.Common.DbProviderConfigurationHandler..ctor
  type: Constructor
  assemblies:
  - System.Data
  namespace: System.Data.Common
  syntax:
    content: public DbProviderConfigurationHandler ();
    parameters: []
- uid: System.Data.Common.DbProviderConfigurationHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  id: Create(System.Object,System.Object,System.Xml.XmlNode)
  parent: System.Data.Common.DbProviderConfigurationHandler
  langs:
  - csharp
  - vb
  name: Create
  nameWithType: DbProviderConfigurationHandler.Create
  fullName: System.Data.Common.DbProviderConfigurationHandler.Create
  type: Method
  assemblies:
  - System.Data
  namespace: System.Data.Common
  syntax:
    content: public virtual object Create (object parent, object configContext, System.Xml.XmlNode section);
    parameters:
    - id: parent
      type: System.Object
      description: Parameter description to be filled
    - id: configContext
      type: System.Object
      description: Parameter description to be filled
    - id: section
      type: System.Xml.XmlNode
      description: Parameter description to be filled
    return:
      type: System.Object
      description: Return description to be filled
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Data.Common.DbProviderConfigurationHandler.#ctor
  parent: System.Data.Common.DbProviderConfigurationHandler
  isExternal: false
  name: .ctor
  nameWithType: DbProviderConfigurationHandler..ctor
  fullName: System.Data.Common.DbProviderConfigurationHandler..ctor
- uid: System.Data.Common.DbProviderConfigurationHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  parent: System.Data.Common.DbProviderConfigurationHandler
  isExternal: false
  name: Create
  nameWithType: DbProviderConfigurationHandler.Create
  fullName: System.Data.Common.DbProviderConfigurationHandler.Create
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
