### YamlMime:ManagedReference
items:
- uid: System.Windows.Input.MouseActionValueSerializer
  id: MouseActionValueSerializer
  children:
  - System.Windows.Input.MouseActionValueSerializer.#ctor
  - System.Windows.Input.MouseActionValueSerializer.CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  - System.Windows.Input.MouseActionValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  - System.Windows.Input.MouseActionValueSerializer.ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  - System.Windows.Input.MouseActionValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  langs:
  - csharp
  name: MouseActionValueSerializer
  nameWithType: MouseActionValueSerializer
  fullName: System.Windows.Input.MouseActionValueSerializer
  type: Class
  summary: Converts instances of <see cref="T:System.String"> to and from instances of <xref:System.Windows.Input.MouseAction>.
  remarks: "This class is typically only utilized by the <xref:System.Windows.Markup.Primitives.MarkupWriter> for serialization purposes.  \n  \n<a name=\"xamlTextUsage_MouseActionValueSerializer\"></a>   \n## XAML Text Usage"
  syntax:
    content: 'public class MouseActionValueSerializer : System.Windows.Markup.ValueSerializer'
  inheritance:
  - System.Windows.Markup.ValueSerializer
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Windows.Input.MouseActionValueSerializer.#ctor
  id: '#ctor'
  parent: System.Windows.Input.MouseActionValueSerializer
  langs:
  - csharp
  name: MouseActionValueSerializer()
  nameWithType: MouseActionValueSerializer.MouseActionValueSerializer()
  fullName: System.Windows.Input.MouseActionValueSerializer.MouseActionValueSerializer()
  type: Constructor
  assemblies:
  - PresentationCore
  namespace: System.Windows.Input
  summary: Initializes a new instance of the <see cref="T:System.Windows.Input.MouseActionValueSerializer"> class.
  remarks: To be added.
  syntax:
    content: public MouseActionValueSerializer ();
    parameters: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Windows.Input.MouseActionValueSerializer.CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  id: CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Input.MouseActionValueSerializer
  langs:
  - csharp
  name: CanConvertFromString(String,IValueSerializerContext)
  nameWithType: MouseActionValueSerializer.CanConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Input.MouseActionValueSerializer.CanConvertFromString(String,IValueSerializerContext)
  type: Method
  assemblies:
  - PresentationCore
  namespace: System.Windows.Input
  summary: Determines if the specified <see cref="T:System.String"> can be convert to an instance of <xref:System.Windows.Input.MouseAction>.
  remarks: To be added.
  syntax:
    content: public override bool CanConvertFromString (string value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.String
      description: String to evaluate for conversion.
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: Context information that is used for conversion.
    return:
      type: System.Boolean
      description: Always returns `true`.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Windows.Input.MouseActionValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  id: CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Input.MouseActionValueSerializer
  langs:
  - csharp
  name: CanConvertToString(Object,IValueSerializerContext)
  nameWithType: MouseActionValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Input.MouseActionValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  type: Method
  assemblies:
  - PresentationCore
  namespace: System.Windows.Input
  summary: Determines if the specified <see cref="T:System.Windows.Input.MouseAction"> can be converted to a <xref:System.String>.
  remarks: To be added.
  syntax:
    content: public override bool CanConvertToString (object value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.Object
      description: The modifier keys to evaluate for conversion.
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: Context information that is used for conversion.
    return:
      type: System.Boolean
      description: '`true` if  can be converted into a <see cref="T:System.String">; otherwise, `false`.'
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Windows.Input.MouseActionValueSerializer.ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  id: ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Input.MouseActionValueSerializer
  langs:
  - csharp
  name: ConvertFromString(String,IValueSerializerContext)
  nameWithType: MouseActionValueSerializer.ConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Input.MouseActionValueSerializer.ConvertFromString(String,IValueSerializerContext)
  type: Method
  assemblies:
  - PresentationCore
  namespace: System.Windows.Input
  summary: Converts a <see cref="T:System.String"> into a <xref:System.Windows.Input.MouseAction>.
  remarks: To be added.
  syntax:
    content: public override object ConvertFromString (string value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.String
      description: The string to convert into a <see cref="T:System.Windows.Input.MouseAction">.
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: Context information that is used for conversion.
    return:
      type: System.Object
      description: A new instance of <see cref="T:System.Windows.Input.MouseAction"> based on the supplied .
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Windows.Input.MouseActionValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  id: ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Input.MouseActionValueSerializer
  langs:
  - csharp
  name: ConvertToString(Object,IValueSerializerContext)
  nameWithType: MouseActionValueSerializer.ConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Input.MouseActionValueSerializer.ConvertToString(Object,IValueSerializerContext)
  type: Method
  assemblies:
  - PresentationCore
  namespace: System.Windows.Input
  summary: Converts an instance of <see cref="T:System.Windows.Input.MouseAction"> to a <xref:System.String>.
  remarks: To be added.
  syntax:
    content: public override string ConvertToString (object value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.Object
      description: The key to convert into a string.
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: Context information that is used for conversion.
    return:
      type: System.String
      description: An invariant string representation of the specified <see cref="T:System.Windows.Input.MouseAction">.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Windows.Markup.ValueSerializer
  isExternal: false
  name: System.Windows.Markup.ValueSerializer
- uid: System.Windows.Input.MouseActionValueSerializer.#ctor
  parent: System.Windows.Input.MouseActionValueSerializer
  isExternal: false
  name: MouseActionValueSerializer()
  nameWithType: MouseActionValueSerializer.MouseActionValueSerializer()
  fullName: System.Windows.Input.MouseActionValueSerializer.MouseActionValueSerializer()
- uid: System.Windows.Input.MouseActionValueSerializer.CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Input.MouseActionValueSerializer
  isExternal: false
  name: CanConvertFromString(String,IValueSerializerContext)
  nameWithType: MouseActionValueSerializer.CanConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Input.MouseActionValueSerializer.CanConvertFromString(String,IValueSerializerContext)
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Windows.Markup.IValueSerializerContext
  parent: System.Windows.Markup
  isExternal: true
  name: IValueSerializerContext
  nameWithType: IValueSerializerContext
  fullName: System.Windows.Markup.IValueSerializerContext
- uid: System.Windows.Input.MouseActionValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Input.MouseActionValueSerializer
  isExternal: false
  name: CanConvertToString(Object,IValueSerializerContext)
  nameWithType: MouseActionValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Input.MouseActionValueSerializer.CanConvertToString(Object,IValueSerializerContext)
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Windows.Markup.IValueSerializerContext
  parent: System.Windows.Markup
  isExternal: true
  name: IValueSerializerContext
  nameWithType: IValueSerializerContext
  fullName: System.Windows.Markup.IValueSerializerContext
- uid: System.Windows.Input.MouseActionValueSerializer.ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Input.MouseActionValueSerializer
  isExternal: false
  name: ConvertFromString(String,IValueSerializerContext)
  nameWithType: MouseActionValueSerializer.ConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Input.MouseActionValueSerializer.ConvertFromString(String,IValueSerializerContext)
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Windows.Markup.IValueSerializerContext
  parent: System.Windows.Markup
  isExternal: true
  name: IValueSerializerContext
  nameWithType: IValueSerializerContext
  fullName: System.Windows.Markup.IValueSerializerContext
- uid: System.Windows.Input.MouseActionValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Input.MouseActionValueSerializer
  isExternal: false
  name: ConvertToString(Object,IValueSerializerContext)
  nameWithType: MouseActionValueSerializer.ConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Input.MouseActionValueSerializer.ConvertToString(Object,IValueSerializerContext)
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Windows.Markup.IValueSerializerContext
  parent: System.Windows.Markup
  isExternal: true
  name: IValueSerializerContext
  nameWithType: IValueSerializerContext
  fullName: System.Windows.Markup.IValueSerializerContext
