### YamlMime:ManagedReference
items:
- uid: System.Security.Permissions.EnvironmentPermission
  id: EnvironmentPermission
  children:
  - System.Security.Permissions.EnvironmentPermission.#ctor(System.Security.Permissions.PermissionState)
  - System.Security.Permissions.EnvironmentPermission.#ctor(System.Security.Permissions.EnvironmentPermissionAccess,System.String)
  - System.Security.Permissions.EnvironmentPermission.AddPathList(System.Security.Permissions.EnvironmentPermissionAccess,System.String)
  - System.Security.Permissions.EnvironmentPermission.Copy
  - System.Security.Permissions.EnvironmentPermission.FromXml(System.Security.SecurityElement)
  - System.Security.Permissions.EnvironmentPermission.GetPathList(System.Security.Permissions.EnvironmentPermissionAccess)
  - System.Security.Permissions.EnvironmentPermission.Intersect(System.Security.IPermission)
  - System.Security.Permissions.EnvironmentPermission.IsSubsetOf(System.Security.IPermission)
  - System.Security.Permissions.EnvironmentPermission.IsUnrestricted
  - System.Security.Permissions.EnvironmentPermission.SetPathList(System.Security.Permissions.EnvironmentPermissionAccess,System.String)
  - System.Security.Permissions.EnvironmentPermission.ToXml
  - System.Security.Permissions.EnvironmentPermission.Union(System.Security.IPermission)
  langs:
  - csharp
  - vb
  name: EnvironmentPermission
  nameWithType: EnvironmentPermission
  fullName: System.Security.Permissions.EnvironmentPermission
  type: Class
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(true)]

      public sealed class EnvironmentPermission : System.Security.CodeAccessPermission, System.Security.Permissions.IUnrestrictedPermission
  inheritance:
  - System.Object
  - System.Security.CodeAccessPermission
  implements:
  - System.Security.Permissions.IUnrestrictedPermission
  inheritedMembers:
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Security.CodeAccessPermission.Assert
  - System.Security.CodeAccessPermission.Demand
  - System.Security.CodeAccessPermission.Deny
  - System.Security.CodeAccessPermission.Equals(System.Object)
  - System.Security.CodeAccessPermission.GetHashCode
  - System.Security.CodeAccessPermission.PermitOnly
  - System.Security.CodeAccessPermission.RevertAll
  - System.Security.CodeAccessPermission.RevertAssert
  - System.Security.CodeAccessPermission.RevertDeny
  - System.Security.CodeAccessPermission.RevertPermitOnly
  - System.Security.CodeAccessPermission.ToString
- uid: System.Security.Permissions.EnvironmentPermission.#ctor(System.Security.Permissions.PermissionState)
  id: '#ctor(System.Security.Permissions.PermissionState)'
  parent: System.Security.Permissions.EnvironmentPermission
  langs:
  - csharp
  - vb
  name: .ctor
  nameWithType: EnvironmentPermission..ctor
  fullName: System.Security.Permissions.EnvironmentPermission..ctor
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System.Security.Permissions
  syntax:
    content: public EnvironmentPermission (System.Security.Permissions.PermissionState state);
    parameters:
    - id: state
      type: System.Security.Permissions.PermissionState
      description: Parameter description to be filled
- uid: System.Security.Permissions.EnvironmentPermission.#ctor(System.Security.Permissions.EnvironmentPermissionAccess,System.String)
  id: '#ctor(System.Security.Permissions.EnvironmentPermissionAccess,System.String)'
  parent: System.Security.Permissions.EnvironmentPermission
  langs:
  - csharp
  - vb
  name: .ctor
  nameWithType: EnvironmentPermission..ctor
  fullName: System.Security.Permissions.EnvironmentPermission..ctor
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System.Security.Permissions
  syntax:
    content: public EnvironmentPermission (System.Security.Permissions.EnvironmentPermissionAccess flag, string pathList);
    parameters:
    - id: flag
      type: System.Security.Permissions.EnvironmentPermissionAccess
      description: Parameter description to be filled
    - id: pathList
      type: System.String
      description: Parameter description to be filled
- uid: System.Security.Permissions.EnvironmentPermission.AddPathList(System.Security.Permissions.EnvironmentPermissionAccess,System.String)
  id: AddPathList(System.Security.Permissions.EnvironmentPermissionAccess,System.String)
  parent: System.Security.Permissions.EnvironmentPermission
  langs:
  - csharp
  - vb
  name: AddPathList
  nameWithType: EnvironmentPermission.AddPathList
  fullName: System.Security.Permissions.EnvironmentPermission.AddPathList
  type: Method
  assemblies:
  - mscorlib
  namespace: System.Security.Permissions
  syntax:
    content: public void AddPathList (System.Security.Permissions.EnvironmentPermissionAccess flag, string pathList);
    parameters:
    - id: flag
      type: System.Security.Permissions.EnvironmentPermissionAccess
      description: Parameter description to be filled
    - id: pathList
      type: System.String
      description: Parameter description to be filled
    return:
      type: System.Void
      description: Return description to be filled
- uid: System.Security.Permissions.EnvironmentPermission.Copy
  id: Copy
  parent: System.Security.Permissions.EnvironmentPermission
  langs:
  - csharp
  - vb
  name: Copy
  nameWithType: EnvironmentPermission.Copy
  fullName: System.Security.Permissions.EnvironmentPermission.Copy
  type: Method
  assemblies:
  - mscorlib
  namespace: System.Security.Permissions
  syntax:
    content: public override System.Security.IPermission Copy ();
    parameters: []
    return:
      type: System.Security.IPermission
      description: Return description to be filled
- uid: System.Security.Permissions.EnvironmentPermission.FromXml(System.Security.SecurityElement)
  id: FromXml(System.Security.SecurityElement)
  parent: System.Security.Permissions.EnvironmentPermission
  langs:
  - csharp
  - vb
  name: FromXml
  nameWithType: EnvironmentPermission.FromXml
  fullName: System.Security.Permissions.EnvironmentPermission.FromXml
  type: Method
  assemblies:
  - mscorlib
  namespace: System.Security.Permissions
  syntax:
    content: public override void FromXml (System.Security.SecurityElement esd);
    parameters:
    - id: esd
      type: System.Security.SecurityElement
      description: Parameter description to be filled
    return:
      type: System.Void
      description: Return description to be filled
- uid: System.Security.Permissions.EnvironmentPermission.GetPathList(System.Security.Permissions.EnvironmentPermissionAccess)
  id: GetPathList(System.Security.Permissions.EnvironmentPermissionAccess)
  parent: System.Security.Permissions.EnvironmentPermission
  langs:
  - csharp
  - vb
  name: GetPathList
  nameWithType: EnvironmentPermission.GetPathList
  fullName: System.Security.Permissions.EnvironmentPermission.GetPathList
  type: Method
  assemblies:
  - mscorlib
  namespace: System.Security.Permissions
  syntax:
    content: public string GetPathList (System.Security.Permissions.EnvironmentPermissionAccess flag);
    parameters:
    - id: flag
      type: System.Security.Permissions.EnvironmentPermissionAccess
      description: Parameter description to be filled
    return:
      type: System.String
      description: Return description to be filled
- uid: System.Security.Permissions.EnvironmentPermission.Intersect(System.Security.IPermission)
  id: Intersect(System.Security.IPermission)
  parent: System.Security.Permissions.EnvironmentPermission
  langs:
  - csharp
  - vb
  name: Intersect
  nameWithType: EnvironmentPermission.Intersect
  fullName: System.Security.Permissions.EnvironmentPermission.Intersect
  type: Method
  assemblies:
  - mscorlib
  namespace: System.Security.Permissions
  syntax:
    content: public override System.Security.IPermission Intersect (System.Security.IPermission target);
    parameters:
    - id: target
      type: System.Security.IPermission
      description: Parameter description to be filled
    return:
      type: System.Security.IPermission
      description: Return description to be filled
- uid: System.Security.Permissions.EnvironmentPermission.IsSubsetOf(System.Security.IPermission)
  id: IsSubsetOf(System.Security.IPermission)
  parent: System.Security.Permissions.EnvironmentPermission
  langs:
  - csharp
  - vb
  name: IsSubsetOf
  nameWithType: EnvironmentPermission.IsSubsetOf
  fullName: System.Security.Permissions.EnvironmentPermission.IsSubsetOf
  type: Method
  assemblies:
  - mscorlib
  namespace: System.Security.Permissions
  syntax:
    content: public override bool IsSubsetOf (System.Security.IPermission target);
    parameters:
    - id: target
      type: System.Security.IPermission
      description: Parameter description to be filled
    return:
      type: System.Boolean
      description: Return description to be filled
- uid: System.Security.Permissions.EnvironmentPermission.IsUnrestricted
  id: IsUnrestricted
  parent: System.Security.Permissions.EnvironmentPermission
  langs:
  - csharp
  - vb
  name: IsUnrestricted
  nameWithType: EnvironmentPermission.IsUnrestricted
  fullName: System.Security.Permissions.EnvironmentPermission.IsUnrestricted
  type: Method
  assemblies:
  - mscorlib
  namespace: System.Security.Permissions
  syntax:
    content: public bool IsUnrestricted ();
    parameters: []
    return:
      type: System.Boolean
      description: Return description to be filled
- uid: System.Security.Permissions.EnvironmentPermission.SetPathList(System.Security.Permissions.EnvironmentPermissionAccess,System.String)
  id: SetPathList(System.Security.Permissions.EnvironmentPermissionAccess,System.String)
  parent: System.Security.Permissions.EnvironmentPermission
  langs:
  - csharp
  - vb
  name: SetPathList
  nameWithType: EnvironmentPermission.SetPathList
  fullName: System.Security.Permissions.EnvironmentPermission.SetPathList
  type: Method
  assemblies:
  - mscorlib
  namespace: System.Security.Permissions
  syntax:
    content: public void SetPathList (System.Security.Permissions.EnvironmentPermissionAccess flag, string pathList);
    parameters:
    - id: flag
      type: System.Security.Permissions.EnvironmentPermissionAccess
      description: Parameter description to be filled
    - id: pathList
      type: System.String
      description: Parameter description to be filled
    return:
      type: System.Void
      description: Return description to be filled
- uid: System.Security.Permissions.EnvironmentPermission.ToXml
  id: ToXml
  parent: System.Security.Permissions.EnvironmentPermission
  langs:
  - csharp
  - vb
  name: ToXml
  nameWithType: EnvironmentPermission.ToXml
  fullName: System.Security.Permissions.EnvironmentPermission.ToXml
  type: Method
  assemblies:
  - mscorlib
  namespace: System.Security.Permissions
  syntax:
    content: public override System.Security.SecurityElement ToXml ();
    parameters: []
    return:
      type: System.Security.SecurityElement
      description: Return description to be filled
- uid: System.Security.Permissions.EnvironmentPermission.Union(System.Security.IPermission)
  id: Union(System.Security.IPermission)
  parent: System.Security.Permissions.EnvironmentPermission
  langs:
  - csharp
  - vb
  name: Union
  nameWithType: EnvironmentPermission.Union
  fullName: System.Security.Permissions.EnvironmentPermission.Union
  type: Method
  assemblies:
  - mscorlib
  namespace: System.Security.Permissions
  syntax:
    content: public override System.Security.IPermission Union (System.Security.IPermission other);
    parameters:
    - id: other
      type: System.Security.IPermission
      description: Parameter description to be filled
    return:
      type: System.Security.IPermission
      description: Return description to be filled
references:
- uid: System.Security.CodeAccessPermission
  isExternal: false
  name: System.Security.CodeAccessPermission
- uid: System.Security.Permissions.EnvironmentPermission.#ctor(System.Security.Permissions.PermissionState)
  parent: System.Security.Permissions.EnvironmentPermission
  isExternal: false
  name: .ctor
  nameWithType: EnvironmentPermission..ctor
  fullName: System.Security.Permissions.EnvironmentPermission..ctor
- uid: System.Security.Permissions.PermissionState
  parent: System.Security.Permissions
  isExternal: false
  name: PermissionState
  nameWithType: PermissionState
  fullName: System.Security.Permissions.PermissionState
- uid: System.Security.Permissions.EnvironmentPermission.#ctor(System.Security.Permissions.EnvironmentPermissionAccess,System.String)
  parent: System.Security.Permissions.EnvironmentPermission
  isExternal: false
  name: .ctor
  nameWithType: EnvironmentPermission..ctor
  fullName: System.Security.Permissions.EnvironmentPermission..ctor
- uid: System.Security.Permissions.EnvironmentPermissionAccess
  parent: System.Security.Permissions
  isExternal: false
  name: EnvironmentPermissionAccess
  nameWithType: EnvironmentPermissionAccess
  fullName: System.Security.Permissions.EnvironmentPermissionAccess
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Security.Permissions.EnvironmentPermission.AddPathList(System.Security.Permissions.EnvironmentPermissionAccess,System.String)
  parent: System.Security.Permissions.EnvironmentPermission
  isExternal: false
  name: AddPathList
  nameWithType: EnvironmentPermission.AddPathList
  fullName: System.Security.Permissions.EnvironmentPermission.AddPathList
- uid: System.Void
  parent: System
  isExternal: false
  name: Void
  nameWithType: Void
  fullName: System.Void
- uid: System.Security.Permissions.EnvironmentPermissionAccess
  parent: System.Security.Permissions
  isExternal: false
  name: EnvironmentPermissionAccess
  nameWithType: EnvironmentPermissionAccess
  fullName: System.Security.Permissions.EnvironmentPermissionAccess
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Security.Permissions.EnvironmentPermission.Copy
  parent: System.Security.Permissions.EnvironmentPermission
  isExternal: false
  name: Copy
  nameWithType: EnvironmentPermission.Copy
  fullName: System.Security.Permissions.EnvironmentPermission.Copy
- uid: System.Security.IPermission
  parent: System.Security
  isExternal: false
  name: IPermission
  nameWithType: IPermission
  fullName: System.Security.IPermission
- uid: System.Security.Permissions.EnvironmentPermission.FromXml(System.Security.SecurityElement)
  parent: System.Security.Permissions.EnvironmentPermission
  isExternal: false
  name: FromXml
  nameWithType: EnvironmentPermission.FromXml
  fullName: System.Security.Permissions.EnvironmentPermission.FromXml
- uid: System.Void
  parent: System
  isExternal: false
  name: Void
  nameWithType: Void
  fullName: System.Void
- uid: System.Security.SecurityElement
  parent: System.Security
  isExternal: false
  name: SecurityElement
  nameWithType: SecurityElement
  fullName: System.Security.SecurityElement
- uid: System.Security.Permissions.EnvironmentPermission.GetPathList(System.Security.Permissions.EnvironmentPermissionAccess)
  parent: System.Security.Permissions.EnvironmentPermission
  isExternal: false
  name: GetPathList
  nameWithType: EnvironmentPermission.GetPathList
  fullName: System.Security.Permissions.EnvironmentPermission.GetPathList
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Security.Permissions.EnvironmentPermissionAccess
  parent: System.Security.Permissions
  isExternal: false
  name: EnvironmentPermissionAccess
  nameWithType: EnvironmentPermissionAccess
  fullName: System.Security.Permissions.EnvironmentPermissionAccess
- uid: System.Security.Permissions.EnvironmentPermission.Intersect(System.Security.IPermission)
  parent: System.Security.Permissions.EnvironmentPermission
  isExternal: false
  name: Intersect
  nameWithType: EnvironmentPermission.Intersect
  fullName: System.Security.Permissions.EnvironmentPermission.Intersect
- uid: System.Security.IPermission
  parent: System.Security
  isExternal: false
  name: IPermission
  nameWithType: IPermission
  fullName: System.Security.IPermission
- uid: System.Security.IPermission
  parent: System.Security
  isExternal: false
  name: IPermission
  nameWithType: IPermission
  fullName: System.Security.IPermission
- uid: System.Security.Permissions.EnvironmentPermission.IsSubsetOf(System.Security.IPermission)
  parent: System.Security.Permissions.EnvironmentPermission
  isExternal: false
  name: IsSubsetOf
  nameWithType: EnvironmentPermission.IsSubsetOf
  fullName: System.Security.Permissions.EnvironmentPermission.IsSubsetOf
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Security.IPermission
  parent: System.Security
  isExternal: false
  name: IPermission
  nameWithType: IPermission
  fullName: System.Security.IPermission
- uid: System.Security.Permissions.EnvironmentPermission.IsUnrestricted
  parent: System.Security.Permissions.EnvironmentPermission
  isExternal: false
  name: IsUnrestricted
  nameWithType: EnvironmentPermission.IsUnrestricted
  fullName: System.Security.Permissions.EnvironmentPermission.IsUnrestricted
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Security.Permissions.EnvironmentPermission.SetPathList(System.Security.Permissions.EnvironmentPermissionAccess,System.String)
  parent: System.Security.Permissions.EnvironmentPermission
  isExternal: false
  name: SetPathList
  nameWithType: EnvironmentPermission.SetPathList
  fullName: System.Security.Permissions.EnvironmentPermission.SetPathList
- uid: System.Void
  parent: System
  isExternal: false
  name: Void
  nameWithType: Void
  fullName: System.Void
- uid: System.Security.Permissions.EnvironmentPermissionAccess
  parent: System.Security.Permissions
  isExternal: false
  name: EnvironmentPermissionAccess
  nameWithType: EnvironmentPermissionAccess
  fullName: System.Security.Permissions.EnvironmentPermissionAccess
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Security.Permissions.EnvironmentPermission.ToXml
  parent: System.Security.Permissions.EnvironmentPermission
  isExternal: false
  name: ToXml
  nameWithType: EnvironmentPermission.ToXml
  fullName: System.Security.Permissions.EnvironmentPermission.ToXml
- uid: System.Security.SecurityElement
  parent: System.Security
  isExternal: false
  name: SecurityElement
  nameWithType: SecurityElement
  fullName: System.Security.SecurityElement
- uid: System.Security.Permissions.EnvironmentPermission.Union(System.Security.IPermission)
  parent: System.Security.Permissions.EnvironmentPermission
  isExternal: false
  name: Union
  nameWithType: EnvironmentPermission.Union
  fullName: System.Security.Permissions.EnvironmentPermission.Union
- uid: System.Security.IPermission
  parent: System.Security
  isExternal: false
  name: IPermission
  nameWithType: IPermission
  fullName: System.Security.IPermission
- uid: System.Security.IPermission
  parent: System.Security
  isExternal: false
  name: IPermission
  nameWithType: IPermission
  fullName: System.Security.IPermission
