### YamlMime:ManagedReference
items:
- uid: System.Activities.Presentation.PropertyEditing.PropertyValueSource
  id: PropertyValueSource
  children:
  - System.Activities.Presentation.PropertyEditing.PropertyValueSource.#ctor
  langs:
  - csharp
  - vb
  name: PropertyValueSource
  nameWithType: PropertyValueSource
  fullName: System.Activities.Presentation.PropertyEditing.PropertyValueSource
  type: Class
  syntax:
    content: public abstract class PropertyValueSource
  inheritance:
  - System.Object
  implements: []
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: System.Activities.Presentation.PropertyEditing.PropertyValueSource.#ctor
  id: '#ctor'
  parent: System.Activities.Presentation.PropertyEditing.PropertyValueSource
  langs:
  - csharp
  - vb
  name: .ctor
  nameWithType: PropertyValueSource..ctor
  fullName: System.Activities.Presentation.PropertyEditing.PropertyValueSource..ctor
  type: Constructor
  assemblies:
  - System.Activities.Presentation
  namespace: System.Activities.Presentation.PropertyEditing
  syntax:
    content: protected PropertyValueSource ();
    parameters: []
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Activities.Presentation.PropertyEditing.PropertyValueSource.#ctor
  parent: System.Activities.Presentation.PropertyEditing.PropertyValueSource
  isExternal: false
  name: .ctor
  nameWithType: PropertyValueSource..ctor
  fullName: System.Activities.Presentation.PropertyEditing.PropertyValueSource..ctor
