### YamlMime:ManagedReference
items:
- uid: System.Activities.XamlIntegration.IValueSerializableExpression
  id: IValueSerializableExpression
  children:
  - System.Activities.XamlIntegration.IValueSerializableExpression.CanConvertToString(System.Windows.Markup.IValueSerializerContext)
  - System.Activities.XamlIntegration.IValueSerializableExpression.ConvertToString(System.Windows.Markup.IValueSerializerContext)
  langs:
  - csharp
  name: IValueSerializableExpression
  nameWithType: IValueSerializableExpression
  fullName: System.Activities.XamlIntegration.IValueSerializableExpression
  type: Interface
  syntax:
    content: public interface IValueSerializableExpression
  implements: []
  platform:
  - net-1.1
  - net-2.0
  - netcore-1.0
- uid: System.Activities.XamlIntegration.IValueSerializableExpression.CanConvertToString(System.Windows.Markup.IValueSerializerContext)
  id: CanConvertToString(System.Windows.Markup.IValueSerializerContext)
  parent: System.Activities.XamlIntegration.IValueSerializableExpression
  langs:
  - csharp
  name: CanConvertToString(IValueSerializerContext)
  nameWithType: IValueSerializableExpression.CanConvertToString(IValueSerializerContext)
  fullName: System.Activities.XamlIntegration.IValueSerializableExpression.CanConvertToString(IValueSerializerContext)
  type: Method
  assemblies:
  - System.Activities
  namespace: System.Activities.XamlIntegration
  syntax:
    content: public bool CanConvertToString (System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: Parameter description to be filled
    return:
      type: System.Boolean
      description: Return description to be filled
  platform:
  - net-1.1
  - net-2.0
  - netcore-1.0
- uid: System.Activities.XamlIntegration.IValueSerializableExpression.ConvertToString(System.Windows.Markup.IValueSerializerContext)
  id: ConvertToString(System.Windows.Markup.IValueSerializerContext)
  parent: System.Activities.XamlIntegration.IValueSerializableExpression
  langs:
  - csharp
  name: ConvertToString(IValueSerializerContext)
  nameWithType: IValueSerializableExpression.ConvertToString(IValueSerializerContext)
  fullName: System.Activities.XamlIntegration.IValueSerializableExpression.ConvertToString(IValueSerializerContext)
  type: Method
  assemblies:
  - System.Activities
  namespace: System.Activities.XamlIntegration
  syntax:
    content: public string ConvertToString (System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: Parameter description to be filled
    return:
      type: System.String
      description: Return description to be filled
  platform:
  - net-1.1
  - net-2.0
  - netcore-1.0
references:
- uid: System.Activities.XamlIntegration.IValueSerializableExpression.CanConvertToString(System.Windows.Markup.IValueSerializerContext)
  parent: System.Activities.XamlIntegration.IValueSerializableExpression
  isExternal: false
  name: CanConvertToString(IValueSerializerContext)
  nameWithType: IValueSerializableExpression.CanConvertToString(IValueSerializerContext)
  fullName: System.Activities.XamlIntegration.IValueSerializableExpression.CanConvertToString(IValueSerializerContext)
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Activities.XamlIntegration.IValueSerializableExpression.ConvertToString(System.Windows.Markup.IValueSerializerContext)
  parent: System.Activities.XamlIntegration.IValueSerializableExpression
  isExternal: false
  name: ConvertToString(IValueSerializerContext)
  nameWithType: IValueSerializableExpression.ConvertToString(IValueSerializerContext)
  fullName: System.Activities.XamlIntegration.IValueSerializableExpression.ConvertToString(IValueSerializerContext)
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
