### YamlMime:ManagedReference
items:
- uid: System.Activities.XamlIntegration.IValueSerializableExpression
  id: IValueSerializableExpression
  children:
  - System.Activities.XamlIntegration.IValueSerializableExpression.CanConvertToString(System.Windows.Markup.IValueSerializerContext)
  - System.Activities.XamlIntegration.IValueSerializableExpression.ConvertToString(System.Windows.Markup.IValueSerializerContext)
  langs:
  - csharp
  - vb
  name: IValueSerializableExpression
  nameWithType: IValueSerializableExpression
  fullName: System.Activities.XamlIntegration.IValueSerializableExpression
  type: Interface
  syntax:
    content: public interface IValueSerializableExpression
  implements: []
- uid: System.Activities.XamlIntegration.IValueSerializableExpression.CanConvertToString(System.Windows.Markup.IValueSerializerContext)
  id: CanConvertToString(System.Windows.Markup.IValueSerializerContext)
  parent: System.Activities.XamlIntegration.IValueSerializableExpression
  langs:
  - csharp
  - vb
  name: CanConvertToString
  nameWithType: IValueSerializableExpression.CanConvertToString
  fullName: System.Activities.XamlIntegration.IValueSerializableExpression.CanConvertToString
  type: Method
  assemblies:
  - System.Activities
  namespace: System.Activities.XamlIntegration
  syntax:
    content: public bool CanConvertToString (System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: Parameter description to be filled
    return:
      type: System.Boolean
      description: Return description to be filled
- uid: System.Activities.XamlIntegration.IValueSerializableExpression.ConvertToString(System.Windows.Markup.IValueSerializerContext)
  id: ConvertToString(System.Windows.Markup.IValueSerializerContext)
  parent: System.Activities.XamlIntegration.IValueSerializableExpression
  langs:
  - csharp
  - vb
  name: ConvertToString
  nameWithType: IValueSerializableExpression.ConvertToString
  fullName: System.Activities.XamlIntegration.IValueSerializableExpression.ConvertToString
  type: Method
  assemblies:
  - System.Activities
  namespace: System.Activities.XamlIntegration
  syntax:
    content: public string ConvertToString (System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: Parameter description to be filled
    return:
      type: System.String
      description: Return description to be filled
references:
- uid: System.Activities.XamlIntegration.IValueSerializableExpression.CanConvertToString(System.Windows.Markup.IValueSerializerContext)
  parent: System.Activities.XamlIntegration.IValueSerializableExpression
  isExternal: false
  name: CanConvertToString
  nameWithType: IValueSerializableExpression.CanConvertToString
  fullName: System.Activities.XamlIntegration.IValueSerializableExpression.CanConvertToString
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Activities.XamlIntegration.IValueSerializableExpression.ConvertToString(System.Windows.Markup.IValueSerializerContext)
  parent: System.Activities.XamlIntegration.IValueSerializableExpression
  isExternal: false
  name: ConvertToString
  nameWithType: IValueSerializableExpression.ConvertToString
  fullName: System.Activities.XamlIntegration.IValueSerializableExpression.ConvertToString
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
