### YamlMime:ManagedReference
items:
- uid: System.Activities.XamlIntegration.ArgumentValueSerializer
  id: ArgumentValueSerializer
  children:
  - System.Activities.XamlIntegration.ArgumentValueSerializer.#ctor
  - System.Activities.XamlIntegration.ArgumentValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  - System.Activities.XamlIntegration.ArgumentValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  langs:
  - csharp
  - vb
  name: ArgumentValueSerializer
  nameWithType: ArgumentValueSerializer
  fullName: System.Activities.XamlIntegration.ArgumentValueSerializer
  type: Class
  syntax:
    content: 'public class ArgumentValueSerializer : System.Windows.Markup.ValueSerializer'
  inheritance:
  - System.Windows.Markup.ValueSerializer
  implements: []
  inheritedMembers: []
- uid: System.Activities.XamlIntegration.ArgumentValueSerializer.#ctor
  id: '#ctor'
  parent: System.Activities.XamlIntegration.ArgumentValueSerializer
  langs:
  - csharp
  - vb
  name: .ctor
  nameWithType: ArgumentValueSerializer..ctor
  fullName: System.Activities.XamlIntegration.ArgumentValueSerializer..ctor
  type: Constructor
  assemblies:
  - System.Activities
  namespace: System.Activities.XamlIntegration
  syntax:
    content: public ArgumentValueSerializer ();
    parameters: []
- uid: System.Activities.XamlIntegration.ArgumentValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  id: CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Activities.XamlIntegration.ArgumentValueSerializer
  langs:
  - csharp
  - vb
  name: CanConvertToString
  nameWithType: ArgumentValueSerializer.CanConvertToString
  fullName: System.Activities.XamlIntegration.ArgumentValueSerializer.CanConvertToString
  type: Method
  assemblies:
  - System.Activities
  namespace: System.Activities.XamlIntegration
  syntax:
    content: public override bool CanConvertToString (object value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.Object
      description: Parameter description to be filled
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: Parameter description to be filled
    return:
      type: System.Boolean
      description: Return description to be filled
- uid: System.Activities.XamlIntegration.ArgumentValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  id: ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Activities.XamlIntegration.ArgumentValueSerializer
  langs:
  - csharp
  - vb
  name: ConvertToString
  nameWithType: ArgumentValueSerializer.ConvertToString
  fullName: System.Activities.XamlIntegration.ArgumentValueSerializer.ConvertToString
  type: Method
  assemblies:
  - System.Activities
  namespace: System.Activities.XamlIntegration
  syntax:
    content: public override string ConvertToString (object value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.Object
      description: Parameter description to be filled
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: Parameter description to be filled
    return:
      type: System.String
      description: Return description to be filled
references:
- uid: System.Windows.Markup.ValueSerializer
  isExternal: false
  name: System.Windows.Markup.ValueSerializer
- uid: System.Activities.XamlIntegration.ArgumentValueSerializer.#ctor
  parent: System.Activities.XamlIntegration.ArgumentValueSerializer
  isExternal: false
  name: .ctor
  nameWithType: ArgumentValueSerializer..ctor
  fullName: System.Activities.XamlIntegration.ArgumentValueSerializer..ctor
- uid: System.Activities.XamlIntegration.ArgumentValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Activities.XamlIntegration.ArgumentValueSerializer
  isExternal: false
  name: CanConvertToString
  nameWithType: ArgumentValueSerializer.CanConvertToString
  fullName: System.Activities.XamlIntegration.ArgumentValueSerializer.CanConvertToString
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Activities.XamlIntegration.ArgumentValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Activities.XamlIntegration.ArgumentValueSerializer
  isExternal: false
  name: ConvertToString
  nameWithType: ArgumentValueSerializer.ConvertToString
  fullName: System.Activities.XamlIntegration.ArgumentValueSerializer.ConvertToString
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
