### YamlMime:ManagedReference
items:
- uid: System.Activities.Validation.ValidationSettings
  id: ValidationSettings
  children:
  - System.Activities.Validation.ValidationSettings.#ctor
  - System.Activities.Validation.ValidationSettings.AdditionalConstraints
  - System.Activities.Validation.ValidationSettings.CancellationToken
  - System.Activities.Validation.ValidationSettings.Environment
  - System.Activities.Validation.ValidationSettings.OnlyUseAdditionalConstraints
  - System.Activities.Validation.ValidationSettings.PrepareForRuntime
  - System.Activities.Validation.ValidationSettings.SingleLevel
  - System.Activities.Validation.ValidationSettings.SkipValidatingRootConfiguration
  langs:
  - csharp
  name: ValidationSettings
  nameWithType: ValidationSettings
  fullName: System.Activities.Validation.ValidationSettings
  type: Class
  summary: Represents a collection of settings that customize the behavior that <xref:System.Activities.Validation.ActivityValidationServices.Validate%2A> will exhibit. It also enables the activity user to apply policy constraints to a workflow.
  remarks: To be added.
  syntax:
    content: public class ValidationSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Activities.Validation.ValidationSettings.#ctor
  id: '#ctor'
  parent: System.Activities.Validation.ValidationSettings
  langs:
  - csharp
  name: ValidationSettings()
  nameWithType: ValidationSettings.ValidationSettings()
  fullName: System.Activities.Validation.ValidationSettings.ValidationSettings()
  type: Constructor
  assemblies:
  - System.Activities
  namespace: System.Activities.Validation
  summary: Creates a new instance of the <see cref="T:System.Activities.Validation.ValidationSettings"> class.
  remarks: To be added.
  syntax:
    content: public ValidationSettings ();
    parameters: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Activities.Validation.ValidationSettings.AdditionalConstraints
  id: AdditionalConstraints
  parent: System.Activities.Validation.ValidationSettings
  langs:
  - csharp
  name: AdditionalConstraints
  nameWithType: ValidationSettings.AdditionalConstraints
  fullName: System.Activities.Validation.ValidationSettings.AdditionalConstraints
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities.Validation
  summary: Gets a  dictionary of type-constraint pairs. Each additional constraint added to the dictionary will be applied to every activity of the specify type in the workflow to validate.
  remarks: To be added.
  syntax:
    content: public System.Collections.Generic.IDictionary<Type,System.Collections.Generic.IList<System.Activities.Validation.Constraint>> AdditionalConstraints { get; }
    return:
      type: System.Collections.Generic.IDictionary{System.Type,System.Collections.Generic.IList{System.Activities.Validation.Constraint}}
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Activities.Validation.ValidationSettings.CancellationToken
  id: CancellationToken
  parent: System.Activities.Validation.ValidationSettings
  langs:
  - csharp
  name: CancellationToken
  nameWithType: ValidationSettings.CancellationToken
  fullName: System.Activities.Validation.ValidationSettings.CancellationToken
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities.Validation
  summary: Gets or sets the cancellation token used to notify should the activity be cancelled.
  remarks: To be added.
  syntax:
    content: public System.Threading.CancellationToken CancellationToken { get; set; }
    return:
      type: System.Threading.CancellationToken
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Activities.Validation.ValidationSettings.Environment
  id: Environment
  parent: System.Activities.Validation.ValidationSettings
  langs:
  - csharp
  name: Environment
  nameWithType: ValidationSettings.Environment
  fullName: System.Activities.Validation.ValidationSettings.Environment
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities.Validation
  summary: Gets or sets the environment of variables and arguments associated with this validation settings.
  remarks: To be added.
  syntax:
    content: public System.Activities.LocationReferenceEnvironment Environment { get; set; }
    return:
      type: System.Activities.LocationReferenceEnvironment
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Activities.Validation.ValidationSettings.OnlyUseAdditionalConstraints
  id: OnlyUseAdditionalConstraints
  parent: System.Activities.Validation.ValidationSettings
  langs:
  - csharp
  name: OnlyUseAdditionalConstraints
  nameWithType: ValidationSettings.OnlyUseAdditionalConstraints
  fullName: System.Activities.Validation.ValidationSettings.OnlyUseAdditionalConstraints
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities.Validation
  summary: Gets or sets a value that indicates whether the additional validation constraints are to be used exclusively to validate the workflow. If set to `true`, all the validation contained inside the activity itself will be ignored.
  remarks: <xref:System.Activities.Validation.ActivityValidationServices.Validate%2A> is called whenever a workflow is executed, and and any resulting errors will cause a <xref:System.Activities.InvalidWorkflowException> to be thrown.
  syntax:
    content: public bool OnlyUseAdditionalConstraints { get; set; }
    return:
      type: System.Boolean
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Activities.Validation.ValidationSettings.PrepareForRuntime
  id: PrepareForRuntime
  parent: System.Activities.Validation.ValidationSettings
  langs:
  - csharp
  name: PrepareForRuntime
  nameWithType: ValidationSettings.PrepareForRuntime
  fullName: System.Activities.Validation.ValidationSettings.PrepareForRuntime
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities.Validation
  summary: Gets or sets a value that indicates whether this instance is prepared for runtime.
  remarks: To be added.
  syntax:
    content: public bool PrepareForRuntime { get; set; }
    return:
      type: System.Boolean
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Activities.Validation.ValidationSettings.SingleLevel
  id: SingleLevel
  parent: System.Activities.Validation.ValidationSettings
  langs:
  - csharp
  name: SingleLevel
  nameWithType: ValidationSettings.SingleLevel
  fullName: System.Activities.Validation.ValidationSettings.SingleLevel
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities.Validation
  summary: Gets or sets a value that indicates whether the supplied activity and all the children and sub-children of the supplied activity are validated, or if the validator should validate only to the supplied activity.
  remarks: To be added.
  syntax:
    content: public bool SingleLevel { get; set; }
    return:
      type: System.Boolean
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Activities.Validation.ValidationSettings.SkipValidatingRootConfiguration
  id: SkipValidatingRootConfiguration
  parent: System.Activities.Validation.ValidationSettings
  langs:
  - csharp
  name: SkipValidatingRootConfiguration
  nameWithType: ValidationSettings.SkipValidatingRootConfiguration
  fullName: System.Activities.Validation.ValidationSettings.SkipValidatingRootConfiguration
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities.Validation
  summary: Gets or sets a value that indicates whether the root configuration is not subject for validation.
  remarks: To be added.
  syntax:
    content: public bool SkipValidatingRootConfiguration { get; set; }
    return:
      type: System.Boolean
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Activities.Validation.ValidationSettings.#ctor
  parent: System.Activities.Validation.ValidationSettings
  isExternal: false
  name: ValidationSettings()
  nameWithType: ValidationSettings.ValidationSettings()
  fullName: System.Activities.Validation.ValidationSettings.ValidationSettings()
- uid: System.Activities.Validation.ValidationSettings.AdditionalConstraints
  parent: System.Activities.Validation.ValidationSettings
  isExternal: false
  name: AdditionalConstraints
  nameWithType: ValidationSettings.AdditionalConstraints
  fullName: System.Activities.Validation.ValidationSettings.AdditionalConstraints
- uid: System.Collections.Generic.IDictionary{System.Type,System.Collections.Generic.IList{System.Activities.Validation.Constraint}}
  parent: System.Collections.Generic
  isExternal: false
  name: IDictionary<Type,IList<Constraint>>
  nameWithType: IDictionary<Type,IList<Constraint>>
  fullName: System.Collections.Generic.IDictionary<System.Type,System.Collections.Generic.IList<System.Activities.Validation.Constraint>>
- uid: System.Activities.Validation.ValidationSettings.CancellationToken
  parent: System.Activities.Validation.ValidationSettings
  isExternal: false
  name: CancellationToken
  nameWithType: ValidationSettings.CancellationToken
  fullName: System.Activities.Validation.ValidationSettings.CancellationToken
- uid: System.Threading.CancellationToken
  parent: System.Threading
  isExternal: false
  name: CancellationToken
  nameWithType: CancellationToken
  fullName: System.Threading.CancellationToken
- uid: System.Activities.Validation.ValidationSettings.Environment
  parent: System.Activities.Validation.ValidationSettings
  isExternal: false
  name: Environment
  nameWithType: ValidationSettings.Environment
  fullName: System.Activities.Validation.ValidationSettings.Environment
- uid: System.Activities.LocationReferenceEnvironment
  parent: System.Activities
  isExternal: false
  name: LocationReferenceEnvironment
  nameWithType: LocationReferenceEnvironment
  fullName: System.Activities.LocationReferenceEnvironment
- uid: System.Activities.Validation.ValidationSettings.OnlyUseAdditionalConstraints
  parent: System.Activities.Validation.ValidationSettings
  isExternal: false
  name: OnlyUseAdditionalConstraints
  nameWithType: ValidationSettings.OnlyUseAdditionalConstraints
  fullName: System.Activities.Validation.ValidationSettings.OnlyUseAdditionalConstraints
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Activities.Validation.ValidationSettings.PrepareForRuntime
  parent: System.Activities.Validation.ValidationSettings
  isExternal: false
  name: PrepareForRuntime
  nameWithType: ValidationSettings.PrepareForRuntime
  fullName: System.Activities.Validation.ValidationSettings.PrepareForRuntime
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Activities.Validation.ValidationSettings.SingleLevel
  parent: System.Activities.Validation.ValidationSettings
  isExternal: false
  name: SingleLevel
  nameWithType: ValidationSettings.SingleLevel
  fullName: System.Activities.Validation.ValidationSettings.SingleLevel
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Activities.Validation.ValidationSettings.SkipValidatingRootConfiguration
  parent: System.Activities.Validation.ValidationSettings
  isExternal: false
  name: SkipValidatingRootConfiguration
  nameWithType: ValidationSettings.SkipValidatingRootConfiguration
  fullName: System.Activities.Validation.ValidationSettings.SkipValidatingRootConfiguration
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
