### YamlMime:ManagedReference
items:
- uid: System.Configuration.Internal.IInternalConfigConfigurationFactory
  id: IInternalConfigConfigurationFactory
  children:
  - System.Configuration.Internal.IInternalConfigConfigurationFactory.Create(System.Type,System.Object[])
  - System.Configuration.Internal.IInternalConfigConfigurationFactory.NormalizeLocationSubPath(System.String,System.Configuration.Internal.IConfigErrorInfo)
  langs:
  - csharp
  name: IInternalConfigConfigurationFactory
  nameWithType: IInternalConfigConfigurationFactory
  fullName: System.Configuration.Internal.IInternalConfigConfigurationFactory
  type: Interface
  summary: Defines the interfaces used by the internal design time API to create a <see cref="T:System.Configuration.Configuration"> object.
  remarks: To be added.
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(false)]

      public interface IInternalConfigConfigurationFactory
  implements: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Internal.IInternalConfigConfigurationFactory.Create(System.Type,System.Object[])
  id: Create(System.Type,System.Object[])
  parent: System.Configuration.Internal.IInternalConfigConfigurationFactory
  langs:
  - csharp
  name: Create(Type,Object[])
  nameWithType: IInternalConfigConfigurationFactory.Create(Type,Object[])
  fullName: System.Configuration.Internal.IInternalConfigConfigurationFactory.Create(Type,Object[])
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: Creates and initializes a <see cref="T:System.Configuration.Configuration"> object.
  remarks: To be added.
  syntax:
    content: public System.Configuration.Configuration Create (Type typeConfigHost, object[] hostInitConfigurationParams);
    parameters:
    - id: typeConfigHost
      type: System.Type
      description: The <see cref="T:System.Type"> of the <xref:System.Configuration.Configuration> object to be created.
    - id: hostInitConfigurationParams
      type: System.Object[]
      description: A parameter array of <see cref="T:System.Object"> that contains the parameters to be applied to the created <xref:System.Configuration.Configuration> object.
    return:
      type: System.Configuration.Configuration
      description: A <see cref="T:System.Configuration.Configuration"> object.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Internal.IInternalConfigConfigurationFactory.NormalizeLocationSubPath(System.String,System.Configuration.Internal.IConfigErrorInfo)
  id: NormalizeLocationSubPath(System.String,System.Configuration.Internal.IConfigErrorInfo)
  parent: System.Configuration.Internal.IInternalConfigConfigurationFactory
  langs:
  - csharp
  name: NormalizeLocationSubPath(String,IConfigErrorInfo)
  nameWithType: IInternalConfigConfigurationFactory.NormalizeLocationSubPath(String,IConfigErrorInfo)
  fullName: System.Configuration.Internal.IInternalConfigConfigurationFactory.NormalizeLocationSubPath(String,IConfigErrorInfo)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: Normalizes a location subpath of a path to a configuration file.
  remarks: To be added.
  syntax:
    content: public string NormalizeLocationSubPath (string subPath, System.Configuration.Internal.IConfigErrorInfo errorInfo);
    parameters:
    - id: subPath
      type: System.String
      description: A string representing the path to the configuration file.
    - id: errorInfo
      type: System.Configuration.Internal.IConfigErrorInfo
      description: An instance of <see cref="T:System.Configuration.Internal.IConfigErrorInfo"> or `null`.
    return:
      type: System.String
      description: A normalized subpath string.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.Internal.IInternalConfigConfigurationFactory.Create(System.Type,System.Object[])
  parent: System.Configuration.Internal.IInternalConfigConfigurationFactory
  isExternal: false
  name: Create(Type,Object[])
  nameWithType: IInternalConfigConfigurationFactory.Create(Type,Object[])
  fullName: System.Configuration.Internal.IInternalConfigConfigurationFactory.Create(Type,Object[])
- uid: System.Configuration.Configuration
  parent: System.Configuration
  isExternal: false
  name: Configuration
  nameWithType: Configuration
  fullName: System.Configuration.Configuration
- uid: System.Type
  parent: System
  isExternal: false
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object[]
- uid: System.Configuration.Internal.IInternalConfigConfigurationFactory.NormalizeLocationSubPath(System.String,System.Configuration.Internal.IConfigErrorInfo)
  parent: System.Configuration.Internal.IInternalConfigConfigurationFactory
  isExternal: false
  name: NormalizeLocationSubPath(String,IConfigErrorInfo)
  nameWithType: IInternalConfigConfigurationFactory.NormalizeLocationSubPath(String,IConfigErrorInfo)
  fullName: System.Configuration.Internal.IInternalConfigConfigurationFactory.NormalizeLocationSubPath(String,IConfigErrorInfo)
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.Internal.IConfigErrorInfo
  parent: System.Configuration.Internal
  isExternal: false
  name: IConfigErrorInfo
  nameWithType: IConfigErrorInfo
  fullName: System.Configuration.Internal.IConfigErrorInfo
