### YamlMime:ManagedReference
items:
- uid: System.Configuration.Internal.InternalConfigEventHandler
  id: InternalConfigEventHandler
  langs:
  - csharp
  name: InternalConfigEventHandler
  nameWithType: InternalConfigEventHandler
  fullName: System.Configuration.Internal.InternalConfigEventHandler
  type: Delegate
  syntax:
    content: public delegate void InternalConfigEventHandler(object sender, InternalConfigEventArgs e);
  inheritance:
  - System.Object
  - System.Delegate
  platform:
  - net-1.1
  - net-2.0
  - netcore-1.0
references:
- uid: System.Delegate
  isExternal: false
  name: System.Delegate
