### YamlMime:ManagedReference
items:
- uid: System.Configuration.Internal.StreamChangeCallback
  id: StreamChangeCallback
  langs:
  - csharp
  name: StreamChangeCallback
  nameWithType: StreamChangeCallback
  fullName: System.Configuration.Internal.StreamChangeCallback
  type: Delegate
  syntax:
    content: public delegate void StreamChangeCallback(string streamName);
  inheritance:
  - System.Object
  - System.Delegate
  platform:
  - net-1.1
  - net-2.0
  - netcore-1.0
references:
- uid: System.Delegate
  isExternal: false
  name: System.Delegate
