### YamlMime:ManagedReference
items:
- uid: System.Configuration.Internal.InternalConfigEventHandler
  id: InternalConfigEventHandler
  langs:
  - csharp
  - vb
  name: InternalConfigEventHandler
  nameWithType: InternalConfigEventHandler
  fullName: System.Configuration.Internal.InternalConfigEventHandler
  type: Delegate
  syntax:
    content: public delegate void InternalConfigEventHandler(object sender, InternalConfigEventArgs e);
  inheritance:
  - System.Object
  - System.Delegate
references:
- uid: System.Delegate
  isExternal: false
  name: System.Delegate
