### YamlMime:ManagedReference
items:
- uid: System.Configuration.Internal.IInternalConfigSystem
  id: IInternalConfigSystem
  children:
  - System.Configuration.Internal.IInternalConfigSystem.GetSection(System.String)
  - System.Configuration.Internal.IInternalConfigSystem.RefreshConfig(System.String)
  - System.Configuration.Internal.IInternalConfigSystem.SupportsUserConfig
  langs:
  - csharp
  - vb
  name: IInternalConfigSystem
  nameWithType: IInternalConfigSystem
  fullName: System.Configuration.Internal.IInternalConfigSystem
  type: Interface
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(false)]

      public interface IInternalConfigSystem
  implements: []
- uid: System.Configuration.Internal.IInternalConfigSystem.GetSection(System.String)
  id: GetSection(System.String)
  parent: System.Configuration.Internal.IInternalConfigSystem
  langs:
  - csharp
  - vb
  name: GetSection
  nameWithType: IInternalConfigSystem.GetSection
  fullName: System.Configuration.Internal.IInternalConfigSystem.GetSection
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  syntax:
    content: public object GetSection (string configKey);
    parameters:
    - id: configKey
      type: System.String
      description: Parameter description to be filled
    return:
      type: System.Object
      description: Return description to be filled
- uid: System.Configuration.Internal.IInternalConfigSystem.RefreshConfig(System.String)
  id: RefreshConfig(System.String)
  parent: System.Configuration.Internal.IInternalConfigSystem
  langs:
  - csharp
  - vb
  name: RefreshConfig
  nameWithType: IInternalConfigSystem.RefreshConfig
  fullName: System.Configuration.Internal.IInternalConfigSystem.RefreshConfig
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  syntax:
    content: public void RefreshConfig (string sectionName);
    parameters:
    - id: sectionName
      type: System.String
      description: Parameter description to be filled
    return:
      type: System.Void
      description: Return description to be filled
- uid: System.Configuration.Internal.IInternalConfigSystem.SupportsUserConfig
  id: SupportsUserConfig
  parent: System.Configuration.Internal.IInternalConfigSystem
  langs:
  - csharp
  - vb
  name: SupportsUserConfig
  nameWithType: IInternalConfigSystem.SupportsUserConfig
  fullName: System.Configuration.Internal.IInternalConfigSystem.SupportsUserConfig
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  syntax:
    content: public bool SupportsUserConfig { get; }
    return:
      type: System.Boolean
      description: Return description to be filled
references:
- uid: System.Configuration.Internal.IInternalConfigSystem.GetSection(System.String)
  parent: System.Configuration.Internal.IInternalConfigSystem
  isExternal: false
  name: GetSection
  nameWithType: IInternalConfigSystem.GetSection
  fullName: System.Configuration.Internal.IInternalConfigSystem.GetSection
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.Internal.IInternalConfigSystem.RefreshConfig(System.String)
  parent: System.Configuration.Internal.IInternalConfigSystem
  isExternal: false
  name: RefreshConfig
  nameWithType: IInternalConfigSystem.RefreshConfig
  fullName: System.Configuration.Internal.IInternalConfigSystem.RefreshConfig
- uid: System.Void
  parent: System
  isExternal: false
  name: Void
  nameWithType: Void
  fullName: System.Void
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.Internal.IInternalConfigSystem.SupportsUserConfig
  parent: System.Configuration.Internal.IInternalConfigSystem
  isExternal: false
  name: SupportsUserConfig
  nameWithType: IInternalConfigSystem.SupportsUserConfig
  fullName: System.Configuration.Internal.IInternalConfigSystem.SupportsUserConfig
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
