### YamlMime:ManagedReference
items:
- uid: System.ComponentModel.Composition.Hosting.ApplicationCatalog
  id: ApplicationCatalog
  children:
  - System.ComponentModel.Composition.Hosting.ApplicationCatalog.#ctor
  - System.ComponentModel.Composition.Hosting.ApplicationCatalog.#ctor(System.ComponentModel.Composition.Primitives.ICompositionElement)
  - System.ComponentModel.Composition.Hosting.ApplicationCatalog.#ctor(System.Reflection.ReflectionContext)
  - System.ComponentModel.Composition.Hosting.ApplicationCatalog.#ctor(System.Reflection.ReflectionContext,System.ComponentModel.Composition.Primitives.ICompositionElement)
  - System.ComponentModel.Composition.Hosting.ApplicationCatalog.Dispose(System.Boolean)
  - System.ComponentModel.Composition.Hosting.ApplicationCatalog.GetEnumerator
  - System.ComponentModel.Composition.Hosting.ApplicationCatalog.GetExports(System.ComponentModel.Composition.Primitives.ImportDefinition)
  - System.ComponentModel.Composition.Hosting.ApplicationCatalog.System#ComponentModel#Composition#Primitives#ICompositionElement#DisplayName
  - System.ComponentModel.Composition.Hosting.ApplicationCatalog.System#ComponentModel#Composition#Primitives#ICompositionElement#Origin
  - System.ComponentModel.Composition.Hosting.ApplicationCatalog.ToString
  langs:
  - csharp
  - vb
  name: ApplicationCatalog
  nameWithType: ApplicationCatalog
  fullName: System.ComponentModel.Composition.Hosting.ApplicationCatalog
  type: Class
  syntax:
    content: 'public class ApplicationCatalog : System.ComponentModel.Composition.Primitives.ComposablePartCatalog, System.ComponentModel.Composition.Primitives.ICompositionElement'
  inheritance:
  - System.Object
  - System.ComponentModel.Composition.Primitives.ComposablePartCatalog
  implements:
  - System.ComponentModel.Composition.Primitives.ICompositionElement
  inheritedMembers:
  - System.ComponentModel.Composition.Primitives.ComposablePartCatalog.Dispose
  - System.ComponentModel.Composition.Primitives.ComposablePartCatalog.Parts
  - System.ComponentModel.Composition.Primitives.ComposablePartCatalog.System#Collections#IEnumerable#GetEnumerator
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
- uid: System.ComponentModel.Composition.Hosting.ApplicationCatalog.#ctor
  id: '#ctor'
  parent: System.ComponentModel.Composition.Hosting.ApplicationCatalog
  langs:
  - csharp
  - vb
  name: .ctor
  nameWithType: ApplicationCatalog..ctor
  fullName: System.ComponentModel.Composition.Hosting.ApplicationCatalog..ctor
  type: Constructor
  assemblies:
  - System.ComponentModel.Composition
  namespace: System.ComponentModel.Composition.Hosting
  syntax:
    content: public ApplicationCatalog ();
    parameters: []
- uid: System.ComponentModel.Composition.Hosting.ApplicationCatalog.#ctor(System.ComponentModel.Composition.Primitives.ICompositionElement)
  id: '#ctor(System.ComponentModel.Composition.Primitives.ICompositionElement)'
  parent: System.ComponentModel.Composition.Hosting.ApplicationCatalog
  langs:
  - csharp
  - vb
  name: .ctor
  nameWithType: ApplicationCatalog..ctor
  fullName: System.ComponentModel.Composition.Hosting.ApplicationCatalog..ctor
  type: Constructor
  assemblies:
  - System.ComponentModel.Composition
  namespace: System.ComponentModel.Composition.Hosting
  syntax:
    content: public ApplicationCatalog (System.ComponentModel.Composition.Primitives.ICompositionElement definitionOrigin);
    parameters:
    - id: definitionOrigin
      type: System.ComponentModel.Composition.Primitives.ICompositionElement
      description: Parameter description to be filled
- uid: System.ComponentModel.Composition.Hosting.ApplicationCatalog.#ctor(System.Reflection.ReflectionContext)
  id: '#ctor(System.Reflection.ReflectionContext)'
  parent: System.ComponentModel.Composition.Hosting.ApplicationCatalog
  langs:
  - csharp
  - vb
  name: .ctor
  nameWithType: ApplicationCatalog..ctor
  fullName: System.ComponentModel.Composition.Hosting.ApplicationCatalog..ctor
  type: Constructor
  assemblies:
  - System.ComponentModel.Composition
  namespace: System.ComponentModel.Composition.Hosting
  syntax:
    content: public ApplicationCatalog (System.Reflection.ReflectionContext reflectionContext);
    parameters:
    - id: reflectionContext
      type: System.Reflection.ReflectionContext
      description: Parameter description to be filled
- uid: System.ComponentModel.Composition.Hosting.ApplicationCatalog.#ctor(System.Reflection.ReflectionContext,System.ComponentModel.Composition.Primitives.ICompositionElement)
  id: '#ctor(System.Reflection.ReflectionContext,System.ComponentModel.Composition.Primitives.ICompositionElement)'
  parent: System.ComponentModel.Composition.Hosting.ApplicationCatalog
  langs:
  - csharp
  - vb
  name: .ctor
  nameWithType: ApplicationCatalog..ctor
  fullName: System.ComponentModel.Composition.Hosting.ApplicationCatalog..ctor
  type: Constructor
  assemblies:
  - System.ComponentModel.Composition
  namespace: System.ComponentModel.Composition.Hosting
  syntax:
    content: public ApplicationCatalog (System.Reflection.ReflectionContext reflectionContext, System.ComponentModel.Composition.Primitives.ICompositionElement definitionOrigin);
    parameters:
    - id: reflectionContext
      type: System.Reflection.ReflectionContext
      description: Parameter description to be filled
    - id: definitionOrigin
      type: System.ComponentModel.Composition.Primitives.ICompositionElement
      description: Parameter description to be filled
- uid: System.ComponentModel.Composition.Hosting.ApplicationCatalog.Dispose(System.Boolean)
  id: Dispose(System.Boolean)
  parent: System.ComponentModel.Composition.Hosting.ApplicationCatalog
  langs:
  - csharp
  - vb
  name: Dispose
  nameWithType: ApplicationCatalog.Dispose
  fullName: System.ComponentModel.Composition.Hosting.ApplicationCatalog.Dispose
  type: Method
  assemblies:
  - System.ComponentModel.Composition
  namespace: System.ComponentModel.Composition.Hosting
  syntax:
    content: protected override void Dispose (bool disposing);
    parameters:
    - id: disposing
      type: System.Boolean
      description: Parameter description to be filled
    return:
      type: System.Void
      description: Return description to be filled
- uid: System.ComponentModel.Composition.Hosting.ApplicationCatalog.GetEnumerator
  id: GetEnumerator
  parent: System.ComponentModel.Composition.Hosting.ApplicationCatalog
  langs:
  - csharp
  - vb
  name: GetEnumerator
  nameWithType: ApplicationCatalog.GetEnumerator
  fullName: System.ComponentModel.Composition.Hosting.ApplicationCatalog.GetEnumerator
  type: Method
  assemblies:
  - System.ComponentModel.Composition
  namespace: System.ComponentModel.Composition.Hosting
  syntax:
    content: public override System.Collections.Generic.IEnumerator<System.ComponentModel.Composition.Primitives.ComposablePartDefinition> GetEnumerator ();
    parameters: []
    return:
      type: System.Collections.Generic.IEnumerator{System.ComponentModel.Composition.Primitives.ComposablePartDefinition}
      description: Return description to be filled
- uid: System.ComponentModel.Composition.Hosting.ApplicationCatalog.GetExports(System.ComponentModel.Composition.Primitives.ImportDefinition)
  id: GetExports(System.ComponentModel.Composition.Primitives.ImportDefinition)
  parent: System.ComponentModel.Composition.Hosting.ApplicationCatalog
  langs:
  - csharp
  - vb
  name: GetExports
  nameWithType: ApplicationCatalog.GetExports
  fullName: System.ComponentModel.Composition.Hosting.ApplicationCatalog.GetExports
  type: Method
  assemblies:
  - System.ComponentModel.Composition
  namespace: System.ComponentModel.Composition.Hosting
  syntax:
    content: public override System.Collections.Generic.IEnumerable<Tuple<System.ComponentModel.Composition.Primitives.ComposablePartDefinition,System.ComponentModel.Composition.Primitives.ExportDefinition>> GetExports (System.ComponentModel.Composition.Primitives.ImportDefinition definition);
    parameters:
    - id: definition
      type: System.ComponentModel.Composition.Primitives.ImportDefinition
      description: Parameter description to be filled
    return:
      type: System.Collections.Generic.IEnumerable{System.Tuple{System.ComponentModel.Composition.Primitives.ComposablePartDefinition,System.ComponentModel.Composition.Primitives.ExportDefinition}}
      description: Return description to be filled
- uid: System.ComponentModel.Composition.Hosting.ApplicationCatalog.System#ComponentModel#Composition#Primitives#ICompositionElement#DisplayName
  id: System#ComponentModel#Composition#Primitives#ICompositionElement#DisplayName
  isEii: true
  parent: System.ComponentModel.Composition.Hosting.ApplicationCatalog
  langs:
  - csharp
  - vb
  name: System.ComponentModel.Composition.Primitives.ICompositionElement.DisplayName
  nameWithType: ApplicationCatalog.System.ComponentModel.Composition.Primitives.ICompositionElement.DisplayName
  fullName: System.ComponentModel.Composition.Hosting.ApplicationCatalog.System.ComponentModel.Composition.Primitives.ICompositionElement.DisplayName
  type: Property
  assemblies:
  - System.ComponentModel.Composition
  namespace: System.ComponentModel.Composition.Hosting
  syntax:
    content: string System.ComponentModel.Composition.Primitives.ICompositionElement.DisplayName { get; }
    return:
      type: System.String
      description: Return description to be filled
- uid: System.ComponentModel.Composition.Hosting.ApplicationCatalog.System#ComponentModel#Composition#Primitives#ICompositionElement#Origin
  id: System#ComponentModel#Composition#Primitives#ICompositionElement#Origin
  isEii: true
  parent: System.ComponentModel.Composition.Hosting.ApplicationCatalog
  langs:
  - csharp
  - vb
  name: System.ComponentModel.Composition.Primitives.ICompositionElement.Origin
  nameWithType: ApplicationCatalog.System.ComponentModel.Composition.Primitives.ICompositionElement.Origin
  fullName: System.ComponentModel.Composition.Hosting.ApplicationCatalog.System.ComponentModel.Composition.Primitives.ICompositionElement.Origin
  type: Property
  assemblies:
  - System.ComponentModel.Composition
  namespace: System.ComponentModel.Composition.Hosting
  syntax:
    content: System.ComponentModel.Composition.Primitives.ICompositionElement System.ComponentModel.Composition.Primitives.ICompositionElement.Origin { get; }
    return:
      type: System.ComponentModel.Composition.Primitives.ICompositionElement
      description: Return description to be filled
- uid: System.ComponentModel.Composition.Hosting.ApplicationCatalog.ToString
  id: ToString
  parent: System.ComponentModel.Composition.Hosting.ApplicationCatalog
  langs:
  - csharp
  - vb
  name: ToString
  nameWithType: ApplicationCatalog.ToString
  fullName: System.ComponentModel.Composition.Hosting.ApplicationCatalog.ToString
  type: Method
  assemblies:
  - System.ComponentModel.Composition
  namespace: System.ComponentModel.Composition.Hosting
  syntax:
    content: public override string ToString ();
    parameters: []
    return:
      type: System.String
      description: Return description to be filled
references:
- uid: System.ComponentModel.Composition.Primitives.ComposablePartCatalog
  isExternal: false
  name: System.ComponentModel.Composition.Primitives.ComposablePartCatalog
- uid: System.ComponentModel.Composition.Hosting.ApplicationCatalog.#ctor
  parent: System.ComponentModel.Composition.Hosting.ApplicationCatalog
  isExternal: false
  name: .ctor
  nameWithType: ApplicationCatalog..ctor
  fullName: System.ComponentModel.Composition.Hosting.ApplicationCatalog..ctor
- uid: System.ComponentModel.Composition.Hosting.ApplicationCatalog.#ctor(System.ComponentModel.Composition.Primitives.ICompositionElement)
  parent: System.ComponentModel.Composition.Hosting.ApplicationCatalog
  isExternal: false
  name: .ctor
  nameWithType: ApplicationCatalog..ctor
  fullName: System.ComponentModel.Composition.Hosting.ApplicationCatalog..ctor
- uid: System.ComponentModel.Composition.Primitives.ICompositionElement
  parent: System.ComponentModel.Composition.Primitives
  isExternal: false
  name: ICompositionElement
  nameWithType: ICompositionElement
  fullName: System.ComponentModel.Composition.Primitives.ICompositionElement
- uid: System.ComponentModel.Composition.Hosting.ApplicationCatalog.#ctor(System.Reflection.ReflectionContext)
  parent: System.ComponentModel.Composition.Hosting.ApplicationCatalog
  isExternal: false
  name: .ctor
  nameWithType: ApplicationCatalog..ctor
  fullName: System.ComponentModel.Composition.Hosting.ApplicationCatalog..ctor
- uid: System.Reflection.ReflectionContext
  parent: System.Reflection
  isExternal: false
  name: ReflectionContext
  nameWithType: ReflectionContext
  fullName: System.Reflection.ReflectionContext
- uid: System.ComponentModel.Composition.Hosting.ApplicationCatalog.#ctor(System.Reflection.ReflectionContext,System.ComponentModel.Composition.Primitives.ICompositionElement)
  parent: System.ComponentModel.Composition.Hosting.ApplicationCatalog
  isExternal: false
  name: .ctor
  nameWithType: ApplicationCatalog..ctor
  fullName: System.ComponentModel.Composition.Hosting.ApplicationCatalog..ctor
- uid: System.Reflection.ReflectionContext
  parent: System.Reflection
  isExternal: false
  name: ReflectionContext
  nameWithType: ReflectionContext
  fullName: System.Reflection.ReflectionContext
- uid: System.ComponentModel.Composition.Primitives.ICompositionElement
  parent: System.ComponentModel.Composition.Primitives
  isExternal: false
  name: ICompositionElement
  nameWithType: ICompositionElement
  fullName: System.ComponentModel.Composition.Primitives.ICompositionElement
- uid: System.ComponentModel.Composition.Hosting.ApplicationCatalog.Dispose(System.Boolean)
  parent: System.ComponentModel.Composition.Hosting.ApplicationCatalog
  isExternal: false
  name: Dispose
  nameWithType: ApplicationCatalog.Dispose
  fullName: System.ComponentModel.Composition.Hosting.ApplicationCatalog.Dispose
- uid: System.Void
  parent: System
  isExternal: false
  name: Void
  nameWithType: Void
  fullName: System.Void
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ComponentModel.Composition.Hosting.ApplicationCatalog.GetEnumerator
  parent: System.ComponentModel.Composition.Hosting.ApplicationCatalog
  isExternal: false
  name: GetEnumerator
  nameWithType: ApplicationCatalog.GetEnumerator
  fullName: System.ComponentModel.Composition.Hosting.ApplicationCatalog.GetEnumerator
- uid: System.ComponentModel.Composition.Hosting.ApplicationCatalog.GetExports(System.ComponentModel.Composition.Primitives.ImportDefinition)
  parent: System.ComponentModel.Composition.Hosting.ApplicationCatalog
  isExternal: false
  name: GetExports
  nameWithType: ApplicationCatalog.GetExports
  fullName: System.ComponentModel.Composition.Hosting.ApplicationCatalog.GetExports
- uid: System.ComponentModel.Composition.Primitives.ImportDefinition
  parent: System.ComponentModel.Composition.Primitives
  isExternal: false
  name: ImportDefinition
  nameWithType: ImportDefinition
  fullName: System.ComponentModel.Composition.Primitives.ImportDefinition
- uid: System.ComponentModel.Composition.Hosting.ApplicationCatalog.System#ComponentModel#Composition#Primitives#ICompositionElement#DisplayName
  parent: System.ComponentModel.Composition.Hosting.ApplicationCatalog
  isExternal: false
  name: System.ComponentModel.Composition.Primitives.ICompositionElement.DisplayName
  nameWithType: ApplicationCatalog.System.ComponentModel.Composition.Primitives.ICompositionElement.DisplayName
  fullName: System.ComponentModel.Composition.Hosting.ApplicationCatalog.System.ComponentModel.Composition.Primitives.ICompositionElement.DisplayName
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ComponentModel.Composition.Hosting.ApplicationCatalog.System#ComponentModel#Composition#Primitives#ICompositionElement#Origin
  parent: System.ComponentModel.Composition.Hosting.ApplicationCatalog
  isExternal: false
  name: System.ComponentModel.Composition.Primitives.ICompositionElement.Origin
  nameWithType: ApplicationCatalog.System.ComponentModel.Composition.Primitives.ICompositionElement.Origin
  fullName: System.ComponentModel.Composition.Hosting.ApplicationCatalog.System.ComponentModel.Composition.Primitives.ICompositionElement.Origin
- uid: System.ComponentModel.Composition.Primitives.ICompositionElement
  parent: System.ComponentModel.Composition.Primitives
  isExternal: false
  name: ICompositionElement
  nameWithType: ICompositionElement
  fullName: System.ComponentModel.Composition.Primitives.ICompositionElement
- uid: System.ComponentModel.Composition.Hosting.ApplicationCatalog.ToString
  parent: System.ComponentModel.Composition.Hosting.ApplicationCatalog
  isExternal: false
  name: ToString
  nameWithType: ApplicationCatalog.ToString
  fullName: System.ComponentModel.Composition.Hosting.ApplicationCatalog.ToString
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
