### YamlMime:ManagedReference
items:
- uid: System.ComponentModel.Design.Data.IDataEnvironment
  id: IDataEnvironment
  children:
  - System.ComponentModel.Design.Data.IDataEnvironment.BuildConnection(System.Windows.Forms.IWin32Window,System.ComponentModel.Design.Data.DesignerDataConnection)
  - System.ComponentModel.Design.Data.IDataEnvironment.BuildQuery(System.Windows.Forms.IWin32Window,System.ComponentModel.Design.Data.DesignerDataConnection,System.ComponentModel.Design.Data.QueryBuilderMode,System.String)
  - System.ComponentModel.Design.Data.IDataEnvironment.ConfigureConnection(System.Windows.Forms.IWin32Window,System.ComponentModel.Design.Data.DesignerDataConnection,System.String)
  - System.ComponentModel.Design.Data.IDataEnvironment.Connections
  - System.ComponentModel.Design.Data.IDataEnvironment.GetCodeExpression(System.ComponentModel.Design.Data.DesignerDataConnection)
  - System.ComponentModel.Design.Data.IDataEnvironment.GetConnectionSchema(System.ComponentModel.Design.Data.DesignerDataConnection)
  - System.ComponentModel.Design.Data.IDataEnvironment.GetDesignTimeConnection(System.ComponentModel.Design.Data.DesignerDataConnection)
  langs:
  - csharp
  - vb
  name: IDataEnvironment
  nameWithType: IDataEnvironment
  fullName: System.ComponentModel.Design.Data.IDataEnvironment
  type: Interface
  syntax:
    content: public interface IDataEnvironment
  implements: []
- uid: System.ComponentModel.Design.Data.IDataEnvironment.BuildConnection(System.Windows.Forms.IWin32Window,System.ComponentModel.Design.Data.DesignerDataConnection)
  id: BuildConnection(System.Windows.Forms.IWin32Window,System.ComponentModel.Design.Data.DesignerDataConnection)
  parent: System.ComponentModel.Design.Data.IDataEnvironment
  langs:
  - csharp
  - vb
  name: BuildConnection
  nameWithType: IDataEnvironment.BuildConnection
  fullName: System.ComponentModel.Design.Data.IDataEnvironment.BuildConnection
  type: Method
  assemblies:
  - System.Design
  namespace: System.ComponentModel.Design.Data
  syntax:
    content: public System.ComponentModel.Design.Data.DesignerDataConnection BuildConnection (System.Windows.Forms.IWin32Window owner, System.ComponentModel.Design.Data.DesignerDataConnection initialConnection);
    parameters:
    - id: owner
      type: System.Windows.Forms.IWin32Window
      description: Parameter description to be filled
    - id: initialConnection
      type: System.ComponentModel.Design.Data.DesignerDataConnection
      description: Parameter description to be filled
    return:
      type: System.ComponentModel.Design.Data.DesignerDataConnection
      description: Return description to be filled
- uid: System.ComponentModel.Design.Data.IDataEnvironment.BuildQuery(System.Windows.Forms.IWin32Window,System.ComponentModel.Design.Data.DesignerDataConnection,System.ComponentModel.Design.Data.QueryBuilderMode,System.String)
  id: BuildQuery(System.Windows.Forms.IWin32Window,System.ComponentModel.Design.Data.DesignerDataConnection,System.ComponentModel.Design.Data.QueryBuilderMode,System.String)
  parent: System.ComponentModel.Design.Data.IDataEnvironment
  langs:
  - csharp
  - vb
  name: BuildQuery
  nameWithType: IDataEnvironment.BuildQuery
  fullName: System.ComponentModel.Design.Data.IDataEnvironment.BuildQuery
  type: Method
  assemblies:
  - System.Design
  namespace: System.ComponentModel.Design.Data
  syntax:
    content: public string BuildQuery (System.Windows.Forms.IWin32Window owner, System.ComponentModel.Design.Data.DesignerDataConnection connection, System.ComponentModel.Design.Data.QueryBuilderMode mode, string initialQueryText);
    parameters:
    - id: owner
      type: System.Windows.Forms.IWin32Window
      description: Parameter description to be filled
    - id: connection
      type: System.ComponentModel.Design.Data.DesignerDataConnection
      description: Parameter description to be filled
    - id: mode
      type: System.ComponentModel.Design.Data.QueryBuilderMode
      description: Parameter description to be filled
    - id: initialQueryText
      type: System.String
      description: Parameter description to be filled
    return:
      type: System.String
      description: Return description to be filled
- uid: System.ComponentModel.Design.Data.IDataEnvironment.ConfigureConnection(System.Windows.Forms.IWin32Window,System.ComponentModel.Design.Data.DesignerDataConnection,System.String)
  id: ConfigureConnection(System.Windows.Forms.IWin32Window,System.ComponentModel.Design.Data.DesignerDataConnection,System.String)
  parent: System.ComponentModel.Design.Data.IDataEnvironment
  langs:
  - csharp
  - vb
  name: ConfigureConnection
  nameWithType: IDataEnvironment.ConfigureConnection
  fullName: System.ComponentModel.Design.Data.IDataEnvironment.ConfigureConnection
  type: Method
  assemblies:
  - System.Design
  namespace: System.ComponentModel.Design.Data
  syntax:
    content: public System.ComponentModel.Design.Data.DesignerDataConnection ConfigureConnection (System.Windows.Forms.IWin32Window owner, System.ComponentModel.Design.Data.DesignerDataConnection connection, string name);
    parameters:
    - id: owner
      type: System.Windows.Forms.IWin32Window
      description: Parameter description to be filled
    - id: connection
      type: System.ComponentModel.Design.Data.DesignerDataConnection
      description: Parameter description to be filled
    - id: name
      type: System.String
      description: Parameter description to be filled
    return:
      type: System.ComponentModel.Design.Data.DesignerDataConnection
      description: Return description to be filled
- uid: System.ComponentModel.Design.Data.IDataEnvironment.Connections
  id: Connections
  parent: System.ComponentModel.Design.Data.IDataEnvironment
  langs:
  - csharp
  - vb
  name: Connections
  nameWithType: IDataEnvironment.Connections
  fullName: System.ComponentModel.Design.Data.IDataEnvironment.Connections
  type: Property
  assemblies:
  - System.Design
  namespace: System.ComponentModel.Design.Data
  syntax:
    content: public System.Collections.ICollection Connections { get; }
    return:
      type: System.Collections.ICollection
      description: Return description to be filled
- uid: System.ComponentModel.Design.Data.IDataEnvironment.GetCodeExpression(System.ComponentModel.Design.Data.DesignerDataConnection)
  id: GetCodeExpression(System.ComponentModel.Design.Data.DesignerDataConnection)
  parent: System.ComponentModel.Design.Data.IDataEnvironment
  langs:
  - csharp
  - vb
  name: GetCodeExpression
  nameWithType: IDataEnvironment.GetCodeExpression
  fullName: System.ComponentModel.Design.Data.IDataEnvironment.GetCodeExpression
  type: Method
  assemblies:
  - System.Design
  namespace: System.ComponentModel.Design.Data
  syntax:
    content: public System.CodeDom.CodeExpression GetCodeExpression (System.ComponentModel.Design.Data.DesignerDataConnection connection);
    parameters:
    - id: connection
      type: System.ComponentModel.Design.Data.DesignerDataConnection
      description: Parameter description to be filled
    return:
      type: System.CodeDom.CodeExpression
      description: Return description to be filled
- uid: System.ComponentModel.Design.Data.IDataEnvironment.GetConnectionSchema(System.ComponentModel.Design.Data.DesignerDataConnection)
  id: GetConnectionSchema(System.ComponentModel.Design.Data.DesignerDataConnection)
  parent: System.ComponentModel.Design.Data.IDataEnvironment
  langs:
  - csharp
  - vb
  name: GetConnectionSchema
  nameWithType: IDataEnvironment.GetConnectionSchema
  fullName: System.ComponentModel.Design.Data.IDataEnvironment.GetConnectionSchema
  type: Method
  assemblies:
  - System.Design
  namespace: System.ComponentModel.Design.Data
  syntax:
    content: public System.ComponentModel.Design.Data.IDesignerDataSchema GetConnectionSchema (System.ComponentModel.Design.Data.DesignerDataConnection connection);
    parameters:
    - id: connection
      type: System.ComponentModel.Design.Data.DesignerDataConnection
      description: Parameter description to be filled
    return:
      type: System.ComponentModel.Design.Data.IDesignerDataSchema
      description: Return description to be filled
- uid: System.ComponentModel.Design.Data.IDataEnvironment.GetDesignTimeConnection(System.ComponentModel.Design.Data.DesignerDataConnection)
  id: GetDesignTimeConnection(System.ComponentModel.Design.Data.DesignerDataConnection)
  parent: System.ComponentModel.Design.Data.IDataEnvironment
  langs:
  - csharp
  - vb
  name: GetDesignTimeConnection
  nameWithType: IDataEnvironment.GetDesignTimeConnection
  fullName: System.ComponentModel.Design.Data.IDataEnvironment.GetDesignTimeConnection
  type: Method
  assemblies:
  - System.Design
  namespace: System.ComponentModel.Design.Data
  syntax:
    content: public System.Data.Common.DbConnection GetDesignTimeConnection (System.ComponentModel.Design.Data.DesignerDataConnection connection);
    parameters:
    - id: connection
      type: System.ComponentModel.Design.Data.DesignerDataConnection
      description: Parameter description to be filled
    return:
      type: System.Data.Common.DbConnection
      description: Return description to be filled
references:
- uid: System.ComponentModel.Design.Data.IDataEnvironment.BuildConnection(System.Windows.Forms.IWin32Window,System.ComponentModel.Design.Data.DesignerDataConnection)
  parent: System.ComponentModel.Design.Data.IDataEnvironment
  isExternal: false
  name: BuildConnection
  nameWithType: IDataEnvironment.BuildConnection
  fullName: System.ComponentModel.Design.Data.IDataEnvironment.BuildConnection
- uid: System.ComponentModel.Design.Data.DesignerDataConnection
  parent: System.ComponentModel.Design.Data
  isExternal: false
  name: DesignerDataConnection
  nameWithType: DesignerDataConnection
  fullName: System.ComponentModel.Design.Data.DesignerDataConnection
- uid: System.ComponentModel.Design.Data.DesignerDataConnection
  parent: System.ComponentModel.Design.Data
  isExternal: false
  name: DesignerDataConnection
  nameWithType: DesignerDataConnection
  fullName: System.ComponentModel.Design.Data.DesignerDataConnection
- uid: System.ComponentModel.Design.Data.IDataEnvironment.BuildQuery(System.Windows.Forms.IWin32Window,System.ComponentModel.Design.Data.DesignerDataConnection,System.ComponentModel.Design.Data.QueryBuilderMode,System.String)
  parent: System.ComponentModel.Design.Data.IDataEnvironment
  isExternal: false
  name: BuildQuery
  nameWithType: IDataEnvironment.BuildQuery
  fullName: System.ComponentModel.Design.Data.IDataEnvironment.BuildQuery
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ComponentModel.Design.Data.DesignerDataConnection
  parent: System.ComponentModel.Design.Data
  isExternal: false
  name: DesignerDataConnection
  nameWithType: DesignerDataConnection
  fullName: System.ComponentModel.Design.Data.DesignerDataConnection
- uid: System.ComponentModel.Design.Data.QueryBuilderMode
  parent: System.ComponentModel.Design.Data
  isExternal: false
  name: QueryBuilderMode
  nameWithType: QueryBuilderMode
  fullName: System.ComponentModel.Design.Data.QueryBuilderMode
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ComponentModel.Design.Data.IDataEnvironment.ConfigureConnection(System.Windows.Forms.IWin32Window,System.ComponentModel.Design.Data.DesignerDataConnection,System.String)
  parent: System.ComponentModel.Design.Data.IDataEnvironment
  isExternal: false
  name: ConfigureConnection
  nameWithType: IDataEnvironment.ConfigureConnection
  fullName: System.ComponentModel.Design.Data.IDataEnvironment.ConfigureConnection
- uid: System.ComponentModel.Design.Data.DesignerDataConnection
  parent: System.ComponentModel.Design.Data
  isExternal: false
  name: DesignerDataConnection
  nameWithType: DesignerDataConnection
  fullName: System.ComponentModel.Design.Data.DesignerDataConnection
- uid: System.ComponentModel.Design.Data.DesignerDataConnection
  parent: System.ComponentModel.Design.Data
  isExternal: false
  name: DesignerDataConnection
  nameWithType: DesignerDataConnection
  fullName: System.ComponentModel.Design.Data.DesignerDataConnection
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ComponentModel.Design.Data.IDataEnvironment.Connections
  parent: System.ComponentModel.Design.Data.IDataEnvironment
  isExternal: false
  name: Connections
  nameWithType: IDataEnvironment.Connections
  fullName: System.ComponentModel.Design.Data.IDataEnvironment.Connections
- uid: System.Collections.ICollection
  parent: System.Collections
  isExternal: false
  name: ICollection
  nameWithType: ICollection
  fullName: System.Collections.ICollection
- uid: System.ComponentModel.Design.Data.IDataEnvironment.GetCodeExpression(System.ComponentModel.Design.Data.DesignerDataConnection)
  parent: System.ComponentModel.Design.Data.IDataEnvironment
  isExternal: false
  name: GetCodeExpression
  nameWithType: IDataEnvironment.GetCodeExpression
  fullName: System.ComponentModel.Design.Data.IDataEnvironment.GetCodeExpression
- uid: System.ComponentModel.Design.Data.DesignerDataConnection
  parent: System.ComponentModel.Design.Data
  isExternal: false
  name: DesignerDataConnection
  nameWithType: DesignerDataConnection
  fullName: System.ComponentModel.Design.Data.DesignerDataConnection
- uid: System.ComponentModel.Design.Data.IDataEnvironment.GetConnectionSchema(System.ComponentModel.Design.Data.DesignerDataConnection)
  parent: System.ComponentModel.Design.Data.IDataEnvironment
  isExternal: false
  name: GetConnectionSchema
  nameWithType: IDataEnvironment.GetConnectionSchema
  fullName: System.ComponentModel.Design.Data.IDataEnvironment.GetConnectionSchema
- uid: System.ComponentModel.Design.Data.IDesignerDataSchema
  parent: System.ComponentModel.Design.Data
  isExternal: false
  name: IDesignerDataSchema
  nameWithType: IDesignerDataSchema
  fullName: System.ComponentModel.Design.Data.IDesignerDataSchema
- uid: System.ComponentModel.Design.Data.DesignerDataConnection
  parent: System.ComponentModel.Design.Data
  isExternal: false
  name: DesignerDataConnection
  nameWithType: DesignerDataConnection
  fullName: System.ComponentModel.Design.Data.DesignerDataConnection
- uid: System.ComponentModel.Design.Data.IDataEnvironment.GetDesignTimeConnection(System.ComponentModel.Design.Data.DesignerDataConnection)
  parent: System.ComponentModel.Design.Data.IDataEnvironment
  isExternal: false
  name: GetDesignTimeConnection
  nameWithType: IDataEnvironment.GetDesignTimeConnection
  fullName: System.ComponentModel.Design.Data.IDataEnvironment.GetDesignTimeConnection
- uid: System.Data.Common.DbConnection
  parent: System.Data.Common
  isExternal: false
  name: DbConnection
  nameWithType: DbConnection
  fullName: System.Data.Common.DbConnection
- uid: System.ComponentModel.Design.Data.DesignerDataConnection
  parent: System.ComponentModel.Design.Data
  isExternal: false
  name: DesignerDataConnection
  nameWithType: DesignerDataConnection
  fullName: System.ComponentModel.Design.Data.DesignerDataConnection
