### YamlMime:ManagedReference
items:
- uid: System.Deployment.Application.DownloadFileGroupCompletedEventArgs
  id: DownloadFileGroupCompletedEventArgs
  children:
  - System.Deployment.Application.DownloadFileGroupCompletedEventArgs.Group
  langs:
  - csharp
  name: DownloadFileGroupCompletedEventArgs
  nameWithType: DownloadFileGroupCompletedEventArgs
  fullName: System.Deployment.Application.DownloadFileGroupCompletedEventArgs
  type: Class
  summary: Describes a file download that has recently completed.
  remarks: ''
  example:
  - "The following code example downloads a file group named `HelpFiles`, and displays download progress in a status bar. This example requires that you deploy a Windows Forms application, and that your main form has a <xref:System.Windows.Forms.StatusStrip> control, and a <xref:System.Windows.Forms.ToolStripStatusLabel> control named `downloadStatus`.  \n  \n [!CODE [ClickOnceAPI#8](../CodeSnippet/VS_Snippets_Winforms/ClickOnceAPI#8)]"
  syntax:
    content: 'public class DownloadFileGroupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs'
  inheritance:
  - System.ComponentModel.AsyncCompletedEventArgs
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Deployment.Application.DownloadFileGroupCompletedEventArgs.Group
  id: Group
  parent: System.Deployment.Application.DownloadFileGroupCompletedEventArgs
  langs:
  - csharp
  name: Group
  nameWithType: DownloadFileGroupCompletedEventArgs.Group
  fullName: System.Deployment.Application.DownloadFileGroupCompletedEventArgs.Group
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: Gets the name of the file group being downloaded.
  remarks: You can initiate multiple calls to <xref:System.Deployment.Application.ApplicationDeployment.DownloadFileGroupAsync%2A> and download multiple file groups simultaneously. Use Group to determine which event callbacks correspond to which group.
  example:
  - "The following code example downloads a file group named `HelpFiles`, and displays download progress in a status bar. This example requires that you deploy a Windows Forms application, and that your main form has a <xref:System.Windows.Forms.StatusStrip> control, and a <xref:System.Windows.Forms.ToolStripStatusLabel> control named `downloadStatus`.  \n  \n [!CODE [ClickOnceAPI#8](../CodeSnippet/VS_Snippets_Winforms/ClickOnceAPI#8)]"
  syntax:
    content: public string Group { get; }
    return:
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.ComponentModel.AsyncCompletedEventArgs
  isExternal: false
  name: System.ComponentModel.AsyncCompletedEventArgs
- uid: System.Deployment.Application.DownloadFileGroupCompletedEventArgs.Group
  parent: System.Deployment.Application.DownloadFileGroupCompletedEventArgs
  isExternal: false
  name: Group
  nameWithType: DownloadFileGroupCompletedEventArgs.Group
  fullName: System.Deployment.Application.DownloadFileGroupCompletedEventArgs.Group
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
