### YamlMime:ManagedReference
items:
- uid: System.Deployment.Application.DeploymentProgressChangedEventHandler
  id: DeploymentProgressChangedEventHandler
  langs:
  - csharp
  name: DeploymentProgressChangedEventHandler
  nameWithType: DeploymentProgressChangedEventHandler
  fullName: System.Deployment.Application.DeploymentProgressChangedEventHandler
  type: Delegate
  summary: Represents the method that will handle the <see cref="E:System.Deployment.Application.ApplicationDeployment.CheckForUpdateProgressChanged"> event, <xref:System.Deployment.Application.ApplicationDeployment.UpdateProgressChanged> event, or <xref:System.Deployment.Application.ApplicationDeployment.DownloadFileGroupProgressChanged> event of an <xref:System.Deployment.Application.ApplicationDeployment>.
  remarks: 'When you create a DeploymentProgressChangedEventHandler delegate, you identify the method that will handle the event. To associate the event with your event handler, add an instance of the delegate to the event. The event handler is called whenever the event occurs, unless you remove the delegate. For more information about event-handler delegates, see [NIB: Events and Delegates](http://msdn.microsoft.com/en-us/d98fd58b-fa4f-4598-8378-addf4355a115).'
  syntax:
    content: public delegate void DeploymentProgressChangedEventHandler(object sender, DeploymentProgressChangedEventArgs e);
  inheritance:
  - System.Object
  - System.Delegate
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Delegate
  isExternal: false
  name: System.Delegate
