### YamlMime:ManagedReference
items:
- uid: System.Deployment.Application.CheckForUpdateCompletedEventHandler
  id: CheckForUpdateCompletedEventHandler
  langs:
  - csharp
  - vb
  name: CheckForUpdateCompletedEventHandler
  nameWithType: CheckForUpdateCompletedEventHandler
  fullName: System.Deployment.Application.CheckForUpdateCompletedEventHandler
  type: Delegate
  syntax:
    content: public delegate void CheckForUpdateCompletedEventHandler(object sender, CheckForUpdateCompletedEventArgs e);
  inheritance:
  - System.Object
  - System.Delegate
references:
- uid: System.Delegate
  isExternal: false
  name: System.Delegate
