### YamlMime:ManagedReference
items:
- uid: System.Deployment.Application.DownloadFileGroupCompletedEventHandler
  id: DownloadFileGroupCompletedEventHandler
  langs:
  - csharp
  name: DownloadFileGroupCompletedEventHandler
  nameWithType: DownloadFileGroupCompletedEventHandler
  fullName: System.Deployment.Application.DownloadFileGroupCompletedEventHandler
  type: Delegate
  syntax:
    content: public delegate void DownloadFileGroupCompletedEventHandler(object sender, DownloadFileGroupCompletedEventArgs e);
  inheritance:
  - System.Object
  - System.Delegate
references:
- uid: System.Delegate
  isExternal: false
  name: System.Delegate
