### YamlMime:ManagedReference
items:
- uid: System.Deployment.Application.DependentPlatformMissingException
  id: DependentPlatformMissingException
  children:
  - System.Deployment.Application.DependentPlatformMissingException.#ctor
  - System.Deployment.Application.DependentPlatformMissingException.#ctor(System.String)
  - System.Deployment.Application.DependentPlatformMissingException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Deployment.Application.DependentPlatformMissingException.#ctor(System.String,System.Exception)
  - System.Deployment.Application.DependentPlatformMissingException.#ctor(System.String,System.Uri)
  - System.Deployment.Application.DependentPlatformMissingException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Deployment.Application.DependentPlatformMissingException.SupportUrl
  langs:
  - csharp
  - vb
  name: DependentPlatformMissingException
  nameWithType: DependentPlatformMissingException
  fullName: System.Deployment.Application.DependentPlatformMissingException
  type: Class
  syntax:
    content: 'public class DependentPlatformMissingException : System.Deployment.Application.DeploymentException'
  inheritance:
  - System.Object
  - System.Exception
  - System.SystemException
  - System.Deployment.Application.DeploymentException
  implements: []
  inheritedMembers:
  - System.Exception.Data
  - System.Exception.GetBaseException
  - System.Exception.GetType
  - System.Exception.HelpLink
  - System.Exception.HResult
  - System.Exception.InnerException
  - System.Exception.Message
  - System.Exception.SerializeObjectState
  - System.Exception.Source
  - System.Exception.StackTrace
  - System.Exception.TargetSite
  - System.Exception.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
- uid: System.Deployment.Application.DependentPlatformMissingException.#ctor
  id: '#ctor'
  parent: System.Deployment.Application.DependentPlatformMissingException
  langs:
  - csharp
  - vb
  name: .ctor
  nameWithType: DependentPlatformMissingException..ctor
  fullName: System.Deployment.Application.DependentPlatformMissingException..ctor
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  syntax:
    content: public DependentPlatformMissingException ();
    parameters: []
- uid: System.Deployment.Application.DependentPlatformMissingException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Deployment.Application.DependentPlatformMissingException
  langs:
  - csharp
  - vb
  name: .ctor
  nameWithType: DependentPlatformMissingException..ctor
  fullName: System.Deployment.Application.DependentPlatformMissingException..ctor
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  syntax:
    content: public DependentPlatformMissingException (string message);
    parameters:
    - id: message
      type: System.String
      description: Parameter description to be filled
- uid: System.Deployment.Application.DependentPlatformMissingException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.Deployment.Application.DependentPlatformMissingException
  langs:
  - csharp
  - vb
  name: .ctor
  nameWithType: DependentPlatformMissingException..ctor
  fullName: System.Deployment.Application.DependentPlatformMissingException..ctor
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  syntax:
    content: protected DependentPlatformMissingException (System.Runtime.Serialization.SerializationInfo serializationInfo, System.Runtime.Serialization.StreamingContext streamingContext);
    parameters:
    - id: serializationInfo
      type: System.Runtime.Serialization.SerializationInfo
      description: Parameter description to be filled
    - id: streamingContext
      type: System.Runtime.Serialization.StreamingContext
      description: Parameter description to be filled
- uid: System.Deployment.Application.DependentPlatformMissingException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Deployment.Application.DependentPlatformMissingException
  langs:
  - csharp
  - vb
  name: .ctor
  nameWithType: DependentPlatformMissingException..ctor
  fullName: System.Deployment.Application.DependentPlatformMissingException..ctor
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  syntax:
    content: public DependentPlatformMissingException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: Parameter description to be filled
    - id: innerException
      type: System.Exception
      description: Parameter description to be filled
- uid: System.Deployment.Application.DependentPlatformMissingException.#ctor(System.String,System.Uri)
  id: '#ctor(System.String,System.Uri)'
  parent: System.Deployment.Application.DependentPlatformMissingException
  langs:
  - csharp
  - vb
  name: .ctor
  nameWithType: DependentPlatformMissingException..ctor
  fullName: System.Deployment.Application.DependentPlatformMissingException..ctor
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  syntax:
    content: public DependentPlatformMissingException (string message, Uri supportUrl);
    parameters:
    - id: message
      type: System.String
      description: Parameter description to be filled
    - id: supportUrl
      type: System.Uri
      description: Parameter description to be filled
- uid: System.Deployment.Application.DependentPlatformMissingException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Deployment.Application.DependentPlatformMissingException
  langs:
  - csharp
  - vb
  name: GetObjectData
  nameWithType: DependentPlatformMissingException.GetObjectData
  fullName: System.Deployment.Application.DependentPlatformMissingException.GetObjectData
  type: Method
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  syntax:
    content: public override void GetObjectData (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: Parameter description to be filled
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: Parameter description to be filled
    return:
      type: System.Void
      description: Return description to be filled
- uid: System.Deployment.Application.DependentPlatformMissingException.SupportUrl
  id: SupportUrl
  parent: System.Deployment.Application.DependentPlatformMissingException
  langs:
  - csharp
  - vb
  name: SupportUrl
  nameWithType: DependentPlatformMissingException.SupportUrl
  fullName: System.Deployment.Application.DependentPlatformMissingException.SupportUrl
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  syntax:
    content: public Uri SupportUrl { get; }
    return:
      type: System.Uri
      description: Return description to be filled
references:
- uid: System.Deployment.Application.DeploymentException
  isExternal: false
  name: System.Deployment.Application.DeploymentException
- uid: System.Deployment.Application.DependentPlatformMissingException.#ctor
  parent: System.Deployment.Application.DependentPlatformMissingException
  isExternal: false
  name: .ctor
  nameWithType: DependentPlatformMissingException..ctor
  fullName: System.Deployment.Application.DependentPlatformMissingException..ctor
- uid: System.Deployment.Application.DependentPlatformMissingException.#ctor(System.String)
  parent: System.Deployment.Application.DependentPlatformMissingException
  isExternal: false
  name: .ctor
  nameWithType: DependentPlatformMissingException..ctor
  fullName: System.Deployment.Application.DependentPlatformMissingException..ctor
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Deployment.Application.DependentPlatformMissingException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Deployment.Application.DependentPlatformMissingException
  isExternal: false
  name: .ctor
  nameWithType: DependentPlatformMissingException..ctor
  fullName: System.Deployment.Application.DependentPlatformMissingException..ctor
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: false
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.Deployment.Application.DependentPlatformMissingException.#ctor(System.String,System.Exception)
  parent: System.Deployment.Application.DependentPlatformMissingException
  isExternal: false
  name: .ctor
  nameWithType: DependentPlatformMissingException..ctor
  fullName: System.Deployment.Application.DependentPlatformMissingException..ctor
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Exception
  parent: System
  isExternal: false
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.Deployment.Application.DependentPlatformMissingException.#ctor(System.String,System.Uri)
  parent: System.Deployment.Application.DependentPlatformMissingException
  isExternal: false
  name: .ctor
  nameWithType: DependentPlatformMissingException..ctor
  fullName: System.Deployment.Application.DependentPlatformMissingException..ctor
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Deployment.Application.DependentPlatformMissingException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Deployment.Application.DependentPlatformMissingException
  isExternal: false
  name: GetObjectData
  nameWithType: DependentPlatformMissingException.GetObjectData
  fullName: System.Deployment.Application.DependentPlatformMissingException.GetObjectData
- uid: System.Void
  parent: System
  isExternal: false
  name: Void
  nameWithType: Void
  fullName: System.Void
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: false
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.Deployment.Application.DependentPlatformMissingException.SupportUrl
  parent: System.Deployment.Application.DependentPlatformMissingException
  isExternal: false
  name: SupportUrl
  nameWithType: DependentPlatformMissingException.SupportUrl
  fullName: System.Deployment.Application.DependentPlatformMissingException.SupportUrl
