### YamlMime:ManagedReference
items:
- uid: System.Deployment.Application.DeploymentProgressChangedEventArgs
  id: DeploymentProgressChangedEventArgs
  children:
  - System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesCompleted
  - System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesTotal
  - System.Deployment.Application.DeploymentProgressChangedEventArgs.Group
  - System.Deployment.Application.DeploymentProgressChangedEventArgs.State
  langs:
  - csharp
  name: DeploymentProgressChangedEventArgs
  nameWithType: DeploymentProgressChangedEventArgs
  fullName: System.Deployment.Application.DeploymentProgressChangedEventArgs
  type: Class
  summary: Represents progress data reported in an asynchronous operation.
  remarks: "This class contains properties that describe progress for the <xref:System.Deployment.Application.ApplicationDeployment.CheckForUpdateProgressChanged>, <xref:System.Deployment.Application.ApplicationDeployment.DownloadFileGroupProgressChanged>, and <xref:System.Deployment.Application.ApplicationDeployment.UpdateProgressChanged> events. Not every property in this class applies to each event.  \n  \n <xref:System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesCompleted%2A> and <xref:System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesTotal%2A> represent the total number of bytes downloaded to date and the total number of bytes in the download operation, respectively; they apply to all three events. <xref:System.Deployment.Application.DeploymentProgressChangedEventArgs.Group%2A> names the file group corresponding to the current <xref:System.Deployment.Application.ApplicationDeployment.DownloadFileGroupProgressChanged> event, and <xref:System.Deployment.Application.DeploymentProgressChangedEventArgs.State%2A> reflects the current stage of the download operation."
  example:
  - "The following code example downloads a file group named `HelpFiles`, and displays download progress in a status bar. This example requires that you deploy a Windows Forms application, and that your main form has a <xref:System.Windows.Forms.StatusStrip> control, and a <xref:System.Windows.Forms.ToolStripStatusLabel> control named `downloadStatus`.  \n  \n [!CODE [ClickOnceAPI#8](../CodeSnippet/VS_Snippets_Winforms/ClickOnceAPI#8)]"
  syntax:
    content: 'public class DeploymentProgressChangedEventArgs : System.ComponentModel.ProgressChangedEventArgs'
  inheritance:
  - System.ComponentModel.ProgressChangedEventArgs
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesCompleted
  id: BytesCompleted
  parent: System.Deployment.Application.DeploymentProgressChangedEventArgs
  langs:
  - csharp
  name: BytesCompleted
  nameWithType: DeploymentProgressChangedEventArgs.BytesCompleted
  fullName: System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesCompleted
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: Gets the number of bytes already downloaded by this operation.
  remarks: For <xref:System.Deployment.Application.ApplicationDeployment.CheckForUpdateProgressChanged>, the BytesCompleted property refers to the downloading of the deployment manifest. For <xref:System.Deployment.Application.ApplicationDeployment.UpdateProgressChanged>, the property refers to the download progress of the entire update, included the manifests, assemblies, and data files. For <xref:System.Deployment.Application.ApplicationDeployment.DownloadFileGroupProgressChanged>, the property refers to the download progress of the entire set of files that are part of the named group.
  example:
  - "The following code example downloads a file group named `HelpFiles`, and displays download progress in a status bar. This example requires that you deploy a Windows Forms application, and that your main form has a <xref:System.Windows.Forms.StatusStrip> control, and a <xref:System.Windows.Forms.ToolStripStatusLabel> control named `downloadStatus`.  \n  \n [!CODE [ClickOnceAPI#8](../CodeSnippet/VS_Snippets_Winforms/ClickOnceAPI#8)]"
  syntax:
    content: public long BytesCompleted { get; }
    return:
      type: System.Int64
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesTotal
  id: BytesTotal
  parent: System.Deployment.Application.DeploymentProgressChangedEventArgs
  langs:
  - csharp
  name: BytesTotal
  nameWithType: DeploymentProgressChangedEventArgs.BytesTotal
  fullName: System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesTotal
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: Gets the total number of bytes in the download operation.
  remarks: For <xref:System.Deployment.Application.ApplicationDeployment.CheckForUpdateProgressChanged>, the BytesTotal property refers to the downloading of the deployment manifest. For <xref:System.Deployment.Application.ApplicationDeployment.UpdateProgressChanged>, the property refers to the download progress of the entire update, included the manifests, assemblies, and data files. For <xref:System.Deployment.Application.ApplicationDeployment.DownloadFileGroupProgressChanged>, the property refers to the download progress of the entire set of files that are part of the named group.
  example:
  - "The following code example downloads a file group named `HelpFiles`, and displays download progress in a status bar. This example requires that you deploy a Windows Forms application, and that your main form has a <xref:System.Windows.Forms.StatusStrip> control, and a <xref:System.Windows.Forms.ToolStripStatusLabel> control named `downloadStatus`.  \n  \n [!CODE [ClickOnceAPI#8](../CodeSnippet/VS_Snippets_Winforms/ClickOnceAPI#8)]"
  syntax:
    content: public long BytesTotal { get; }
    return:
      type: System.Int64
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Deployment.Application.DeploymentProgressChangedEventArgs.Group
  id: Group
  parent: System.Deployment.Application.DeploymentProgressChangedEventArgs
  langs:
  - csharp
  name: Group
  nameWithType: DeploymentProgressChangedEventArgs.Group
  fullName: System.Deployment.Application.DeploymentProgressChangedEventArgs.Group
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: Gets the name of the file group being downloaded.
  remarks: You can initiate multiple calls to <xref:System.Deployment.Application.ApplicationDeployment.DownloadFileGroupAsync%2A> and download multiple file groups simultaneously. Use Group to determine which event callbacks correspond to which group.
  example:
  - "The following code example downloads a file group named `HelpFiles`, and displays download progress in a status bar. This example requires that you deploy a Windows Forms application, and that your main form has a <xref:System.Windows.Forms.StatusStrip> control, and a <xref:System.Windows.Forms.ToolStripStatusLabel> control named `downloadStatus`.  \n  \n [!CODE [ClickOnceAPI#8](../CodeSnippet/VS_Snippets_Winforms/ClickOnceAPI#8)]"
  syntax:
    content: public string Group { get; }
    return:
      type: System.String
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Deployment.Application.DeploymentProgressChangedEventArgs.State
  id: State
  parent: System.Deployment.Application.DeploymentProgressChangedEventArgs
  langs:
  - csharp
  name: State
  nameWithType: DeploymentProgressChangedEventArgs.State
  fullName: System.Deployment.Application.DeploymentProgressChangedEventArgs.State
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: Gets the action that the process is currently executing.
  remarks: ''
  example:
  - "The following code example downloads a file group named `HelpFiles`, and displays download progress in a status bar. This example requires that you deploy a Windows Forms application, and that your main form has a <xref:System.Windows.Forms.StatusStrip> control, and a <xref:System.Windows.Forms.ToolStripStatusLabel> control named `downloadStatus`.  \n  \n [!CODE [ClickOnceAPI#8](../CodeSnippet/VS_Snippets_Winforms/ClickOnceAPI#8)]"
  syntax:
    content: public System.Deployment.Application.DeploymentProgressState State { get; }
    return:
      type: System.Deployment.Application.DeploymentProgressState
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.ComponentModel.ProgressChangedEventArgs
  isExternal: false
  name: System.ComponentModel.ProgressChangedEventArgs
- uid: System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesCompleted
  parent: System.Deployment.Application.DeploymentProgressChangedEventArgs
  isExternal: false
  name: BytesCompleted
  nameWithType: DeploymentProgressChangedEventArgs.BytesCompleted
  fullName: System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesCompleted
- uid: System.Int64
  parent: System
  isExternal: false
  name: Int64
  nameWithType: Int64
  fullName: System.Int64
- uid: System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesTotal
  parent: System.Deployment.Application.DeploymentProgressChangedEventArgs
  isExternal: false
  name: BytesTotal
  nameWithType: DeploymentProgressChangedEventArgs.BytesTotal
  fullName: System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesTotal
- uid: System.Int64
  parent: System
  isExternal: false
  name: Int64
  nameWithType: Int64
  fullName: System.Int64
- uid: System.Deployment.Application.DeploymentProgressChangedEventArgs.Group
  parent: System.Deployment.Application.DeploymentProgressChangedEventArgs
  isExternal: false
  name: Group
  nameWithType: DeploymentProgressChangedEventArgs.Group
  fullName: System.Deployment.Application.DeploymentProgressChangedEventArgs.Group
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Deployment.Application.DeploymentProgressChangedEventArgs.State
  parent: System.Deployment.Application.DeploymentProgressChangedEventArgs
  isExternal: false
  name: State
  nameWithType: DeploymentProgressChangedEventArgs.State
  fullName: System.Deployment.Application.DeploymentProgressChangedEventArgs.State
- uid: System.Deployment.Application.DeploymentProgressState
  parent: System.Deployment.Application
  isExternal: false
  name: DeploymentProgressState
  nameWithType: DeploymentProgressState
  fullName: System.Deployment.Application.DeploymentProgressState
