### YamlMime:ManagedReference
items:
- uid: System.Deployment.Application.DeploymentProgressState
  id: DeploymentProgressState
  children:
  - System.Deployment.Application.DeploymentProgressState.DownloadingApplicationFiles
  - System.Deployment.Application.DeploymentProgressState.DownloadingApplicationInformation
  - System.Deployment.Application.DeploymentProgressState.DownloadingDeploymentInformation
  langs:
  - csharp
  - vb
  name: DeploymentProgressState
  nameWithType: DeploymentProgressState
  fullName: System.Deployment.Application.DeploymentProgressState
  type: Enum
  syntax:
    content: public enum DeploymentProgressState
  inheritance:
  - System.Object
  - System.ValueType
  - System.Enum
- uid: System.Deployment.Application.DeploymentProgressState.DownloadingApplicationFiles
  id: DownloadingApplicationFiles
  parent: System.Deployment.Application.DeploymentProgressState
  langs:
  - csharp
  - vb
  name: DownloadingApplicationFiles
  nameWithType: DeploymentProgressState.DownloadingApplicationFiles
  fullName: System.Deployment.Application.DeploymentProgressState.DownloadingApplicationFiles
  type: Field
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  syntax:
    content: DownloadingApplicationFiles
    return:
      type: System.Deployment.Application.DeploymentProgressState
      description: Return description to be filled
- uid: System.Deployment.Application.DeploymentProgressState.DownloadingApplicationInformation
  id: DownloadingApplicationInformation
  parent: System.Deployment.Application.DeploymentProgressState
  langs:
  - csharp
  - vb
  name: DownloadingApplicationInformation
  nameWithType: DeploymentProgressState.DownloadingApplicationInformation
  fullName: System.Deployment.Application.DeploymentProgressState.DownloadingApplicationInformation
  type: Field
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  syntax:
    content: DownloadingApplicationInformation
    return:
      type: System.Deployment.Application.DeploymentProgressState
      description: Return description to be filled
- uid: System.Deployment.Application.DeploymentProgressState.DownloadingDeploymentInformation
  id: DownloadingDeploymentInformation
  parent: System.Deployment.Application.DeploymentProgressState
  langs:
  - csharp
  - vb
  name: DownloadingDeploymentInformation
  nameWithType: DeploymentProgressState.DownloadingDeploymentInformation
  fullName: System.Deployment.Application.DeploymentProgressState.DownloadingDeploymentInformation
  type: Field
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  syntax:
    content: DownloadingDeploymentInformation
    return:
      type: System.Deployment.Application.DeploymentProgressState
      description: Return description to be filled
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Deployment.Application.DeploymentProgressState.DownloadingApplicationFiles
  parent: System.Deployment.Application.DeploymentProgressState
  isExternal: false
  name: DownloadingApplicationFiles
  nameWithType: DeploymentProgressState.DownloadingApplicationFiles
  fullName: System.Deployment.Application.DeploymentProgressState.DownloadingApplicationFiles
- uid: System.Deployment.Application.DeploymentProgressState
  parent: System.Deployment.Application
  isExternal: false
  name: DeploymentProgressState
  nameWithType: DeploymentProgressState
  fullName: System.Deployment.Application.DeploymentProgressState
- uid: System.Deployment.Application.DeploymentProgressState.DownloadingApplicationInformation
  parent: System.Deployment.Application.DeploymentProgressState
  isExternal: false
  name: DownloadingApplicationInformation
  nameWithType: DeploymentProgressState.DownloadingApplicationInformation
  fullName: System.Deployment.Application.DeploymentProgressState.DownloadingApplicationInformation
- uid: System.Deployment.Application.DeploymentProgressState
  parent: System.Deployment.Application
  isExternal: false
  name: DeploymentProgressState
  nameWithType: DeploymentProgressState
  fullName: System.Deployment.Application.DeploymentProgressState
- uid: System.Deployment.Application.DeploymentProgressState.DownloadingDeploymentInformation
  parent: System.Deployment.Application.DeploymentProgressState
  isExternal: false
  name: DownloadingDeploymentInformation
  nameWithType: DeploymentProgressState.DownloadingDeploymentInformation
  fullName: System.Deployment.Application.DeploymentProgressState.DownloadingDeploymentInformation
- uid: System.Deployment.Application.DeploymentProgressState
  parent: System.Deployment.Application
  isExternal: false
  name: DeploymentProgressState
  nameWithType: DeploymentProgressState
  fullName: System.Deployment.Application.DeploymentProgressState
