### YamlMime:ManagedReference
items:
- uid: System.Environment.SpecialFolderOption
  id: Environment.SpecialFolderOption
  children:
  - System.Environment.SpecialFolderOption.Create
  - System.Environment.SpecialFolderOption.DoNotVerify
  - System.Environment.SpecialFolderOption.None
  langs:
  - csharp
  - vb
  name: Environment+SpecialFolderOption
  nameWithType: Environment+SpecialFolderOption
  fullName: System.Environment+SpecialFolderOption
  type: Enum
  syntax:
    content: public enum Environment.SpecialFolderOption
  inheritance:
  - System.Object
  - System.ValueType
  - System.Enum
  inheritedMembers:
  - System.Enum.CompareTo(System.Object)
  - System.Enum.Equals(System.Object)
  - System.Enum.Format(System.Type,System.Object,System.String)
  - System.Enum.GetHashCode
  - System.Enum.GetName(System.Type,System.Object)
  - System.Enum.GetNames(System.Type)
  - System.Enum.GetTypeCode
  - System.Enum.GetUnderlyingType(System.Type)
  - System.Enum.GetValues(System.Type)
  - System.Enum.HasFlag(System.Enum)
  - System.Enum.IsDefined(System.Type,System.Object)
  - System.Enum.Parse(System.Type,System.String)
  - System.Enum.Parse(System.Type,System.String,System.Boolean)
  - System.Enum.System#IConvertible#ToBoolean(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToByte(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToChar(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToDateTime(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToDecimal(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToDouble(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToInt16(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToInt32(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToInt64(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToSByte(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToSingle(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToType(System.Type,System.IFormatProvider)
  - System.Enum.System#IConvertible#ToUInt16(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToUInt32(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToUInt64(System.IFormatProvider)
  - System.Enum.ToObject(System.Type,System.Byte)
  - System.Enum.ToObject(System.Type,System.Int16)
  - System.Enum.ToObject(System.Type,System.Int32)
  - System.Enum.ToObject(System.Type,System.Int64)
  - System.Enum.ToObject(System.Type,System.Object)
  - System.Enum.ToObject(System.Type,System.SByte)
  - System.Enum.ToObject(System.Type,System.UInt16)
  - System.Enum.ToObject(System.Type,System.UInt32)
  - System.Enum.ToObject(System.Type,System.UInt64)
  - System.Enum.ToString
  - System.Enum.ToString(System.IFormatProvider)
  - System.Enum.ToString(System.String)
  - System.Enum.ToString(System.String,System.IFormatProvider)
  - System.Enum.TryParse``1(System.String,``0@)
  - System.Enum.TryParse``1(System.String,System.Boolean,``0@)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
- uid: System.Environment.SpecialFolderOption.Create
  id: Create
  parent: System.Environment.SpecialFolderOption
  langs:
  - csharp
  - vb
  name: Create
  nameWithType: Environment+SpecialFolderOption.Create
  fullName: System.Environment+SpecialFolderOption.Create
  type: Field
  assemblies:
  - mscorlib
  namespace: System
  syntax:
    content: Create
    return:
      type: System.Environment+SpecialFolderOption
      description: Return description to be filled
- uid: System.Environment.SpecialFolderOption.DoNotVerify
  id: DoNotVerify
  parent: System.Environment.SpecialFolderOption
  langs:
  - csharp
  - vb
  name: DoNotVerify
  nameWithType: Environment+SpecialFolderOption.DoNotVerify
  fullName: System.Environment+SpecialFolderOption.DoNotVerify
  type: Field
  assemblies:
  - mscorlib
  namespace: System
  syntax:
    content: DoNotVerify
    return:
      type: System.Environment+SpecialFolderOption
      description: Return description to be filled
- uid: System.Environment.SpecialFolderOption.None
  id: None
  parent: System.Environment.SpecialFolderOption
  langs:
  - csharp
  - vb
  name: None
  nameWithType: Environment+SpecialFolderOption.None
  fullName: System.Environment+SpecialFolderOption.None
  type: Field
  assemblies:
  - mscorlib
  namespace: System
  syntax:
    content: None
    return:
      type: System.Environment+SpecialFolderOption
      description: Return description to be filled
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Environment.SpecialFolderOption.Create
  parent: System.Environment.SpecialFolderOption
  isExternal: false
  name: Create
  nameWithType: Environment+SpecialFolderOption.Create
  fullName: System.Environment+SpecialFolderOption.Create
- uid: System.Environment.SpecialFolderOption
  parent: System
  isExternal: false
  name: Environment+SpecialFolderOption
  nameWithType: Environment+SpecialFolderOption
  fullName: System.Environment+SpecialFolderOption
- uid: System.Environment.SpecialFolderOption.DoNotVerify
  parent: System.Environment.SpecialFolderOption
  isExternal: false
  name: DoNotVerify
  nameWithType: Environment+SpecialFolderOption.DoNotVerify
  fullName: System.Environment+SpecialFolderOption.DoNotVerify
- uid: System.Environment.SpecialFolderOption
  parent: System
  isExternal: false
  name: Environment+SpecialFolderOption
  nameWithType: Environment+SpecialFolderOption
  fullName: System.Environment+SpecialFolderOption
- uid: System.Environment.SpecialFolderOption.None
  parent: System.Environment.SpecialFolderOption
  isExternal: false
  name: None
  nameWithType: Environment+SpecialFolderOption.None
  fullName: System.Environment+SpecialFolderOption.None
- uid: System.Environment.SpecialFolderOption
  parent: System
  isExternal: false
  name: Environment+SpecialFolderOption
  nameWithType: Environment+SpecialFolderOption
  fullName: System.Environment+SpecialFolderOption
