### YamlMime:ManagedReference
items:
- uid: System.ApplicationIdentity
  id: ApplicationIdentity
  children:
  - System.ApplicationIdentity.#ctor(System.String)
  - System.ApplicationIdentity.CodeBase
  - System.ApplicationIdentity.FullName
  - System.ApplicationIdentity.System#Runtime#Serialization#ISerializable#GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.ApplicationIdentity.ToString
  langs:
  - csharp
  - vb
  name: ApplicationIdentity
  nameWithType: ApplicationIdentity
  fullName: System.ApplicationIdentity
  type: Class
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(false)]

      public sealed class ApplicationIdentity : System.Runtime.Serialization.ISerializable
  inheritance:
  - System.Object
  implements:
  - System.Runtime.Serialization.ISerializable
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
- uid: System.ApplicationIdentity.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.ApplicationIdentity
  langs:
  - csharp
  - vb
  name: .ctor
  nameWithType: ApplicationIdentity..ctor
  fullName: System.ApplicationIdentity..ctor
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System
  syntax:
    content: public ApplicationIdentity (string applicationIdentityFullName);
    parameters:
    - id: applicationIdentityFullName
      type: System.String
      description: Parameter description to be filled
- uid: System.ApplicationIdentity.CodeBase
  id: CodeBase
  parent: System.ApplicationIdentity
  langs:
  - csharp
  - vb
  name: CodeBase
  nameWithType: ApplicationIdentity.CodeBase
  fullName: System.ApplicationIdentity.CodeBase
  type: Property
  assemblies:
  - mscorlib
  namespace: System
  syntax:
    content: public string CodeBase { get; }
    return:
      type: System.String
      description: Return description to be filled
- uid: System.ApplicationIdentity.FullName
  id: FullName
  parent: System.ApplicationIdentity
  langs:
  - csharp
  - vb
  name: FullName
  nameWithType: ApplicationIdentity.FullName
  fullName: System.ApplicationIdentity.FullName
  type: Property
  assemblies:
  - mscorlib
  namespace: System
  syntax:
    content: public string FullName { get; }
    return:
      type: System.String
      description: Return description to be filled
- uid: System.ApplicationIdentity.System#Runtime#Serialization#ISerializable#GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: System#Runtime#Serialization#ISerializable#GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  isEii: true
  parent: System.ApplicationIdentity
  langs:
  - csharp
  - vb
  name: System.Runtime.Serialization.ISerializable.GetObjectData
  nameWithType: ApplicationIdentity.System.Runtime.Serialization.ISerializable.GetObjectData
  fullName: System.ApplicationIdentity.System.Runtime.Serialization.ISerializable.GetObjectData
  type: Method
  assemblies:
  - mscorlib
  namespace: System
  syntax:
    content: void ISerializable.GetObjectData (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: Parameter description to be filled
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: Parameter description to be filled
    return:
      type: System.Void
      description: Return description to be filled
- uid: System.ApplicationIdentity.ToString
  id: ToString
  parent: System.ApplicationIdentity
  langs:
  - csharp
  - vb
  name: ToString
  nameWithType: ApplicationIdentity.ToString
  fullName: System.ApplicationIdentity.ToString
  type: Method
  assemblies:
  - mscorlib
  namespace: System
  syntax:
    content: public override string ToString ();
    parameters: []
    return:
      type: System.String
      description: Return description to be filled
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ApplicationIdentity.#ctor(System.String)
  parent: System.ApplicationIdentity
  isExternal: false
  name: .ctor
  nameWithType: ApplicationIdentity..ctor
  fullName: System.ApplicationIdentity..ctor
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ApplicationIdentity.CodeBase
  parent: System.ApplicationIdentity
  isExternal: false
  name: CodeBase
  nameWithType: ApplicationIdentity.CodeBase
  fullName: System.ApplicationIdentity.CodeBase
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ApplicationIdentity.FullName
  parent: System.ApplicationIdentity
  isExternal: false
  name: FullName
  nameWithType: ApplicationIdentity.FullName
  fullName: System.ApplicationIdentity.FullName
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ApplicationIdentity.System#Runtime#Serialization#ISerializable#GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.ApplicationIdentity
  isExternal: false
  name: System.Runtime.Serialization.ISerializable.GetObjectData
  nameWithType: ApplicationIdentity.System.Runtime.Serialization.ISerializable.GetObjectData
  fullName: System.ApplicationIdentity.System.Runtime.Serialization.ISerializable.GetObjectData
- uid: System.Void
  parent: System
  isExternal: false
  name: Void
  nameWithType: Void
  fullName: System.Void
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: false
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.ApplicationIdentity.ToString
  parent: System.ApplicationIdentity
  isExternal: false
  name: ToString
  nameWithType: ApplicationIdentity.ToString
  fullName: System.ApplicationIdentity.ToString
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
