### YamlMime:ManagedReference
items:
- uid: Microsoft.Build.Execution.ProjectInstanceSettings
  id: ProjectInstanceSettings
  children:
  - Microsoft.Build.Execution.ProjectInstanceSettings.Immutable
  - Microsoft.Build.Execution.ProjectInstanceSettings.ImmutableWithFastItemLookup
  - Microsoft.Build.Execution.ProjectInstanceSettings.None
  langs:
  - csharp
  - vb
  name: ProjectInstanceSettings
  nameWithType: ProjectInstanceSettings
  fullName: Microsoft.Build.Execution.ProjectInstanceSettings
  type: Enum
  syntax:
    content: >-
      [System.Flags]

      public enum ProjectInstanceSettings
  inheritance:
  - System.Object
  - System.ValueType
  - System.Enum
  inheritedMembers:
  - System.Enum.CompareTo(System.Object)
  - System.Enum.Equals(System.Object)
  - System.Enum.Format(System.Type,System.Object,System.String)
  - System.Enum.GetHashCode
  - System.Enum.GetName(System.Type,System.Object)
  - System.Enum.GetNames(System.Type)
  - System.Enum.GetTypeCode
  - System.Enum.GetUnderlyingType(System.Type)
  - System.Enum.GetValues(System.Type)
  - System.Enum.HasFlag(System.Enum)
  - System.Enum.IsDefined(System.Type,System.Object)
  - System.Enum.Parse(System.Type,System.String)
  - System.Enum.Parse(System.Type,System.String,System.Boolean)
  - System.Enum.System#IConvertible#ToBoolean(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToByte(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToChar(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToDateTime(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToDecimal(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToDouble(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToInt16(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToInt32(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToInt64(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToSByte(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToSingle(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToType(System.Type,System.IFormatProvider)
  - System.Enum.System#IConvertible#ToUInt16(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToUInt32(System.IFormatProvider)
  - System.Enum.System#IConvertible#ToUInt64(System.IFormatProvider)
  - System.Enum.ToObject(System.Type,System.Byte)
  - System.Enum.ToObject(System.Type,System.Int16)
  - System.Enum.ToObject(System.Type,System.Int32)
  - System.Enum.ToObject(System.Type,System.Int64)
  - System.Enum.ToObject(System.Type,System.Object)
  - System.Enum.ToObject(System.Type,System.SByte)
  - System.Enum.ToObject(System.Type,System.UInt16)
  - System.Enum.ToObject(System.Type,System.UInt32)
  - System.Enum.ToObject(System.Type,System.UInt64)
  - System.Enum.ToString
  - System.Enum.ToString(System.IFormatProvider)
  - System.Enum.ToString(System.String)
  - System.Enum.ToString(System.String,System.IFormatProvider)
  - System.Enum.TryParse``1(System.String,``0@)
  - System.Enum.TryParse``1(System.String,System.Boolean,``0@)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
- uid: Microsoft.Build.Execution.ProjectInstanceSettings.Immutable
  id: Immutable
  parent: Microsoft.Build.Execution.ProjectInstanceSettings
  langs:
  - csharp
  - vb
  name: Immutable
  nameWithType: ProjectInstanceSettings.Immutable
  fullName: Microsoft.Build.Execution.ProjectInstanceSettings.Immutable
  type: Field
  assemblies:
  - Microsoft.Build
  namespace: Microsoft.Build.Execution
  syntax:
    content: Immutable
    return:
      type: Microsoft.Build.Execution.ProjectInstanceSettings
      description: Return description to be filled
- uid: Microsoft.Build.Execution.ProjectInstanceSettings.ImmutableWithFastItemLookup
  id: ImmutableWithFastItemLookup
  parent: Microsoft.Build.Execution.ProjectInstanceSettings
  langs:
  - csharp
  - vb
  name: ImmutableWithFastItemLookup
  nameWithType: ProjectInstanceSettings.ImmutableWithFastItemLookup
  fullName: Microsoft.Build.Execution.ProjectInstanceSettings.ImmutableWithFastItemLookup
  type: Field
  assemblies:
  - Microsoft.Build
  namespace: Microsoft.Build.Execution
  syntax:
    content: ImmutableWithFastItemLookup
    return:
      type: Microsoft.Build.Execution.ProjectInstanceSettings
      description: Return description to be filled
- uid: Microsoft.Build.Execution.ProjectInstanceSettings.None
  id: None
  parent: Microsoft.Build.Execution.ProjectInstanceSettings
  langs:
  - csharp
  - vb
  name: None
  nameWithType: ProjectInstanceSettings.None
  fullName: Microsoft.Build.Execution.ProjectInstanceSettings.None
  type: Field
  assemblies:
  - Microsoft.Build
  namespace: Microsoft.Build.Execution
  syntax:
    content: None
    return:
      type: Microsoft.Build.Execution.ProjectInstanceSettings
      description: Return description to be filled
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: Microsoft.Build.Execution.ProjectInstanceSettings.Immutable
  parent: Microsoft.Build.Execution.ProjectInstanceSettings
  isExternal: false
  name: Immutable
  nameWithType: ProjectInstanceSettings.Immutable
  fullName: Microsoft.Build.Execution.ProjectInstanceSettings.Immutable
- uid: Microsoft.Build.Execution.ProjectInstanceSettings
  parent: Microsoft.Build.Execution
  isExternal: false
  name: ProjectInstanceSettings
  nameWithType: ProjectInstanceSettings
  fullName: Microsoft.Build.Execution.ProjectInstanceSettings
- uid: Microsoft.Build.Execution.ProjectInstanceSettings.ImmutableWithFastItemLookup
  parent: Microsoft.Build.Execution.ProjectInstanceSettings
  isExternal: false
  name: ImmutableWithFastItemLookup
  nameWithType: ProjectInstanceSettings.ImmutableWithFastItemLookup
  fullName: Microsoft.Build.Execution.ProjectInstanceSettings.ImmutableWithFastItemLookup
- uid: Microsoft.Build.Execution.ProjectInstanceSettings
  parent: Microsoft.Build.Execution
  isExternal: false
  name: ProjectInstanceSettings
  nameWithType: ProjectInstanceSettings
  fullName: Microsoft.Build.Execution.ProjectInstanceSettings
- uid: Microsoft.Build.Execution.ProjectInstanceSettings.None
  parent: Microsoft.Build.Execution.ProjectInstanceSettings
  isExternal: false
  name: None
  nameWithType: ProjectInstanceSettings.None
  fullName: Microsoft.Build.Execution.ProjectInstanceSettings.None
- uid: Microsoft.Build.Execution.ProjectInstanceSettings
  parent: Microsoft.Build.Execution
  isExternal: false
  name: ProjectInstanceSettings
  nameWithType: ProjectInstanceSettings
  fullName: Microsoft.Build.Execution.ProjectInstanceSettings
