### YamlMime:ManagedReference
items:
- uid: System.Activities.WorkflowApplicationAbortedEventArgs
  id: WorkflowApplicationAbortedEventArgs
  children:
  - System.Activities.WorkflowApplicationAbortedEventArgs.Reason
  langs:
  - csharp
  - vb
  name: WorkflowApplicationAbortedEventArgs
  nameWithType: WorkflowApplicationAbortedEventArgs
  fullName: System.Activities.WorkflowApplicationAbortedEventArgs
  type: Class
  syntax:
    content: 'public class WorkflowApplicationAbortedEventArgs : System.Activities.WorkflowApplicationEventArgs'
  inheritance:
  - System.Object
  - System.EventArgs
  - System.Activities.WorkflowApplicationEventArgs
  implements: []
  inheritedMembers:
  - System.Activities.WorkflowApplicationEventArgs.GetInstanceExtensions``1
  - System.Activities.WorkflowApplicationEventArgs.InstanceId
  - System.EventArgs.Empty
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: System.Activities.WorkflowApplicationAbortedEventArgs.Reason
  id: Reason
  parent: System.Activities.WorkflowApplicationAbortedEventArgs
  langs:
  - csharp
  - vb
  name: Reason
  nameWithType: WorkflowApplicationAbortedEventArgs.Reason
  fullName: System.Activities.WorkflowApplicationAbortedEventArgs.Reason
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities
  syntax:
    content: public Exception Reason { get; }
    return:
      type: System.Exception
      description: Return description to be filled
references:
- uid: System.Activities.WorkflowApplicationEventArgs
  isExternal: false
  name: System.Activities.WorkflowApplicationEventArgs
- uid: System.Activities.WorkflowApplicationAbortedEventArgs.Reason
  parent: System.Activities.WorkflowApplicationAbortedEventArgs
  isExternal: false
  name: Reason
  nameWithType: WorkflowApplicationAbortedEventArgs.Reason
  fullName: System.Activities.WorkflowApplicationAbortedEventArgs.Reason
- uid: System.Exception
  parent: System
  isExternal: false
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
