### YamlMime:ManagedReference
items:
- uid: System.Activities.LocationReferenceEnvironment
  id: LocationReferenceEnvironment
  children:
  - System.Activities.LocationReferenceEnvironment.#ctor
  - System.Activities.LocationReferenceEnvironment.GetLocationReferences
  - System.Activities.LocationReferenceEnvironment.IsVisible(System.Activities.LocationReference)
  - System.Activities.LocationReferenceEnvironment.Parent
  - System.Activities.LocationReferenceEnvironment.Root
  - System.Activities.LocationReferenceEnvironment.TryGetLocationReference(System.String,System.Activities.LocationReference@)
  langs:
  - csharp
  - vb
  name: LocationReferenceEnvironment
  nameWithType: LocationReferenceEnvironment
  fullName: System.Activities.LocationReferenceEnvironment
  type: Class
  syntax:
    content: public abstract class LocationReferenceEnvironment
  inheritance:
  - System.Object
  implements: []
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: System.Activities.LocationReferenceEnvironment.#ctor
  id: '#ctor'
  parent: System.Activities.LocationReferenceEnvironment
  langs:
  - csharp
  - vb
  name: .ctor
  nameWithType: LocationReferenceEnvironment..ctor
  fullName: System.Activities.LocationReferenceEnvironment..ctor
  type: Constructor
  assemblies:
  - System.Activities
  namespace: System.Activities
  syntax:
    content: protected LocationReferenceEnvironment ();
    parameters: []
- uid: System.Activities.LocationReferenceEnvironment.GetLocationReferences
  id: GetLocationReferences
  parent: System.Activities.LocationReferenceEnvironment
  langs:
  - csharp
  - vb
  name: GetLocationReferences
  nameWithType: LocationReferenceEnvironment.GetLocationReferences
  fullName: System.Activities.LocationReferenceEnvironment.GetLocationReferences
  type: Method
  assemblies:
  - System.Activities
  namespace: System.Activities
  syntax:
    content: public abstract System.Collections.Generic.IEnumerable<System.Activities.LocationReference> GetLocationReferences ();
    parameters: []
    return:
      type: System.Collections.Generic.IEnumerable{System.Activities.LocationReference}
      description: Return description to be filled
- uid: System.Activities.LocationReferenceEnvironment.IsVisible(System.Activities.LocationReference)
  id: IsVisible(System.Activities.LocationReference)
  parent: System.Activities.LocationReferenceEnvironment
  langs:
  - csharp
  - vb
  name: IsVisible
  nameWithType: LocationReferenceEnvironment.IsVisible
  fullName: System.Activities.LocationReferenceEnvironment.IsVisible
  type: Method
  assemblies:
  - System.Activities
  namespace: System.Activities
  syntax:
    content: public abstract bool IsVisible (System.Activities.LocationReference locationReference);
    parameters:
    - id: locationReference
      type: System.Activities.LocationReference
      description: Parameter description to be filled
    return:
      type: System.Boolean
      description: Return description to be filled
- uid: System.Activities.LocationReferenceEnvironment.Parent
  id: Parent
  parent: System.Activities.LocationReferenceEnvironment
  langs:
  - csharp
  - vb
  name: Parent
  nameWithType: LocationReferenceEnvironment.Parent
  fullName: System.Activities.LocationReferenceEnvironment.Parent
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities
  syntax:
    content: public System.Activities.LocationReferenceEnvironment Parent { get; protected set; }
    return:
      type: System.Activities.LocationReferenceEnvironment
      description: Return description to be filled
- uid: System.Activities.LocationReferenceEnvironment.Root
  id: Root
  parent: System.Activities.LocationReferenceEnvironment
  langs:
  - csharp
  - vb
  name: Root
  nameWithType: LocationReferenceEnvironment.Root
  fullName: System.Activities.LocationReferenceEnvironment.Root
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities
  syntax:
    content: public abstract System.Activities.Activity Root { get; }
    return:
      type: System.Activities.Activity
      description: Return description to be filled
- uid: System.Activities.LocationReferenceEnvironment.TryGetLocationReference(System.String,System.Activities.LocationReference@)
  id: TryGetLocationReference(System.String,System.Activities.LocationReference@)
  parent: System.Activities.LocationReferenceEnvironment
  langs:
  - csharp
  - vb
  name: TryGetLocationReference
  nameWithType: LocationReferenceEnvironment.TryGetLocationReference
  fullName: System.Activities.LocationReferenceEnvironment.TryGetLocationReference
  type: Method
  assemblies:
  - System.Activities
  namespace: System.Activities
  syntax:
    content: public abstract bool TryGetLocationReference (string name, out System.Activities.LocationReference result);
    parameters:
    - id: name
      type: System.String
      description: Parameter description to be filled
    - id: result
      type: System.Activities.LocationReference
      description: Parameter description to be filled
    return:
      type: System.Boolean
      description: Return description to be filled
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Activities.LocationReferenceEnvironment.#ctor
  parent: System.Activities.LocationReferenceEnvironment
  isExternal: false
  name: .ctor
  nameWithType: LocationReferenceEnvironment..ctor
  fullName: System.Activities.LocationReferenceEnvironment..ctor
- uid: System.Activities.LocationReferenceEnvironment.GetLocationReferences
  parent: System.Activities.LocationReferenceEnvironment
  isExternal: false
  name: GetLocationReferences
  nameWithType: LocationReferenceEnvironment.GetLocationReferences
  fullName: System.Activities.LocationReferenceEnvironment.GetLocationReferences
- uid: System.Activities.LocationReferenceEnvironment.IsVisible(System.Activities.LocationReference)
  parent: System.Activities.LocationReferenceEnvironment
  isExternal: false
  name: IsVisible
  nameWithType: LocationReferenceEnvironment.IsVisible
  fullName: System.Activities.LocationReferenceEnvironment.IsVisible
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Activities.LocationReference
  parent: System.Activities
  isExternal: false
  name: LocationReference
  nameWithType: LocationReference
  fullName: System.Activities.LocationReference
- uid: System.Activities.LocationReferenceEnvironment.Parent
  parent: System.Activities.LocationReferenceEnvironment
  isExternal: false
  name: Parent
  nameWithType: LocationReferenceEnvironment.Parent
  fullName: System.Activities.LocationReferenceEnvironment.Parent
- uid: System.Activities.LocationReferenceEnvironment
  parent: System.Activities
  isExternal: false
  name: LocationReferenceEnvironment
  nameWithType: LocationReferenceEnvironment
  fullName: System.Activities.LocationReferenceEnvironment
- uid: System.Activities.LocationReferenceEnvironment.Root
  parent: System.Activities.LocationReferenceEnvironment
  isExternal: false
  name: Root
  nameWithType: LocationReferenceEnvironment.Root
  fullName: System.Activities.LocationReferenceEnvironment.Root
- uid: System.Activities.Activity
  parent: System.Activities
  isExternal: false
  name: Activity
  nameWithType: Activity
  fullName: System.Activities.Activity
- uid: System.Activities.LocationReferenceEnvironment.TryGetLocationReference(System.String,System.Activities.LocationReference@)
  parent: System.Activities.LocationReferenceEnvironment
  isExternal: false
  name: TryGetLocationReference
  nameWithType: LocationReferenceEnvironment.TryGetLocationReference
  fullName: System.Activities.LocationReferenceEnvironment.TryGetLocationReference
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Activities.LocationReference
  parent: System.Activities
  isExternal: false
  name: LocationReference
  nameWithType: LocationReference
  fullName: System.Activities.LocationReference
