### YamlMime:ManagedReference
items:
- uid: System.Activities.WorkflowApplicationIdleEventArgs
  id: WorkflowApplicationIdleEventArgs
  children:
  - System.Activities.WorkflowApplicationIdleEventArgs.Bookmarks
  langs:
  - csharp
  name: WorkflowApplicationIdleEventArgs
  nameWithType: WorkflowApplicationIdleEventArgs
  fullName: System.Activities.WorkflowApplicationIdleEventArgs
  type: Class
  summary: Holds information about the workflow instance that has become idle.
  remarks: ''
  example:
  - "The following code example inspects the WorkflowApplicationIdleEventArgs passed into the <xref:System.Activities.WorkflowApplication.Idle%2A> handler of a <xref:System.Activities.WorkflowApplication> instance. In this example the workflow going idle has one <xref:System.Activities.Bookmark> with a name of `EnterGuess`, owned by an activity named `ReadInt`. This code example is based off of [How to: Run a Workflow](../Topic/How%20to:%20Run%20a%20Workflow.md), which is part of the [Getting Started Tutorial &#91;.NET Framework 4.5&#93;](../Topic/Getting%20Started%20Tutorial2.md). If the <xref:System.Activities.WorkflowApplication.Idle%2A> handler in that step is modified to contain the code from this example, the following output is displayed.  \n  \n```Output  \nBookmarkName: EnterGuess - OwnerDisplayName: ReadInt  \n```  \n  \n [!CODE [CFX_WorkflowApplicationExample#2](../CodeSnippet/VS_Snippets_CFX/cfx_workflowapplicationexample#2)]"
  syntax:
    content: 'public class WorkflowApplicationIdleEventArgs : System.Activities.WorkflowApplicationEventArgs'
  inheritance:
  - System.Object
  - System.EventArgs
  - System.Activities.WorkflowApplicationEventArgs
  implements: []
  inheritedMembers:
  - System.Activities.WorkflowApplicationEventArgs.GetInstanceExtensions``1
  - System.Activities.WorkflowApplicationEventArgs.InstanceId
  - System.EventArgs.Empty
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Activities.WorkflowApplicationIdleEventArgs.Bookmarks
  id: Bookmarks
  parent: System.Activities.WorkflowApplicationIdleEventArgs
  langs:
  - csharp
  name: Bookmarks
  nameWithType: WorkflowApplicationIdleEventArgs.Bookmarks
  fullName: System.Activities.WorkflowApplicationIdleEventArgs.Bookmarks
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: Gets the read-only collection of bookmarks for the workflow instance.
  remarks: ''
  example:
  - "The following code example inspects the <xref:System.Activities.WorkflowApplicationIdleEventArgs> passed into the <xref:System.Activities.WorkflowApplication.Idle%2A> handler of a <xref:System.Activities.WorkflowApplication> instance. In this example the workflow going idle has one <xref:System.Activities.Bookmark> with a name of `EnterGuess`, owned by an activity named `ReadInt`. This code example is based off of [How to: Run a Workflow](../Topic/How%20to:%20Run%20a%20Workflow.md), which is part of the [Getting Started Tutorial &#91;.NET Framework 4.5&#93;](../Topic/Getting%20Started%20Tutorial2.md). If the <xref:System.Activities.WorkflowApplication.Idle%2A> handler in that step is modified to contain the code from this example, the following output is displayed.  \n  \n```Output  \nBookmarkName: EnterGuess - OwnerDisplayName: ReadInt  \n```  \n  \n [!CODE [CFX_WorkflowApplicationExample#2](../CodeSnippet/VS_Snippets_CFX/cfx_workflowapplicationexample#2)]"
  syntax:
    content: public System.Collections.ObjectModel.ReadOnlyCollection<System.Activities.Hosting.BookmarkInfo> Bookmarks { get; }
    return:
      type: System.Collections.ObjectModel.ReadOnlyCollection{System.Activities.Hosting.BookmarkInfo}
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Activities.WorkflowApplicationEventArgs
  isExternal: false
  name: System.Activities.WorkflowApplicationEventArgs
- uid: System.Activities.WorkflowApplicationIdleEventArgs.Bookmarks
  parent: System.Activities.WorkflowApplicationIdleEventArgs
  isExternal: false
  name: Bookmarks
  nameWithType: WorkflowApplicationIdleEventArgs.Bookmarks
  fullName: System.Activities.WorkflowApplicationIdleEventArgs.Bookmarks
- uid: System.Collections.ObjectModel.ReadOnlyCollection{System.Activities.Hosting.BookmarkInfo}
  parent: System.Collections.ObjectModel
  isExternal: false
  name: ReadOnlyCollection<BookmarkInfo>
  nameWithType: ReadOnlyCollection<BookmarkInfo>
  fullName: System.Collections.ObjectModel.ReadOnlyCollection<System.Activities.Hosting.BookmarkInfo>
