### YamlMime:ManagedReference
items:
- uid: System.Activities.WorkflowApplicationEventArgs
  id: WorkflowApplicationEventArgs
  children:
  - System.Activities.WorkflowApplicationEventArgs.GetInstanceExtensions``1
  - System.Activities.WorkflowApplicationEventArgs.InstanceId
  langs:
  - csharp
  name: WorkflowApplicationEventArgs
  nameWithType: WorkflowApplicationEventArgs
  fullName: System.Activities.WorkflowApplicationEventArgs
  type: Class
  summary: A base class for events associated with a <see cref="T:System.Activities.WorkflowApplication"> .
  remarks: WorkflowApplicationEventArgs is also used in the <xref:System.Activities.WorkflowApplication.Unloaded%2A> handler of a <xref:System.Activities.WorkflowApplication> instance.
  example:
  - "The following code example inspects the WorkflowApplicationEventArgs passed into the <xref:System.Activities.WorkflowApplication.Unloaded%2A> handler of a <xref:System.Activities.WorkflowApplication> instance and displays the <xref:System.Activities.WorkflowApplicationEventArgs.InstanceId%2A> of the workflow that was unloaded.  \n  \n [!CODE [CFX_WorkflowApplicationExample#3](../CodeSnippet/VS_Snippets_CFX/cfx_workflowapplicationexample#3)]"
  syntax:
    content: 'public class WorkflowApplicationEventArgs : EventArgs'
  inheritance:
  - System.Object
  - System.EventArgs
  implements: []
  inheritedMembers:
  - System.EventArgs.Empty
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Activities.WorkflowApplicationEventArgs.GetInstanceExtensions``1
  id: GetInstanceExtensions``1
  parent: System.Activities.WorkflowApplicationEventArgs
  langs:
  - csharp
  name: GetInstanceExtensions()
  nameWithType: WorkflowApplicationEventArgs.GetInstanceExtensions()
  fullName: System.Activities.WorkflowApplicationEventArgs.GetInstanceExtensions()
  type: Method
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: To be added.
  remarks: To be added.
  syntax:
    content: 'public System.Collections.Generic.IEnumerable<T> GetInstanceExtensions<T> () where T : class;'
    parameters: []
    return:
      type: System.Collections.Generic.IEnumerable`1
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Activities.WorkflowApplicationEventArgs.InstanceId
  id: InstanceId
  parent: System.Activities.WorkflowApplicationEventArgs
  langs:
  - csharp
  name: InstanceId
  nameWithType: WorkflowApplicationEventArgs.InstanceId
  fullName: System.Activities.WorkflowApplicationEventArgs.InstanceId
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: The unique identifier of the workflow instance.
  remarks: ''
  example:
  - "The following code example inspects the <xref:System.Activities.WorkflowApplicationEventArgs> passed into the <xref:System.Activities.WorkflowApplication.Unloaded%2A> handler of a <xref:System.Activities.WorkflowApplication> instance and displays the InstanceId of the workflow that was unloaded.  \n  \n [!CODE [CFX_WorkflowApplicationExample#3](../CodeSnippet/VS_Snippets_CFX/cfx_workflowapplicationexample#3)]"
  syntax:
    content: public Guid InstanceId { get; }
    return:
      type: System.Guid
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.EventArgs
  isExternal: false
  name: System.EventArgs
- uid: System.Activities.WorkflowApplicationEventArgs.GetInstanceExtensions``1
  parent: System.Activities.WorkflowApplicationEventArgs
  isExternal: false
  name: GetInstanceExtensions()
  nameWithType: WorkflowApplicationEventArgs.GetInstanceExtensions()
  fullName: System.Activities.WorkflowApplicationEventArgs.GetInstanceExtensions()
- uid: System.Collections.Generic.IEnumerable`1
  parent: System.Collections.Generic
  isExternal: false
  name: IEnumerable<T>
  nameWithType: IEnumerable<T>
  fullName: System.Collections.Generic.IEnumerable<T>
- uid: System.Activities.WorkflowApplicationEventArgs.InstanceId
  parent: System.Activities.WorkflowApplicationEventArgs
  isExternal: false
  name: InstanceId
  nameWithType: WorkflowApplicationEventArgs.InstanceId
  fullName: System.Activities.WorkflowApplicationEventArgs.InstanceId
- uid: System.Guid
  parent: System
  isExternal: false
  name: Guid
  nameWithType: Guid
  fullName: System.Guid
