### YamlMime:ManagedReference
items:
- uid: System.Security.Policy.ApplicationDirectoryMembershipCondition
  id: ApplicationDirectoryMembershipCondition
  children:
  - System.Security.Policy.ApplicationDirectoryMembershipCondition.#ctor
  - System.Security.Policy.ApplicationDirectoryMembershipCondition.Check(System.Security.Policy.Evidence)
  - System.Security.Policy.ApplicationDirectoryMembershipCondition.Copy
  - System.Security.Policy.ApplicationDirectoryMembershipCondition.Equals(System.Object)
  - System.Security.Policy.ApplicationDirectoryMembershipCondition.FromXml(System.Security.SecurityElement)
  - System.Security.Policy.ApplicationDirectoryMembershipCondition.FromXml(System.Security.SecurityElement,System.Security.Policy.PolicyLevel)
  - System.Security.Policy.ApplicationDirectoryMembershipCondition.GetHashCode
  - System.Security.Policy.ApplicationDirectoryMembershipCondition.ToString
  - System.Security.Policy.ApplicationDirectoryMembershipCondition.ToXml
  - System.Security.Policy.ApplicationDirectoryMembershipCondition.ToXml(System.Security.Policy.PolicyLevel)
  langs:
  - csharp
  - vb
  name: ApplicationDirectoryMembershipCondition
  nameWithType: ApplicationDirectoryMembershipCondition
  fullName: System.Security.Policy.ApplicationDirectoryMembershipCondition
  type: Class
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(true)]

      public sealed class ApplicationDirectoryMembershipCondition
  inheritance:
  - System.Object
  implements: []
  inheritedMembers:
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
- uid: System.Security.Policy.ApplicationDirectoryMembershipCondition.#ctor
  id: '#ctor'
  parent: System.Security.Policy.ApplicationDirectoryMembershipCondition
  langs:
  - csharp
  - vb
  name: .ctor
  nameWithType: ApplicationDirectoryMembershipCondition..ctor
  fullName: System.Security.Policy.ApplicationDirectoryMembershipCondition..ctor
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System.Security.Policy
  syntax:
    content: public ApplicationDirectoryMembershipCondition ();
    parameters: []
- uid: System.Security.Policy.ApplicationDirectoryMembershipCondition.Check(System.Security.Policy.Evidence)
  id: Check(System.Security.Policy.Evidence)
  parent: System.Security.Policy.ApplicationDirectoryMembershipCondition
  langs:
  - csharp
  - vb
  name: Check
  nameWithType: ApplicationDirectoryMembershipCondition.Check
  fullName: System.Security.Policy.ApplicationDirectoryMembershipCondition.Check
  type: Method
  assemblies:
  - mscorlib
  namespace: System.Security.Policy
  syntax:
    content: public bool Check (System.Security.Policy.Evidence evidence);
    parameters:
    - id: evidence
      type: System.Security.Policy.Evidence
      description: Parameter description to be filled
    return:
      type: System.Boolean
      description: Return description to be filled
- uid: System.Security.Policy.ApplicationDirectoryMembershipCondition.Copy
  id: Copy
  parent: System.Security.Policy.ApplicationDirectoryMembershipCondition
  langs:
  - csharp
  - vb
  name: Copy
  nameWithType: ApplicationDirectoryMembershipCondition.Copy
  fullName: System.Security.Policy.ApplicationDirectoryMembershipCondition.Copy
  type: Method
  assemblies:
  - mscorlib
  namespace: System.Security.Policy
  syntax:
    content: public System.Security.Policy.IMembershipCondition Copy ();
    parameters: []
    return:
      type: System.Security.Policy.IMembershipCondition
      description: Return description to be filled
- uid: System.Security.Policy.ApplicationDirectoryMembershipCondition.Equals(System.Object)
  id: Equals(System.Object)
  parent: System.Security.Policy.ApplicationDirectoryMembershipCondition
  langs:
  - csharp
  - vb
  name: Equals
  nameWithType: ApplicationDirectoryMembershipCondition.Equals
  fullName: System.Security.Policy.ApplicationDirectoryMembershipCondition.Equals
  type: Method
  assemblies:
  - mscorlib
  namespace: System.Security.Policy
  syntax:
    content: public override bool Equals (object o);
    parameters:
    - id: o
      type: System.Object
      description: Parameter description to be filled
    return:
      type: System.Boolean
      description: Return description to be filled
- uid: System.Security.Policy.ApplicationDirectoryMembershipCondition.FromXml(System.Security.SecurityElement)
  id: FromXml(System.Security.SecurityElement)
  parent: System.Security.Policy.ApplicationDirectoryMembershipCondition
  langs:
  - csharp
  - vb
  name: FromXml
  nameWithType: ApplicationDirectoryMembershipCondition.FromXml
  fullName: System.Security.Policy.ApplicationDirectoryMembershipCondition.FromXml
  type: Method
  assemblies:
  - mscorlib
  namespace: System.Security.Policy
  syntax:
    content: public void FromXml (System.Security.SecurityElement e);
    parameters:
    - id: e
      type: System.Security.SecurityElement
      description: Parameter description to be filled
    return:
      type: System.Void
      description: Return description to be filled
  overload: System.Security.Policy.ApplicationDirectoryMembershipCondition.FromXml*
- uid: System.Security.Policy.ApplicationDirectoryMembershipCondition.FromXml(System.Security.SecurityElement,System.Security.Policy.PolicyLevel)
  id: FromXml(System.Security.SecurityElement,System.Security.Policy.PolicyLevel)
  parent: System.Security.Policy.ApplicationDirectoryMembershipCondition
  langs:
  - csharp
  - vb
  name: FromXml
  nameWithType: ApplicationDirectoryMembershipCondition.FromXml
  fullName: System.Security.Policy.ApplicationDirectoryMembershipCondition.FromXml
  type: Method
  assemblies:
  - mscorlib
  namespace: System.Security.Policy
  syntax:
    content: public void FromXml (System.Security.SecurityElement e, System.Security.Policy.PolicyLevel level);
    parameters:
    - id: e
      type: System.Security.SecurityElement
      description: Parameter description to be filled
    - id: level
      type: System.Security.Policy.PolicyLevel
      description: Parameter description to be filled
    return:
      type: System.Void
      description: Return description to be filled
  overload: System.Security.Policy.ApplicationDirectoryMembershipCondition.FromXml*
- uid: System.Security.Policy.ApplicationDirectoryMembershipCondition.GetHashCode
  id: GetHashCode
  parent: System.Security.Policy.ApplicationDirectoryMembershipCondition
  langs:
  - csharp
  - vb
  name: GetHashCode
  nameWithType: ApplicationDirectoryMembershipCondition.GetHashCode
  fullName: System.Security.Policy.ApplicationDirectoryMembershipCondition.GetHashCode
  type: Method
  assemblies:
  - mscorlib
  namespace: System.Security.Policy
  syntax:
    content: public override int GetHashCode ();
    parameters: []
    return:
      type: System.Int32
      description: Return description to be filled
- uid: System.Security.Policy.ApplicationDirectoryMembershipCondition.ToString
  id: ToString
  parent: System.Security.Policy.ApplicationDirectoryMembershipCondition
  langs:
  - csharp
  - vb
  name: ToString
  nameWithType: ApplicationDirectoryMembershipCondition.ToString
  fullName: System.Security.Policy.ApplicationDirectoryMembershipCondition.ToString
  type: Method
  assemblies:
  - mscorlib
  namespace: System.Security.Policy
  syntax:
    content: public override string ToString ();
    parameters: []
    return:
      type: System.String
      description: Return description to be filled
- uid: System.Security.Policy.ApplicationDirectoryMembershipCondition.ToXml
  id: ToXml
  parent: System.Security.Policy.ApplicationDirectoryMembershipCondition
  langs:
  - csharp
  - vb
  name: ToXml
  nameWithType: ApplicationDirectoryMembershipCondition.ToXml
  fullName: System.Security.Policy.ApplicationDirectoryMembershipCondition.ToXml
  type: Method
  assemblies:
  - mscorlib
  namespace: System.Security.Policy
  syntax:
    content: public System.Security.SecurityElement ToXml ();
    parameters: []
    return:
      type: System.Security.SecurityElement
      description: Return description to be filled
  overload: System.Security.Policy.ApplicationDirectoryMembershipCondition.ToXml*
- uid: System.Security.Policy.ApplicationDirectoryMembershipCondition.ToXml(System.Security.Policy.PolicyLevel)
  id: ToXml(System.Security.Policy.PolicyLevel)
  parent: System.Security.Policy.ApplicationDirectoryMembershipCondition
  langs:
  - csharp
  - vb
  name: ToXml
  nameWithType: ApplicationDirectoryMembershipCondition.ToXml
  fullName: System.Security.Policy.ApplicationDirectoryMembershipCondition.ToXml
  type: Method
  assemblies:
  - mscorlib
  namespace: System.Security.Policy
  syntax:
    content: public System.Security.SecurityElement ToXml (System.Security.Policy.PolicyLevel level);
    parameters:
    - id: level
      type: System.Security.Policy.PolicyLevel
      description: Parameter description to be filled
    return:
      type: System.Security.SecurityElement
      description: Return description to be filled
  overload: System.Security.Policy.ApplicationDirectoryMembershipCondition.ToXml*
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Security.Policy.ApplicationDirectoryMembershipCondition.#ctor
  parent: System.Security.Policy.ApplicationDirectoryMembershipCondition
  isExternal: false
  name: .ctor
  nameWithType: ApplicationDirectoryMembershipCondition..ctor
  fullName: System.Security.Policy.ApplicationDirectoryMembershipCondition..ctor
- uid: System.Security.Policy.ApplicationDirectoryMembershipCondition.Check(System.Security.Policy.Evidence)
  parent: System.Security.Policy.ApplicationDirectoryMembershipCondition
  isExternal: false
  name: Check
  nameWithType: ApplicationDirectoryMembershipCondition.Check
  fullName: System.Security.Policy.ApplicationDirectoryMembershipCondition.Check
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Security.Policy.Evidence
  parent: System.Security.Policy
  isExternal: false
  name: Evidence
  nameWithType: Evidence
  fullName: System.Security.Policy.Evidence
- uid: System.Security.Policy.ApplicationDirectoryMembershipCondition.Copy
  parent: System.Security.Policy.ApplicationDirectoryMembershipCondition
  isExternal: false
  name: Copy
  nameWithType: ApplicationDirectoryMembershipCondition.Copy
  fullName: System.Security.Policy.ApplicationDirectoryMembershipCondition.Copy
- uid: System.Security.Policy.IMembershipCondition
  parent: System.Security.Policy
  isExternal: false
  name: IMembershipCondition
  nameWithType: IMembershipCondition
  fullName: System.Security.Policy.IMembershipCondition
- uid: System.Security.Policy.ApplicationDirectoryMembershipCondition.Equals(System.Object)
  parent: System.Security.Policy.ApplicationDirectoryMembershipCondition
  isExternal: false
  name: Equals
  nameWithType: ApplicationDirectoryMembershipCondition.Equals
  fullName: System.Security.Policy.ApplicationDirectoryMembershipCondition.Equals
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Security.Policy.ApplicationDirectoryMembershipCondition.FromXml(System.Security.SecurityElement)
  parent: System.Security.Policy.ApplicationDirectoryMembershipCondition
  isExternal: false
  name: FromXml
  nameWithType: ApplicationDirectoryMembershipCondition.FromXml
  fullName: System.Security.Policy.ApplicationDirectoryMembershipCondition.FromXml
- uid: System.Void
  parent: System
  isExternal: false
  name: Void
  nameWithType: Void
  fullName: System.Void
- uid: System.Security.SecurityElement
  parent: System.Security
  isExternal: false
  name: SecurityElement
  nameWithType: SecurityElement
  fullName: System.Security.SecurityElement
- uid: System.Security.Policy.ApplicationDirectoryMembershipCondition.FromXml(System.Security.SecurityElement,System.Security.Policy.PolicyLevel)
  parent: System.Security.Policy.ApplicationDirectoryMembershipCondition
  isExternal: false
  name: FromXml
  nameWithType: ApplicationDirectoryMembershipCondition.FromXml
  fullName: System.Security.Policy.ApplicationDirectoryMembershipCondition.FromXml
- uid: System.Void
  parent: System
  isExternal: false
  name: Void
  nameWithType: Void
  fullName: System.Void
- uid: System.Security.SecurityElement
  parent: System.Security
  isExternal: false
  name: SecurityElement
  nameWithType: SecurityElement
  fullName: System.Security.SecurityElement
- uid: System.Security.Policy.PolicyLevel
  parent: System.Security.Policy
  isExternal: false
  name: PolicyLevel
  nameWithType: PolicyLevel
  fullName: System.Security.Policy.PolicyLevel
- uid: System.Security.Policy.ApplicationDirectoryMembershipCondition.GetHashCode
  parent: System.Security.Policy.ApplicationDirectoryMembershipCondition
  isExternal: false
  name: GetHashCode
  nameWithType: ApplicationDirectoryMembershipCondition.GetHashCode
  fullName: System.Security.Policy.ApplicationDirectoryMembershipCondition.GetHashCode
- uid: System.Int32
  parent: System
  isExternal: false
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Security.Policy.ApplicationDirectoryMembershipCondition.ToString
  parent: System.Security.Policy.ApplicationDirectoryMembershipCondition
  isExternal: false
  name: ToString
  nameWithType: ApplicationDirectoryMembershipCondition.ToString
  fullName: System.Security.Policy.ApplicationDirectoryMembershipCondition.ToString
- uid: System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Security.Policy.ApplicationDirectoryMembershipCondition.ToXml
  parent: System.Security.Policy.ApplicationDirectoryMembershipCondition
  isExternal: false
  name: ToXml
  nameWithType: ApplicationDirectoryMembershipCondition.ToXml
  fullName: System.Security.Policy.ApplicationDirectoryMembershipCondition.ToXml
- uid: System.Security.SecurityElement
  parent: System.Security
  isExternal: false
  name: SecurityElement
  nameWithType: SecurityElement
  fullName: System.Security.SecurityElement
- uid: System.Security.Policy.ApplicationDirectoryMembershipCondition.ToXml(System.Security.Policy.PolicyLevel)
  parent: System.Security.Policy.ApplicationDirectoryMembershipCondition
  isExternal: false
  name: ToXml
  nameWithType: ApplicationDirectoryMembershipCondition.ToXml
  fullName: System.Security.Policy.ApplicationDirectoryMembershipCondition.ToXml
- uid: System.Security.SecurityElement
  parent: System.Security
  isExternal: false
  name: SecurityElement
  nameWithType: SecurityElement
  fullName: System.Security.SecurityElement
- uid: System.Security.Policy.PolicyLevel
  parent: System.Security.Policy
  isExternal: false
  name: PolicyLevel
  nameWithType: PolicyLevel
  fullName: System.Security.Policy.PolicyLevel
- uid: System.Security.Policy.ApplicationDirectoryMembershipCondition.FromXml
  parent: System.Security.Policy.ApplicationDirectoryMembershipCondition
  isExternal: false
  name: Check
  nameWithType: ApplicationDirectoryMembershipCondition.Check
- uid: System.Security.Policy.ApplicationDirectoryMembershipCondition.ToXml
  parent: System.Security.Policy.ApplicationDirectoryMembershipCondition
  isExternal: false
  name: Check
  nameWithType: ApplicationDirectoryMembershipCondition.Check
